--- @class JetBrains.Annotations.StringFormatMethodAttribute:System.Attribute 
--- @field FormatParameterName string
--- @field TypeId System.Object
JetBrains.Annotations.StringFormatMethodAttribute = {}

---  Generated By xerysherry