--- @class UnityEngine.Rendering.CommandBufferExecutionFlags Flags describing the intention for how the command buffer will be executed. Set these via CommandBuffer.SetExecutionFlags.
UnityEngine.Rendering.CommandBufferExecutionFlags = {
    --- When no flags are specified, the command buffer is considered valid for all means of execution. This is the default for new command buffers.
    None = 0,
    --- Command buffers flagged for async compute execution will throw exceptions if non-compatible commands are added to them. See ScriptableRenderContext.ExecuteCommandBufferAsync and Graphics.ExecuteCommandBufferAsync.
    AsyncCompute = 2,
}

---  Generated By xerysherry