--- @class UnityEngine.RelativeJoint2D:UnityEngine.Joint2D Keeps two Rigidbody2D at their relative orientations.
--- @field maxForce number property getset
---       The maximum force that can be generated when trying to maintain the relative joint constraint.
--- @field maxTorque number property getset
---       The maximum torque that can be generated when trying to maintain the relative joint constraint.
--- @field correctionScale number property getset
---       Scales both the linear and angular forces used to correct the required relative orientation.
--- @field autoConfigureOffset boolean property getset
---       Should both the linearOffset and angularOffset be calculated automatically?
--- @field linearOffset UnityEngine.Vector2 property getset
---       The current linear offset between the Rigidbody2D that the joint connects.
--- @field angularOffset number property getset
---       The current angular offset between the Rigidbody2D that the joint connects.
--- @field target UnityEngine.Vector2 property get
---       The world-space position that is currently trying to be maintained.
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field connectedBody UnityEngine.Rigidbody2D
--- @field enableCollision boolean
--- @field breakForce number
--- @field breakTorque number
--- @field reactionForce UnityEngine.Vector2
--- @field reactionTorque number
--- @field collideConnected boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.RelativeJoint2D = {}

--- @param value number 
function UnityEngine.RelativeJoint2D:set_maxForce(value) end

--- @param value number 
function UnityEngine.RelativeJoint2D:set_maxTorque(value) end

--- @param value number 
function UnityEngine.RelativeJoint2D:set_correctionScale(value) end

--- @param value boolean 
function UnityEngine.RelativeJoint2D:set_autoConfigureOffset(value) end

--- @param value UnityEngine.Vector2 
function UnityEngine.RelativeJoint2D:set_linearOffset(value) end

--- @param value number 
function UnityEngine.RelativeJoint2D:set_angularOffset(value) end

---  Generated By xerysherry