--- @class UnityEngine.SortingLayer SortingLayer allows you to set the render order of multiple sprites easily. There is always a default SortingLayer named "Default" which all sprites are added to initially. Added more SortingLayers to easily control the order of rendering of groups of sprites. Layers can be ordered before or after the default layer.
--- @field layers UnityEngine.SortingLayer[] property get
---       Returns all the layers defined in this project.
--- @field id number property get
---       This is the unique id assigned to the layer. It is not an ordered running value and it should not be used to compare with other layers to determine the sorting order.
--- @field name string property get
---       Returns the name of the layer as defined in the TagManager.
--- @field value number property get
---       This is the relative value that indicates the sort order of this layer relative to the other layers.
UnityEngine.SortingLayer = {}

--- Returns the final sorting layer value. To determine the sorting order between the various sorting layers, use this method to retrieve the final sorting value and use CompareTo to determine the order.
--- @param id number The unique value of the sorting layer as returned by any renderer's sortingLayerID property.
--- @return number The final sorting value of the layer relative to other layers.
function UnityEngine.SortingLayer.GetLayerValueFromID(id) end

--- Returns the final sorting layer value. See Also: GetLayerValueFromID.
--- @param name string The unique value of the sorting layer as returned by any renderer's sortingLayerID property.
--- @return number The final sorting value of the layer relative to other layers.
function UnityEngine.SortingLayer.GetLayerValueFromName(name) end

--- Returns the id given the name. Will return 0 if an invalid name was given.
--- @param name string The name of the layer.
--- @return number The unique id of the layer with name.
function UnityEngine.SortingLayer.NameToID(name) end

--- Returns the unique id of the layer. Will return "<unknown layer>" if an invalid id is given.
--- @param id number The unique id of the layer.
--- @return string The name of the layer with id or "<unknown layer>" for invalid id.
function UnityEngine.SortingLayer.IDToName(id) end

--- Returns true if the id provided is a valid layer id.
--- @param id number The unique id of a layer.
--- @return boolean True if the id provided is valid and assigned to a layer.
function UnityEngine.SortingLayer.IsValid(id) end

---  Generated By xerysherry