--- @class UnityEngine.RenderMode RenderMode for the Canvas.
UnityEngine.RenderMode = {
    --- Render at the end of the Scene using a 2D Canvas.
    ScreenSpaceOverlay = 0,
    --- Render using the Camera configured on the Canvas.
    ScreenSpaceCamera = 1,
    --- Render using any Camera in the Scene that can render the layer.
    WorldSpace = 2,
}

---  Generated By xerysherry