--- @class UnityEngine.Rendering.DepthState Values for the depth state.
--- @field defaultValue UnityEngine.Rendering.DepthState property get
---       Default values for the depth state.
--- @field writeEnabled boolean property getset
---       Controls whether pixels from this object are written to the depth buffer.
--- @field compareFunction UnityEngine.Rendering.CompareFunction property getset
---       How should depth testing be performed.
UnityEngine.Rendering.DepthState = {}

--- @return boolean
function UnityEngine.Rendering.DepthState.op_Equality(left, right) end

--- @return boolean
function UnityEngine.Rendering.DepthState.op_Inequality(left, right) end

function UnityEngine.Rendering.DepthState:set_writeEnabled(value) end

function UnityEngine.Rendering.DepthState:set_compareFunction(value) end

--- @return boolean
function UnityEngine.Rendering.DepthState:Equals(other) end

--- @return boolean
function UnityEngine.Rendering.DepthState:Equals(obj) end

--- @return number
function UnityEngine.Rendering.DepthState:GetHashCode() end

---  Generated By xerysherry