--- @class UnityEngine.StackTraceUtility 
UnityEngine.StackTraceUtility = {}

--- @return string
function UnityEngine.StackTraceUtility.ExtractStackTrace() end

--- @param exception System.Object 
--- @return string
function UnityEngine.StackTraceUtility.ExtractStringFromException(exception) end

---  Generated By xerysherry