--- @class UnityEngine.TextCore.GlyphMetrics A set of values that define the size, position and spacing of a glyph when performing text layout.
--- @field width number property getset
---       The width of the glyph.
--- @field height number property getset
---       The height of the glyph.
--- @field horizontalBearingX number property getset
---       The horizontal distance from the current drawing position (origin) relative to the element's left bounding box edge (bbox).
--- @field horizontalBearingY number property getset
---       The vertical distance from the current baseline relative to the element's top bounding box edge (bbox).
--- @field horizontalAdvance number property getset
---       The horizontal distance to increase (left to right) or decrease (right to left) the drawing position relative to the origin of the text element.
UnityEngine.TextCore.GlyphMetrics = {}

--- @param lhs UnityEngine.TextCore.GlyphMetrics 
--- @param rhs UnityEngine.TextCore.GlyphMetrics 
--- @return boolean
function UnityEngine.TextCore.GlyphMetrics.op_Equality(lhs, rhs) end

--- @param lhs UnityEngine.TextCore.GlyphMetrics 
--- @param rhs UnityEngine.TextCore.GlyphMetrics 
--- @return boolean
function UnityEngine.TextCore.GlyphMetrics.op_Inequality(lhs, rhs) end

--- @param value number 
function UnityEngine.TextCore.GlyphMetrics:set_width(value) end

--- @param value number 
function UnityEngine.TextCore.GlyphMetrics:set_height(value) end

--- @param value number 
function UnityEngine.TextCore.GlyphMetrics:set_horizontalBearingX(value) end

--- @param value number 
function UnityEngine.TextCore.GlyphMetrics:set_horizontalBearingY(value) end

--- @param value number 
function UnityEngine.TextCore.GlyphMetrics:set_horizontalAdvance(value) end

--- @return number
function UnityEngine.TextCore.GlyphMetrics:GetHashCode() end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.TextCore.GlyphMetrics:Equals(obj) end

--- @param other UnityEngine.TextCore.GlyphMetrics 
--- @return boolean
function UnityEngine.TextCore.GlyphMetrics:Equals(other) end

---  Generated By xerysherry