--- @class UnityEngine.FrameTimingManager The FrameTimingManager allows the user to capture and access FrameTiming data for multple frames.
UnityEngine.FrameTimingManager = {}

--- This function triggers the FrameTimingManager to capture a snapshot of FrameTiming's data, that can then be accessed by the user.
function UnityEngine.FrameTimingManager.CaptureFrameTimings() end

--- Allows the user to access the currently captured FrameTimings.
--- @param numFrames number User supplies a desired number of frames they would like FrameTimings for. This should be equal to or less than the maximum FrameTimings the platform can capture.
--- @param timings UnityEngine.FrameTiming[] An array of FrameTiming structs that is passed in by the user and will be filled with data as requested. It is the users job to make sure the array that is passed is large enough to hold the requested number of FrameTimings.
--- @return number Returns the number of FrameTimings it actually was able to get. This will always be equal to or less than the requested numFrames depending on availability of captured FrameTimings.
function UnityEngine.FrameTimingManager.GetLatestTimings(numFrames, timings) end

--- This returns the number of vsyncs per second on the current platform, used to interpret timing results. If the platform does not support returning this value it will return 0.
--- @return number Number of vsyncs per second of the current platform.
function UnityEngine.FrameTimingManager.GetVSyncsPerSecond() end

--- This returns the frequency of GPU timer on the current platform, used to interpret timing results. If the platform does not support returning this value it will return 0.
--- @return number GPU timer frequency for current platform.
function UnityEngine.FrameTimingManager.GetGpuTimerFrequency() end

--- This returns the frequency of CPU timer on the current platform, used to interpret timing results. If the platform does not support returning this value it will return 0.
--- @return number CPU timer frequency for current platform.
function UnityEngine.FrameTimingManager.GetCpuTimerFrequency() end

---  Generated By xerysherry