--- @class UnityEngine.RequireComponent:System.Attribute The RequireComponent attribute automatically adds required components as dependencies.
--- @field TypeId System.Object
--- @field m_Type0 System.Type
--- @field m_Type1 System.Type
--- @field m_Type2 System.Type
UnityEngine.RequireComponent = {}

---  Generated By xerysherry