--- @class UnityEngine.XR.WSA.HolographicStreamerConnectionState Current state of the holographis streamer remote connection.
UnityEngine.XR.WSA.HolographicStreamerConnectionState = {
    --- Indicates app being currently disconnected from any other remote device.
    Disconnected = 0,
    --- Indicates app trying to connect to remote device.
    Connecting = 1,
    --- Indicates app being connected to remote device.
    Connected = 2,
}

---  Generated By xerysherry