--- @class UnityEngine.U2D.ShapeControlPoint Data that describes the important points of the shape.
--- @field position UnityEngine.Vector3 The position of this point in the object's local space.
--- @field leftTangent UnityEngine.Vector3 The position of the left tangent in local space.
--- @field rightTangent UnityEngine.Vector3 The position of the right tangent point in the local space.
--- @field mode number The various modes of the tangent handles. They could be continuous or broken.
UnityEngine.U2D.ShapeControlPoint = {}

---  Generated By xerysherry