--- @class UnityEngine.AnimationState:UnityEngine.TrackedReference The AnimationState gives full control over animation blending.
--- @field enabled boolean property getset
---       Enables / disables the animation.
--- @field weight number property getset
---       The weight of animation.
--- @field wrapMode UnityEngine.WrapMode property getset
---       Wrapping mode of the animation.
--- @field time number property getset
---       The current time of the animation.
--- @field normalizedTime number property getset
---       The normalized time of the animation.
--- @field speed number property getset
---       The playback speed of the animation. 1 is normal playback speed.
--- @field normalizedSpeed number property getset
---       The normalized playback speed.
--- @field length number property get
---       The length of the animation clip in seconds.
--- @field layer number
--- @field clip UnityEngine.AnimationClip property get
---       The clip that is being played by this animation state.
--- @field name string property getset
---       The name of the animation.
--- @field blendMode UnityEngine.AnimationBlendMode property getset
---       Which blend mode should be used?
UnityEngine.AnimationState = {}

--- @param value boolean 
function UnityEngine.AnimationState:set_enabled(value) end

--- @param value number 
function UnityEngine.AnimationState:set_weight(value) end

--- @param value UnityEngine.WrapMode 
function UnityEngine.AnimationState:set_wrapMode(value) end

--- @param value number 
function UnityEngine.AnimationState:set_time(value) end

--- @param value number 
function UnityEngine.AnimationState:set_normalizedTime(value) end

--- @param value number 
function UnityEngine.AnimationState:set_speed(value) end

--- @param value number 
function UnityEngine.AnimationState:set_normalizedSpeed(value) end

--- @param value number 
function UnityEngine.AnimationState:set_layer(value) end

--- Adds a transform which should be animated. This allows you to reduce the number of animations you have to create.
--- @param mix UnityEngine.Transform The transform to animate.
--- @param recursive boolean Whether to also animate all children of the specified transform.
function UnityEngine.AnimationState:AddMixingTransform(mix, recursive) end

--- Adds a transform which should be animated. This allows you to reduce the number of animations you have to create.
--- @param mix UnityEngine.Transform 
function UnityEngine.AnimationState:AddMixingTransform(mix) end

--- Removes a transform which should be animated.
--- @param mix UnityEngine.Transform 
function UnityEngine.AnimationState:RemoveMixingTransform(mix) end

--- @param value string 
function UnityEngine.AnimationState:set_name(value) end

--- @param value UnityEngine.AnimationBlendMode 
function UnityEngine.AnimationState:set_blendMode(value) end

---  Generated By xerysherry