--- @class UnityEngine.UI.MaskUtilities 
UnityEngine.UI.MaskUtilities = {}

--- @param mask UnityEngine.Component 
function UnityEngine.UI.MaskUtilities.Notify2DMaskStateChanged(mask) end

--- @param mask UnityEngine.Component 
function UnityEngine.UI.MaskUtilities.NotifyStencilStateChanged(mask) end

--- @param start UnityEngine.Transform 
--- @return UnityEngine.Transform
function UnityEngine.UI.MaskUtilities.FindRootSortOverrideCanvas(start) end

--- @param transform UnityEngine.Transform 
--- @param stopAfter UnityEngine.Transform 
--- @return number
function UnityEngine.UI.MaskUtilities.GetStencilDepth(transform, stopAfter) end

--- @param father UnityEngine.Transform 
--- @param child UnityEngine.Transform 
--- @return boolean
function UnityEngine.UI.MaskUtilities.IsDescendantOrSelf(father, child) end

--- @param clippable UnityEngine.UI.IClippable 
--- @return UnityEngine.UI.RectMask2D
function UnityEngine.UI.MaskUtilities.GetRectMaskForClippable(clippable) end

--- @param clipper UnityEngine.UI.RectMask2D 
--- @param masks UnityEngine.UI.RectMask2D[] 
function UnityEngine.UI.MaskUtilities.GetRectMasksForClip(clipper, masks) end

---  Generated By xerysherry