--- @class UnityEngine.XR.UserPresenceState Represents the current user presence state detected by the device.
UnityEngine.XR.UserPresenceState = {
    --- The device does not support detecting user presence.
    Unsupported = -1,
    --- The device does not detect that the user is present.
    NotPresent = 0,
    --- The device detects that the user is present.
    Present = 1,
    --- The device is currently in a state where it cannot determine user presence.
    Unknown = 2,
}

---  Generated By xerysherry