--- @class UnityEngine.UIElements.ScrollView:UnityEngine.UIElements.VisualElement Displays its contents inside a scrollable frame.
--- @field ussClassName string USS class name of elements of this type.
--- @field viewportUssClassName string USS class name of viewport elements in elements of this type.
--- @field contentUssClassName string USS class name of content elements in elements of this type.
--- @field hScrollerUssClassName string USS class name of horizontal scrollers in elements of this type.
--- @field vScrollerUssClassName string USS class name of vertical scrollers in elements of this type.
--- @field horizontalVariantUssClassName string
--- @field verticalVariantUssClassName string
--- @field verticalHorizontalVariantUssClassName string
--- @field scrollVariantUssClassName string
--- @field showHorizontal boolean property getset
---       Should the horizontal scroller be visible.
--- @field showVertical boolean property getset
---       Should the vertical scroller be visible.
--- @field scrollOffset UnityEngine.Vector2 property getset
---       The current scrolling position.
--- @field horizontalPageSize number property getset
---       This property is controlling the scrolling speed of the horizontal scroller.
--- @field verticalPageSize number property getset
---       This property is controlling the scrolling speed of the vertical scroller.
--- @field contentViewport UnityEngine.UIElements.VisualElement property get
---       Represents the visible part of contentContainer.
--- @field horizontalScroller UnityEngine.UIElements.Scroller property get
---       Horizontal scrollbar.
--- @field verticalScroller UnityEngine.UIElements.Scroller property get
---       Vertical Scrollbar.
--- @field contentContainer UnityEngine.UIElements.VisualElement property get
---       Contains full content, potentially partially visible.
--- @field viewDataKey string
--- @field userData System.Object
--- @field canGrabFocus boolean
--- @field focusController UnityEngine.UIElements.FocusController
--- @field usageHints UnityEngine.UIElements.UsageHints
--- @field transform UnityEngine.UIElements.ITransform
--- @field layout UnityEngine.Rect
--- @field contentRect UnityEngine.Rect
--- @field worldBound UnityEngine.Rect
--- @field localBound UnityEngine.Rect
--- @field worldTransform UnityEngine.Matrix4x4
--- @field pickingMode UnityEngine.UIElements.PickingMode
--- @field name string
--- @field enabledInHierarchy boolean
--- @field enabledSelf boolean
--- @field visible boolean
--- @field generateVisualContent function
--- @field experimental UnityEngine.UIElements.IExperimentalFeatures
--- @field hierarchy UnityEngine.UIElements.VisualElement.Hierarchy
--- @field cacheAsBitmap boolean
--- @field parent UnityEngine.UIElements.VisualElement
--- @field panel UnityEngine.UIElements.IPanel
--- @field Item UnityEngine.UIElements.VisualElement
--- @field childCount number
--- @field schedule UnityEngine.UIElements.IVisualElementScheduler
--- @field style UnityEngine.UIElements.IStyle
--- @field customStyle UnityEngine.UIElements.ICustomStyle
--- @field resolvedStyle UnityEngine.UIElements.IResolvedStyle
--- @field styleSheets UnityEngine.UIElements.VisualElementStyleSheetSet
--- @field tooltip string
--- @field focusable boolean
--- @field tabIndex number
--- @field delegatesFocus boolean
UnityEngine.UIElements.ScrollView = {}

function UnityEngine.UIElements.ScrollView:set_showHorizontal(value) end

function UnityEngine.UIElements.ScrollView:set_showVertical(value) end

function UnityEngine.UIElements.ScrollView:set_scrollOffset(value) end

function UnityEngine.UIElements.ScrollView:set_horizontalPageSize(value) end

function UnityEngine.UIElements.ScrollView:set_verticalPageSize(value) end

--- Scroll to a specific child element.
--- @param child UnityEngine.UIElements.VisualElement The child to scroll to.
function UnityEngine.UIElements.ScrollView:ScrollTo(child) end

---  Generated By xerysherry