--- @class UnityEngine.Tilemaps.TileBase:UnityEngine.ScriptableObject Base class for a tile in the Tilemap.
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Tilemaps.TileBase = {}

--- This method is called when the tile is refreshed.
--- @param position UnityEngine.Vector3Int Position of the Tile on the Tilemap.
--- @param tilemap UnityEngine.Tilemaps.ITilemap The Tilemap the tile is present on.
function UnityEngine.Tilemaps.TileBase:RefreshTile(position, tilemap) end

--- Retrieves any tile rendering data from the scripted tile.
--- @param position UnityEngine.Vector3Int Position of the Tile on the Tilemap.
--- @param tilemap UnityEngine.Tilemaps.ITilemap The Tilemap the tile is present on.
--- @param tileData UnityEngine.Tilemaps.TileData& Data to render the tile.
function UnityEngine.Tilemaps.TileBase:GetTileData(position, tilemap, tileData) end

--- Retrieves any tile animation data from the scripted tile.
--- @param position UnityEngine.Vector3Int Position of the Tile on the Tilemap.
--- @param tilemap UnityEngine.Tilemaps.ITilemap The Tilemap the tile is present on.
--- @param tileAnimationData UnityEngine.Tilemaps.TileAnimationData& Data to run an animation on the tile.
--- @return boolean Whether the call was successful.
function UnityEngine.Tilemaps.TileBase:GetTileAnimationData(position, tilemap, tileAnimationData) end

--- StartUp is called on the first frame of the running Scene.
--- @param position UnityEngine.Vector3Int Position of the Tile on the Tilemap.
--- @param tilemap UnityEngine.Tilemaps.ITilemap The Tilemap the tile is present on.
--- @param go UnityEngine.GameObject The GameObject instantiated for the Tile.
--- @return boolean Whether the call was successful.
function UnityEngine.Tilemaps.TileBase:StartUp(position, tilemap, go) end

---  Generated By xerysherry