--- @class UnityEngine.Collider:UnityEngine.Component A base class of all colliders.
--- @field enabled boolean property getset
---       Enabled Colliders will collide with other Colliders, disabled Colliders won't.
--- @field attachedRigidbody UnityEngine.Rigidbody property get
---       The rigidbody the collider is attached to.
--- @field isTrigger boolean property getset
---       Is the collider a trigger?
--- @field contactOffset number property getset
---       Contact offset value of this collider.
--- @field bounds UnityEngine.Bounds property get
---       The world space bounding volume of the collider (Read Only).
--- @field sharedMaterial UnityEngine.PhysicMaterial property getset
---       The shared physic material of this collider.
--- @field material UnityEngine.PhysicMaterial property getset
---       The material used by the collider.
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Collider = {}

function UnityEngine.Collider:set_enabled(value) end

function UnityEngine.Collider:set_isTrigger(value) end

function UnityEngine.Collider:set_contactOffset(value) end

--- Returns a point on the collider that is closest to a given location.
--- @param position UnityEngine.Vector3 Location you want to find the closest point to.
--- @return UnityEngine.Vector3 The point on the collider that is closest to the specified location.
function UnityEngine.Collider:ClosestPoint(position) end

function UnityEngine.Collider:set_sharedMaterial(value) end

function UnityEngine.Collider:set_material(value) end

--- Casts a Ray that ignores all Colliders except this one.
--- @param ray UnityEngine.Ray The starting point and direction of the ray.
--- @param maxDistance number The max length of the ray.
--- @return boolean True when the ray intersects the collider, otherwise false.
--- @return UnityEngine.RaycastHit& If true is returned, hitInfo will contain more information about where the collider was hit.
function UnityEngine.Collider:Raycast(ray, maxDistance) end

--- The closest point to the bounding box of the attached collider.
--- @param position UnityEngine.Vector3 
--- @return UnityEngine.Vector3 
function UnityEngine.Collider:ClosestPointOnBounds(position) end

---  Generated By xerysherry