--- @class UnityEngine.RenderBuffer Color or depth buffer part of a RenderTexture.
UnityEngine.RenderBuffer = {}

--- Returns native RenderBuffer. Be warned this is not native Texture, but rather pointer to unity struct that can be used with native unity API. Currently such API exists only on iOS.
--- @return System.IntPtr 
function UnityEngine.RenderBuffer:GetNativeRenderBufferPtr() end

---  Generated By xerysherry