--- @class UnityEngine.GridBrushBase.RotationDirection Rotate tiles in the GridBrushBase in this direction.
UnityEngine.GridBrushBase.RotationDirection = {
    --- Rotates tiles clockwise.
    Clockwise = 0,
    --- Rotates tiles counter-clockwise.
    CounterClockwise = 1,
}

---  Generated By xerysherry