--- @class UnityEngine.Rendering.VisibleLight Holds data of a visible light.
--- @field light UnityEngine.Light property get
---       Accessor to Light component.
--- @field lightType UnityEngine.LightType property getset
---       Light type.
--- @field finalColor UnityEngine.Color property getset
---       Light color multiplied by intensity.
--- @field screenRect UnityEngine.Rect property getset
---       Light's influence rectangle on screen.
--- @field localToWorldMatrix UnityEngine.Matrix4x4 property getset
---       Light transformation matrix.
--- @field range number property getset
---       Light range.
--- @field spotAngle number property getset
---       Spot light angle.
--- @field intersectsNearPlane boolean property getset
---       Light intersects near clipping plane.
--- @field intersectsFarPlane boolean property getset
---       Light intersects far clipping plane.
UnityEngine.Rendering.VisibleLight = {}

--- @return boolean
function UnityEngine.Rendering.VisibleLight.op_Equality(left, right) end

--- @return boolean
function UnityEngine.Rendering.VisibleLight.op_Inequality(left, right) end

function UnityEngine.Rendering.VisibleLight:set_lightType(value) end

function UnityEngine.Rendering.VisibleLight:set_finalColor(value) end

function UnityEngine.Rendering.VisibleLight:set_screenRect(value) end

function UnityEngine.Rendering.VisibleLight:set_localToWorldMatrix(value) end

function UnityEngine.Rendering.VisibleLight:set_range(value) end

function UnityEngine.Rendering.VisibleLight:set_spotAngle(value) end

function UnityEngine.Rendering.VisibleLight:set_intersectsNearPlane(value) end

function UnityEngine.Rendering.VisibleLight:set_intersectsFarPlane(value) end

--- @return boolean
function UnityEngine.Rendering.VisibleLight:Equals(other) end

--- @return boolean
function UnityEngine.Rendering.VisibleLight:Equals(obj) end

--- @return number
function UnityEngine.Rendering.VisibleLight:GetHashCode() end

---  Generated By xerysherry