--- @class UnityEngine.SubsystemDescriptor Information about a subsystem that can be queried before creating a subsystem instance.
--- @field id string property getset
---       A unique string that identifies the subsystem that this Descriptor can create.
--- @field subsystemImplementationType System.Type property getset
---       The System.Type of the subsystem implementation associated with this descriptor.
UnityEngine.SubsystemDescriptor = {}

function UnityEngine.SubsystemDescriptor:set_id(value) end

function UnityEngine.SubsystemDescriptor:set_subsystemImplementationType(value) end

---  Generated By xerysherry