--- @class UnityEngine.Rendering.RasterState Values for the raster state.
--- @field defaultValue UnityEngine.Rendering.RasterState Default values for the raster state.
--- @field cullingMode UnityEngine.Rendering.CullMode property getset
---       Controls which sides of polygons should be culled (not drawn).
--- @field depthClip boolean property getset
---       Enable clipping based on depth.
--- @field offsetUnits number property getset
---       Scales the minimum resolvable depth buffer value in the GPU's depth bias setting.
--- @field offsetFactor number property getset
---       Scales the maximum Z slope in the GPU's depth bias setting.
UnityEngine.Rendering.RasterState = {}

--- @param left UnityEngine.Rendering.RasterState 
--- @param right UnityEngine.Rendering.RasterState 
--- @return boolean
function UnityEngine.Rendering.RasterState.op_Equality(left, right) end

--- @param left UnityEngine.Rendering.RasterState 
--- @param right UnityEngine.Rendering.RasterState 
--- @return boolean
function UnityEngine.Rendering.RasterState.op_Inequality(left, right) end

--- @param value UnityEngine.Rendering.CullMode 
function UnityEngine.Rendering.RasterState:set_cullingMode(value) end

--- @param value boolean 
function UnityEngine.Rendering.RasterState:set_depthClip(value) end

--- @param value number 
function UnityEngine.Rendering.RasterState:set_offsetUnits(value) end

--- @param value number 
function UnityEngine.Rendering.RasterState:set_offsetFactor(value) end

--- @param other UnityEngine.Rendering.RasterState 
--- @return boolean
function UnityEngine.Rendering.RasterState:Equals(other) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.Rendering.RasterState:Equals(obj) end

--- @return number
function UnityEngine.Rendering.RasterState:GetHashCode() end

---  Generated By xerysherry