--- @class UnityEngine.ParticleSystemCullingMode The action to perform when the Particle System is offscreen.
UnityEngine.ParticleSystemCullingMode = {
    --- For looping effects, the simulation is paused when offscreen, and for one-shot effects, the simulation will continue playing.
    Automatic = 0,
    --- Pause the Particle System simulation when it is offscreen, and perform an extra simulation when the system comes back onscreen, creating the impression that it was never paused.
    PauseAndCatchup = 1,
    --- Pause the Particle System simulation when it is offscreen.
    Pause = 2,
    --- Continue simulating the Particle System when it is offscreen.
    AlwaysSimulate = 3,
}

---  Generated By xerysherry