--- @class UnityEngine.LightProbeProxyVolume.RefreshMode An enum describing the way a Light Probe Proxy Volume refreshes in the Player.
UnityEngine.LightProbeProxyVolume.RefreshMode = {
    --- Automatically detects updates in Light Probes and triggers an update of the Light Probe volume.
    Automatic = 0,
    --- Causes Unity to update the Light Probe Proxy Volume every frame.
    EveryFrame = 1,
    --- Use this option to indicate that the Light Probe Proxy Volume is never to be automatically updated by Unity.
    ViaScripting = 2,
}

--- @class UnityEngine.LightProbeProxyVolume.RefreshMode An enum describing the way a Light Probe Proxy Volume refreshes in the Player.
UnityEngine.LightProbeProxyVolume.RefreshMode = {
    --- Automatically detects updates in Light Probes and triggers an update of the Light Probe volume.
    Automatic = 0,
    --- Causes Unity to update the Light Probe Proxy Volume every frame.
    EveryFrame = 1,
    --- Use this option to indicate that the Light Probe Proxy Volume is never to be automatically updated by Unity.
    ViaScripting = 2,
}

---  Generated By xerysherry