--- @class UnityEngine.Windows.Speech.SemanticMeaning Semantic meaning is a collection of semantic properties of a recognized phrase. These semantic properties can be specified in SRGS grammar files.
--- @field key string A key of semantic meaning.
--- @field values string[] Values of semantic property that the correspond to the semantic meaning key.
UnityEngine.Windows.Speech.SemanticMeaning = {}

---  Generated By xerysherry