--- @class UnityEngine.XR.InputFeatureUsage Defines a generic usage that maps to an input feature on a device. Use the As method to turn into a generic usage.
--- @field name string property get
---       The string name of this usage feature; used internally to map to an input feature on a device.
--- @field type System.Type property get
---       The type of this usage feature; used internally to map to an input feature on a device.
UnityEngine.XR.InputFeatureUsage = {}

--- @return boolean
function UnityEngine.XR.InputFeatureUsage.op_Equality(a, b) end

--- @return boolean
function UnityEngine.XR.InputFeatureUsage.op_Inequality(a, b) end

--- @return boolean
function UnityEngine.XR.InputFeatureUsage:Equals(obj) end

--- @return boolean
function UnityEngine.XR.InputFeatureUsage:Equals(other) end

--- @return number
function UnityEngine.XR.InputFeatureUsage:GetHashCode() end

--- Returns the generic version of this type for retrieving a feature value from a device.
--- @return UnityEngine.XR.InputFeatureUsage`1 
function UnityEngine.XR.InputFeatureUsage:As() end

---  Generated By xerysherry