--- @class UnityEngine.WaitForFixedUpdate:UnityEngine.YieldInstruction Waits until next fixed frame rate update function. See Also: MonoBehaviour.FixedUpdate.
UnityEngine.WaitForFixedUpdate = {}

---  Generated By xerysherry