--- @class UnityEngine.Windows.WebCam.WebCam Contains general information about the current state of the web camera.
--- @field Mode UnityEngine.Windows.WebCam.WebCamMode property get
---       Specifies what mode the Web Camera is currently in.
UnityEngine.Windows.WebCam.WebCam = {}

---  Generated By xerysherry