--- @class Unity.Jobs.IJobForExtensions Extension methods for Jobs using the IJobFor.
Unity.Jobs.IJobForExtensions = {}

--- Schedule the job for execution on a single worker thread.
--- @param jobData Unity.Jobs.IJobForExtensions.T The job and data to Schedule.
--- @param arrayLength number The number of iterations the for loop will execute.
--- @param dependency Unity.Jobs.JobHandle Dependencies are used to ensure that a job executes on worker threads after the dependency has completed execution. Making sure that two jobs reading or writing to same data do not run in parallel.
--- @return Unity.Jobs.JobHandle The handle identifying the scheduled job. Can be used as a dependency for a later job or ensure completion on the main thread.
function Unity.Jobs.IJobForExtensions.Schedule(jobData, arrayLength, dependency) end

--- Schedule the job for concurrent execution on a number of worker threads.
--- @param jobData Unity.Jobs.IJobForExtensions.T The job and data to Schedule.
--- @param arrayLength number The number of iterations the for loop will execute.
--- @param innerloopBatchCount number Granularity in which workstealing is performed. A value of 32, means the job queue will steal 32 iterations and then perform them in an efficient inner loop.
--- @param dependency Unity.Jobs.JobHandle Dependencies are used to ensure that a job executes on worker threads after the dependency has completed execution. Making sure that two jobs reading or writing to same data do not run in parallel.
--- @return Unity.Jobs.JobHandle The handle identifying the scheduled job. Can be used as a dependency for a later job or ensure completion on the main thread.
function Unity.Jobs.IJobForExtensions.ScheduleParallel(jobData, arrayLength, innerloopBatchCount, dependency) end

--- Perform the job's Execute method immediately on the main thread.
--- @param jobData Unity.Jobs.IJobForExtensions.T The job and data to Run.
--- @param arrayLength number The number of iterations the for loop will execute.
function Unity.Jobs.IJobForExtensions.Run(jobData, arrayLength) end

---  Generated By xerysherry