--- @class UnityEngine.SystemLanguage The language the user's operating system is running in. Returned by Application.systemLanguage.
UnityEngine.SystemLanguage = {
    --- Afrikaans.
    Afrikaans = 0,
    --- Arabic.
    Arabic = 1,
    --- Basque.
    Basque = 2,
    --- Belarusian.
    Belarusian = 3,
    --- Bulgarian.
    Bulgarian = 4,
    --- Catalan.
    Catalan = 5,
    --- Chinese.
    Chinese = 6,
    --- Czech.
    Czech = 7,
    --- Danish.
    Danish = 8,
    --- Dutch.
    Dutch = 9,
    --- English.
    English = 10,
    --- Estonian.
    Estonian = 11,
    --- Faroese.
    Faroese = 12,
    --- Finnish.
    Finnish = 13,
    --- French.
    French = 14,
    --- German.
    German = 15,
    --- Greek.
    Greek = 16,
    --- Hebrew.
    Hebrew = 17,
    --- Icelandic.
    Icelandic = 19,
    --- Indonesian.
    Indonesian = 20,
    --- Italian.
    Italian = 21,
    --- Japanese.
    Japanese = 22,
    --- Korean.
    Korean = 23,
    --- Latvian.
    Latvian = 24,
    --- Lithuanian.
    Lithuanian = 25,
    --- Norwegian.
    Norwegian = 26,
    --- Polish.
    Polish = 27,
    --- Portuguese.
    Portuguese = 28,
    --- Romanian.
    Romanian = 29,
    --- Russian.
    Russian = 30,
    --- Serbo-Croatian.
    SerboCroatian = 31,
    --- Slovak.
    Slovak = 32,
    --- Slovenian.
    Slovenian = 33,
    --- Spanish.
    Spanish = 34,
    --- Swedish.
    Swedish = 35,
    --- Thai.
    Thai = 36,
    --- Turkish.
    Turkish = 37,
    --- Ukrainian.
    Ukrainian = 38,
    --- Vietnamese.
    Vietnamese = 39,
    --- ChineseSimplified.
    ChineseSimplified = 40,
    --- ChineseTraditional.
    ChineseTraditional = 41,
    --- Unknown.
    Unknown = 42,
    --- Hungarian.
    Hungarian = 18,
}

---  Generated By xerysherry