--- @class UnityEngine.Rendering.LODParameters LODGroup culling parameters.
--- @field isOrthographic boolean property getset
---       Indicates whether camera is orthographic.
--- @field cameraPosition UnityEngine.Vector3 property getset
---       Camera position.
--- @field fieldOfView number property getset
---       Camera's field of view.
--- @field orthoSize number property getset
---       Orhographic camera size.
--- @field cameraPixelHeight number property getset
---       Rendering view height in pixels.
UnityEngine.Rendering.LODParameters = {}

--- @param left UnityEngine.Rendering.LODParameters 
--- @param right UnityEngine.Rendering.LODParameters 
--- @return boolean
function UnityEngine.Rendering.LODParameters.op_Equality(left, right) end

--- @param left UnityEngine.Rendering.LODParameters 
--- @param right UnityEngine.Rendering.LODParameters 
--- @return boolean
function UnityEngine.Rendering.LODParameters.op_Inequality(left, right) end

--- @param value boolean 
function UnityEngine.Rendering.LODParameters:set_isOrthographic(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.Rendering.LODParameters:set_cameraPosition(value) end

--- @param value number 
function UnityEngine.Rendering.LODParameters:set_fieldOfView(value) end

--- @param value number 
function UnityEngine.Rendering.LODParameters:set_orthoSize(value) end

--- @param value number 
function UnityEngine.Rendering.LODParameters:set_cameraPixelHeight(value) end

--- @param other UnityEngine.Rendering.LODParameters 
--- @return boolean
function UnityEngine.Rendering.LODParameters:Equals(other) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.Rendering.LODParameters:Equals(obj) end

--- @return number
function UnityEngine.Rendering.LODParameters:GetHashCode() end

---  Generated By xerysherry