--- @class UnityEngine.Playables.PlayState Status of a Playable.
UnityEngine.Playables.PlayState = {
    --- The Playable has been paused. Its local time will not advance.
    Paused = 0,
    --- The Playable is currently Playing.
    Playing = 1,
}

---  Generated By xerysherry