--- @class UnityEngine.ComputeBuffer GPU data buffer, mostly for use with compute shaders.
--- @field count number property get
---       Number of elements in the buffer (Read Only).
--- @field stride number property get
---       Size of one element in the buffer (Read Only).
--- @field name string property set
---       The debug label for the ComputeBuffer. This name shows up in profiling and frame debugger tools, wherever supported.
UnityEngine.ComputeBuffer = {}

--- Copy counter value of append/consume buffer into another buffer.
--- @param src UnityEngine.ComputeBuffer Append/consume buffer to copy the counter from.
--- @param dst UnityEngine.ComputeBuffer A buffer to copy the counter to.
--- @param dstOffsetBytes number Target byte offset in dst.
function UnityEngine.ComputeBuffer.CopyCount(src, dst, dstOffsetBytes) end

function UnityEngine.ComputeBuffer:Dispose() end

--- Release a Compute Buffer.
function UnityEngine.ComputeBuffer:Release() end

--- Returns true if this compute buffer is valid and false otherwise.
--- @return boolean 
function UnityEngine.ComputeBuffer:IsValid() end

--- Set the buffer with values from an array.
--- @param data table Array of values to fill the buffer.
function UnityEngine.ComputeBuffer:SetData(data) end

--- Set the buffer with values from an array.
--- @param data UnityEngine.ComputeBuffer.T[] Array of values to fill the buffer.
function UnityEngine.ComputeBuffer:SetData(data) end

--- Set the buffer with values from an array.
--- @param data Unity.Collections.NativeArray`1 Array of values to fill the buffer.
function UnityEngine.ComputeBuffer:SetData(data) end

--- Set the buffer with values from an array.
--- @param data table 
--- @param managedBufferStartIndex number 
--- @param computeBufferStartIndex number 
--- @param count number 
function UnityEngine.ComputeBuffer:SetData(data, managedBufferStartIndex, computeBufferStartIndex, count) end

--- Set the buffer with values from an array.
--- @param data UnityEngine.ComputeBuffer.T[] 
--- @param managedBufferStartIndex number 
--- @param computeBufferStartIndex number 
--- @param count number 
function UnityEngine.ComputeBuffer:SetData(data, managedBufferStartIndex, computeBufferStartIndex, count) end

--- Set the buffer with values from an array.
--- @param data Unity.Collections.NativeArray`1 
--- @param nativeBufferStartIndex number 
--- @param computeBufferStartIndex number 
--- @param count number 
function UnityEngine.ComputeBuffer:SetData(data, nativeBufferStartIndex, computeBufferStartIndex, count) end

--- Read data values from the buffer into an array. The array can only use <a href="https:docs.microsoft.comen-usdotnetframeworkinteropblittable-and-non-blittable-types">blittable<a> types.
--- @param data table An array to receive the data.
function UnityEngine.ComputeBuffer:GetData(data) end

--- Partial read of data values from the buffer into an array.
--- @param data table An array to receive the data.
--- @param managedBufferStartIndex number The first element index in data where retrieved elements are copied.
--- @param computeBufferStartIndex number The first element index of the compute buffer from which elements are read.
--- @param count number The number of elements to retrieve.
function UnityEngine.ComputeBuffer:GetData(data, managedBufferStartIndex, computeBufferStartIndex, count) end

--- @param value string 
function UnityEngine.ComputeBuffer:set_name(value) end

--- Sets counter value of append/consume buffer.
--- @param counterValue number Value of the append/consume counter.
function UnityEngine.ComputeBuffer:SetCounterValue(counterValue) end

--- Retrieve a native (underlying graphics API) pointer to the buffer.
--- @return System.IntPtr Pointer to the underlying graphics API buffer.
function UnityEngine.ComputeBuffer:GetNativeBufferPtr() end

---  Generated By xerysherry