--- @class UnityEngine.UI.Slider:UnityEngine.UI.Selectable 
--- @field fillRect UnityEngine.RectTransform
--- @field handleRect UnityEngine.RectTransform
--- @field direction UnityEngine.UI.Slider.Direction
--- @field minValue number
--- @field maxValue number
--- @field wholeNumbers boolean
--- @field value number
--- @field normalizedValue number
--- @field onValueChanged UnityEngine.UI.Slider.SliderEvent
--- @field navigation UnityEngine.UI.Navigation
--- @field transition UnityEngine.UI.Selectable.Transition
--- @field colors UnityEngine.UI.ColorBlock
--- @field spriteState UnityEngine.UI.SpriteState
--- @field animationTriggers UnityEngine.UI.AnimationTriggers
--- @field targetGraphic UnityEngine.UI.Graphic
--- @field interactable boolean
--- @field image UnityEngine.UI.Image
--- @field animator UnityEngine.Animator
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.Slider = {}

--- @param value UnityEngine.RectTransform 
function UnityEngine.UI.Slider:set_fillRect(value) end

--- @param value UnityEngine.RectTransform 
function UnityEngine.UI.Slider:set_handleRect(value) end

--- @param value UnityEngine.UI.Slider.Direction 
function UnityEngine.UI.Slider:set_direction(value) end

--- @param value number 
function UnityEngine.UI.Slider:set_minValue(value) end

--- @param value number 
function UnityEngine.UI.Slider:set_maxValue(value) end

--- @param value boolean 
function UnityEngine.UI.Slider:set_wholeNumbers(value) end

--- @param value number 
function UnityEngine.UI.Slider:set_value(value) end

--- @param input number 
function UnityEngine.UI.Slider:SetValueWithoutNotify(input) end

--- @param value number 
function UnityEngine.UI.Slider:set_normalizedValue(value) end

--- @param value UnityEngine.UI.Slider.SliderEvent 
function UnityEngine.UI.Slider:set_onValueChanged(value) end

--- @param executing UnityEngine.UI.CanvasUpdate 
function UnityEngine.UI.Slider:Rebuild(executing) end

function UnityEngine.UI.Slider:LayoutComplete() end

function UnityEngine.UI.Slider:GraphicUpdateComplete() end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.UI.Slider:OnPointerDown(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.UI.Slider:OnDrag(eventData) end

--- @param eventData UnityEngine.EventSystems.AxisEventData 
function UnityEngine.UI.Slider:OnMove(eventData) end

--- @return UnityEngine.UI.Selectable
function UnityEngine.UI.Slider:FindSelectableOnLeft() end

--- @return UnityEngine.UI.Selectable
function UnityEngine.UI.Slider:FindSelectableOnRight() end

--- @return UnityEngine.UI.Selectable
function UnityEngine.UI.Slider:FindSelectableOnUp() end

--- @return UnityEngine.UI.Selectable
function UnityEngine.UI.Slider:FindSelectableOnDown() end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.UI.Slider:OnInitializePotentialDrag(eventData) end

--- @param direction UnityEngine.UI.Slider.Direction 
--- @param includeRectLayouts boolean 
function UnityEngine.UI.Slider:SetDirection(direction, includeRectLayouts) end

---  Generated By xerysherry