--- @class UnityEngine.XR.InputTracking A collection of methods and properties for accessing XR input devices by their XR Node representation.
--- @field disablePositionalTracking boolean property getset
---       Disables positional tracking in XR. This takes effect the next time the head pose is sampled.  If set to true the camera only tracks headset rotation state.
UnityEngine.XR.InputTracking = {}

--- @param value function 
function UnityEngine.XR.InputTracking.add_trackingAcquired(value) end

--- @param value function 
function UnityEngine.XR.InputTracking.remove_trackingAcquired(value) end

--- @param value function 
function UnityEngine.XR.InputTracking.add_trackingLost(value) end

--- @param value function 
function UnityEngine.XR.InputTracking.remove_trackingLost(value) end

--- @param value function 
function UnityEngine.XR.InputTracking.add_nodeAdded(value) end

--- @param value function 
function UnityEngine.XR.InputTracking.remove_nodeAdded(value) end

--- @param value function 
function UnityEngine.XR.InputTracking.add_nodeRemoved(value) end

--- @param value function 
function UnityEngine.XR.InputTracking.remove_nodeRemoved(value) end

--- Note: This API has been marked as obsolete in code, and is no longer in use. Please use InputTracking.GetNodeStates and look for the XRNodeState with the corresponding XRNode type instead.
--- Gets the position of a specific node.
--- @param node UnityEngine.XR.XRNode Specifies which node's position should be returned.
--- @return UnityEngine.Vector3 The position of the node in its local tracking space.
function UnityEngine.XR.InputTracking.GetLocalPosition(node) end

--- Note: This API has been marked as obsolete in code, and is no longer in use. Please use InputTracking.GetNodeStates and look for the XRNodeState with the corresponding XRNode type instead.
--- Gets the rotation of a specific node.
--- @param node UnityEngine.XR.XRNode Specifies which node's rotation should be returned.
--- @return UnityEngine.Quaternion The rotation of the node in its local tracking space.
function UnityEngine.XR.InputTracking.GetLocalRotation(node) end

--- Center tracking to the current position and orientation of the HMD.
function UnityEngine.XR.InputTracking.Recenter() end

--- Accepts the unique identifier for a tracked node and returns a friendly name for it.
--- @param uniqueId number 
--- @return string The name of the tracked node if the given 64-bit identifier maps to a currently tracked node. Empty string otherwise.
function UnityEngine.XR.InputTracking.GetNodeName(uniqueId) end

--- Describes all currently connected XRNodes and provides available tracking states for each.
--- @param nodeStates UnityEngine.XR.XRNodeState[] A list that is populated with XR.XRNodeState objects.
function UnityEngine.XR.InputTracking.GetNodeStates(nodeStates) end

--- @param value boolean 
function UnityEngine.XR.InputTracking.set_disablePositionalTracking(value) end

---  Generated By xerysherry