--- @class UnityEngine.AvatarMaskBodyPart Avatar body part.
UnityEngine.AvatarMaskBodyPart = {
    --- The Root.
    Root = 0,
    --- The Body.
    Body = 1,
    --- The Head.
    Head = 2,
    --- The Left Leg.
    LeftLeg = 3,
    --- The Right Leg.
    RightLeg = 4,
    --- The Left Arm.
    LeftArm = 5,
    --- The Right Arm.
    RightArm = 6,
    --- Left Fingers.
    LeftFingers = 7,
    --- Right Fingers.
    RightFingers = 8,
    --- Left Foot IK.
    LeftFootIK = 9,
    --- Right Foot IK.
    RightFootIK = 10,
    --- Left Hand IK.
    LeftHandIK = 11,
    --- Right Hand IK.
    RightHandIK = 12,
    --- Total number of body parts.
    LastBodyPart = 13,
}

---  Generated By xerysherry