--- @class UnityEngine.UIElements.IBindingExtensions Extensions methods to provide additional IBindable functionality.
UnityEngine.UIElements.IBindingExtensions = {}

--- Checks if a IBindable is bound to a property.
--- @param control UnityEngine.UIElements.IBindable This Bindable object.
--- @return boolean True if this IBindable is bound to a property.
function UnityEngine.UIElements.IBindingExtensions.IsBound(control) end

---  Generated By xerysherry