--- @class UnityEngine.Analytics.AnalyticsEventPriority Analytics event priority.
UnityEngine.Analytics.AnalyticsEventPriority = {
    --- Any current or previous events in the memory queue persist immediately to the filesystem and dispatcher service makes the events available to send to the server. It adds the events to the bottom of the dispatch queue and makes them available to send to the server.
    FlushQueueFlag = 1,
    --- Any current or previous events in the memory queue persist immediately to the filesystem.
    CacheImmediatelyFlag = 2,
    --- Use this flag to send events while in the stop state.
    AllowInStopModeFlag = 4,
    --- Events with this flag are given higher priority compared to others while dispatching to the server.
    SendImmediateFlag = 8,
    --- This priority queues events in-memory.
    NormalPriorityEvent = 0,
    --- This priority queues events in-memory and writes them to the filesystem immediately.
    NormalPriorityEvent_WithCaching = 2,
    --- Any current or previous events in the memory queue persist immediately to the filesystem. It adds the events to the bottom of the dispatch queue and makes them available to send to the server.
    HighPriorityEvent = 1,
    --- This priority lets you send events in the stop state, and makes any current or previous events in the memory queue persist immediately to the filesystem. It adds the events to the bottom of the dispatch queue and makes them available to send to the server.
    HighPriorityEvent_InStopMode = 5,
    --- This priority is similar to the Analytics.AnalyticsEventPriority.HighPriorityEvent, except these events are given a highest priority than other events in the disptach queue. It adds the events to the top of the dispatch queue and makes them available to send to the server.
    HighestPriorityEvent = 9,
}

---  Generated By xerysherry