--- @class UnityEngine.NetworkViewID The NetworkViewID is a unique identifier for a network view instance in a multiplayer game.
--- @field unassigned UnityEngine.NetworkViewID property get
---       Represents an invalid network view ID.
--- @field isMine boolean property get
---       True if instantiated by me.
--- @field owner UnityEngine.NetworkPlayer property get
---       The NetworkPlayer who owns the NetworkView. Could be the server.
UnityEngine.NetworkViewID = {}

---  Generated By xerysherry