--- @class UnityEngine.Audio.AudioMixer:UnityEngine.Object AudioMixer asset.
--- @field outputAudioMixerGroup UnityEngine.Audio.AudioMixerGroup property getset
---       Routing target.
--- @field updateMode UnityEngine.Audio.AudioMixerUpdateMode property getset
---       How time should progress for this AudioMixer. Used during Snapshot transitions.
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Audio.AudioMixer = {}

function UnityEngine.Audio.AudioMixer:set_outputAudioMixerGroup(value) end

--- The name must be an exact match.
--- @param name string Name of snapshot object to be returned.
--- @return UnityEngine.Audio.AudioMixerSnapshot The snapshot identified by the name.
function UnityEngine.Audio.AudioMixer:FindSnapshot(name) end

--- Connected groups in the mixer form a path from the mixer's master group to the leaves. This path has the format "Master GroupChild of Master GroupGrandchild of Master Group", so to find the grandchild group in this example, a valid search string would be for instance "randchi" which would return exactly one group while "hild" or "oup/" would return 2 different groups.
--- @param subPath string Sub-string of the paths to be matched.
--- @return UnityEngine.Audio.AudioMixerGroup[] Groups in the mixer whose paths match the specified search path.
function UnityEngine.Audio.AudioMixer:FindMatchingGroups(subPath) end

--- Transitions to a weighted mixture of the snapshots specified. This can be used for games that specify the game state as a continuum between states or for interpolating snapshots from a triangulated map location.
--- @param snapshots UnityEngine.Audio.AudioMixerSnapshot[] The set of snapshots to be mixed.
--- @param weights number[] The mix weights for the snapshots specified.
--- @param timeToReach number Relative time after which the mixture should be reached from any current state.
function UnityEngine.Audio.AudioMixer:TransitionToSnapshots(snapshots, weights, timeToReach) end

function UnityEngine.Audio.AudioMixer:set_updateMode(value) end

--- Sets the value of the exposed parameter specified. When a parameter is exposed, it is not controlled by mixer snapshots and can therefore only be changed via this function.
--- @param name string Name of exposed parameter.
--- @param value number New value of exposed parameter.
--- @return boolean Returns false if the exposed parameter was not found or snapshots are currently being edited.
function UnityEngine.Audio.AudioMixer:SetFloat(name, value) end

--- Resets an exposed parameter to its initial value.
--- @param name string Exposed parameter.
--- @return boolean Returns false if the parameter was not found or could not be set.
function UnityEngine.Audio.AudioMixer:ClearFloat(name) end

--- Returns the value of the exposed parameter specified. If the parameter doesn't exist the function returns false. Prior to calling SetFloat and after ClearFloat has been called on this parameter the value returned will be that of the current snapshot or snapshot transition.
--- @param name string Name of exposed parameter.
--- @return boolean Returns false if the exposed parameter specified doesn't exist.
--- @return System.Single& Return value of exposed parameter.
function UnityEngine.Audio.AudioMixer:GetFloat(name) end

---  Generated By xerysherry