--- @class UnityEngine.iOS.Device Interface into iOS specific functionality.
--- @field systemVersion string property get
---       iOS version.
--- @field generation UnityEngine.iOS.DeviceGeneration property get
---       The generation of the device. (Read Only)
--- @field vendorIdentifier string property get
---       Vendor ID.
--- @field advertisingIdentifier string property get
---       Advertising ID.
--- @field advertisingTrackingEnabled boolean property get
---       Is advertising tracking enabled.
--- @field hideHomeButton boolean property getset
---       Specifies whether the home button should be hidden in the iOS build of this application.
--- @field lowPowerModeEnabled boolean property get
---       Indicates whether Low Power Mode is enabled on the device.
--- @field wantsSoftwareDimming boolean property getset
---       Indicates whether the screen may be dimmed lower than the hardware is normally capable of by emulating it in software.
--- @field iosAppOnMac boolean property get
---       Specifies whether app built for iOS is running on Mac.
--- @field deferSystemGesturesMode UnityEngine.iOS.SystemGestureDeferMode property getset
---       Defer system gestures until the second swipe on specific edges.
UnityEngine.iOS.Device = {}

function UnityEngine.iOS.Device.set_hideHomeButton(value) end

function UnityEngine.iOS.Device.set_wantsSoftwareDimming(value) end

function UnityEngine.iOS.Device.set_deferSystemGesturesMode(value) end

--- Set file flag to be excluded from iCloud/iTunes backup.
--- @param path string 
function UnityEngine.iOS.Device.SetNoBackupFlag(path) end

--- Reset "no backup" file flag: file will be synced with iCloud/iTunes backup and can be deleted by OS in low storage situations.
--- @param path string 
function UnityEngine.iOS.Device.ResetNoBackupFlag(path) end

--- Request App Store rating and review from the user.
--- @return boolean Value indicating whether the underlying API is available or not. False indicates that the iOS version isn't recent enough or that the StoreKit framework is not linked with the app.
function UnityEngine.iOS.Device.RequestStoreReview() end

---  Generated By xerysherry