--- @class UnityEngine.UI.Shadow:UnityEngine.UI.BaseMeshEffect 
--- @field effectColor UnityEngine.Color
--- @field effectDistance UnityEngine.Vector2
--- @field useGraphicAlpha boolean
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.Shadow = {}

function UnityEngine.UI.Shadow:set_effectColor(value) end

function UnityEngine.UI.Shadow:set_effectDistance(value) end

function UnityEngine.UI.Shadow:set_useGraphicAlpha(value) end

function UnityEngine.UI.Shadow:ModifyMesh(vh) end

---  Generated By xerysherry