--- @class Unity.Profiling.ProfilerMarker Performance marker used for profiling arbitrary code blocks.
Unity.Profiling.ProfilerMarker = {}

--- Begin profiling a piece of code marked with a custom name defined by this instance of ProfilerMarker.
function Unity.Profiling.ProfilerMarker:Begin() end

--- Begin profiling a piece of code marked with a custom name defined by this instance of ProfilerMarker.
--- @param contextUnityObject UnityEngine.Object Object associated with the operation.
function Unity.Profiling.ProfilerMarker:Begin(contextUnityObject) end

--- End profiling a piece of code marked with a custom name defined by this instance of ProfilerMarker.
function Unity.Profiling.ProfilerMarker:End() end

--- Creates a helper struct for the scoped using blocks.
--- @return Unity.Profiling.ProfilerMarker.AutoScope IDisposable struct which calls Begin and End automatically.
function Unity.Profiling.ProfilerMarker:Auto() end

---  Generated By xerysherry