--- @class UnityEngine.XR.InputDeviceRole Enumeration describing the role of a XR.InputDevice in providing input.
UnityEngine.XR.InputDeviceRole = {
    --- This device does not have a known role.
    Unknown = 0,
    --- This device is typically a HMD or Camera.
    Generic = 1,
    --- This device is a controller that represents the left hand.
    LeftHanded = 2,
    --- This device is a controller that represents the right hand.
    RightHanded = 3,
    --- This device is a game controller.
    GameController = 4,
    --- This device is a tracking reference used to track other devices in 3D.
    TrackingReference = 5,
    --- This device is a hardware tracker.
    HardwareTracker = 6,
    --- This device is a legacy controller.
    LegacyController = 7,
}

---  Generated By xerysherry