--- @class UnityEngine.DelayedAttribute:UnityEngine.PropertyAttribute Attribute used to make a float, int, or string variable in a script be delayed.
--- @field order number
--- @field TypeId System.Object
UnityEngine.DelayedAttribute = {}

---  Generated By xerysherry