--- @class UnityEngine.Rendering.ShaderPropertyFlags Flags that control how a shader property behaves.
UnityEngine.Rendering.ShaderPropertyFlags = {
    --- No flags are set.
    None = 0,
    --- Signifies that Unity hides the property in the default Material Inspector.
    HideInInspector = 1,
    --- Unity queries the Texture value for this property from the renderer's MaterialPropertyBlock, instead of from the Material.
    PerRendererData = 2,
    --- Do not show UV scale/offset fields next to Textures in the default Material Inspector.
    NoScaleOffset = 4,
    --- Signifies that values of this property contain Normal (normalized vector) data.
    Normal = 8,
    --- Signifies that values of this property contain High Dynamic Range (HDR) data.
    HDR = 16,
    --- Signifies that values of this property are in gamma space. If the active color space is linear, Unity converts the values to linear space values.
    Gamma = 32,
    --- You cannot edit this Texture property in the default Material Inspector.
    NonModifiableTextureData = 64,
    --- Signifies that value of this property contains the main texture of the Material.
    MainTexture = 128,
    --- Signifies that value of this property contains the main color of the Material.
    MainColor = 256,
}

---  Generated By xerysherry