--- @class UnityEngine.UIElements.MouseCaptureOutEvent:UnityEngine.UIElements.MouseCaptureEventBase`1 Event sent before a handler stops capturing the mouse.
--- @field relatedTarget UnityEngine.UIElements.IEventHandler
--- @field pointerId number
--- @field eventTypeId number
--- @field timestamp number
--- @field bubbles boolean
--- @field tricklesDown boolean
--- @field target UnityEngine.UIElements.IEventHandler
--- @field isPropagationStopped boolean
--- @field isImmediatePropagationStopped boolean
--- @field isDefaultPrevented boolean
--- @field propagationPhase UnityEngine.UIElements.PropagationPhase
--- @field currentTarget UnityEngine.UIElements.IEventHandler
--- @field dispatch boolean
--- @field imguiEvent UnityEngine.Event
--- @field originalMousePosition UnityEngine.Vector2
UnityEngine.UIElements.MouseCaptureOutEvent = {}

---  Generated By xerysherry