--- @class UnityEngine.ExcludeFromPresetAttribute:System.Attribute Add this attribute to a class to prevent creating a Preset from the instances of the class.
--- @field TypeId System.Object
UnityEngine.ExcludeFromPresetAttribute = {}

---  Generated By xerysherry