--- @class UnityEngine.Playables.Notification Default implementation for Playable notifications.
--- @field id UnityEngine.PropertyName property get
---       The name that identifies this notification.
UnityEngine.Playables.Notification = {}

---  Generated By xerysherry