--- @class UnityEngine.Networking.DownloadHandlerTexture:UnityEngine.Networking.DownloadHandler A DownloadHandler subclass specialized for downloading images for use as Texture objects.
--- @field texture UnityEngine.Texture2D property get
---       Returns the downloaded Texture, or null. (Read Only)
--- @field isDone boolean
--- @field data number[]
--- @field text string
UnityEngine.Networking.DownloadHandlerTexture = {}

--- Returns the downloaded Texture, or null.
--- @param www UnityEngine.Networking.UnityWebRequest A finished UnityWebRequest object with DownloadHandlerTexture attached.
--- @return UnityEngine.Texture2D The same as DownloadHandlerTexture.texture
function UnityEngine.Networking.DownloadHandlerTexture.GetContent(www) end

---  Generated By xerysherry