--- @class UnityEngine.SocialPlatforms.Impl.UserProfile 
--- @field userName string
--- @field id string
--- @field legacyId string property get
---       Returns the ID provided in the Apple GameKit by GKPlayer.playerID (deprecated and marked obsolete in iOS 12.4).
--- @field gameId string
--- @field isFriend boolean
--- @field state UnityEngine.SocialPlatforms.UserState
--- @field image UnityEngine.Texture2D
UnityEngine.SocialPlatforms.Impl.UserProfile = {}

--- @return string
function UnityEngine.SocialPlatforms.Impl.UserProfile:ToString() end

function UnityEngine.SocialPlatforms.Impl.UserProfile:SetUserName(name) end

function UnityEngine.SocialPlatforms.Impl.UserProfile:SetUserID(id) end

function UnityEngine.SocialPlatforms.Impl.UserProfile:SetLegacyUserID(id) end

function UnityEngine.SocialPlatforms.Impl.UserProfile:SetUserGameID(id) end

function UnityEngine.SocialPlatforms.Impl.UserProfile:SetImage(image) end

function UnityEngine.SocialPlatforms.Impl.UserProfile:SetIsFriend(value) end

function UnityEngine.SocialPlatforms.Impl.UserProfile:SetState(state) end

---  Generated By xerysherry