--- @class UnityEngine.PhysicMaterial:UnityEngine.Object Physics material describes how to handle colliding objects (friction, bounciness).
--- @field bounciness number property getset
---       How bouncy is the surface? A value of 0 will not bounce. A value of 1 will bounce without any loss of energy.
--- @field dynamicFriction number property getset
---       The friction used when already moving.  This value is usually between 0 and 1.
--- @field staticFriction number property getset
---       The friction coefficient used when an object is lying on a surface.
--- @field frictionCombine UnityEngine.PhysicMaterialCombine property getset
---       Determines how the friction is combined.
--- @field bounceCombine UnityEngine.PhysicMaterialCombine property getset
---       Determines how the bounciness is combined.
--- @field bouncyness number
--- @field frictionDirection2 UnityEngine.Vector3 property getset
---       The direction of anisotropy. Anisotropic friction is enabled if the vector is not zero.
--- @field dynamicFriction2 number property getset
---       If anisotropic friction is enabled, dynamicFriction2 will be applied along frictionDirection2.
--- @field staticFriction2 number property getset
---       If anisotropic friction is enabled, staticFriction2 will be applied along frictionDirection2.
--- @field frictionDirection UnityEngine.Vector3
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.PhysicMaterial = {}

function UnityEngine.PhysicMaterial:set_bounciness(value) end

function UnityEngine.PhysicMaterial:set_dynamicFriction(value) end

function UnityEngine.PhysicMaterial:set_staticFriction(value) end

function UnityEngine.PhysicMaterial:set_frictionCombine(value) end

function UnityEngine.PhysicMaterial:set_bounceCombine(value) end

function UnityEngine.PhysicMaterial:set_bouncyness(value) end

function UnityEngine.PhysicMaterial:set_frictionDirection2(value) end

function UnityEngine.PhysicMaterial:set_dynamicFriction2(value) end

function UnityEngine.PhysicMaterial:set_staticFriction2(value) end

function UnityEngine.PhysicMaterial:set_frictionDirection(value) end

---  Generated By xerysherry