--- @class UnityEngine.BoneWeight Describes 4 skinning bone weights that affect a vertex in a mesh.
--- @field weight0 number property getset
---       Skinning weight for first bone.
--- @field weight1 number property getset
---       Skinning weight for second bone.
--- @field weight2 number property getset
---       Skinning weight for third bone.
--- @field weight3 number property getset
---       Skinning weight for fourth bone.
--- @field boneIndex0 number property getset
---       Index of first bone.
--- @field boneIndex1 number property getset
---       Index of second bone.
--- @field boneIndex2 number property getset
---       Index of third bone.
--- @field boneIndex3 number property getset
---       Index of fourth bone.
UnityEngine.BoneWeight = {}

--- @param lhs UnityEngine.BoneWeight 
--- @param rhs UnityEngine.BoneWeight 
--- @return boolean
function UnityEngine.BoneWeight.op_Equality(lhs, rhs) end

--- @param lhs UnityEngine.BoneWeight 
--- @param rhs UnityEngine.BoneWeight 
--- @return boolean
function UnityEngine.BoneWeight.op_Inequality(lhs, rhs) end

--- @param value number 
function UnityEngine.BoneWeight:set_weight0(value) end

--- @param value number 
function UnityEngine.BoneWeight:set_weight1(value) end

--- @param value number 
function UnityEngine.BoneWeight:set_weight2(value) end

--- @param value number 
function UnityEngine.BoneWeight:set_weight3(value) end

--- @param value number 
function UnityEngine.BoneWeight:set_boneIndex0(value) end

--- @param value number 
function UnityEngine.BoneWeight:set_boneIndex1(value) end

--- @param value number 
function UnityEngine.BoneWeight:set_boneIndex2(value) end

--- @param value number 
function UnityEngine.BoneWeight:set_boneIndex3(value) end

--- @return number
function UnityEngine.BoneWeight:GetHashCode() end

--- @param other System.Object 
--- @return boolean
function UnityEngine.BoneWeight:Equals(other) end

--- @param other UnityEngine.BoneWeight 
--- @return boolean
function UnityEngine.BoneWeight:Equals(other) end

---  Generated By xerysherry