--- @class UnityEngine.Resources The Resources class allows you to find and access Objects including assets.
UnityEngine.Resources = {}

--- Returns a list of all objects of Type type.
--- @param type System.Type 
--- @return UnityEngine.Object[] 
function UnityEngine.Resources.FindObjectsOfTypeAll(type) end

--- Returns a list of all objects of Type T.
--- @return UnityEngine.Resources.T[] 
function UnityEngine.Resources.FindObjectsOfTypeAll() end

--- Loads an asset stored at path in a folder called Resources.
--- @param path string Path to the target resource to load.
--- @return UnityEngine.Object The requested asset's Type.
function UnityEngine.Resources.Load(path) end

--- Loads an asset stored at path in a folder called Resources.
--- @param path string Path to the target resource to load.
--- @return UnityEngine.Resources.T The requested asset's Type.
function UnityEngine.Resources.Load(path) end

--- Loads an asset stored at path in a Resources folder.
--- @param path string Path to the target resource to load. When using an empty string (i.e., ""), the function loads the entire contents of the Resources folder.
--- @param systemTypeInstance System.Type Type filter for objects returned.
--- @return UnityEngine.Object The requested asset returned as an Object.
function UnityEngine.Resources.Load(path, systemTypeInstance) end

--- Asynchronously loads an asset stored at path in a Resources folder.
--- @param path string Pathname of the target folder. When using the empty string (i.e., ""), the function will load the entire contents of the Resources folder.
--- @return UnityEngine.ResourceRequest 
function UnityEngine.Resources.LoadAsync(path) end

--- Asynchronously loads an asset stored at path in a Resources folder.
--- @param path string Pathname of the target folder. When using the empty string (i.e., ""), the function will load the entire contents of the Resources folder.
--- @return UnityEngine.ResourceRequest 
function UnityEngine.Resources.LoadAsync(path) end

--- Asynchronously loads an asset stored at path in a Resources folder.
--- @param path string 
--- @param type System.Type 
--- @return UnityEngine.ResourceRequest 
function UnityEngine.Resources.LoadAsync(path, type) end

--- Loads all assets in a folder or file at path in a Resources folder.
--- @param path string Pathname of the target folder. When using the empty string (i.e., ""), the function will load the entire contents of the Resources folder.
--- @param systemTypeInstance System.Type Type filter for objects returned.
--- @return UnityEngine.Object[] 
function UnityEngine.Resources.LoadAll(path, systemTypeInstance) end

--- Loads all assets in a folder or file at path in a Resources folder.
--- @param path string Pathname of the target folder. When using the empty string (i.e., ""), the function will load the entire contents of the Resources folder.
--- @return UnityEngine.Object[] 
function UnityEngine.Resources.LoadAll(path) end

--- Loads all assets in a folder or file at path in a Resources folder.
--- @param path string Pathname of the target folder. When using the empty string (i.e., ""), the function will load the entire contents of the Resources folder.
--- @return UnityEngine.Resources.T[] 
function UnityEngine.Resources.LoadAll(path) end

--- @param type System.Type 
--- @param path string 
--- @return UnityEngine.Object
function UnityEngine.Resources.GetBuiltinResource(type, path) end

--- @param path string 
--- @return UnityEngine.Resources.T
function UnityEngine.Resources.GetBuiltinResource(path) end

--- Unloads assetToUnload from memory.
--- @param assetToUnload UnityEngine.Object 
function UnityEngine.Resources.UnloadAsset(assetToUnload) end

--- Unloads assets that are not used.
--- @return UnityEngine.AsyncOperation Object on which you can yield to wait until the operation completes.
function UnityEngine.Resources.UnloadUnusedAssets() end

--- Returns a resource at an asset path (Editor Only).
--- @param assetPath string Pathname of the target asset.
--- @param type System.Type Type filter for objects returned.
--- @return UnityEngine.Object 
function UnityEngine.Resources.LoadAssetAtPath(assetPath, type) end

--- Returns a resource at an asset path (Editor Only).
--- @param assetPath string Pathname of the target asset.
--- @return UnityEngine.Resources.T 
function UnityEngine.Resources.LoadAssetAtPath(assetPath) end

---  Generated By xerysherry