--- @class UnityEngine.AudioDistortionFilter:UnityEngine.Behaviour The Audio Distortion Filter distorts the sound from an AudioSource or sounds reaching the AudioListener.
--- @field distortionLevel number property getset
---       Distortion value. 0.0 to 1.0. Default = 0.5.
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.AudioDistortionFilter = {}

--- @param value number 
function UnityEngine.AudioDistortionFilter:set_distortionLevel(value) end

---  Generated By xerysherry