--- @class UnityEngine.WaitUntil:UnityEngine.CustomYieldInstruction Suspends the coroutine execution until the supplied delegate evaluates to true.
--- @field keepWaiting boolean
--- @field Current System.Object
UnityEngine.WaitUntil = {}

---  Generated By xerysherry