--- @class UnityEngine.TextClipping Different methods for how the GUI system handles text being too large to fit the rectangle allocated.
UnityEngine.TextClipping = {
    --- Text flows freely outside the element.
    Overflow = 0,
    --- Text gets clipped to be inside the element.
    Clip = 1,
}

---  Generated By xerysherry