--- @class UnityEngine.AnimationClip:UnityEngine.Motion Stores keyframe based animations.
--- @field length number property get
---       Animation length in seconds. (Read Only)
--- @field frameRate number property getset
---       Frame rate at which keyframes are sampled. (Read Only)
--- @field wrapMode UnityEngine.WrapMode property getset
---       Sets the default wrap mode used in the animation state.
--- @field localBounds UnityEngine.Bounds property getset
---       AABB of this Animation Clip in local space of Animation component that it is attached too.
--- @field legacy boolean property getset
---       Set to true if the AnimationClip will be used with the Legacy Animation component ( instead of the Animator ).
--- @field humanMotion boolean property get
---       Returns true if the animation contains curve that drives a humanoid rig.
--- @field empty boolean property get
---       Returns true if the animation clip has no curves and no events.
--- @field hasGenericRootTransform boolean property get
---       Returns true if the Animation has animation on the root transform.
--- @field hasMotionFloatCurves boolean property get
---       Returns true if the AnimationClip has editor curves for its root motion.
--- @field hasMotionCurves boolean property get
---       Returns true if the AnimationClip has root motion curves.
--- @field hasRootCurves boolean property get
---       Returns true if the AnimationClip has root Curves.
--- @field events UnityEngine.AnimationEvent[] property getset
---       Animation Events for this animation clip.
--- @field averageDuration number
--- @field averageAngularSpeed number
--- @field averageSpeed UnityEngine.Vector3
--- @field apparentSpeed number
--- @field isLooping boolean
--- @field isHumanMotion boolean
--- @field isAnimatorMotion boolean
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.AnimationClip = {}

--- Samples an animation at a given time for any animated properties.
--- @param go UnityEngine.GameObject The animated game object.
--- @param time number The time to sample an animation.
function UnityEngine.AnimationClip:SampleAnimation(go, time) end

function UnityEngine.AnimationClip:set_frameRate(value) end

--- Assigns the curve to animate a specific property.
--- @param relativePath string Path to the game object this curve applies to. The relativePath
---               is formatted similar to a pathname, e.g. "rootspineleftArm".  If relativePath
---               is empty it refers to the game object the animation clip is attached to.
--- @param type System.Type The class type of the component that is animated.
--- @param propertyName string The name or path to the property being animated.
--- @param curve UnityEngine.AnimationCurve The animation curve.
function UnityEngine.AnimationClip:SetCurve(relativePath, type, propertyName, curve) end

--- Realigns quaternion keys to ensure shortest interpolation paths.
function UnityEngine.AnimationClip:EnsureQuaternionContinuity() end

--- Clears all curves from the clip.
function UnityEngine.AnimationClip:ClearCurves() end

function UnityEngine.AnimationClip:set_wrapMode(value) end

function UnityEngine.AnimationClip:set_localBounds(value) end

function UnityEngine.AnimationClip:set_legacy(value) end

--- Adds an animation event to the clip.
--- @param evt UnityEngine.AnimationEvent AnimationEvent to add.
function UnityEngine.AnimationClip:AddEvent(evt) end

function UnityEngine.AnimationClip:set_events(value) end

---  Generated By xerysherry