--- @class UnityEngine.BitStream The BitStream class represents seralized variables, packed into a stream.
--- @field isReading boolean property get
---       Is the BitStream currently being read? (Read Only)
--- @field isWriting boolean property get
---       Is the BitStream currently being written? (Read Only)
UnityEngine.BitStream = {}

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value, maxDelta) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value, maxDelta) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value, maxDelta) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
function UnityEngine.BitStream:Serialize(viewID) end

---  Generated By xerysherry