--- @class UnityEngine.UI.GraphicRegistry 
--- @field instance UnityEngine.UI.GraphicRegistry
UnityEngine.UI.GraphicRegistry = {}

--- @param c UnityEngine.Canvas 
--- @param graphic UnityEngine.UI.Graphic 
function UnityEngine.UI.GraphicRegistry.RegisterGraphicForCanvas(c, graphic) end

--- @param c UnityEngine.Canvas 
--- @param graphic UnityEngine.UI.Graphic 
function UnityEngine.UI.GraphicRegistry.UnregisterGraphicForCanvas(c, graphic) end

--- @param canvas UnityEngine.Canvas 
--- @return System.Collections.Generic.IList`1
function UnityEngine.UI.GraphicRegistry.GetGraphicsForCanvas(canvas) end

---  Generated By xerysherry