--- @class UnityEngine.XR.TrackingOriginMode Represents how the device is reporting pose data.
UnityEngine.XR.TrackingOriginMode = {
    --- Represents a Device relative tracking origin. A Device relative tracking origin defines a Local Origin at the position of the device in space at some previous point in time, usually at a recenter event, power-on or AR/VR session start. Pose data provided by the device will be in this space relative to the local origin. This means that poses returned in this mode will not include the user height (for VR) or the device height (for AR) and any camera tracking from the XR Device will need to be manually offset accordingly.
    Device = 0,
    --- Represents the tracking origin whereby 0,0,0 is on the "floor" or other surface determined by the XR Device being used. The pose values reported by an XR Device in this mode will include the height of the XR Device above this surface, removing the need to offset the position of the camera tracking the XR Device by the height of the user (VR) or the height of the device above the floor (AR).
    Floor = 1,
    --- This indicates that the device does not know, or is unable to determine how it is reporting pose data. This value should be treated as an error condition.
    Unknown = 2,
}

---  Generated By xerysherry