--- @class UnityEngine.Rendering.SortingGroup:UnityEngine.Behaviour Adding a SortingGroup component to a GameObject will ensure that all Renderers within the GameObject's descendants will be sorted and rendered together.
--- @field sortingLayerName string property getset
---       Name of the Renderer's sorting layer.
--- @field sortingLayerID number property getset
---       Unique ID of the Renderer's sorting layer.
--- @field sortingOrder number property getset
---       Renderer's order within a sorting layer.
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Rendering.SortingGroup = {}

--- Updates all Sorting Group immediately.
function UnityEngine.Rendering.SortingGroup.UpdateAllSortingGroups() end

function UnityEngine.Rendering.SortingGroup:set_sortingLayerName(value) end

function UnityEngine.Rendering.SortingGroup:set_sortingLayerID(value) end

function UnityEngine.Rendering.SortingGroup:set_sortingOrder(value) end

---  Generated By xerysherry