--- @class UnityEngine.XR.WSA.SurfaceData SurfaceData is a container struct used for requesting baked spatial mapping data and receiving that data once baked.
--- @field id UnityEngine.XR.WSA.SurfaceId This is the ID for the surface to be baked or the surface that was baked and being returned to the user.
--- @field outputMesh UnityEngine.MeshFilter This MeshFilter will receive the baked mesh prepared by the system when requesting baked surface data.  The MeshFilter is returned in the SurfaceDataReadyDelegate for those users requiring advanced workflows.
--- @field outputAnchor UnityEngine.XR.WSA.WorldAnchor This WorldAnchor is used to lock the surface into place relative to real world objects.  It will be filled in when calling RequestMeshAsync to generate data for a surface and returned with the SurfaceDataReadyDelegate.
--- @field outputCollider UnityEngine.MeshCollider This MeshCollider will receive the baked physics mesh prepared by the system when requesting baked surface data through RequestMeshAsync.  The MeshCollider is returned in the SurfaceDataReadyDelegate for those users requiring advanced workflows.
--- @field trianglesPerCubicMeter number This value controls the basic resolution of baked mesh data and is returned with the SurfaceDataReadyDelegate.  The device will deliver up to this number of triangles per cubic meter.
--- @field bakeCollider boolean Set this field to true when requesting data to bake collider data.  This field will be set to true when receiving baked data if it was requested.  Setting this field to true requires that a valid outputCollider is also specified.
UnityEngine.XR.WSA.SurfaceData = {}

---  Generated By xerysherry