--- @class UnityEngine.BillboardAsset:UnityEngine.Object BillboardAsset describes how a billboard is rendered.
--- @field width number property getset
---       Width of the billboard.
--- @field height number property getset
---       Height of the billboard.
--- @field bottom number property getset
---       Height of the billboard that is below ground.
--- @field imageCount number property get
---       Number of pre-rendered images that can be switched when the billboard is viewed from different angles.
--- @field vertexCount number property get
---       Number of vertices in the billboard mesh.
--- @field indexCount number property get
---       Number of indices in the billboard mesh.
--- @field material UnityEngine.Material property getset
---       The material used for rendering.
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.BillboardAsset = {}

function UnityEngine.BillboardAsset:set_width(value) end

function UnityEngine.BillboardAsset:set_height(value) end

function UnityEngine.BillboardAsset:set_bottom(value) end

function UnityEngine.BillboardAsset:set_material(value) end

--- Get the array of billboard image texture coordinate data.
--- @param imageTexCoords UnityEngine.Vector4[] The list that receives the array.
function UnityEngine.BillboardAsset:GetImageTexCoords(imageTexCoords) end

--- Get the array of billboard image texture coordinate data.
--- @return UnityEngine.Vector4[] 
function UnityEngine.BillboardAsset:GetImageTexCoords() end

--- Set the array of billboard image texture coordinate data.
--- @param imageTexCoords UnityEngine.Vector4[] The array of data to set.
function UnityEngine.BillboardAsset:SetImageTexCoords(imageTexCoords) end

--- Set the array of billboard image texture coordinate data.
--- @param imageTexCoords UnityEngine.Vector4[] The array of data to set.
function UnityEngine.BillboardAsset:SetImageTexCoords(imageTexCoords) end

--- Get the vertices of the billboard mesh.
--- @param vertices UnityEngine.Vector2[] The list that receives the array.
function UnityEngine.BillboardAsset:GetVertices(vertices) end

--- Get the vertices of the billboard mesh.
--- @return UnityEngine.Vector2[] 
function UnityEngine.BillboardAsset:GetVertices() end

--- Set the vertices of the billboard mesh.
--- @param vertices UnityEngine.Vector2[] The array of data to set.
function UnityEngine.BillboardAsset:SetVertices(vertices) end

--- Set the vertices of the billboard mesh.
--- @param vertices UnityEngine.Vector2[] The array of data to set.
function UnityEngine.BillboardAsset:SetVertices(vertices) end

--- Get the indices of the billboard mesh.
--- @param indices number[] The list that receives the array.
function UnityEngine.BillboardAsset:GetIndices(indices) end

--- Get the indices of the billboard mesh.
--- @return number[] 
function UnityEngine.BillboardAsset:GetIndices() end

--- Set the indices of the billboard mesh.
--- @param indices number[] The array of data to set.
function UnityEngine.BillboardAsset:SetIndices(indices) end

--- Set the indices of the billboard mesh.
--- @param indices number[] The array of data to set.
function UnityEngine.BillboardAsset:SetIndices(indices) end

---  Generated By xerysherry