--- @class UnityEngine.SocialPlatforms.Impl.Leaderboard 
--- @field loading boolean
--- @field id string
--- @field userScope UnityEngine.SocialPlatforms.UserScope
--- @field range UnityEngine.SocialPlatforms.Range
--- @field timeScope UnityEngine.SocialPlatforms.TimeScope
--- @field localUserScore UnityEngine.SocialPlatforms.IScore
--- @field maxRange number
--- @field scores UnityEngine.SocialPlatforms.IScore[]
--- @field title string
UnityEngine.SocialPlatforms.Impl.Leaderboard = {}

--- @param userIDs string[] 
function UnityEngine.SocialPlatforms.Impl.Leaderboard:SetUserFilter(userIDs) end

--- @return string
function UnityEngine.SocialPlatforms.Impl.Leaderboard:ToString() end

--- @param callback function 
function UnityEngine.SocialPlatforms.Impl.Leaderboard:LoadScores(callback) end

--- @param score UnityEngine.SocialPlatforms.IScore 
function UnityEngine.SocialPlatforms.Impl.Leaderboard:SetLocalUserScore(score) end

--- @param maxRange number 
function UnityEngine.SocialPlatforms.Impl.Leaderboard:SetMaxRange(maxRange) end

--- @param scores UnityEngine.SocialPlatforms.IScore[] 
function UnityEngine.SocialPlatforms.Impl.Leaderboard:SetScores(scores) end

--- @param title string 
function UnityEngine.SocialPlatforms.Impl.Leaderboard:SetTitle(title) end

--- @return string[]
function UnityEngine.SocialPlatforms.Impl.Leaderboard:GetUserFilter() end

--- @param value string 
function UnityEngine.SocialPlatforms.Impl.Leaderboard:set_id(value) end

--- @param value UnityEngine.SocialPlatforms.UserScope 
function UnityEngine.SocialPlatforms.Impl.Leaderboard:set_userScope(value) end

--- @param value UnityEngine.SocialPlatforms.Range 
function UnityEngine.SocialPlatforms.Impl.Leaderboard:set_range(value) end

--- @param value UnityEngine.SocialPlatforms.TimeScope 
function UnityEngine.SocialPlatforms.Impl.Leaderboard:set_timeScope(value) end

---  Generated By xerysherry