--- @class UnityEngine.Animations.AnimationStreamHandleUtility Static class providing utility functions for animation stream handles.
UnityEngine.Animations.AnimationStreamHandleUtility = {}

--- Write integers from buffer to property stream handles.
--- @param stream UnityEngine.Animations.AnimationStream The animation stream.
--- @param handles Unity.Collections.NativeArray`1 The PropertyStreamHandle array to write to.
--- @param buffer Unity.Collections.NativeArray`1 The buffer of integer properties.
--- @param useMask boolean Set to true to write new values if the matching stream handles have not already been modified.
function UnityEngine.Animations.AnimationStreamHandleUtility.WriteInts(stream, handles, buffer, useMask) end

--- Writes float properties from the buffer to the PropertyStreamHandle array (handles).
--- @param stream UnityEngine.Animations.AnimationStream The animation stream.
--- @param handles Unity.Collections.NativeArray`1 The PropertyStreamHandle array to write to.
--- @param buffer Unity.Collections.NativeArray`1 The buffer of float properties.
--- @param useMask boolean Set to true to write new values if the matching stream handles have not already been modified.
function UnityEngine.Animations.AnimationStreamHandleUtility.WriteFloats(stream, handles, buffer, useMask) end

--- Reads integer properties from the PropertyStreamHandle array (handles) and stores the integers in the provided buffer. The buffer must have enough allocated space to store all values.
--- @param stream UnityEngine.Animations.AnimationStream The animation stream.
--- @param handles Unity.Collections.NativeArray`1 The PropertyStreamHandle array to read from.
--- @param buffer Unity.Collections.NativeArray`1 The buffer that stores integer values.
function UnityEngine.Animations.AnimationStreamHandleUtility.ReadInts(stream, handles, buffer) end

--- Reads float properties from the PropertyStreamHandle array (handles) and stores the floats in the provided buffer. The buffer must have enough allocated space to store all values.
--- @param stream UnityEngine.Animations.AnimationStream The animation stream.
--- @param handles Unity.Collections.NativeArray`1 The PropertyStreamHandle array to read from.
--- @param buffer Unity.Collections.NativeArray`1 The buffer that stores float values.
function UnityEngine.Animations.AnimationStreamHandleUtility.ReadFloats(stream, handles, buffer) end

---  Generated By xerysherry