--- @class UnityEngine.AI.OffMeshLinkType Link type specifier.
UnityEngine.AI.OffMeshLinkType = {
    --- Manually specified type of link.
    LinkTypeManual = 0,
    --- Vertical drop.
    LinkTypeDropDown = 1,
    --- Horizontal jump.
    LinkTypeJumpAcross = 2,
}

---  Generated By xerysherry