--- @class UnityEngine.AnimationCurve Store a collection of Keyframes that can be evaluated over time.
--- @field keys UnityEngine.Keyframe[] property getset
---       All keys defined in the animation curve.
--- @field Item UnityEngine.Keyframe
--- @field length number property get
---       The number of keys in the curve. (Read Only)
--- @field preWrapMode UnityEngine.WrapMode property getset
---       The behaviour of the animation before the first keyframe.
--- @field postWrapMode UnityEngine.WrapMode property getset
---       The behaviour of the animation after the last keyframe.
UnityEngine.AnimationCurve = {}

--- Creates a constant "curve" starting at timeStart, ending at timeEnd and with the value value.
--- @param timeStart number The start time for the constant curve.
--- @param timeEnd number The start time for the constant curve.
--- @param value number The value for the constant curve.
--- @return UnityEngine.AnimationCurve The constant curve created from the specified values.
function UnityEngine.AnimationCurve.Constant(timeStart, timeEnd, value) end

--- A straight Line starting at timeStart, valueStart and ending at timeEnd, valueEnd.
--- @param timeStart number The start time for the linear curve.
--- @param valueStart number The start value for the linear curve.
--- @param timeEnd number The end time for the linear curve.
--- @param valueEnd number The end value for the linear curve.
--- @return UnityEngine.AnimationCurve The linear curve created from the specified values.
function UnityEngine.AnimationCurve.Linear(timeStart, valueStart, timeEnd, valueEnd) end

--- Creates an ease-in and out curve starting at timeStart, valueStart and ending at timeEnd, valueEnd.
--- @param timeStart number The start time for the ease curve.
--- @param valueStart number The start value for the ease curve.
--- @param timeEnd number The end time for the ease curve.
--- @param valueEnd number The end value for the ease curve.
--- @return UnityEngine.AnimationCurve The ease-in and out curve generated from the specified values.
function UnityEngine.AnimationCurve.EaseInOut(timeStart, valueStart, timeEnd, valueEnd) end

--- Evaluate the curve at time.
--- @param time number The time within the curve you want to evaluate (the horizontal axis in the curve graph).
--- @return number The value of the curve, at the point in time specified.
function UnityEngine.AnimationCurve:Evaluate(time) end

function UnityEngine.AnimationCurve:set_keys(value) end

--- Add a new key to the curve.
--- @param time number The time at which to add the key (horizontal axis in the curve graph).
--- @param value number The value for the key (vertical axis in the curve graph).
--- @return number The index of the added key, or -1 if the key could not be added.
function UnityEngine.AnimationCurve:AddKey(time, value) end

--- Add a new key to the curve.
--- @param key UnityEngine.Keyframe The key to add to the curve.
--- @return number The index of the added key, or -1 if the key could not be added.
function UnityEngine.AnimationCurve:AddKey(key) end

--- Removes the keyframe at index and inserts key.
--- @param index number The index of the key to move.
--- @param key UnityEngine.Keyframe The key (with its new time) to insert.
--- @return number The index of the keyframe after moving it.
function UnityEngine.AnimationCurve:MoveKey(index, key) end

--- Removes a key.
--- @param index number The index of the key to remove.
function UnityEngine.AnimationCurve:RemoveKey(index) end

--- Smooth the in and out tangents of the keyframe at index.
--- @param index number The index of the keyframe to be smoothed.
--- @param weight number The smoothing weight to apply to the keyframe's tangents.
function UnityEngine.AnimationCurve:SmoothTangents(index, weight) end

function UnityEngine.AnimationCurve:set_preWrapMode(value) end

function UnityEngine.AnimationCurve:set_postWrapMode(value) end

--- @return boolean
function UnityEngine.AnimationCurve:Equals(o) end

--- @return boolean
function UnityEngine.AnimationCurve:Equals(other) end

--- @return number
function UnityEngine.AnimationCurve:GetHashCode() end

---  Generated By xerysherry