--- @class UnityEngine.UI.HorizontalOrVerticalLayoutGroup:UnityEngine.UI.LayoutGroup 
--- @field spacing number
--- @field childForceExpandWidth boolean
--- @field childForceExpandHeight boolean
--- @field childControlWidth boolean
--- @field childControlHeight boolean
--- @field childScaleWidth boolean
--- @field childScaleHeight boolean
--- @field padding UnityEngine.RectOffset
--- @field childAlignment UnityEngine.TextAnchor
--- @field minWidth number
--- @field preferredWidth number
--- @field flexibleWidth number
--- @field minHeight number
--- @field preferredHeight number
--- @field flexibleHeight number
--- @field layoutPriority number
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.HorizontalOrVerticalLayoutGroup = {}

--- @param value number 
function UnityEngine.UI.HorizontalOrVerticalLayoutGroup:set_spacing(value) end

--- @param value boolean 
function UnityEngine.UI.HorizontalOrVerticalLayoutGroup:set_childForceExpandWidth(value) end

--- @param value boolean 
function UnityEngine.UI.HorizontalOrVerticalLayoutGroup:set_childForceExpandHeight(value) end

--- @param value boolean 
function UnityEngine.UI.HorizontalOrVerticalLayoutGroup:set_childControlWidth(value) end

--- @param value boolean 
function UnityEngine.UI.HorizontalOrVerticalLayoutGroup:set_childControlHeight(value) end

--- @param value boolean 
function UnityEngine.UI.HorizontalOrVerticalLayoutGroup:set_childScaleWidth(value) end

--- @param value boolean 
function UnityEngine.UI.HorizontalOrVerticalLayoutGroup:set_childScaleHeight(value) end

---  Generated By xerysherry