--- @class UnityEngine.HDROutputSettings The HDROutputSettings allows the user to modify and set the  data for multple frames.
UnityEngine.HDROutputSettings = {}

--- Sets the base luminance of a white paper surface in nits or candela per square meter (cd/m2).
--- @param paperWhite number The brightness level for basic white.
function UnityEngine.HDROutputSettings.SetPaperWhiteInNits(paperWhite) end

---  Generated By xerysherry