--- @class UnityEngine.UIElements.VisualElementFocusChangeDirection:UnityEngine.UIElements.FocusChangeDirection Define focus change directions for the VisualElementFocusRing.
--- @field left UnityEngine.UIElements.FocusChangeDirection property get
---       The focus is moving to the left.
--- @field right UnityEngine.UIElements.FocusChangeDirection property get
---       The focus is moving to the right.
UnityEngine.UIElements.VisualElementFocusChangeDirection = {}

---  Generated By xerysherry