--- @class UnityEngine.HumanDescription Class that holds humanoid avatar parameters to pass to the AvatarBuilder.BuildHumanAvatar function.
--- @field upperArmTwist number property getset
---       Defines how the upper arm's roll/twisting is distributed between the shoulder and elbow joints.
--- @field lowerArmTwist number property getset
---       Defines how the lower arm's roll/twisting is distributed between the elbow and wrist joints.
--- @field upperLegTwist number property getset
---       Defines how the upper leg's roll/twisting is distributed between the thigh and knee joints.
--- @field lowerLegTwist number property getset
---       Defines how the lower leg's roll/twisting is distributed between the knee and ankle.
--- @field armStretch number property getset
---       Amount by which the arm's length is allowed to stretch when using IK.
--- @field legStretch number property getset
---       Amount by which the leg's length is allowed to stretch when using IK.
--- @field feetSpacing number property getset
---       Modification to the minimum distance between the feet of a humanoid model.
--- @field hasTranslationDoF boolean property getset
---       True for any human that has a translation Degree of Freedom (DoF). It is set to false by default.
--- @field human UnityEngine.HumanBone[] Mapping between Mecanim bone names and bone names in the rig.
--- @field skeleton UnityEngine.SkeletonBone[] List of bone Transforms to include in the model.
UnityEngine.HumanDescription = {}

--- @param value number 
function UnityEngine.HumanDescription:set_upperArmTwist(value) end

--- @param value number 
function UnityEngine.HumanDescription:set_lowerArmTwist(value) end

--- @param value number 
function UnityEngine.HumanDescription:set_upperLegTwist(value) end

--- @param value number 
function UnityEngine.HumanDescription:set_lowerLegTwist(value) end

--- @param value number 
function UnityEngine.HumanDescription:set_armStretch(value) end

--- @param value number 
function UnityEngine.HumanDescription:set_legStretch(value) end

--- @param value number 
function UnityEngine.HumanDescription:set_feetSpacing(value) end

--- @param value boolean 
function UnityEngine.HumanDescription:set_hasTranslationDoF(value) end

---  Generated By xerysherry