--- @class UnityEngine.AudioListener:UnityEngine.AudioBehaviour Representation of a listener in 3D space.
--- @field volume number property getset
---       Controls the game sound volume (0.0 to 1.0).
--- @field pause boolean property getset
---       The paused state of the audio system.
--- @field velocityUpdateMode UnityEngine.AudioVelocityUpdateMode property getset
---       This lets you set whether the Audio Listener should be updated in the fixed or dynamic update.
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.AudioListener = {}

--- @param value number 
function UnityEngine.AudioListener.set_volume(value) end

--- @param value boolean 
function UnityEngine.AudioListener.set_pause(value) end

--- Deprecated Version. Returns a block of the listener (master)'s output data.
--- @param numSamples number 
--- @param channel number 
--- @return number[] 
function UnityEngine.AudioListener.GetOutputData(numSamples, channel) end

--- Provides a block of the listener (master)'s output data.
--- @param samples number[] The array to populate with audio samples. Its length must be a power of 2.
--- @param channel number The channel to sample from.
function UnityEngine.AudioListener.GetOutputData(samples, channel) end

--- Deprecated Version. Returns a block of the listener (master)'s spectrum data.
--- @param numSamples number Number of values (the length of the samples array). Must be a power of 2. Min = 64. Max = 8192.
--- @param channel number The channel to sample from.
--- @param window UnityEngine.FFTWindow The FFTWindow type to use when sampling.
--- @return number[] 
function UnityEngine.AudioListener.GetSpectrumData(numSamples, channel, window) end

--- Provides a block of the listener (master)'s spectrum data.
--- @param samples number[] The array to populate with audio samples. Its length must be a power of 2.
--- @param channel number The channel to sample from.
--- @param window UnityEngine.FFTWindow The FFTWindow type to use when sampling.
function UnityEngine.AudioListener.GetSpectrumData(samples, channel, window) end

--- @param value UnityEngine.AudioVelocityUpdateMode 
function UnityEngine.AudioListener:set_velocityUpdateMode(value) end

---  Generated By xerysherry