--- @class UnityEngine.Animations.AnimationLayerMixerPlayable An implementation of IPlayable that controls an animation layer mixer.
--- @field Null UnityEngine.Animations.AnimationLayerMixerPlayable property get
---       Returns an invalid AnimationLayerMixerPlayable.
UnityEngine.Animations.AnimationLayerMixerPlayable = {}

--- Creates an AnimationLayerMixerPlayable in the PlayableGraph.
--- @param graph UnityEngine.Playables.PlayableGraph The PlayableGraph that will contain the new AnimationLayerMixerPlayable.
--- @param inputCount number The number of layers.
--- @return UnityEngine.Animations.AnimationLayerMixerPlayable A new AnimationLayerMixerPlayable linked to the PlayableGraph.
function UnityEngine.Animations.AnimationLayerMixerPlayable.Create(graph, inputCount) end

--- @param playable UnityEngine.Animations.AnimationLayerMixerPlayable 
--- @return UnityEngine.Playables.Playable
function UnityEngine.Animations.AnimationLayerMixerPlayable.op_Implicit(playable) end

--- @param playable UnityEngine.Playables.Playable 
--- @return UnityEngine.Animations.AnimationLayerMixerPlayable
function UnityEngine.Animations.AnimationLayerMixerPlayable.op_Explicit(playable) end

--- @return UnityEngine.Playables.PlayableHandle
function UnityEngine.Animations.AnimationLayerMixerPlayable:GetHandle() end

--- @param other UnityEngine.Animations.AnimationLayerMixerPlayable 
--- @return boolean
function UnityEngine.Animations.AnimationLayerMixerPlayable:Equals(other) end

--- Returns true if the layer is additive, false otherwise.
--- @param layerIndex number The layer index.
--- @return boolean True if the layer is additive, false otherwise.
function UnityEngine.Animations.AnimationLayerMixerPlayable:IsLayerAdditive(layerIndex) end

--- Specifies whether a layer is additive or not. Additive layers blend with previous layers.
--- @param layerIndex number The layer index.
--- @param value boolean Whether the layer is additive or not. Set to true for an additive blend, or false for a regular blend.
function UnityEngine.Animations.AnimationLayerMixerPlayable:SetLayerAdditive(layerIndex, value) end

--- Sets the mask for the current layer.
--- @param layerIndex number The layer index.
--- @param mask UnityEngine.AvatarMask The AvatarMask used to create the new LayerMask.
function UnityEngine.Animations.AnimationLayerMixerPlayable:SetLayerMaskFromAvatarMask(layerIndex, mask) end

---  Generated By xerysherry