--- @class UnityEngine.NetworkPlayer The NetworkPlayer is a data structure with which you can locate another player over the network.
--- @field ipAddress string property get
---       The IP address of this player.
--- @field port number property get
---       The port of this player.
--- @field guid string property get
---       The GUID for this player, used when connecting with NAT punchthrough.
--- @field externalIP string property get
---       Returns the external IP address of the network interface.
--- @field externalPort number property get
---       Returns the external port of the network interface.
UnityEngine.NetworkPlayer = {}

---  Generated By xerysherry