--- @class UnityEngine.UIElements.TrickleDown Use this enum to specify during which phases the event handler is executed.
UnityEngine.UIElements.TrickleDown = {
    --- The event handler should be executed during the AtTarget and BubbleUp phases.
    NoTrickleDown = 0,
    --- The event handler should be executed during the TrickleDown and AtTarget phases.
    TrickleDown = 1,
}

---  Generated By xerysherry