--- @class UnityEngine.SocialPlatforms.Impl.Achievement 
--- @field id string
--- @field percentCompleted number
--- @field completed boolean
--- @field hidden boolean
--- @field lastReportedDate System.DateTime
UnityEngine.SocialPlatforms.Impl.Achievement = {}

--- @return string
function UnityEngine.SocialPlatforms.Impl.Achievement:ToString() end

--- @param callback function 
function UnityEngine.SocialPlatforms.Impl.Achievement:ReportProgress(callback) end

--- @param value boolean 
function UnityEngine.SocialPlatforms.Impl.Achievement:SetCompleted(value) end

--- @param value boolean 
function UnityEngine.SocialPlatforms.Impl.Achievement:SetHidden(value) end

--- @param date System.DateTime 
function UnityEngine.SocialPlatforms.Impl.Achievement:SetLastReportedDate(date) end

--- @param value string 
function UnityEngine.SocialPlatforms.Impl.Achievement:set_id(value) end

--- @param value number 
function UnityEngine.SocialPlatforms.Impl.Achievement:set_percentCompleted(value) end

---  Generated By xerysherry