--- @class UnityEngine.UIElements.Toggle:UnityEngine.UIElements.BaseField`1 This is the Toggle field.
--- @field ussClassName string USS class name of elements of this type.
--- @field labelUssClassName string USS class name of labels in elements of this type.
--- @field inputUssClassName string USS class name of input elements in elements of this type.
--- @field noTextVariantUssClassName string USS class name of elements of this type, when there is no text.
--- @field checkmarkUssClassName string USS class name of elements of this type.
--- @field textUssClassName string USS class name of text elements in elements of this type.
--- @field text string property getset
---       Optional text after the toggle.
--- @field value boolean
--- @field labelElement UnityEngine.UIElements.Label
--- @field label string
--- @field binding UnityEngine.UIElements.IBinding
--- @field bindingPath string
--- @field viewDataKey string
--- @field userData System.Object
--- @field canGrabFocus boolean
--- @field focusController UnityEngine.UIElements.FocusController
--- @field usageHints UnityEngine.UIElements.UsageHints
--- @field transform UnityEngine.UIElements.ITransform
--- @field layout UnityEngine.Rect
--- @field contentRect UnityEngine.Rect
--- @field worldBound UnityEngine.Rect
--- @field localBound UnityEngine.Rect
--- @field worldTransform UnityEngine.Matrix4x4
--- @field pickingMode UnityEngine.UIElements.PickingMode
--- @field name string
--- @field enabledInHierarchy boolean
--- @field enabledSelf boolean
--- @field visible boolean
--- @field generateVisualContent function
--- @field experimental UnityEngine.UIElements.IExperimentalFeatures
--- @field hierarchy UnityEngine.UIElements.VisualElement.Hierarchy
--- @field cacheAsBitmap boolean
--- @field parent UnityEngine.UIElements.VisualElement
--- @field panel UnityEngine.UIElements.IPanel
--- @field contentContainer UnityEngine.UIElements.VisualElement
--- @field Item UnityEngine.UIElements.VisualElement
--- @field childCount number
--- @field schedule UnityEngine.UIElements.IVisualElementScheduler
--- @field style UnityEngine.UIElements.IStyle
--- @field customStyle UnityEngine.UIElements.ICustomStyle
--- @field resolvedStyle UnityEngine.UIElements.IResolvedStyle
--- @field styleSheets UnityEngine.UIElements.VisualElementStyleSheetSet
--- @field tooltip string
--- @field focusable boolean
--- @field tabIndex number
--- @field delegatesFocus boolean
UnityEngine.UIElements.Toggle = {}

function UnityEngine.UIElements.Toggle:set_text(value) end

function UnityEngine.UIElements.Toggle:SetValueWithoutNotify(newValue) end

---  Generated By xerysherry