--- @class UnityEngine.iPhoneKeyboardType
UnityEngine.iPhoneKeyboardType = {
    Default = 0,
    ASCIICapable = 1,
    NumbersAndPunctuation = 2,
    URL = 3,
    NumberPad = 4,
    PhonePad = 5,
    NamePhonePad = 6,
    EmailAddress = 7,
}

---  Generated By xerysherry