--- @class UnityEngine.VFX.VisualEffectAsset:UnityEngine.VFX.VisualEffectObject This class contains a graph of the elements needed to describe a visual effect. These include: the visual effects system, generated shaders, and compiled data.
--- @field PlayEventID number The default name ID of the play event.
--- @field StopEventID number The default name ID of the stop event.
--- @field PlayEventName string The default name of the play event.
--- @field StopEventName string The default name of the stop event.
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.VFX.VisualEffectAsset = {}

--- Gets the TextureDimension of a named exposed Texture.
--- @param nameID number 
--- @return UnityEngine.Rendering.TextureDimension 
function UnityEngine.VFX.VisualEffectAsset:GetTextureDimension(nameID) end

--- Gets the name and type of every exposed property.
--- @param exposedProperties UnityEngine.VFX.VFXExposedProperty[] The List that this function populates with exposed properties.
function UnityEngine.VFX.VisualEffectAsset:GetExposedProperties(exposedProperties) end

--- Gets the name of every Event connected to a system.
--- @param names string[] The List that this function populates with the event system names.
function UnityEngine.VFX.VisualEffectAsset:GetEvents(names) end

--- Gets the TextureDimension of a named exposed Texture.
--- @param name string 
--- @return UnityEngine.Rendering.TextureDimension 
function UnityEngine.VFX.VisualEffectAsset:GetTextureDimension(name) end

---  Generated By xerysherry