--- @class UnityEngine.CapsuleCollider:UnityEngine.Collider A capsule-shaped primitive collider.
--- @field center UnityEngine.Vector3 property getset
---       The center of the capsule, measured in the object's local space.
--- @field radius number property getset
---       The radius of the sphere, measured in the object's local space.
--- @field height number property getset
---       The height of the capsule measured in the object's local space.
--- @field direction number property getset
---       The direction of the capsule.
--- @field enabled boolean
--- @field attachedRigidbody UnityEngine.Rigidbody
--- @field isTrigger boolean
--- @field contactOffset number
--- @field bounds UnityEngine.Bounds
--- @field sharedMaterial UnityEngine.PhysicMaterial
--- @field material UnityEngine.PhysicMaterial
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.CapsuleCollider = {}

function UnityEngine.CapsuleCollider:set_center(value) end

function UnityEngine.CapsuleCollider:set_radius(value) end

function UnityEngine.CapsuleCollider:set_height(value) end

function UnityEngine.CapsuleCollider:set_direction(value) end

---  Generated By xerysherry