--- @class UnityEngine.ArmDof Enumeration of all the muscles in an arm.
UnityEngine.ArmDof = {
    --- The shoulder down-up muscle.
    ShoulderDownUp = 0,
    --- The shoulder front-back muscle.
    ShoulderFrontBack = 1,
    --- The arm down-up muscle.
    ArmDownUp = 2,
    --- The arm front-back muscle.
    ArmFrontBack = 3,
    --- The arm roll in-out muscle.
    ArmRollInOut = 4,
    --- The forearm close-open muscle.
    ForeArmCloseOpen = 5,
    --- The forearm roll in-out muscle.
    ForeArmRollInOut = 6,
    --- The hand down-up muscle.
    HandDownUp = 7,
    --- The hand in-out muscle.
    HandInOut = 8,
    --- The last value of the ArmDof enum.
    LastArmDof = 9,
}

---  Generated By xerysherry