--- @class UnityEngine.XR.WSA.HolographicStreamerConnectionFailureReason Enum indicating the reason why connection to remote device has failed.
UnityEngine.XR.WSA.HolographicStreamerConnectionFailureReason = {
    --- No failure.
    None = 0,
    --- Couldn't identify the reason why connection failed.
    Unknown = 1,
    --- No certificate for the app attempting to remote.
    NoServerCertificate = 2,
    --- Handshake port is in use by another application.
    HandshakePortBusy = 3,
    --- Handshake connection could not be estabilished because the device could not be found.
    HandshakeUnreachable = 4,
    --- Handshake connection could not be established between application and device.
    HandshakeConnectionFailed = 5,
    --- User authentication could not be verified.
    AuthenticationFailed = 6,
    --- The remoting app on device is not supported by the version used in the remoting player.
    RemotingVersionMismatch = 7,
    --- Incompatible network protocol used.
    IncompatibleTransportProtocols = 8,
    --- Handshake failed while traying to establish connection with remote device.
    HandshakeFailed = 9,
    --- Transport port is already in use.
    TransportPortBusy = 10,
    --- Could not find a device to establish data transfer with.
    TransportUnreachable = 11,
    --- Could not establish a connection to transport data between device and application.
    TransportConnectionFailed = 12,
    --- Protocol used by the app does not match remoting app running on remote device.
    ProtocolVersionMismatch = 13,
    --- The network protocol encounted an error.
    ProtocolError = 14,
    --- The video codec used is unsupported by the remoting app on device.
    VideoCodecNotAvailable = 15,
    --- Connect manually cancelled.
    Canceled = 16,
    --- Enum indicating the reason why remote connection failed.
    ConnectionLost = 17,
    --- Connection to the device was lost. Primarily seen when the device loses user presence.
    DeviceLost = 18,
    --- Disconnect requested manually by the user.
    DisconnectRequest = 19,
}

---  Generated By xerysherry