--- @class UnityEngine.Experimental.GlobalIllumination.AngularFalloffType Sets the method to use to compute the angular attenuation of spot lights.
UnityEngine.Experimental.GlobalIllumination.AngularFalloffType = {
    --- Uses a lookup table to calculate falloff and does not support the inner angle.
    LUT = 0,
    --- No falloff inside inner angle then compute falloff using analytic formula.
    AnalyticAndInnerAngle = 1,
}

---  Generated By xerysherry