--- @class UnityEngine.XR.HandFinger Enumeration describing the AR rendering mode used with XR.Hand.
UnityEngine.XR.HandFinger = {
    --- Thumb finger on a hand.
    Thumb = 0,
    --- Index finger on a hand.
    Index = 1,
    --- Middle finger on a hand.
    Middle = 2,
    --- Ring finger on a hand.
    Ring = 3,
    --- Pinky finger on a hand.
    Pinky = 4,
}

---  Generated By xerysherry