--- @class UnityEngine.UI.StencilMaterial 
UnityEngine.UI.StencilMaterial = {}

--- @return UnityEngine.Material
function UnityEngine.UI.StencilMaterial.Add(baseMat, stencilID) end

--- @return UnityEngine.Material
function UnityEngine.UI.StencilMaterial.Add(baseMat, stencilID, operation, compareFunction, colorWriteMask) end

--- @return UnityEngine.Material
function UnityEngine.UI.StencilMaterial.Add(baseMat, stencilID, operation, compareFunction, colorWriteMask, readMask, writeMask) end

function UnityEngine.UI.StencilMaterial.Remove(customMat) end

function UnityEngine.UI.StencilMaterial.ClearAll() end

---  Generated By xerysherry