--- @class UnityEngineInternal.MathfInternal 
--- @field FloatMinNormal number
--- @field FloatMinDenormal number
--- @field IsFlushToZeroEnabled boolean
UnityEngineInternal.MathfInternal = {}

---  Generated By xerysherry