--- @class UnityEngine.FocusType Used by GUIUtility.GetControlID to inform the IMGUI system if a given control can get keyboard focus. This allows the IMGUI system to give focus appropriately when a user presses tab for cycling between controls.
UnityEngine.FocusType = {
    --- This control can receive keyboard focus.
    Keyboard = 1,
    --- This control can not receive keyboard focus.
    Passive = 2,
}

---  Generated By xerysherry