--- @class UnityEngine.iOS.ADInterstitialAd ADInterstitialAd is a wrapper around the ADInterstitialAd class found in the Apple iAd framework and is only available on iPad.
--- @field isAvailable boolean property get
---       Checks if InterstitialAd is available (it is available on iPad since iOS 4.3, and on iPhone since iOS 7.0).
--- @field loaded boolean property get
---       Has the interstitial ad object downloaded an advertisement? (Read Only)
UnityEngine.iOS.ADInterstitialAd = {}

function UnityEngine.iOS.ADInterstitialAd.add_onInterstitialWasLoaded(value) end

function UnityEngine.iOS.ADInterstitialAd.remove_onInterstitialWasLoaded(value) end

function UnityEngine.iOS.ADInterstitialAd.add_onInterstitialWasViewed(value) end

function UnityEngine.iOS.ADInterstitialAd.remove_onInterstitialWasViewed(value) end

--- Shows full-screen advertisement to user.
function UnityEngine.iOS.ADInterstitialAd:Show() end

--- Reload advertisement.
function UnityEngine.iOS.ADInterstitialAd:ReloadAd() end

---  Generated By xerysherry