--- @class UnityEngine.XR.WSA.WorldAnchor:UnityEngine.Component The WorldAnchor component allows a GameObject's position to be locked in physical space.
--- @field isLocated boolean property get
---       Returns true if this WorldAnchor is located (read only).  A return of false typically indicates a loss of tracking.
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.XR.WSA.WorldAnchor = {}

function UnityEngine.XR.WSA.WorldAnchor:add_OnTrackingChanged(value) end

function UnityEngine.XR.WSA.WorldAnchor:remove_OnTrackingChanged(value) end

--- Assigns the <a href="https:msdn.microsoft.comen-uslibrarywindowsappswindows.perception.spatial.spatialanchor.aspx">Windows.Perception.Spatial.SpatialAnchor<a> COM pointer maintained by this WorldAnchor.
--- @param spatialAnchorPtr System.IntPtr A live <a href="https:msdn.microsoft.comen-uslibrarywindowsappswindows.perception.spatial.spatialanchor.aspx">Windows.Perception.Spatial.SpatialAnchor<a> COM pointer.
function UnityEngine.XR.WSA.WorldAnchor:SetNativeSpatialAnchorPtr(spatialAnchorPtr) end

--- Retrieve a native pointer to the <a href="https:msdn.microsoft.comen-uslibrarywindowsappswindows.perception.spatial.spatialanchor.aspx">Windows.Perception.Spatial.SpatialAnchor<a> COM object.
--- This function calls <a href=" https:msdn.microsoft.comen-uslibrarywindowsdesktopms691379.aspx">IUnknown::AddRef<a> on the pointer before returning it. The pointer must be released by calling <a href=" https:msdn.microsoft.comen-uslibrarywindowsdesktopms682317.aspx">IUnknown::Release<a>.
--- @return System.IntPtr The native pointer to the <a href=" https:msdn.microsoft.comen-uslibrarywindowsappswindows.perception.spatial.spatialanchor.aspx">Windows.Perception.Spatial.SpatialAnchor<a> COM object.
function UnityEngine.XR.WSA.WorldAnchor:GetNativeSpatialAnchorPtr() end

---  Generated By xerysherry