--- @class UnityEngine.UIElements.StyleKeyword Keyword that can be used on any style value types.
UnityEngine.UIElements.StyleKeyword = {
    --- Means that there's no keyword defined for that property.
    Undefined = 0,
    --- Means that an inline style from IStyle has no value or keyword.
    Null = 1,
    --- For style properties accepting auto.
    Auto = 2,
    --- For style properties accepting none.
    None = 3,
    --- The initial (or default) value of a style property.
    Initial = 4,
}

---  Generated By xerysherry