--- @class UnityEngine.UIElements.DropdownMenu A drop-down menu.
UnityEngine.UIElements.DropdownMenu = {}

--- Get the list of menu items.
--- @return UnityEngine.UIElements.DropdownMenuItem[] The list of items in the menu.
function UnityEngine.UIElements.DropdownMenu:MenuItems() end

--- Add an item that will execute an action in the drop-down menu. The item is added at the end of the current item list.
function UnityEngine.UIElements.DropdownMenu:AppendAction(actionName, action, actionStatusCallback, userData) end

--- Add an item that will execute an action in the drop-down menu. The item is added at the end of the current item list.
function UnityEngine.UIElements.DropdownMenu:AppendAction(actionName, action, status) end

--- Add an item that will execute an action in the drop-down menu. The item is added at the end of the specified index in the list.
function UnityEngine.UIElements.DropdownMenu:InsertAction(atIndex, actionName, action, actionStatusCallback, userData) end

--- Add an item that will execute an action in the drop-down menu. The item is added at the end of the specified index in the list.
function UnityEngine.UIElements.DropdownMenu:InsertAction(atIndex, actionName, action, status) end

--- Add a separator line in the menu. The separator is added at the end of the current item list.
--- @param subMenuPath string The submenu path where the separator will be added. Path components are delimited by forward slashes ('/').
function UnityEngine.UIElements.DropdownMenu:AppendSeparator(subMenuPath) end

--- Add a separator line in the menu. The separator is added at the end of the specified index in the list.
function UnityEngine.UIElements.DropdownMenu:InsertSeparator(subMenuPath, atIndex) end

--- Remove the menu item at index.
--- @param index number The index of the item to remove.
function UnityEngine.UIElements.DropdownMenu:RemoveItemAt(index) end

--- Update the status of all items by calling their status callback and remove the separators in excess. This is called just before displaying the menu.
--- @param e UnityEngine.UIElements.EventBase 
function UnityEngine.UIElements.DropdownMenu:PrepareForDisplay(e) end

---  Generated By xerysherry