--- @class UnityEngine.AI.NavMeshBuildDebugSettings Specify which of the temporary data generated while building the NavMesh should be retained in memory after the process has completed.
--- @field flags UnityEngine.AI.NavMeshBuildDebugFlags property getset
---       Specify which types of debug data to collect when building the NavMesh.
UnityEngine.AI.NavMeshBuildDebugSettings = {}

function UnityEngine.AI.NavMeshBuildDebugSettings:set_flags(value) end

---  Generated By xerysherry