--- @class UnityEngine.UIElements.PickingMode Describes the picking behavior.
UnityEngine.UIElements.PickingMode = {
    --- Picking enabled. Default Value.
    Position = 0,
    --- Disables picking.
    Ignore = 1,
}

---  Generated By xerysherry