--- @class UnityEngine.Networking.UnityWebRequestAssetBundle Helpers for downloading asset bundles using UnityWebRequest.
UnityEngine.Networking.UnityWebRequestAssetBundle = {}

--- Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest configured to downloading a Unity Asset Bundle.
function UnityEngine.Networking.UnityWebRequestAssetBundle.GetAssetBundle(uri) end

--- Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest configured to downloading a Unity Asset Bundle.
function UnityEngine.Networking.UnityWebRequestAssetBundle.GetAssetBundle(uri) end

--- Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest configured to downloading a Unity Asset Bundle.
function UnityEngine.Networking.UnityWebRequestAssetBundle.GetAssetBundle(uri, crc) end

--- Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest configured to downloading a Unity Asset Bundle.
function UnityEngine.Networking.UnityWebRequestAssetBundle.GetAssetBundle(uri, crc) end

--- Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest configured to downloading a Unity Asset Bundle.
function UnityEngine.Networking.UnityWebRequestAssetBundle.GetAssetBundle(uri, version, crc) end

--- Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest configured to downloading a Unity Asset Bundle.
function UnityEngine.Networking.UnityWebRequestAssetBundle.GetAssetBundle(uri, version, crc) end

--- Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest configured to downloading a Unity Asset Bundle.
function UnityEngine.Networking.UnityWebRequestAssetBundle.GetAssetBundle(uri, hash, crc) end

--- Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest configured to downloading a Unity Asset Bundle.
function UnityEngine.Networking.UnityWebRequestAssetBundle.GetAssetBundle(uri, hash, crc) end

--- Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest configured to downloading a Unity Asset Bundle.
function UnityEngine.Networking.UnityWebRequestAssetBundle.GetAssetBundle(uri, cachedAssetBundle, crc) end

--- Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest configured to downloading a Unity Asset Bundle.
function UnityEngine.Networking.UnityWebRequestAssetBundle.GetAssetBundle(uri, cachedAssetBundle, crc) end

---  Generated By xerysherry