--- @class UnityEngine.Audio.AudioClipPlayable An implementation of IPlayable that controls an AudioClip.
UnityEngine.Audio.AudioClipPlayable = {}

--- Creates an AudioClipPlayable in the PlayableGraph.
--- @param graph UnityEngine.Playables.PlayableGraph The PlayableGraph that will contain the new AnimationLayerMixerPlayable.
--- @param clip UnityEngine.AudioClip The AudioClip that will be added in the PlayableGraph.
--- @param looping boolean True if the clip should loop, false otherwise.
--- @return UnityEngine.Audio.AudioClipPlayable A AudioClipPlayable linked to the PlayableGraph.
function UnityEngine.Audio.AudioClipPlayable.Create(graph, clip, looping) end

--- @return UnityEngine.Playables.Playable
function UnityEngine.Audio.AudioClipPlayable.op_Implicit(playable) end

--- @return UnityEngine.Audio.AudioClipPlayable
function UnityEngine.Audio.AudioClipPlayable.op_Explicit(playable) end

--- @return UnityEngine.Playables.PlayableHandle
function UnityEngine.Audio.AudioClipPlayable:GetHandle() end

--- @return boolean
function UnityEngine.Audio.AudioClipPlayable:Equals(other) end

--- @return UnityEngine.AudioClip
function UnityEngine.Audio.AudioClipPlayable:GetClip() end

function UnityEngine.Audio.AudioClipPlayable:SetClip(value) end

--- @return boolean
function UnityEngine.Audio.AudioClipPlayable:GetLooped() end

function UnityEngine.Audio.AudioClipPlayable:SetLooped(value) end

--- @return boolean
function UnityEngine.Audio.AudioClipPlayable:IsPlaying() end

--- @return boolean
function UnityEngine.Audio.AudioClipPlayable:IsChannelPlaying() end

--- @return number
function UnityEngine.Audio.AudioClipPlayable:GetStartDelay() end

--- @return number
function UnityEngine.Audio.AudioClipPlayable:GetPauseDelay() end

function UnityEngine.Audio.AudioClipPlayable:Seek(startTime, startDelay) end

function UnityEngine.Audio.AudioClipPlayable:Seek(startTime, startDelay, duration) end

---  Generated By xerysherry