--- @class UnityEngine.XR.WSA.Sharing.SerializationCompletionReason This enum represents the result of a WorldAnchorTransferBatch operation.
UnityEngine.XR.WSA.Sharing.SerializationCompletionReason = {
    --- The operation has completed successfully.
    Succeeded = 0,
    --- The operation has failed because it was not supported.
    NotSupported = 1,
    --- The operation has failed because access was denied.  This occurs typically because the transfer batch was not readable when deserializing or writable when serializing.
    AccessDenied = 2,
    --- The operation has failed in an unexpected way.
    UnknownError = 3,
}

---  Generated By xerysherry