UnityEngine.UI.Image.Origin360 = {
    Bottom = 0,
    Right = 1,
    Top = 2,
    Left = 3,
}

UnityEngine.UI.Image.Origin360 = {
    Bottom = 0,
    Right = 1,
    Top = 2,
    Left = 3,
}

---  Generated By xerysherry