--- @class UnityEngine.WheelJoint2D:UnityEngine.AnchoredJoint2D The wheel joint allows the simulation of wheels by providing a constraining suspension motion with an optional motor.
--- @field suspension UnityEngine.JointSuspension2D property getset
---       Set the joint suspension configuration.
--- @field useMotor boolean property getset
---       Should a motor force be applied automatically to the Rigidbody2D?
--- @field motor UnityEngine.JointMotor2D property getset
---       Parameters for a motor force that is applied automatically to the Rigibody2D along the line.
--- @field jointTranslation number property get
---       The current joint translation.
--- @field jointLinearSpeed number property get
---       The current joint linear speed in meters/sec.
--- @field jointSpeed number property get
---       The current joint rotational speed in degrees/sec.
--- @field jointAngle number property get
---       The current joint angle (in degrees) defined as the relative angle between the two Rigidbody2D that the joint connects to.
--- @field anchor UnityEngine.Vector2
--- @field connectedAnchor UnityEngine.Vector2
--- @field autoConfigureConnectedAnchor boolean
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field connectedBody UnityEngine.Rigidbody2D
--- @field enableCollision boolean
--- @field breakForce number
--- @field breakTorque number
--- @field reactionForce UnityEngine.Vector2
--- @field reactionTorque number
--- @field collideConnected boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.WheelJoint2D = {}

--- @param value UnityEngine.JointSuspension2D 
function UnityEngine.WheelJoint2D:set_suspension(value) end

--- @param value boolean 
function UnityEngine.WheelJoint2D:set_useMotor(value) end

--- @param value UnityEngine.JointMotor2D 
function UnityEngine.WheelJoint2D:set_motor(value) end

--- Gets the motor torque of the joint given the specified timestep.
--- @param timeStep number The time to calculate the motor torque for.
--- @return number 
function UnityEngine.WheelJoint2D:GetMotorTorque(timeStep) end

---  Generated By xerysherry