--- @class UnityEngine.GridLayout:UnityEngine.Behaviour An abstract class that defines a grid layout.
--- @field cellSize UnityEngine.Vector3 property get
---       The size of each cell in the layout.
--- @field cellGap UnityEngine.Vector3 property get
---       The size of the gap between each cell in the layout.
--- @field cellLayout UnityEngine.GridLayout.CellLayout property get
---       The layout of the cells.
--- @field cellSwizzle UnityEngine.GridLayout.CellSwizzle property get
---       The cell swizzle for the layout.
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.GridLayout = {}

--- Returns the local bounds for a cell at the location.
--- @param cellPosition UnityEngine.Vector3Int Location of the cell.
--- @return UnityEngine.Bounds Local bounds of cell at the location.
function UnityEngine.GridLayout:GetBoundsLocal(cellPosition) end

--- Returns the local bounds for the groups of cells at the location.
--- @param origin UnityEngine.Vector3 Origin of the group of cells.
--- @param size UnityEngine.Vector3 Size of the group of cells.
--- @return UnityEngine.Bounds Local bounds of the group of cells at the location.
function UnityEngine.GridLayout:GetBoundsLocal(origin, size) end

--- Converts a cell position to local position space.
--- @param cellPosition UnityEngine.Vector3Int Cell position to convert.
--- @return UnityEngine.Vector3 Local position of the cell position.
function UnityEngine.GridLayout:CellToLocal(cellPosition) end

--- Converts a local position to cell position.
--- @param localPosition UnityEngine.Vector3 Local Position to convert.
--- @return UnityEngine.Vector3Int Cell position of the local position.
function UnityEngine.GridLayout:LocalToCell(localPosition) end

--- Converts an interpolated cell position in floats to local position space.
--- @param cellPosition UnityEngine.Vector3 Interpolated cell position to convert.
--- @return UnityEngine.Vector3 Local position of the cell position.
function UnityEngine.GridLayout:CellToLocalInterpolated(cellPosition) end

--- Converts a local position to cell position.
--- @param localPosition UnityEngine.Vector3 Local Position to convert.
--- @return UnityEngine.Vector3 Interpolated cell position of the local position.
function UnityEngine.GridLayout:LocalToCellInterpolated(localPosition) end

--- Converts a cell position to world position space.
--- @param cellPosition UnityEngine.Vector3Int Cell position to convert.
--- @return UnityEngine.Vector3 World position of the cell position.
function UnityEngine.GridLayout:CellToWorld(cellPosition) end

--- Converts a world position to cell position.
--- @param worldPosition UnityEngine.Vector3 World Position to convert.
--- @return UnityEngine.Vector3Int Cell position of the world position.
function UnityEngine.GridLayout:WorldToCell(worldPosition) end

--- Converts a local position to world position.
--- @param localPosition UnityEngine.Vector3 Local Position to convert.
--- @return UnityEngine.Vector3 World position of the local position.
function UnityEngine.GridLayout:LocalToWorld(localPosition) end

--- Converts a world position to local position.
--- @param worldPosition UnityEngine.Vector3 World Position to convert.
--- @return UnityEngine.Vector3 Local position of the world position.
function UnityEngine.GridLayout:WorldToLocal(worldPosition) end

--- Get the default center coordinate of a cell for the set layout of the Grid.
--- @return UnityEngine.Vector3 Cell Center coordinate.
function UnityEngine.GridLayout:GetLayoutCellCenter() end

---  Generated By xerysherry