--- @class UnityEngine.UIElements.EventBase The base class for all UIElements events.
--- @field eventTypeId number property get
---       Retrieves the type ID for this event instance.
--- @field timestamp number property get
---       The time when the event was created.
--- @field bubbles boolean property get
---       Whether this event type bubbles up in the event propagation path.
--- @field tricklesDown boolean property get
---       Whether this event is sent down the event propagation path during the TrickleDown phase.
--- @field target UnityEngine.UIElements.IEventHandler property getset
---       The target visual element that received this event. Unlike currentTarget, this target does not change when the event is sent to other elements along the propagation path.
--- @field isPropagationStopped boolean property get
---       Whether StopPropagation() was called for this event.
--- @field isImmediatePropagationStopped boolean property get
---       Whether StopImmediatePropagation() was called for this event.
--- @field isDefaultPrevented boolean property get
---       Return true if the default actions should not be executed for this event.
--- @field propagationPhase UnityEngine.UIElements.PropagationPhase property get
---       The current propagation phase.
--- @field currentTarget UnityEngine.UIElements.IEventHandler property get
---       The current target of the event. This is the VisualElement, in the propagation path, for which event handlers are currently being executed.
--- @field dispatch boolean property get
---       Whether the event is being dispatched to a visual element. An event cannot be redispatched while it being dispatched. If you need to recursively dispatch an event, it is recommended that you use a copy of the event.
--- @field imguiEvent UnityEngine.Event property get
---       The IMGUIEvent at the source of this event. The source can be null since not all events are generated by IMGUI.
--- @field originalMousePosition UnityEngine.Vector2 property get
---       The original mouse position of the IMGUI event, before it is transformed to the current target local coordinates.
UnityEngine.UIElements.EventBase = {}

--- Implementation of IDisposable.
function UnityEngine.UIElements.EventBase:Dispose() end

--- @param value UnityEngine.UIElements.IEventHandler 
function UnityEngine.UIElements.EventBase:set_target(value) end

--- Stops propagating this event. The event is not sent to other elements along the propagation path. This method does not prevent other event handlers from executing on the current target.
function UnityEngine.UIElements.EventBase:StopPropagation() end

--- Immediately stops the propagation of the event. The event is not sent to other elements along the propagation path. This method prevents other event handlers from executing on the current target.
function UnityEngine.UIElements.EventBase:StopImmediatePropagation() end

--- Whether the default actions are prevented from being executed for this event.
function UnityEngine.UIElements.EventBase:PreventDefault() end

---  Generated By xerysherry