--- @class UnityEngine.XR.WSA.Input.InteractionSourceUpdatedEventArgs Contains fields that are relevent when an interaction source updates.
--- @field state UnityEngine.XR.WSA.Input.InteractionSourceState property get
---       The current state of the reported interaction source that just updated.
UnityEngine.XR.WSA.Input.InteractionSourceUpdatedEventArgs = {}

---  Generated By xerysherry