--- @class UnityEngine.MeshCollider:UnityEngine.Collider A mesh collider allows you to do between meshes and primitives.
--- @field sharedMesh UnityEngine.Mesh property getset
---       The mesh object used for collision detection.
--- @field convex boolean property getset
---       Use a convex collider from the mesh.
--- @field inflateMesh boolean property getset
---       Allow the physics engine to increase the volume of the input mesh in attempt to generate a valid convex mesh.
--- @field cookingOptions UnityEngine.MeshColliderCookingOptions property getset
---       Options used to enable or disable certain features in mesh cooking.
--- @field skinWidth number property getset
---       Used when set to inflateMesh to determine how much inflation is acceptable.
--- @field smoothSphereCollisions boolean property getset
---       Uses interpolated normals for sphere collisions instead of flat polygonal normals.
--- @field enabled boolean
--- @field attachedRigidbody UnityEngine.Rigidbody
--- @field isTrigger boolean
--- @field contactOffset number
--- @field bounds UnityEngine.Bounds
--- @field sharedMaterial UnityEngine.PhysicMaterial
--- @field material UnityEngine.PhysicMaterial
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.MeshCollider = {}

--- @param value UnityEngine.Mesh 
function UnityEngine.MeshCollider:set_sharedMesh(value) end

--- @param value boolean 
function UnityEngine.MeshCollider:set_convex(value) end

--- @param value boolean 
function UnityEngine.MeshCollider:set_inflateMesh(value) end

--- @param value UnityEngine.MeshColliderCookingOptions 
function UnityEngine.MeshCollider:set_cookingOptions(value) end

--- @param value number 
function UnityEngine.MeshCollider:set_skinWidth(value) end

--- @param value boolean 
function UnityEngine.MeshCollider:set_smoothSphereCollisions(value) end

---  Generated By xerysherry