--- @class UnityEngine.IMECompositionMode Controls IME input.
UnityEngine.IMECompositionMode = {
    --- Enable IME input only when a text field is selected (default).
    Auto = 0,
    --- Enable IME input.
    On = 1,
    --- Disable IME input.
    Off = 2,
}

---  Generated By xerysherry