--- @class UnityEngine.Analytics.AnalyticsSessionInfo Provides access to the Analytics session information for the current game instance.
--- @field sessionState UnityEngine.Analytics.AnalyticsSessionState property get
---       The current state of the session.
--- @field sessionId number property get
---       A random, unique GUID identifying the current game or app session.
--- @field sessionCount number property get
---       The number of sessions played since the app was installed.
--- @field sessionElapsedTime number property get
---       The time elapsed, in milliseconds, since the beginning of the current game session.
--- @field sessionFirstRun boolean property get
---       Reports whether the current session is the first session since the player installed the game or application.
--- @field userId string property get
---       A random GUID uniquely identifying sessions played on the same instance of your game or app.
--- @field customUserId string property getset
---       Reports the current custom user ID.
--- @field customDeviceId string property getset
---       Reports the current custom device ID.
--- @field identityToken string property get
---       The current user identity token that the Analytics server returns based on AnalyticsSessionInfo.userId.
UnityEngine.Analytics.AnalyticsSessionInfo = {}

function UnityEngine.Analytics.AnalyticsSessionInfo.add_sessionStateChanged(value) end

function UnityEngine.Analytics.AnalyticsSessionInfo.remove_sessionStateChanged(value) end

function UnityEngine.Analytics.AnalyticsSessionInfo.set_customUserId(value) end

function UnityEngine.Analytics.AnalyticsSessionInfo.set_customDeviceId(value) end

function UnityEngine.Analytics.AnalyticsSessionInfo.add_identityTokenChanged(value) end

function UnityEngine.Analytics.AnalyticsSessionInfo.remove_identityTokenChanged(value) end

---  Generated By xerysherry