--- @class UnityEngine.XR.WSA.Input.InteractionSource Represents one detected instance of an interaction source (hand, controller, or user's voice) that can cause interactions and gestures.
--- @field id number property get
---       The identifier for the interaction source (hand, controller, or user's voice).
--- @field kind UnityEngine.XR.WSA.Input.InteractionSourceKind property get
---       Specifies the kind of an interaction source.
--- @field handedness UnityEngine.XR.WSA.Input.InteractionSourceHandedness property get
---       Denotes which hand was used as the input source.
--- @field supportsGrasp boolean property get
---       This property returns true when the interaction source has at least one grasp button, and false if otherwise.
--- @field supportsMenu boolean property get
---       This property returns true when the interaction source has a menu button, and false if otherwise.
--- @field supportsPointing boolean property get
---       This property returns true if the interaction source has a separate pose for the pointer, and false if otherwise.
--- @field supportsThumbstick boolean property get
---       Returns true if the interaction source has a thumbstick, and false if otherwise.
--- @field supportsTouchpad boolean property get
---       Returns true if the interaction source has a touchpad, and false if otherwise.
--- @field vendorId number property get
---       All interaction sources developed by the same company will have the same vendor ID.
--- @field productId number property get
---       Following the make and model nomenclature of cars, this equates to the model number.
--- @field productVersion number property get
---       Following the make and model nomenclature of cars, this would be a minor update to the model.
UnityEngine.XR.WSA.Input.InteractionSource = {}

--- @return boolean
function UnityEngine.XR.WSA.Input.InteractionSource:Equals(obj) end

--- @return boolean
function UnityEngine.XR.WSA.Input.InteractionSource:Equals(other) end

--- @return number
function UnityEngine.XR.WSA.Input.InteractionSource:GetHashCode() end

---  Generated By xerysherry