--- @class UnityEngine.BoundingSphere Describes a single bounding sphere for use by a CullingGroup.
--- @field position UnityEngine.Vector3 The position of the center of the BoundingSphere.
--- @field radius number The radius of the BoundingSphere.
UnityEngine.BoundingSphere = {}

---  Generated By xerysherry