--- @class UnityEngine.ParticleSystemVertexStream All possible Particle System vertex shader inputs.
UnityEngine.ParticleSystemVertexStream = {
    --- The position of each particle vertex, in world space.
    Position = 0,
    --- The vertex normal of each particle.
    Normal = 1,
    --- The tangent vector for each particle (for normal mapping).
    Tangent = 2,
    --- The color of each particle.
    Color = 3,
    --- The first UV stream of each particle.
    UV = 4,
    --- The second UV stream of each particle.
    UV2 = 5,
    --- The third UV stream of each particle (only for meshes).
    UV3 = 6,
    --- The fourth UV stream of each particle (only for meshes).
    UV4 = 7,
    --- The amount to blend between animated texture frames, from 0 to 1.
    AnimBlend = 8,
    --- The current animation frame index of each particle.
    AnimFrame = 9,
    --- The center position of the entire particle, in world space.
    Center = 10,
    --- The vertex ID of each particle.
    VertexID = 11,
    --- The X axis size of each particle.
    SizeX = 12,
    --- The X and Y axis sizes of each particle.
    SizeXY = 13,
    --- The 3D size of each particle.
    SizeXYZ = 14,
    --- The Z axis rotation of each particle.
    Rotation = 15,
    --- The 3D rotation of each particle.
    Rotation3D = 16,
    --- The Z axis rotational speed of each particle.
    RotationSpeed = 17,
    --- The 3D rotational speed of each particle.
    RotationSpeed3D = 18,
    --- The velocity of each particle, in world space.
    Velocity = 19,
    --- The speed of each particle, calculated by taking the magnitude of the velocity.
    Speed = 20,
    --- The normalized age of each particle, from 0 to 1.
    AgePercent = 21,
    --- The reciprocal of the starting lifetime, in seconds (1.0f / startLifetime).
    InvStartLifetime = 22,
    --- A random number for each particle, which remains constant during their lifetime.
    StableRandomX = 23,
    --- Two random numbers for each particle, which remain constant during their lifetime.
    StableRandomXY = 24,
    --- Three random numbers for each particle, which remain constant during their lifetime.
    StableRandomXYZ = 25,
    --- Four random numbers for each particle, which remain constant during their lifetime.
    StableRandomXYZW = 26,
    --- A random number for each particle, which changes during their lifetime.
    VaryingRandomX = 27,
    --- Two random numbers for each particle, which change during their lifetime.
    VaryingRandomXY = 28,
    --- Three random numbers for each particle, which change during their lifetime.
    VaryingRandomXYZ = 29,
    --- Four random numbers for each particle, which change during their lifetime.
    VaryingRandomXYZW = 30,
    --- One custom value for each particle, defined by the Custom Data Module, or ParticleSystem.SetCustomParticleData.
    Custom1X = 31,
    --- Two custom values for each particle, defined by the Custom Data Module, or ParticleSystem.SetCustomParticleData.
    Custom1XY = 32,
    --- Three custom values for each particle, defined by the Custom Data Module, or ParticleSystem.SetCustomParticleData.
    Custom1XYZ = 33,
    --- Four custom values for each particle, defined by the Custom Data Module, or ParticleSystem.SetCustomParticleData.
    Custom1XYZW = 34,
    --- One custom value for each particle, defined by the Custom Data Module, or ParticleSystem.SetCustomParticleData.
    Custom2X = 35,
    --- Two custom values for each particle, defined by the Custom Data Module, or ParticleSystem.SetCustomParticleData.
    Custom2XY = 36,
    --- Three custom values for each particle, defined by the Custom Data Module, or ParticleSystem.SetCustomParticleData.
    Custom2XYZ = 37,
    --- Four custom values for each particle, defined by the Custom Data Module, or ParticleSystem.SetCustomParticleData.
    Custom2XYZW = 38,
    --- The accumulated X axis noise, over the lifetime of the particle.
    NoiseSumX = 39,
    --- The accumulated X and Y axis noise, over the lifetime of the particle.
    NoiseSumXY = 40,
    --- The accumulated 3D noise, over the lifetime of the particle.
    NoiseSumXYZ = 41,
    --- The X axis noise on the current frame.
    NoiseImpulseX = 42,
    --- The X and Y axis noise on the current frame.
    NoiseImpulseXY = 43,
    --- The 3D noise on the current frame.
    NoiseImpulseXYZ = 44,
    --- The index of the mesh used by the current particle.
    MeshIndex = 45,
}

---  Generated By xerysherry