--- @class UnityEngine.HelpURLAttribute:System.Attribute Provide a custom documentation URL for a class.
--- @field URL string property get
---       The documentation URL specified for this class.
--- @field TypeId System.Object
UnityEngine.HelpURLAttribute = {}

---  Generated By xerysherry