--- @class UnityEngine.BatteryStatus Enumeration for SystemInfo.batteryStatus which represents the current status of the device's battery.
UnityEngine.BatteryStatus = {
    --- The device's battery status cannot be determined. If battery status is not available on your target platform, SystemInfo.batteryStatus will return this value.
    Unknown = 0,
    --- Device is plugged in and charging.
    Charging = 1,
    --- Device is unplugged and discharging.
    Discharging = 2,
    --- Device is plugged in, but is not charging.
    NotCharging = 3,
    --- Device is plugged in and the battery is full.
    Full = 4,
}

---  Generated By xerysherry