--- @class UnityEngine.Assertions.Comparers.FloatComparer A float comparer used by Assertions.Assert performing approximate comparison.
--- @field s_ComparerWithDefaultTolerance UnityEngine.Assertions.Comparers.FloatComparer Default instance of a comparer class with deafult error epsilon and absolute error check.
--- @field kEpsilon number Default epsilon used by the comparer.
UnityEngine.Assertions.Comparers.FloatComparer = {}

--- Performs equality check with absolute error check.
--- @param expected number Expected value.
--- @param actual number Actual value.
--- @param error number Comparison error.
--- @return boolean Result of the comparison.
function UnityEngine.Assertions.Comparers.FloatComparer.AreEqual(expected, actual, error) end

--- Performs equality check with relative error check.
--- @param expected number Expected value.
--- @param actual number Actual value.
--- @param error number Comparison error.
--- @return boolean Result of the comparison.
function UnityEngine.Assertions.Comparers.FloatComparer.AreEqualRelative(expected, actual, error) end

--- @return boolean
function UnityEngine.Assertions.Comparers.FloatComparer:Equals(a, b) end

--- @return number
function UnityEngine.Assertions.Comparers.FloatComparer:GetHashCode(obj) end

---  Generated By xerysherry