--- @class UnityEngine.Networking.DownloadHandlerMovieTexture:UnityEngine.Networking.DownloadHandler MovieTexture has been removed. Use VideoPlayer instead.
--- @field movieTexture UnityEngine.MovieTexture property get
---       MovieTexture has been removed. Use VideoPlayer instead.
--- @field isDone boolean
--- @field data number[]
--- @field text string
UnityEngine.Networking.DownloadHandlerMovieTexture = {}

--- MovieTexture has been removed. Use VideoPlayer instead.
--- @param uwr UnityEngine.Networking.UnityWebRequest 
--- @return UnityEngine.MovieTexture 
function UnityEngine.Networking.DownloadHandlerMovieTexture.GetContent(uwr) end

---  Generated By xerysherry