--- @class UnityEngine.ProceduralLoadingBehavior Deprecated feature, no longer available
UnityEngine.ProceduralLoadingBehavior = {
    --- Deprecated feature, no longer available
    DoNothing = 0,
    --- Deprecated feature, no longer available
    Generate = 1,
    --- Deprecated feature, no longer available
    BakeAndKeep = 2,
    --- Deprecated feature, no longer available
    BakeAndDiscard = 3,
    --- Deprecated feature, no longer available
    Cache = 4,
    --- Deprecated feature, no longer available
    DoNothingAndCache = 5,
}

---  Generated By xerysherry