--- @class UnityEngine.Windows.WebCam.VideoCapture Records a video from the web camera directly to disk.
--- @field SupportedResolutions System.Collections.Generic.IEnumerable`1 property get
---       A list of all the supported device resolutions for recording videos.
--- @field IsRecording boolean property get
---       Indicates whether or not the VideoCapture instance is currently recording video.
UnityEngine.Windows.WebCam.VideoCapture = {}

--- Returns the supported frame rates at which a video can be recorded given a resolution.
--- @param resolution UnityEngine.Resolution A recording resolution.
--- @return System.Collections.Generic.IEnumerable`1 The frame rates at which the video can be recorded.
function UnityEngine.Windows.WebCam.VideoCapture.GetSupportedFrameRatesForResolution(resolution) end

--- Asynchronously creates an instance of a VideoCapture object that can be used to record videos from the web camera to disk.
--- @param showHolograms boolean Will allow you to capture holograms in your video.
--- @param onCreatedCallback function This callback will be invoked when the VideoCapture instance is created and ready to be used.
function UnityEngine.Windows.WebCam.VideoCapture.CreateAsync(showHolograms, onCreatedCallback) end

--- Asynchronously creates an instance of a VideoCapture object that can be used to record videos from the web camera to disk.
function UnityEngine.Windows.WebCam.VideoCapture.CreateAsync(onCreatedCallback) end

--- Asynchronously starts video mode.
--- @param setupParams UnityEngine.Windows.WebCam.CameraParameters The various settings that should be applied to the web camera.
--- @param audioState UnityEngine.Windows.WebCam.VideoCapture.AudioState Indicates how audio should be recorded.
--- @param onVideoModeStartedCallback function This callback will be invoked once video mode has been activated.
function UnityEngine.Windows.WebCam.VideoCapture:StartVideoModeAsync(setupParams, audioState, onVideoModeStartedCallback) end

--- Asynchronously stops video mode.
--- @param onVideoModeStoppedCallback function This callback will be invoked once video mode has been deactivated.
function UnityEngine.Windows.WebCam.VideoCapture:StopVideoModeAsync(onVideoModeStoppedCallback) end

--- Asynchronously records a video from the web camera to the file system.
--- @param filename string The name of the video to be recorded to.
--- @param onStartedRecordingVideoCallback function Invoked as soon as the video recording begins.
function UnityEngine.Windows.WebCam.VideoCapture:StartRecordingAsync(filename, onStartedRecordingVideoCallback) end

--- Asynchronously stops recording a video from the web camera to the file system.
--- @param onStoppedRecordingVideoCallback function Invoked as soon as video recording has finished.
function UnityEngine.Windows.WebCam.VideoCapture:StopRecordingAsync(onStoppedRecordingVideoCallback) end

--- Provides a COM pointer to the native IVideoDeviceController.
--- @return System.IntPtr A native COM pointer to the IVideoDeviceController.
function UnityEngine.Windows.WebCam.VideoCapture:GetUnsafePointerToVideoDeviceController() end

--- Dispose must be called to shutdown the PhotoCapture instance.
function UnityEngine.Windows.WebCam.VideoCapture:Dispose() end

---  Generated By xerysherry