--- @class UnityEngine.UIElements.ScrollViewMode Mode configuring the ScrollView for the intended usage.
UnityEngine.UIElements.ScrollViewMode = {
    --- Configure ScrollView for vertical scrolling.
    Vertical = 0,
    --- Configure ScrollView for horizontal scrolling.
    Horizontal = 1,
    --- Configure ScrollView for vertical and horizontal scrolling.
    VerticalAndHorizontal = 2,
}

---  Generated By xerysherry