--- @class UnityEngine.UIElements.PointerType A static class that holds pointer type values.
--- @field mouse string The pointer type for mouse events.
--- @field touch string The pointer type for touch events.
--- @field pen string The pointer type for pen events.
--- @field unknown string The pointer type for events created by unknown devices.
UnityEngine.UIElements.PointerType = {}

---  Generated By xerysherry