--- @class UnityEngine.BoneWeight1 Describes any number of skinning bone weights that affect a vertex in a mesh.
--- @field weight number property getset
---       Skinning weight for bone.
--- @field boneIndex number property getset
---       Index of bone.
UnityEngine.BoneWeight1 = {}

--- @return boolean
function UnityEngine.BoneWeight1.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.BoneWeight1.op_Inequality(lhs, rhs) end

function UnityEngine.BoneWeight1:set_weight(value) end

function UnityEngine.BoneWeight1:set_boneIndex(value) end

--- @return boolean
function UnityEngine.BoneWeight1:Equals(other) end

--- @return boolean
function UnityEngine.BoneWeight1:Equals(other) end

--- @return number
function UnityEngine.BoneWeight1:GetHashCode() end

---  Generated By xerysherry