--- @class UnityEngine.UIElements.DetachFromPanelEvent:UnityEngine.UIElements.PanelChangedEventBase`1 Event sent just before an element is detach from its parent, if the parent is the descendant of a panel.
--- @field originPanel UnityEngine.UIElements.IPanel
--- @field destinationPanel UnityEngine.UIElements.IPanel
--- @field eventTypeId number
--- @field timestamp number
--- @field bubbles boolean
--- @field tricklesDown boolean
--- @field target UnityEngine.UIElements.IEventHandler
--- @field isPropagationStopped boolean
--- @field isImmediatePropagationStopped boolean
--- @field isDefaultPrevented boolean
--- @field propagationPhase UnityEngine.UIElements.PropagationPhase
--- @field currentTarget UnityEngine.UIElements.IEventHandler
--- @field dispatch boolean
--- @field imguiEvent UnityEngine.Event
--- @field originalMousePosition UnityEngine.Vector2
UnityEngine.UIElements.DetachFromPanelEvent = {}

---  Generated By xerysherry