--- @class UnityEditorInternal.StateMachine:UnityEngine.Object 
--- @field defaultState UnityEditorInternal.State
--- @field anyStatePosition UnityEngine.Vector3
--- @field parentStateMachinePosition UnityEngine.Vector3
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEditorInternal.StateMachine = {}

function UnityEditorInternal.StateMachine:set_defaultState(value) end

function UnityEditorInternal.StateMachine:set_anyStatePosition(value) end

function UnityEditorInternal.StateMachine:set_parentStateMachinePosition(value) end

--- @return UnityEditorInternal.State
function UnityEditorInternal.StateMachine:GetState(index) end

--- @return UnityEditorInternal.State
function UnityEditorInternal.StateMachine:AddState(stateName) end

--- @return UnityEditorInternal.StateMachine
function UnityEditorInternal.StateMachine:GetStateMachine(index) end

--- @return UnityEditorInternal.StateMachine
function UnityEditorInternal.StateMachine:AddStateMachine(stateMachineName) end

--- @return UnityEditorInternal.Transition
function UnityEditorInternal.StateMachine:AddTransition(src, dst) end

--- @return UnityEditorInternal.Transition
function UnityEditorInternal.StateMachine:AddAnyStateTransition(dst) end

--- @return UnityEngine.Vector3
function UnityEditorInternal.StateMachine:GetStateMachinePosition(i) end

--- @return UnityEditorInternal.Transition[]
function UnityEditorInternal.StateMachine:GetTransitionsFromState(srcState) end

---  Generated By xerysherry