--- @class UnityEngine.XR.WSA.Input.InteractionSourceDetectedEventArgs Contains fields that are relevent when an interaction source is detected.
--- @field state UnityEngine.XR.WSA.Input.InteractionSourceState property get
---       The current state of the reported interaction source that was just detected.
UnityEngine.XR.WSA.Input.InteractionSourceDetectedEventArgs = {}

---  Generated By xerysherry