--- @class UnityEngine.XR.WSA.Input.InteractionSourcePose Pose data of the interaction source at the time of either the gesture or interaction.
--- @field positionAccuracy UnityEngine.XR.WSA.Input.InteractionSourcePositionAccuracy property get
---       The position-tracking accuracy of the interaction source.
UnityEngine.XR.WSA.Input.InteractionSourcePose = {}

--- Gets the position of the interaction source, assuming the backing data is valid.
--- @return boolean This method returns true when the Vector3 passed in was filled out correctly, and false if otherwise.
--- @return UnityEngine.Vector3& 
function UnityEngine.XR.WSA.Input.InteractionSourcePose:TryGetPosition() end

--- Gets the position of the interaction source, assuming the backing data is valid.
--- @param node UnityEngine.XR.WSA.Input.InteractionSourceNode Specifies which part of the controller to query for its position.
--- @return boolean This method returns true when the Vector3 passed in was filled out correctly, and false if otherwise.
--- @return UnityEngine.Vector3& The position of the interaction source, is the function returns true.
function UnityEngine.XR.WSA.Input.InteractionSourcePose:TryGetPosition(node) end

--- Gets the rotation of the interaction source, assuming the backing data is valid.
--- @param node UnityEngine.XR.WSA.Input.InteractionSourceNode 
--- @return boolean This method returns true if the Quaternion passed in was filled out correctly, and false if otherwise.
--- @return UnityEngine.Quaternion& 
function UnityEngine.XR.WSA.Input.InteractionSourcePose:TryGetRotation(node) end

--- Gets the forward vector of the interaction source, assuming rotation is valid.
--- @param node UnityEngine.XR.WSA.Input.InteractionSourceNode Specifies which part of the controller to query for its forward vector.
--- @return boolean This method returns true when the rotation is valid and the Vector3 passed in was filled out correctly, and false if otherwise.
--- @return UnityEngine.Vector3& The forward vector of the interaction source, if the function returns true.
function UnityEngine.XR.WSA.Input.InteractionSourcePose:TryGetForward(node) end

--- Gets the right vector of the interaction source, assuming rotation is valid.
--- @param node UnityEngine.XR.WSA.Input.InteractionSourceNode Specifies which part of the controller to query for its right vector.
--- @return boolean This method returns true if rotation is valid and the Vector3 passed in was filled out correctly, and false if otherwise.
--- @return UnityEngine.Vector3& The right vector of the interaction source, if the function returns true.
function UnityEngine.XR.WSA.Input.InteractionSourcePose:TryGetRight(node) end

--- Gets the up vector of the interaction source, assuming rotation is valid.
--- @param node UnityEngine.XR.WSA.Input.InteractionSourceNode Specifies which part of the controller to query for its up vector.
--- @return boolean Returns true if the rotation is valid and the Vector3 passed in was filled out correctly, and false if otherwise.
--- @return UnityEngine.Vector3& The up vector of the interaction source, if the function returns true.
function UnityEngine.XR.WSA.Input.InteractionSourcePose:TryGetUp(node) end

--- Gets the velocity of the interaction source, assuming the backing data is valid.
--- @return boolean Returns true if the Vector3 passed in was filled out correctly, and false if otherwise.
--- @return UnityEngine.Vector3& The velocity of the interaction source, if the function returns true.
function UnityEngine.XR.WSA.Input.InteractionSourcePose:TryGetVelocity() end

--- Attempts to retrieve a Vector3 representing the current angular velocity of the tracked node.
--- @return boolean True if the angular velocity was set in the output parameter. False if the angular velocity is not available due to limitations of the underlying platform or if the node is not presently tracked.
--- @return UnityEngine.Vector3& If the function returns true, this will be filled out with the angular velocity of the interaction source. If the function returns false, the value filled out should not be used.
function UnityEngine.XR.WSA.Input.InteractionSourcePose:TryGetAngularVelocity() end

---  Generated By xerysherry