--- @class UnityEngine.U2D.SpriteBone A struct that holds a rich set of information that describes the bind pose of this Sprite.
--- @field name string property getset
---       The name of the bone. This is useful when recreating bone hierarchy at editor or runtime. You can also use this as a way of resolving the bone path when a Sprite is bound to a more complex or richer hierarchy.
--- @field position UnityEngine.Vector3 property getset
---       The position in local space of this bone.
--- @field rotation UnityEngine.Quaternion property getset
---       The rotation of this bone in local space.
--- @field length number property getset
---       The length of the bone. This is important for the leaf bones to describe their length without needing another bone as the terminal bone.
--- @field parentId number property getset
---       The ID of the parent of this bone.
UnityEngine.U2D.SpriteBone = {}

function UnityEngine.U2D.SpriteBone:set_name(value) end

function UnityEngine.U2D.SpriteBone:set_position(value) end

function UnityEngine.U2D.SpriteBone:set_rotation(value) end

function UnityEngine.U2D.SpriteBone:set_length(value) end

function UnityEngine.U2D.SpriteBone:set_parentId(value) end

---  Generated By xerysherry