--- @class UnityEngine.CustomYieldInstruction Base class for custom yield instructions to suspend coroutines.
--- @field keepWaiting boolean property get
---       Indicates if coroutine should be kept suspended.
--- @field Current System.Object
UnityEngine.CustomYieldInstruction = {}

--- @return boolean
function UnityEngine.CustomYieldInstruction:MoveNext() end

function UnityEngine.CustomYieldInstruction:Reset() end

---  Generated By xerysherry