--- @class UnityEngine.RaycastHit2D Information returned about an object detected by a raycast in 2D physics.
--- @field centroid UnityEngine.Vector2 property getset
---       The centroid of the primitive used to perform the cast.
--- @field point UnityEngine.Vector2 property getset
---       The point in world space where the ray hit the collider's surface.
--- @field normal UnityEngine.Vector2 property getset
---       The normal vector of the surface hit by the ray.
--- @field distance number property getset
---       The distance from the ray origin to the impact point.
--- @field fraction number property getset
---       Fraction of the distance along the ray that the hit occurred.
--- @field collider UnityEngine.Collider2D property get
---       The collider hit by the ray.
--- @field rigidbody UnityEngine.Rigidbody2D property get
---       The Rigidbody2D attached to the object that was hit.
--- @field transform UnityEngine.Transform property get
---       The Transform of the object that was hit.
UnityEngine.RaycastHit2D = {}

--- @return boolean
function UnityEngine.RaycastHit2D.op_Implicit(hit) end

function UnityEngine.RaycastHit2D:set_centroid(value) end

function UnityEngine.RaycastHit2D:set_point(value) end

function UnityEngine.RaycastHit2D:set_normal(value) end

function UnityEngine.RaycastHit2D:set_distance(value) end

function UnityEngine.RaycastHit2D:set_fraction(value) end

--- @return number
function UnityEngine.RaycastHit2D:CompareTo(other) end

---  Generated By xerysherry