--- @class UnityEngine.XR.WSA.HolographicSettings The Holographic Settings contain functions which effect the performance and presentation of Holograms on Windows Holographic platforms.
--- @field IsDisplayOpaque boolean property get
---       This method returns whether or not the display associated with the main camera reports as opaque.
--- @field IsContentProtectionEnabled boolean property getset
---       Whether the app is displaying protected content.
--- @field ReprojectionMode UnityEngine.XR.WSA.HolographicSettings.HolographicReprojectionMode property getset
---       The kind of reprojection the app is requesting to stabilize its holographic rendering relative to the user's head motion.
--- @field IsLatentFramePresentation boolean property get
---       Returns true if Holographic rendering is currently running with Latent Frame Presentation.  Default value is false.
UnityEngine.XR.WSA.HolographicSettings = {}

--- Sets a point in 3d space that is the focal point of the Scene for the user for this frame. This helps improve the visual fidelity of content around this point. This must be set every frame.
function UnityEngine.XR.WSA.HolographicSettings.SetFocusPointForFrame(position) end

--- Sets a point in 3d space that is the focal point of the Scene for the user for this frame. This helps improve the visual fidelity of content around this point. This must be set every frame.
function UnityEngine.XR.WSA.HolographicSettings.SetFocusPointForFrame(position, normal) end

--- Sets a point in 3d space that is the focal point of the Scene for the user for this frame. This helps improve the visual fidelity of content around this point. This must be set every frame.
--- @param position UnityEngine.Vector3 The position of the focal point in the Scene, relative to the camera.
--- @param normal UnityEngine.Vector3 Surface normal of the plane being viewed at the focal point.
--- @param velocity UnityEngine.Vector3 A vector that describes how the focus point is moving in the Scene at this point in time. This allows the HoloLens to compensate for both your head movement and the movement of the object in the Scene.
function UnityEngine.XR.WSA.HolographicSettings.SetFocusPointForFrame(position, normal, velocity) end

function UnityEngine.XR.WSA.HolographicSettings.set_IsContentProtectionEnabled(value) end

function UnityEngine.XR.WSA.HolographicSettings.set_ReprojectionMode(value) end

--- Option to allow developers to achieve higher framerate at the cost of high latency.  By default this option is off.
--- @param activated boolean True to enable or false to disable Low Latent Frame Presentation.
function UnityEngine.XR.WSA.HolographicSettings.ActivateLatentFramePresentation(activated) end

---  Generated By xerysherry