--- @class UnityEngine.Rendering.BlendOp Blend operation.
UnityEngine.Rendering.BlendOp = {
    --- Add (s + d).
    Add = 0,
    --- Subtract.
    Subtract = 1,
    --- Reverse subtract.
    ReverseSubtract = 2,
    --- Min.
    Min = 3,
    --- Max.
    Max = 4,
    --- Logical Clear (0).
    LogicalClear = 5,
    --- Logical SET (1) (D3D11.1 only).
    LogicalSet = 6,
    --- Logical Copy (s) (D3D11.1 only).
    LogicalCopy = 7,
    --- Logical inverted Copy (!s) (D3D11.1 only).
    LogicalCopyInverted = 8,
    --- Logical No-op (d) (D3D11.1 only).
    LogicalNoop = 9,
    --- Logical Inverse (!d) (D3D11.1 only).
    LogicalInvert = 10,
    --- Logical AND (s & d) (D3D11.1 only).
    LogicalAnd = 11,
    --- Logical NAND !(s & d). D3D11.1 only.
    LogicalNand = 12,
    --- Logical OR (s | d) (D3D11.1 only).
    LogicalOr = 13,
    --- Logical NOR !(s | d) (D3D11.1 only).
    LogicalNor = 14,
    --- Logical XOR (s XOR d) (D3D11.1 only).
    LogicalXor = 15,
    --- Logical Equivalence !(s XOR d) (D3D11.1 only).
    LogicalEquivalence = 16,
    --- Logical reverse AND (s & !d) (D3D11.1 only).
    LogicalAndReverse = 17,
    --- Logical inverted AND (!s & d) (D3D11.1 only).
    LogicalAndInverted = 18,
    --- Logical reverse OR (s | !d) (D3D11.1 only).
    LogicalOrReverse = 19,
    --- Logical inverted OR (!s | d) (D3D11.1 only).
    LogicalOrInverted = 20,
    --- Multiply (Advanced OpenGL blending).
    Multiply = 21,
    --- Screen (Advanced OpenGL blending).
    Screen = 22,
    --- Overlay (Advanced OpenGL blending).
    Overlay = 23,
    --- Darken (Advanced OpenGL blending).
    Darken = 24,
    --- Lighten (Advanced OpenGL blending).
    Lighten = 25,
    --- Color dodge (Advanced OpenGL blending).
    ColorDodge = 26,
    --- Color burn (Advanced OpenGL blending).
    ColorBurn = 27,
    --- Hard light (Advanced OpenGL blending).
    HardLight = 28,
    --- Soft light (Advanced OpenGL blending).
    SoftLight = 29,
    --- Difference (Advanced OpenGL blending).
    Difference = 30,
    --- Exclusion (Advanced OpenGL blending).
    Exclusion = 31,
    --- HSL Hue (Advanced OpenGL blending).
    HSLHue = 32,
    --- HSL saturation (Advanced OpenGL blending).
    HSLSaturation = 33,
    --- HSL color (Advanced OpenGL blending).
    HSLColor = 34,
    --- HSL luminosity (Advanced OpenGL blending).
    HSLLuminosity = 35,
}

---  Generated By xerysherry