--- @class UnityEngine.UIElements.StyleLength Style value that can be either a Length or a StyleKeyword.
--- @field value UnityEngine.UIElements.Length property getset
---       The Length value.
--- @field keyword UnityEngine.UIElements.StyleKeyword property getset
---       The style keyword.
UnityEngine.UIElements.StyleLength = {}

--- @param lhs UnityEngine.UIElements.StyleLength 
--- @param rhs UnityEngine.UIElements.StyleLength 
--- @return boolean
function UnityEngine.UIElements.StyleLength.op_Equality(lhs, rhs) end

--- @param lhs UnityEngine.UIElements.StyleLength 
--- @param rhs UnityEngine.UIElements.StyleLength 
--- @return boolean
function UnityEngine.UIElements.StyleLength.op_Inequality(lhs, rhs) end

--- @param keyword UnityEngine.UIElements.StyleKeyword 
--- @return UnityEngine.UIElements.StyleLength
function UnityEngine.UIElements.StyleLength.op_Implicit(keyword) end

--- @param v number 
--- @return UnityEngine.UIElements.StyleLength
function UnityEngine.UIElements.StyleLength.op_Implicit(v) end

--- @param v UnityEngine.UIElements.Length 
--- @return UnityEngine.UIElements.StyleLength
function UnityEngine.UIElements.StyleLength.op_Implicit(v) end

--- @param value UnityEngine.UIElements.Length 
function UnityEngine.UIElements.StyleLength:set_value(value) end

--- @param value UnityEngine.UIElements.StyleKeyword 
function UnityEngine.UIElements.StyleLength:set_keyword(value) end

--- @param other UnityEngine.UIElements.StyleLength 
--- @return boolean
function UnityEngine.UIElements.StyleLength:Equals(other) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.UIElements.StyleLength:Equals(obj) end

--- @return number
function UnityEngine.UIElements.StyleLength:GetHashCode() end

--- @return string
function UnityEngine.UIElements.StyleLength:ToString() end

---  Generated By xerysherry