--- @class UnityEngine.UIElements.EventDispatcherGate Gates control when the dispatcher processes events.
UnityEngine.UIElements.EventDispatcherGate = {}

--- @return boolean
function UnityEngine.UIElements.EventDispatcherGate.op_Equality(left, right) end

--- @return boolean
function UnityEngine.UIElements.EventDispatcherGate.op_Inequality(left, right) end

--- Implementation of IDisposable.Dispose. Opens the gate. If all gates are open, events in the queue are processed.
function UnityEngine.UIElements.EventDispatcherGate:Dispose() end

--- @return boolean
function UnityEngine.UIElements.EventDispatcherGate:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.EventDispatcherGate:Equals(obj) end

--- @return number
function UnityEngine.UIElements.EventDispatcherGate:GetHashCode() end

---  Generated By xerysherry