--- @class UnityEngine.Windows.Speech.ConfidenceLevel Used by KeywordRecognizer, GrammarRecognizer, DictationRecognizer. Phrases under the specified minimum level will be ignored.
UnityEngine.Windows.Speech.ConfidenceLevel = {
    --- High confidence level.
    High = 0,
    --- Medium confidence level.
    Medium = 1,
    --- Low confidence level.
    Low = 2,
    --- Everything is rejected.
    Rejected = 3,
}

---  Generated By xerysherry