--- @class UnityEngine.Networking.UnityWebRequestTexture Helpers for downloading image files into Textures using UnityWebRequest.
UnityEngine.Networking.UnityWebRequestTexture = {}

--- Create a UnityWebRequest intended to download an image via HTTP GET and create a Texture based on the retrieved data.
--- @param uri string 
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest properly configured to download an image and convert it to a Texture.
function UnityEngine.Networking.UnityWebRequestTexture.GetTexture(uri) end

--- Create a UnityWebRequest intended to download an image via HTTP GET and create a Texture based on the retrieved data.
--- @param uri System.Uri 
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest properly configured to download an image and convert it to a Texture.
function UnityEngine.Networking.UnityWebRequestTexture.GetTexture(uri) end

--- Create a UnityWebRequest intended to download an image via HTTP GET and create a Texture based on the retrieved data.
--- @param uri string The URI of the image to download.
--- @param nonReadable boolean If true, the texture's raw data will not be accessible to script. This can conserve memory. Default: false.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest properly configured to download an image and convert it to a Texture.
function UnityEngine.Networking.UnityWebRequestTexture.GetTexture(uri, nonReadable) end

--- Create a UnityWebRequest intended to download an image via HTTP GET and create a Texture based on the retrieved data.
--- @param uri System.Uri The URI of the image to download.
--- @param nonReadable boolean If true, the texture's raw data will not be accessible to script. This can conserve memory. Default: false.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest properly configured to download an image and convert it to a Texture.
function UnityEngine.Networking.UnityWebRequestTexture.GetTexture(uri, nonReadable) end

---  Generated By xerysherry