--- @class UnityEngine.WWWAudioExtensions 
UnityEngine.WWWAudioExtensions = {}

--- @return UnityEngine.AudioClip
function UnityEngine.WWWAudioExtensions.GetAudioClip(www) end

--- @return UnityEngine.AudioClip
function UnityEngine.WWWAudioExtensions.GetAudioClip(www, threeD) end

--- @return UnityEngine.AudioClip
function UnityEngine.WWWAudioExtensions.GetAudioClip(www, threeD, stream) end

--- @return UnityEngine.AudioClip
function UnityEngine.WWWAudioExtensions.GetAudioClip(www, threeD, stream, audioType) end

--- @return UnityEngine.AudioClip
function UnityEngine.WWWAudioExtensions.GetAudioClipCompressed(www) end

--- @return UnityEngine.AudioClip
function UnityEngine.WWWAudioExtensions.GetAudioClipCompressed(www, threeD) end

--- @return UnityEngine.AudioClip
function UnityEngine.WWWAudioExtensions.GetAudioClipCompressed(www, threeD, audioType) end

--- @return UnityEngine.MovieTexture
function UnityEngine.WWWAudioExtensions.GetMovieTexture(www) end

---  Generated By xerysherry