--- @class UnityEngine.Search.SearchViewFlags Search view flags used to open the Object Picker in various states.
UnityEngine.Search.SearchViewFlags = {
    --- The Search Picker window will be opened using default options.
    None = 0,
    --- The Search Picker window reports debugging information while running queries.
    Debug = 16,
    --- The Search Picker window will ignore any indexed search entry while executing the search query.
    NoIndexing = 32,
    --- The Search Picker window will include results from packages.
    Packages = 256,
    --- The Search Picker window will open with the Saved Searches panel open.
    OpenLeftSidePanel = 2048,
    --- The Search Picker window will open with the Preview Inspector open.
    OpenInspectorPreview = 4096,
    --- The Object Picker window will open centered in the main Editor window.
    Centered = 8192,
    --- The Search Picker window will hide the Search field. This means the user will not be able to edit the initial search query used to open the Search window.
    HideSearchBar = 16384,
    --- The Object Picker window will open in compact list view.
    CompactView = 32768,
    --- The Search Picker window will open in list view.
    ListView = 65536,
    --- The Search Picker window will open in grid view.
    GridView = 131072,
    --- The Search Picker window will open in table view.
    TableView = 262144,
    --- This flag enables the use of the Saved Searches workflow in the Search Picker window.
    EnableSearchQuery = 524288,
    --- This flag disables the use of the Inspector Preview in the Search Picker window.
    DisableInspectorPreview = 1048576,
    --- When creating a new search window, this flag can be used to disable the saved search query side panel.
    DisableSavedSearchQuery = 2097152,
    --- This flag forces the picker to open in builder mode.
    OpenInBuilderMode = 4194304,
    --- This flag forces the picker to open in text mode.
    OpenInTextMode = 8388608,
    --- This flag disables the ability to switch between text mode and builder mode.
    DisableBuilderModeToggle = 16777216,
}

---  Generated By xerysherry