--- @class UnityEngine.iOS.OnDemandResources On Demand Resources API.
--- @field enabled boolean property get
---       Indicates whether player was built with "Use On Demand Resources" player setting enabled.
UnityEngine.iOS.OnDemandResources = {}

--- Creates an On Demand Resources (ODR) request.
--- @param tags string[] Tags for On Demand Resources that should be included in the request.
--- @return UnityEngine.iOS.OnDemandResourcesRequest Object representing ODR request.
function UnityEngine.iOS.OnDemandResources.PreloadAsync(tags) end

---  Generated By xerysherry