--- 
---  Represents a translation of the object. Percentage values in X and Y are relative to the width and height of the visual element where the style value is applied.
---  
--- @class UnityEngine.UIElements.Translate
--- @field x UnityEngine.UIElements.Length
--- @field y UnityEngine.UIElements.Length
--- @field z number
UnityEngine.UIElements.Translate = {}

--- 
---  Returns the value of a Translate object with no translation applied.
---  
--- @return UnityEngine.UIElements.Translate 
function UnityEngine.UIElements.Translate.None() end

--- @param lhs UnityEngine.UIElements.Translate 
--- @param rhs UnityEngine.UIElements.Translate 
--- @return boolean
function UnityEngine.UIElements.Translate.op_Equality(lhs, rhs) end

--- @param lhs UnityEngine.UIElements.Translate 
--- @param rhs UnityEngine.UIElements.Translate 
--- @return boolean
function UnityEngine.UIElements.Translate.op_Inequality(lhs, rhs) end

--- @param value UnityEngine.UIElements.Length 
function UnityEngine.UIElements.Translate:set_x(value) end

--- @param value UnityEngine.UIElements.Length 
function UnityEngine.UIElements.Translate:set_y(value) end

--- @param value number 
function UnityEngine.UIElements.Translate:set_z(value) end

--- @param other UnityEngine.UIElements.Translate 
--- @return boolean
function UnityEngine.UIElements.Translate:Equals(other) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.UIElements.Translate:Equals(obj) end

--- @return number
function UnityEngine.UIElements.Translate:GetHashCode() end

--- @return string
function UnityEngine.UIElements.Translate:ToString() end

---  Generated By xerysherry