--- @class UnityEngine.TextMesh:UnityEngine.Component A script interface for the.
--- @field text string property getset
---       The text that is displayed.
--- @field font UnityEngine.Font property getset
---       The Font used.
--- @field fontSize number property getset
---       The font size to use (for dynamic fonts).
--- @field fontStyle UnityEngine.FontStyle property getset
---       The font style to use (for dynamic fonts).
--- @field offsetZ number property getset
---       How far should the text be offset from the transform.position.z when drawing.
--- @field alignment UnityEngine.TextAlignment property getset
---       How lines of text are aligned (Left, Right, Center).
--- @field anchor UnityEngine.TextAnchor property getset
---       Which point of the text shares the position of the Transform.
--- @field characterSize number property getset
---       The size of each character (This scales the whole text).
--- @field lineSpacing number property getset
---       How much space will be in-between lines of text.
--- @field tabSize number property getset
---       How much space will be inserted for a tab '\t' character. This is a multiplum of the 'spacebar' character offset.
--- @field richText boolean property getset
---       Enable HTML-style tags for Text Formatting Markup.
--- @field color UnityEngine.Color property getset
---       The color used to render the text.
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.TextMesh = {}

function UnityEngine.TextMesh:set_text(value) end

function UnityEngine.TextMesh:set_font(value) end

function UnityEngine.TextMesh:set_fontSize(value) end

function UnityEngine.TextMesh:set_fontStyle(value) end

function UnityEngine.TextMesh:set_offsetZ(value) end

function UnityEngine.TextMesh:set_alignment(value) end

function UnityEngine.TextMesh:set_anchor(value) end

function UnityEngine.TextMesh:set_characterSize(value) end

function UnityEngine.TextMesh:set_lineSpacing(value) end

function UnityEngine.TextMesh:set_tabSize(value) end

function UnityEngine.TextMesh:set_richText(value) end

function UnityEngine.TextMesh:set_color(value) end

---  Generated By xerysherry