--- 
---  Event typically sent when the user presses the D-pad, moves a joystick or presses the arrow keys.
---  
--- @class UnityEngine.UIElements.NavigationMoveEvent:UnityEngine.UIElements.NavigationEventBase`1
--- @field direction UnityEngine.UIElements.NavigationMoveEvent.Direction property get
---       
---        The direction of the navigation.
---        
--- @field move UnityEngine.Vector2 property get
---       
---        The move vector.
---        
--- @field eventTypeId number
--- @field timestamp number
--- @field bubbles boolean
--- @field tricklesDown boolean
--- @field target UnityEngine.UIElements.IEventHandler
--- @field isPropagationStopped boolean
--- @field isImmediatePropagationStopped boolean
--- @field isDefaultPrevented boolean
--- @field propagationPhase UnityEngine.UIElements.PropagationPhase
--- @field currentTarget UnityEngine.UIElements.IEventHandler
--- @field dispatch boolean
--- @field imguiEvent UnityEngine.Event
--- @field originalMousePosition UnityEngine.Vector2
UnityEngine.UIElements.NavigationMoveEvent = {}

--- 
---  Gets an event from the event pool and initializes it with the given values.
---  Use this function instead of creating new events.
---  Events obtained from this method should be released back to the pool using Dispose().
---  
--- @param moveVector UnityEngine.Vector2 The move vector.
--- @return UnityEngine.UIElements.NavigationMoveEvent An initialized navigation event.
function UnityEngine.UIElements.NavigationMoveEvent.GetPooled(moveVector) end

---  Generated By xerysherry