--- @class UnityEngine.UI.Image:UnityEngine.UI.MaskableGraphic 
--- @field defaultETC1GraphicMaterial UnityEngine.Material
--- @field sprite UnityEngine.Sprite
--- @field overrideSprite UnityEngine.Sprite
--- @field type UnityEngine.UI.Image.Type
--- @field preserveAspect boolean
--- @field fillCenter boolean
--- @field fillMethod UnityEngine.UI.Image.FillMethod
--- @field fillAmount number
--- @field fillClockwise boolean
--- @field fillOrigin number
--- @field eventAlphaThreshold number
--- @field alphaHitTestMinimumThreshold number
--- @field useSpriteMesh boolean
--- @field mainTexture UnityEngine.Texture
--- @field hasBorder boolean
--- @field pixelsPerUnitMultiplier number
--- @field pixelsPerUnit number
--- @field material UnityEngine.Material
--- @field minWidth number
--- @field preferredWidth number
--- @field flexibleWidth number
--- @field minHeight number
--- @field preferredHeight number
--- @field flexibleHeight number
--- @field layoutPriority number
--- @field onCullStateChanged UnityEngine.UI.MaskableGraphic.CullStateChangedEvent
--- @field maskable boolean
--- @field isMaskingGraphic boolean
--- @field color UnityEngine.Color
--- @field raycastTarget boolean
--- @field raycastPadding UnityEngine.Vector4
--- @field depth number
--- @field rectTransform UnityEngine.RectTransform
--- @field canvas UnityEngine.Canvas
--- @field canvasRenderer UnityEngine.CanvasRenderer
--- @field defaultMaterial UnityEngine.Material
--- @field materialForRendering UnityEngine.Material
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.Image = {}

--- @param value UnityEngine.Sprite 
function UnityEngine.UI.Image:set_sprite(value) end

function UnityEngine.UI.Image:DisableSpriteOptimizations() end

--- @param value UnityEngine.Sprite 
function UnityEngine.UI.Image:set_overrideSprite(value) end

--- @param value UnityEngine.UI.Image.Type 
function UnityEngine.UI.Image:set_type(value) end

--- @param value boolean 
function UnityEngine.UI.Image:set_preserveAspect(value) end

--- @param value boolean 
function UnityEngine.UI.Image:set_fillCenter(value) end

--- @param value UnityEngine.UI.Image.FillMethod 
function UnityEngine.UI.Image:set_fillMethod(value) end

--- @param value number 
function UnityEngine.UI.Image:set_fillAmount(value) end

--- @param value boolean 
function UnityEngine.UI.Image:set_fillClockwise(value) end

--- @param value number 
function UnityEngine.UI.Image:set_fillOrigin(value) end

--- @param value number 
function UnityEngine.UI.Image:set_eventAlphaThreshold(value) end

--- @param value number 
function UnityEngine.UI.Image:set_alphaHitTestMinimumThreshold(value) end

--- @param value boolean 
function UnityEngine.UI.Image:set_useSpriteMesh(value) end

--- @param value number 
function UnityEngine.UI.Image:set_pixelsPerUnitMultiplier(value) end

--- @param value UnityEngine.Material 
function UnityEngine.UI.Image:set_material(value) end

function UnityEngine.UI.Image:OnBeforeSerialize() end

function UnityEngine.UI.Image:OnAfterDeserialize() end

function UnityEngine.UI.Image:SetNativeSize() end

function UnityEngine.UI.Image:CalculateLayoutInputHorizontal() end

function UnityEngine.UI.Image:CalculateLayoutInputVertical() end

--- @param screenPoint UnityEngine.Vector2 
--- @param eventCamera UnityEngine.Camera 
--- @return boolean
function UnityEngine.UI.Image:IsRaycastLocationValid(screenPoint, eventCamera) end

---  Generated By xerysherry