--- @class UnityEngine.EdgeCollider2D:UnityEngine.Collider2D Collider for 2D physics representing an arbitrary set of connected edges (lines) defined by its vertices.
--- @field edgeRadius number property getset
---       Controls the radius of all edges created by the collider.
--- @field edgeCount number property get
---       Gets the number of edges.
--- @field pointCount number property get
---       Gets the number of points.
--- @field points UnityEngine.Vector2[] property getset
---       Get or set the points defining multiple continuous edges.
--- @field useAdjacentStartPoint boolean property getset
---       Set this to true to use the adjacentStartPoint to form the collision normal that is used to calculate the collision response when a collision occurs at the Edge Collider's start point. Set this to false to not use the adjacentStartPoint, and the collision normal becomes the direction of motion of the collision.
--- @field useAdjacentEndPoint boolean property getset
---       Set this to true to use the adjacentEndPoint to form the collision normal that is used to calculate the collision response when a collision occurs at the Edge Collider's end point. Set this to false to not use the adjacentEndPoint, and the collision normal becomes the direction of motion of the collision.
--- @field adjacentStartPoint UnityEngine.Vector2 property getset
---       Defines the position of a virtual point adjacent to the start point of the EdgeCollider2D.
--- @field adjacentEndPoint UnityEngine.Vector2 property getset
---       Defines the position of a virtual point adjacent to the end point of the EdgeCollider2D.
--- @field density number
--- @field isTrigger boolean
--- @field usedByEffector boolean
--- @field usedByComposite boolean
--- @field composite UnityEngine.CompositeCollider2D
--- @field offset UnityEngine.Vector2
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field shapeCount number
--- @field bounds UnityEngine.Bounds
--- @field errorState UnityEngine.ColliderErrorState2D
--- @field sharedMaterial UnityEngine.PhysicsMaterial2D
--- @field friction number
--- @field bounciness number
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.EdgeCollider2D = {}

--- Reset to a single edge consisting of two points.
function UnityEngine.EdgeCollider2D:Reset() end

function UnityEngine.EdgeCollider2D:set_edgeRadius(value) end

function UnityEngine.EdgeCollider2D:set_points(value) end

--- Gets all the points that define a set of continuous edges.
--- @param points UnityEngine.Vector2[] A list of Vector2 used to receive the points.
--- @return number Returns the number of points placed in the points list.
function UnityEngine.EdgeCollider2D:GetPoints(points) end

--- Sets all the points that define a set of continuous edges.
--- @param points UnityEngine.Vector2[] A list of Vector2 used to set the points. This list must contain at least two points.
--- @return boolean Returns true if the list contains two or more points and the points are correctly set. Returns false otherwise.
function UnityEngine.EdgeCollider2D:SetPoints(points) end

function UnityEngine.EdgeCollider2D:set_useAdjacentStartPoint(value) end

function UnityEngine.EdgeCollider2D:set_useAdjacentEndPoint(value) end

function UnityEngine.EdgeCollider2D:set_adjacentStartPoint(value) end

function UnityEngine.EdgeCollider2D:set_adjacentEndPoint(value) end

---  Generated By xerysherry