--- @class UnityEngine.HumanPartDof Enumeration of all the parts in a human.
UnityEngine.HumanPartDof = {
    --- The human body part.
    Body = 0,
    --- The human head part.
    Head = 1,
    --- The human left leg part.
    LeftLeg = 2,
    --- The human right leg part.
    RightLeg = 3,
    --- The human left arm part.
    LeftArm = 4,
    --- The human right arm part.
    RightArm = 5,
    --- The human left thumb finger part.
    LeftThumb = 6,
    --- The human left index finger part.
    LeftIndex = 7,
    --- The human left middle finger part.
    LeftMiddle = 8,
    --- The human left ring finger part.
    LeftRing = 9,
    --- The human left little finger part.
    LeftLittle = 10,
    --- The human right thumb finger part.
    RightThumb = 11,
    --- The human right index finger part.
    RightIndex = 12,
    --- The human right middle finger part.
    RightMiddle = 13,
    --- The human right ring finger part.
    RightRing = 14,
    --- The human right little finger part.
    RightLittle = 15,
    LastHumanPartDof = 16,
}

---  Generated By xerysherry