--- @class UnityEngine.Tilemaps.TileAnimationData A Struct for the required data for animating a Tile.
--- @field animatedSprites UnityEngine.Sprite[] property getset
---       The array of that are ordered by appearance in the animation.
--- @field animationSpeed number property getset
---       The animation speed.
--- @field animationStartTime number property getset
---       The start time of the animation. The animation will begin at this time offset.
UnityEngine.Tilemaps.TileAnimationData = {}

--- @param value UnityEngine.Sprite[] 
function UnityEngine.Tilemaps.TileAnimationData:set_animatedSprites(value) end

--- @param value number 
function UnityEngine.Tilemaps.TileAnimationData:set_animationSpeed(value) end

--- @param value number 
function UnityEngine.Tilemaps.TileAnimationData:set_animationStartTime(value) end

---  Generated By xerysherry