--- @class UnityEngine.TextAlignment How multiline text should be aligned.
UnityEngine.TextAlignment = {
    --- Text lines are aligned on the left side.
    Left = 0,
    --- Text lines are centered.
    Center = 1,
    --- Text lines are aligned on the right side.
    Right = 2,
}

---  Generated By xerysherry