--- @class UnityEngine.Display Provides access to a display / screen for rendering operations.
--- @field main UnityEngine.Display property get
---       Main Display.
--- @field displays UnityEngine.Display[] The list of currently connected displays.
--- @field renderingWidth number property get
---       Horizontal resolution that the display is rendering at.
--- @field renderingHeight number property get
---       Vertical resolution that the display is rendering at.
--- @field systemWidth number property get
---       Horizontal native display resolution.
--- @field systemHeight number property get
---       Vertical native display resolution.
--- @field colorBuffer UnityEngine.RenderBuffer property get
---       Color RenderBuffer.
--- @field depthBuffer UnityEngine.RenderBuffer property get
---       Depth RenderBuffer.
--- @field active boolean property get
---       Gets the state of the display and returns true if the display is active and false if otherwise.
--- @field requiresBlitToBackbuffer boolean property get
---       True when the back buffer requires an intermediate texture to render.
--- @field requiresSrgbBlitToBackbuffer boolean property get
---       True when doing a blit to the back buffer requires manual color space conversion.
UnityEngine.Display = {}

--- @return boolean
function UnityEngine.Display.MultiDisplayLicense() end

--- Query relative mouse coordinates.
--- @param inputMouseCoordinates UnityEngine.Vector3 Mouse Input Position as Coordinates.
--- @return UnityEngine.Vector3 
function UnityEngine.Display.RelativeMouseAt(inputMouseCoordinates) end

--- @param value function 
function UnityEngine.Display.add_onDisplaysUpdated(value) end

--- @param value function 
function UnityEngine.Display.remove_onDisplaysUpdated(value) end

--- Activate an external display. Eg. Secondary Monitors connected to the System.
function UnityEngine.Display:Activate() end

--- This overloaded function available for Windows allows specifying desired Window Width, Height and Refresh Rate.
--- @param width number Desired Width of the Window (for Windows only. On Linux and Mac uses Screen Width).
--- @param height number Desired Height of the Window (for Windows only. On Linux and Mac uses Screen Height).
--- @param refreshRate number Desired Refresh Rate.
function UnityEngine.Display:Activate(width, height, refreshRate) end

--- Set rendering size and position on screen (Windows only).
--- @param width number Change Window Width (Windows Only).
--- @param height number Change Window Height (Windows Only).
--- @param x number Change Window Position X (Windows Only).
--- @param y number Change Window Position Y (Windows Only).
function UnityEngine.Display:SetParams(width, height, x, y) end

--- Sets rendering resolution for the display.
--- @param w number Rendering width in pixels.
--- @param h number Rendering height in pixels.
function UnityEngine.Display:SetRenderingResolution(w, h) end

---  Generated By xerysherry