--- @class UnityEngine.TextCore.Text.TextSettings:UnityEngine.ScriptableObject 
--- @field version string
--- @field defaultFontAsset UnityEngine.TextCore.Text.FontAsset
--- @field defaultFontAssetPath string
--- @field fallbackFontAssets UnityEngine.TextCore.Text.FontAsset[]
--- @field matchMaterialPreset boolean
--- @field missingCharacterUnicode number
--- @field clearDynamicDataOnBuild boolean
--- @field defaultSpriteAsset UnityEngine.TextCore.Text.SpriteAsset
--- @field defaultSpriteAssetPath string
--- @field fallbackSpriteAssets UnityEngine.TextCore.Text.SpriteAsset[]
--- @field missingSpriteCharacterUnicode number
--- @field defaultStyleSheet UnityEngine.TextCore.Text.TextStyleSheet
--- @field styleSheetsResourcePath string
--- @field defaultColorGradientPresetsPath string
--- @field lineBreakingRules UnityEngine.TextCore.Text.UnicodeLineBreakingRules
--- @field displayWarnings boolean
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.TextCore.Text.TextSettings = {}

--- @param value UnityEngine.TextCore.Text.FontAsset 
function UnityEngine.TextCore.Text.TextSettings:set_defaultFontAsset(value) end

--- @param value string 
function UnityEngine.TextCore.Text.TextSettings:set_defaultFontAssetPath(value) end

--- @param value UnityEngine.TextCore.Text.FontAsset[] 
function UnityEngine.TextCore.Text.TextSettings:set_fallbackFontAssets(value) end

--- @param value boolean 
function UnityEngine.TextCore.Text.TextSettings:set_matchMaterialPreset(value) end

--- @param value number 
function UnityEngine.TextCore.Text.TextSettings:set_missingCharacterUnicode(value) end

--- @param value boolean 
function UnityEngine.TextCore.Text.TextSettings:set_clearDynamicDataOnBuild(value) end

--- @param value UnityEngine.TextCore.Text.SpriteAsset 
function UnityEngine.TextCore.Text.TextSettings:set_defaultSpriteAsset(value) end

--- @param value string 
function UnityEngine.TextCore.Text.TextSettings:set_defaultSpriteAssetPath(value) end

--- @param value UnityEngine.TextCore.Text.SpriteAsset[] 
function UnityEngine.TextCore.Text.TextSettings:set_fallbackSpriteAssets(value) end

--- @param value number 
function UnityEngine.TextCore.Text.TextSettings:set_missingSpriteCharacterUnicode(value) end

--- @param value UnityEngine.TextCore.Text.TextStyleSheet 
function UnityEngine.TextCore.Text.TextSettings:set_defaultStyleSheet(value) end

--- @param value string 
function UnityEngine.TextCore.Text.TextSettings:set_styleSheetsResourcePath(value) end

--- @param value string 
function UnityEngine.TextCore.Text.TextSettings:set_defaultColorGradientPresetsPath(value) end

--- @param value UnityEngine.TextCore.Text.UnicodeLineBreakingRules 
function UnityEngine.TextCore.Text.TextSettings:set_lineBreakingRules(value) end

--- @param value boolean 
function UnityEngine.TextCore.Text.TextSettings:set_displayWarnings(value) end

---  Generated By xerysherry