--- 
---  A menu action item.
---  
--- @class UnityEngine.UIElements.DropdownMenuAction:UnityEngine.UIElements.DropdownMenuItem
--- @field name string property get
---       
---        The name of the item. The name can be prefixed by its submenu path. Path components are delimited by forward slashes ('/').
---        
--- @field status UnityEngine.UIElements.DropdownMenuAction.Status property get
---       
---        The status of the item.
---        
--- @field eventInfo UnityEngine.UIElements.DropdownMenuEventInfo property get
---       
---        Provides information on the event that triggered the drop-down menu.
---        
--- @field userData System.Object property get
---       
---        The userData object stored by the constructor.
---        
UnityEngine.UIElements.DropdownMenuAction = {}

--- 
---  Status callback that always returns Status.Enabled.
---  
--- @param a UnityEngine.UIElements.DropdownMenuAction Unused parameter.
--- @return UnityEngine.UIElements.DropdownMenuAction.Status Always return Status.Enabled.
function UnityEngine.UIElements.DropdownMenuAction.AlwaysEnabled(a) end

--- 
---  Status callback that always returns Status.Disabled.
---  
--- @param a UnityEngine.UIElements.DropdownMenuAction Unused parameter.
--- @return UnityEngine.UIElements.DropdownMenuAction.Status Always return Status.Disabled.
function UnityEngine.UIElements.DropdownMenuAction.AlwaysDisabled(a) end

--- 
---  Update the status flag of this item by calling the item status callback.
---  
--- @param eventInfo UnityEngine.UIElements.DropdownMenuEventInfo Information about the event that triggered the display of the drop-down menu, such as the mouse position or the key pressed.
function UnityEngine.UIElements.DropdownMenuAction:UpdateActionStatus(eventInfo) end

--- 
---  Execute the callback associated with this item.
---  
function UnityEngine.UIElements.DropdownMenuAction:Execute() end

---  Generated By xerysherry