--- @class Unity.Rendering.HybridV2.DOTSInstancingPropertyType Describes the type of a DOTS instancing property.
Unity.Rendering.HybridV2.DOTSInstancingPropertyType = {
    --- The property has an unknown type.
    Unknown = 0,
    --- The property has type float.
    Float = 1,
    --- The property has type half.
    Half = 2,
    --- The property has type int.
    Int = 3,
    --- The property has type short.
    Short = 4,
    --- The property has type uint.
    Uint = 5,
    --- The property has type bool.
    Bool = 6,
    --- The property has a structure type.
    Struct = 7,
}

---  Generated By xerysherry