--- @class UnityEngine.ResourcesAPI Derive from this base class to provide alternative implementations to the C# behavior of specific Resources methods.
--- @field overrideAPI UnityEngine.ResourcesAPI property getset
---       The specific ResourcesAPI instance to use to handle overridden Resources methods.
UnityEngine.ResourcesAPI = {}

--- @param value UnityEngine.ResourcesAPI 
function UnityEngine.ResourcesAPI.set_overrideAPI(value) end

---  Generated By xerysherry