UnityEngine.EventSystems.PointerEventData.InputButton = {
    Left = 0,
    Right = 1,
    Middle = 2,
}

UnityEngine.EventSystems.PointerEventData.InputButton = {
    Left = 0,
    Right = 1,
    Middle = 2,
}

---  Generated By xerysherry