--- 
---  Style value that can be either a FontDefinition or a StyleKeyword.
---  
--- @class UnityEngine.UIElements.StyleFontDefinition
--- @field value UnityEngine.UIElements.FontDefinition property getset
---       
---        The actual value of the definition.
---        
--- @field keyword UnityEngine.UIElements.StyleKeyword property getset
---       
---        The style keyword.
---        
UnityEngine.UIElements.StyleFontDefinition = {}

--- @param keyword UnityEngine.UIElements.StyleKeyword 
--- @return UnityEngine.UIElements.StyleFontDefinition
function UnityEngine.UIElements.StyleFontDefinition.op_Implicit(keyword) end

--- @param f UnityEngine.UIElements.FontDefinition 
--- @return UnityEngine.UIElements.StyleFontDefinition
function UnityEngine.UIElements.StyleFontDefinition.op_Implicit(f) end

--- @param left UnityEngine.UIElements.StyleFontDefinition 
--- @param right UnityEngine.UIElements.StyleFontDefinition 
--- @return boolean
function UnityEngine.UIElements.StyleFontDefinition.op_Equality(left, right) end

--- @param left UnityEngine.UIElements.StyleFontDefinition 
--- @param right UnityEngine.UIElements.StyleFontDefinition 
--- @return boolean
function UnityEngine.UIElements.StyleFontDefinition.op_Inequality(left, right) end

--- @param value UnityEngine.UIElements.FontDefinition 
function UnityEngine.UIElements.StyleFontDefinition:set_value(value) end

--- @param value UnityEngine.UIElements.StyleKeyword 
function UnityEngine.UIElements.StyleFontDefinition:set_keyword(value) end

--- @param other UnityEngine.UIElements.StyleFontDefinition 
--- @return boolean
function UnityEngine.UIElements.StyleFontDefinition:Equals(other) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.UIElements.StyleFontDefinition:Equals(obj) end

--- @return number
function UnityEngine.UIElements.StyleFontDefinition:GetHashCode() end

---  Generated By xerysherry