--- @class UnityEngine.SparseTexture:UnityEngine.Texture Class for handling Sparse Textures.
--- @field tileWidth number property get
---       Get sparse texture tile width (Read Only).
--- @field tileHeight number property get
---       Get sparse texture tile height (Read Only).
--- @field isCreated boolean property get
---       Is the sparse texture actually created? (Read Only)
--- @field mipmapCount number
--- @field graphicsFormat UnityEngine.Experimental.Rendering.GraphicsFormat
--- @field width number
--- @field height number
--- @field dimension UnityEngine.Rendering.TextureDimension
--- @field isReadable boolean
--- @field wrapMode UnityEngine.TextureWrapMode
--- @field wrapModeU UnityEngine.TextureWrapMode
--- @field wrapModeV UnityEngine.TextureWrapMode
--- @field wrapModeW UnityEngine.TextureWrapMode
--- @field filterMode UnityEngine.FilterMode
--- @field anisoLevel number
--- @field mipMapBias number
--- @field texelSize UnityEngine.Vector2
--- @field updateCount number
--- @field imageContentsHash UnityEngine.Hash128
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.SparseTexture = {}

--- Update sparse texture tile with color values.
--- @param tileX number Tile X coordinate.
--- @param tileY number Tile Y coordinate.
--- @param miplevel number Mipmap level of the texture.
--- @param data UnityEngine.Color32[] Tile color data.
function UnityEngine.SparseTexture:UpdateTile(tileX, tileY, miplevel, data) end

--- Update sparse texture tile with raw pixel values.
--- @param tileX number Tile X coordinate.
--- @param tileY number Tile Y coordinate.
--- @param miplevel number Mipmap level of the texture.
--- @param data number[] Tile raw pixel data.
function UnityEngine.SparseTexture:UpdateTileRaw(tileX, tileY, miplevel, data) end

--- Unload sparse texture tile.
--- @param tileX number Tile X coordinate.
--- @param tileY number Tile Y coordinate.
--- @param miplevel number Mipmap level of the texture.
function UnityEngine.SparseTexture:UnloadTile(tileX, tileY, miplevel) end

---  Generated By xerysherry