--- @class UnityEngine.Rendering.RenderPipelineManager Render Pipeline manager.
--- @field currentPipeline UnityEngine.Rendering.RenderPipeline property get
---       Returns the instance of the current RenderPipeline.
UnityEngine.Rendering.RenderPipelineManager = {}

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.add_beginContextRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.remove_beginContextRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.add_endContextRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.remove_endContextRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.add_beginFrameRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.remove_beginFrameRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.add_beginCameraRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.remove_beginCameraRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.add_endFrameRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.remove_endFrameRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.add_endCameraRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.remove_endCameraRendering(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.add_activeRenderPipelineTypeChanged(value) end

--- @param value function 
function UnityEngine.Rendering.RenderPipelineManager.remove_activeRenderPipelineTypeChanged(value) end

---  Generated By xerysherry