--- @class UnityEngine.WindZone:UnityEngine.Component Wind Zones add realism to the trees you create by making them wave their branches and leaves as if blown by the wind.
--- @field mode UnityEngine.WindZoneMode property getset
---       Defines the type of wind zone to be used (Spherical or Directional).
--- @field radius number property getset
---       Radius of the Spherical Wind Zone (only active if the WindZoneMode is set to Spherical).
--- @field windMain number property getset
---       The primary wind force.
--- @field windTurbulence number property getset
---       The turbulence wind force.
--- @field windPulseMagnitude number property getset
---       Defines how much the wind changes over time.
--- @field windPulseFrequency number property getset
---       Defines the frequency of the wind changes.
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.WindZone = {}

function UnityEngine.WindZone:set_mode(value) end

function UnityEngine.WindZone:set_radius(value) end

function UnityEngine.WindZone:set_windMain(value) end

function UnityEngine.WindZone:set_windTurbulence(value) end

function UnityEngine.WindZone:set_windPulseMagnitude(value) end

function UnityEngine.WindZone:set_windPulseFrequency(value) end

---  Generated By xerysherry