--- 
---  Controls how many items can be selected at once.
---  
--- @class UnityEngine.UIElements.SelectionType
UnityEngine.UIElements.SelectionType = {
    --- 
    ---  Selections are disabled.
    ---  
    None = 0,
    --- 
    ---  Only one item is selectable.
    ---  
    Single = 1,
    --- 
    ---  Multiple items are selectable at once.
    ---  
    Multiple = 2,
}

---  Generated By xerysherry