--- @class UnityEngine.Analytics.AnalyticsSessionState Session tracking states.
UnityEngine.Analytics.AnalyticsSessionState = {
    --- Session tracking has stopped.
    kSessionStopped = 0,
    --- Session tracking has started.
    kSessionStarted = 1,
    --- Session tracking has paused.
    kSessionPaused = 2,
    --- Session tracking has resumed.
    kSessionResumed = 3,
}

---  Generated By xerysherry