--- 
---  Represents a time value.
---  
--- @class UnityEngine.UIElements.TimeValue
--- @field value number property getset
---       
---        The time value.
---        
--- @field unit UnityEngine.UIElements.TimeUnit property getset
---       
---        The unit of the value property.
---        
UnityEngine.UIElements.TimeValue = {}

--- @return UnityEngine.UIElements.TimeValue
function UnityEngine.UIElements.TimeValue.op_Implicit(value) end

--- @return boolean
function UnityEngine.UIElements.TimeValue.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.UIElements.TimeValue.op_Inequality(lhs, rhs) end

function UnityEngine.UIElements.TimeValue:set_value(value) end

function UnityEngine.UIElements.TimeValue:set_unit(value) end

--- @return boolean
function UnityEngine.UIElements.TimeValue:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.TimeValue:Equals(obj) end

--- @return number
function UnityEngine.UIElements.TimeValue:GetHashCode() end

--- @return string
function UnityEngine.UIElements.TimeValue:ToString() end

---  Generated By xerysherry