--- The ExternalGPUProfiler API allows developers to programatically take GPU frame captures in conjunction with supported external GPU profilers.
--- 
--- GPU frame captures can be used to both analyze performance and debug graphics related issues.
--- @class UnityEngine.Experimental.Rendering.ExternalGPUProfiler
UnityEngine.Experimental.Rendering.ExternalGPUProfiler = {}

--- Begins the current GPU frame capture in the external GPU profiler.
function UnityEngine.Experimental.Rendering.ExternalGPUProfiler.BeginGPUCapture() end

--- Ends the current GPU frame capture in the external GPU profiler.
function UnityEngine.Experimental.Rendering.ExternalGPUProfiler.EndGPUCapture() end

--- Returns true when a development build is launched by an external GPU profiler.
--- @return boolean 
function UnityEngine.Experimental.Rendering.ExternalGPUProfiler.IsAttached() end

---  Generated By xerysherry