--- @class UnityEngine.UI.GraphicRebuildTracker 
UnityEngine.UI.GraphicRebuildTracker = {}

--- @param g UnityEngine.UI.Graphic 
function UnityEngine.UI.GraphicRebuildTracker.TrackGraphic(g) end

--- @param g UnityEngine.UI.Graphic 
function UnityEngine.UI.GraphicRebuildTracker.UnTrackGraphic(g) end

---  Generated By xerysherry