--- @class UnityEngine.DistanceJoint2D:UnityEngine.AnchoredJoint2D Joint that keeps two Rigidbody2D objects a fixed distance apart.
--- @field autoConfigureDistance boolean property getset
---       Should the distance be calculated automatically?
--- @field distance number property getset
---       The distance separating the two ends of the joint.
--- @field maxDistanceOnly boolean property getset
---       Whether to maintain a maximum distance only or not.  If not then the absolute distance will be maintained instead.
--- @field anchor UnityEngine.Vector2
--- @field connectedAnchor UnityEngine.Vector2
--- @field autoConfigureConnectedAnchor boolean
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field connectedBody UnityEngine.Rigidbody2D
--- @field enableCollision boolean
--- @field breakForce number
--- @field breakTorque number
--- @field reactionForce UnityEngine.Vector2
--- @field reactionTorque number
--- @field collideConnected boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.DistanceJoint2D = {}

function UnityEngine.DistanceJoint2D:set_autoConfigureDistance(value) end

function UnityEngine.DistanceJoint2D:set_distance(value) end

function UnityEngine.DistanceJoint2D:set_maxDistanceOnly(value) end

---  Generated By xerysherry