--- @class UnityEngine.ComputeBufferType ComputeBuffer type.
UnityEngine.ComputeBufferType = {
    --- Default ComputeBuffer type (structured buffer).
    Default = 0,
    --- Raw ComputeBuffer type (byte address buffer).
    Raw = 1,
    --- Append-consume ComputeBuffer type.
    Append = 2,
    --- ComputeBuffer with a counter.
    Counter = 4,
    --- ComputeBuffer that you can use as a constant buffer (uniform buffer).
    Constant = 8,
    --- ComputeBuffer that you can use as a structured buffer.
    Structured = 16,
    --- ComputeBuffer used for Graphics.DrawProceduralIndirect, ComputeShader.DispatchIndirect or Graphics.DrawMeshInstancedIndirect arguments.
    IndirectArguments = 256,
}

---  Generated By xerysherry