--- @class UnityEngine.EventSystems.BaseEventData:UnityEngine.EventSystems.AbstractEventData 
--- @field currentInputModule UnityEngine.EventSystems.BaseInputModule
--- @field selectedObject UnityEngine.GameObject
--- @field used boolean
UnityEngine.EventSystems.BaseEventData = {}

--- @param value UnityEngine.GameObject 
function UnityEngine.EventSystems.BaseEventData:set_selectedObject(value) end

---  Generated By xerysherry