--- 
---  Contains the settings used by the dynamic atlas system.
---  
--- @class UnityEngine.UIElements.DynamicAtlasSettings
--- @field defaultFilters UnityEngine.UIElements.DynamicAtlasFilters property get
---       
---        Default filters for a dynamic atlas.
---        
--- @field defaults UnityEngine.UIElements.DynamicAtlasSettings property get
---       
---        Specifies default values used to initialize the structure.
---        
--- @field minAtlasSize number property getset
---       
---        Specifies the minimum size (width/height) of the atlas texture, in pixels. This value must be a power of two,
---        and must be greater than 0 and less than or equal to maxAtlasSize.
---        
--- @field maxAtlasSize number property getset
---       
---        Specifies the maximum size (width/height) of the atlas texture, in pixels. This value must be a power of two,
---        and must be greater than or equal to minAtlasSize.
---        
--- @field maxSubTextureSize number property getset
---       
---        Specifies the maximum size (width/height) of a texture that can be added to the atlas. When activeFilters
---        contains DynamicAtlasFilters.Size, textures larger than this size are excluded from the atlas. Otherwise, this
---        value is not used.
---        
--- @field activeFilters UnityEngine.UIElements.DynamicAtlasFilters property getset
---       
---        Defines the filters that the dynamic atlas system uses to exclude textures from the texture atlas.
---        
--- @field customFilter function property getset
---       
---        When a delegate is assigned, the dynamic atlas system calls it to determine whether or not a texture can be added to the atlas.
---        
UnityEngine.UIElements.DynamicAtlasSettings = {}

function UnityEngine.UIElements.DynamicAtlasSettings:set_minAtlasSize(value) end

function UnityEngine.UIElements.DynamicAtlasSettings:set_maxAtlasSize(value) end

function UnityEngine.UIElements.DynamicAtlasSettings:set_maxSubTextureSize(value) end

function UnityEngine.UIElements.DynamicAtlasSettings:set_activeFilters(value) end

function UnityEngine.UIElements.DynamicAtlasSettings:set_customFilter(value) end

---  Generated By xerysherry