--- @class UnityEngine.VFX.VFXSpawnerState The spawn state of a Spawn system.
--- @field playing boolean property getset
---       The current playing state.
--- @field newLoop boolean property get
---       This boolean indicates if a new loop has just started.
--- @field loopState UnityEngine.VFX.VFXSpawnerLoopState property getset
---       The current state of VFXSpawnerState.
--- @field spawnCount number property getset
---       The current Spawn count.
--- @field deltaTime number property getset
---       The current delta time.
--- @field totalTime number property getset
---       The accumulated delta time since the last Play event.
--- @field delayBeforeLoop number property getset
---       The current delay time that the VFXSpawner waits for before it starts a loop.
--- @field loopDuration number property getset
---       The duration of the looping state.
--- @field delayAfterLoop number property getset
---       The current delay time that the VFXSpawner waits for after it finishes a loop.
--- @field loopIndex number property getset
---       The current index of loop.
--- @field loopCount number property getset
---       The current loop count.
--- @field vfxEventAttribute UnityEngine.VFX.VFXEventAttribute property get
---       Gets the modifiable current event attribute (Read Only).
UnityEngine.VFX.VFXSpawnerState = {}

function UnityEngine.VFX.VFXSpawnerState:Dispose() end

--- @param value boolean 
function UnityEngine.VFX.VFXSpawnerState:set_playing(value) end

--- @param value UnityEngine.VFX.VFXSpawnerLoopState 
function UnityEngine.VFX.VFXSpawnerState:set_loopState(value) end

--- @param value number 
function UnityEngine.VFX.VFXSpawnerState:set_spawnCount(value) end

--- @param value number 
function UnityEngine.VFX.VFXSpawnerState:set_deltaTime(value) end

--- @param value number 
function UnityEngine.VFX.VFXSpawnerState:set_totalTime(value) end

--- @param value number 
function UnityEngine.VFX.VFXSpawnerState:set_delayBeforeLoop(value) end

--- @param value number 
function UnityEngine.VFX.VFXSpawnerState:set_loopDuration(value) end

--- @param value number 
function UnityEngine.VFX.VFXSpawnerState:set_delayAfterLoop(value) end

--- @param value number 
function UnityEngine.VFX.VFXSpawnerState:set_loopIndex(value) end

--- @param value number 
function UnityEngine.VFX.VFXSpawnerState:set_loopCount(value) end

---  Generated By xerysherry