--- @class UnityEngine.EventSystems.PointerEventData:UnityEngine.EventSystems.BaseEventData 
--- @field pointerEnter UnityEngine.GameObject
--- @field lastPress UnityEngine.GameObject
--- @field rawPointerPress UnityEngine.GameObject
--- @field pointerDrag UnityEngine.GameObject
--- @field pointerClick UnityEngine.GameObject
--- @field pointerCurrentRaycast UnityEngine.EventSystems.RaycastResult
--- @field pointerPressRaycast UnityEngine.EventSystems.RaycastResult
--- @field eligibleForClick boolean
--- @field pointerId number
--- @field position UnityEngine.Vector2
--- @field delta UnityEngine.Vector2
--- @field pressPosition UnityEngine.Vector2
--- @field worldPosition UnityEngine.Vector3
--- @field worldNormal UnityEngine.Vector3
--- @field clickTime number
--- @field clickCount number
--- @field scrollDelta UnityEngine.Vector2
--- @field useDragThreshold boolean
--- @field dragging boolean
--- @field button UnityEngine.EventSystems.PointerEventData.InputButton
--- @field pressure number
--- @field tangentialPressure number
--- @field altitudeAngle number
--- @field azimuthAngle number
--- @field twist number
--- @field radius UnityEngine.Vector2
--- @field radiusVariance UnityEngine.Vector2
--- @field enterEventCamera UnityEngine.Camera
--- @field pressEventCamera UnityEngine.Camera
--- @field pointerPress UnityEngine.GameObject
--- @field currentInputModule UnityEngine.EventSystems.BaseInputModule
--- @field selectedObject UnityEngine.GameObject
--- @field used boolean
--- @field hovered UnityEngine.GameObject[]
UnityEngine.EventSystems.PointerEventData = {}

function UnityEngine.EventSystems.PointerEventData:set_pointerEnter(value) end

function UnityEngine.EventSystems.PointerEventData:set_rawPointerPress(value) end

function UnityEngine.EventSystems.PointerEventData:set_pointerDrag(value) end

function UnityEngine.EventSystems.PointerEventData:set_pointerClick(value) end

function UnityEngine.EventSystems.PointerEventData:set_pointerCurrentRaycast(value) end

function UnityEngine.EventSystems.PointerEventData:set_pointerPressRaycast(value) end

function UnityEngine.EventSystems.PointerEventData:set_eligibleForClick(value) end

function UnityEngine.EventSystems.PointerEventData:set_pointerId(value) end

function UnityEngine.EventSystems.PointerEventData:set_position(value) end

function UnityEngine.EventSystems.PointerEventData:set_delta(value) end

function UnityEngine.EventSystems.PointerEventData:set_pressPosition(value) end

function UnityEngine.EventSystems.PointerEventData:set_worldPosition(value) end

function UnityEngine.EventSystems.PointerEventData:set_worldNormal(value) end

function UnityEngine.EventSystems.PointerEventData:set_clickTime(value) end

function UnityEngine.EventSystems.PointerEventData:set_clickCount(value) end

function UnityEngine.EventSystems.PointerEventData:set_scrollDelta(value) end

function UnityEngine.EventSystems.PointerEventData:set_useDragThreshold(value) end

function UnityEngine.EventSystems.PointerEventData:set_dragging(value) end

function UnityEngine.EventSystems.PointerEventData:set_button(value) end

function UnityEngine.EventSystems.PointerEventData:set_pressure(value) end

function UnityEngine.EventSystems.PointerEventData:set_tangentialPressure(value) end

function UnityEngine.EventSystems.PointerEventData:set_altitudeAngle(value) end

function UnityEngine.EventSystems.PointerEventData:set_azimuthAngle(value) end

function UnityEngine.EventSystems.PointerEventData:set_twist(value) end

function UnityEngine.EventSystems.PointerEventData:set_radius(value) end

function UnityEngine.EventSystems.PointerEventData:set_radiusVariance(value) end

--- @return boolean
function UnityEngine.EventSystems.PointerEventData:IsPointerMoving() end

--- @return boolean
function UnityEngine.EventSystems.PointerEventData:IsScrolling() end

function UnityEngine.EventSystems.PointerEventData:set_pointerPress(value) end

--- @return string
function UnityEngine.EventSystems.PointerEventData:ToString() end

---  Generated By xerysherry