--- @class UnityEngine.Microphone Use this class to record to an AudioClip using a connected microphone.
--- @field devices string[] property get
---       A list of available microphone devices, identified by name.
UnityEngine.Microphone = {}

--- Start Recording with device.
--- @param deviceName string The name of the device.
--- @param loop boolean Indicates whether the recording should continue recording if lengthSec is reached, and wrap around and record from the beginning of the AudioClip.
--- @param lengthSec number Is the length of the AudioClip produced by the recording.
--- @param frequency number The sample rate of the AudioClip produced by the recording.
--- @return UnityEngine.AudioClip The function returns null if the recording fails to start.
function UnityEngine.Microphone.Start(deviceName, loop, lengthSec, frequency) end

--- Stops recording.
--- @param deviceName string The name of the device.
function UnityEngine.Microphone.End(deviceName) end

--- Query if a device is currently recording.
--- @param deviceName string The name of the device.
--- @return boolean 
function UnityEngine.Microphone.IsRecording(deviceName) end

--- Get the position in samples of the recording.
--- @param deviceName string The name of the device.
--- @return number 
function UnityEngine.Microphone.GetPosition(deviceName) end

--- Get the frequency capabilities of a device.
--- @param deviceName string The name of the device.
--- @return System.Int32& Returns the minimum sampling frequency of the device.
--- @return System.Int32& Returns the maximum sampling frequency of the device.
function UnityEngine.Microphone.GetDeviceCaps(deviceName) end

---  Generated By xerysherry