--- @class UnityEngine.PhysicsShape2D Represents an efficient low-level physics shape used by the physics engine.
--- @field shapeType UnityEngine.PhysicsShapeType2D property getset
---       The shape type determines how the vertices and radius are used by this PhysicsShape2D.
--- @field radius number property getset
---       The radius of the shape.
--- @field vertexStartIndex number property getset
---       The start index for the geometry of this shape within the PhysicsShapeGroup2D.
--- @field vertexCount number property getset
---       The total number of vertices used to represent the PhysicsShape2D.shapeType|shape type.
--- @field useAdjacentStart boolean property getset
---       When the value is true, then the shape will use the PhysicsShape2D.adjacentStart|adjacentStart feature. When the value is false, then the shape will not use the PhysicsShape2D.adjacentEnd|adjacentStart feature.
--- @field useAdjacentEnd boolean property getset
---       When the value is true, then the shape will use the PhysicsShape2D.adjacentEnd|adjacentEnd feature. When the value is false, then the shape will not use the PhysicsShape2D.adjacentEnd|adjacentEnd feature.
--- @field adjacentStart UnityEngine.Vector2 property getset
---       Defines the position of a virtual point adjacent to the start vertex of an edge shape.
--- @field adjacentEnd UnityEngine.Vector2 property getset
---       Defines the position of a virtual point adjacent to the end vertex of an edge shape.
UnityEngine.PhysicsShape2D = {}

--- @param value UnityEngine.PhysicsShapeType2D 
function UnityEngine.PhysicsShape2D:set_shapeType(value) end

--- @param value number 
function UnityEngine.PhysicsShape2D:set_radius(value) end

--- @param value number 
function UnityEngine.PhysicsShape2D:set_vertexStartIndex(value) end

--- @param value number 
function UnityEngine.PhysicsShape2D:set_vertexCount(value) end

--- @param value boolean 
function UnityEngine.PhysicsShape2D:set_useAdjacentStart(value) end

--- @param value boolean 
function UnityEngine.PhysicsShape2D:set_useAdjacentEnd(value) end

--- @param value UnityEngine.Vector2 
function UnityEngine.PhysicsShape2D:set_adjacentStart(value) end

--- @param value UnityEngine.Vector2 
function UnityEngine.PhysicsShape2D:set_adjacentEnd(value) end

---  Generated By xerysherry