--- 
---  Style value that can be either a Font or a StyleKeyword.
---  
--- @class UnityEngine.UIElements.StyleFont
--- @field value UnityEngine.Font property getset
---       
---        The Font value.
---        
--- @field keyword UnityEngine.UIElements.StyleKeyword property getset
---       
---        The style keyword.
---        
UnityEngine.UIElements.StyleFont = {}

--- @return boolean
function UnityEngine.UIElements.StyleFont.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.UIElements.StyleFont.op_Inequality(lhs, rhs) end

--- @return UnityEngine.UIElements.StyleFont
function UnityEngine.UIElements.StyleFont.op_Implicit(keyword) end

--- @return UnityEngine.UIElements.StyleFont
function UnityEngine.UIElements.StyleFont.op_Implicit(v) end

function UnityEngine.UIElements.StyleFont:set_value(value) end

function UnityEngine.UIElements.StyleFont:set_keyword(value) end

--- @return boolean
function UnityEngine.UIElements.StyleFont:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.StyleFont:Equals(obj) end

--- @return number
function UnityEngine.UIElements.StyleFont:GetHashCode() end

--- @return string
function UnityEngine.UIElements.StyleFont:ToString() end

---  Generated By xerysherry