--- @class UnityEngine.PlayerPrefs `PlayerPrefs` is a class that stores Player preferences between game sessions. It can store string, float and integer values into the user’s platform registry.
UnityEngine.PlayerPrefs = {}

--- Sets a single integer value for the preference identified by the given key. You can use PlayerPrefs.GetInt to retrieve this value.
--- @param key string 
--- @param value number 
function UnityEngine.PlayerPrefs.SetInt(key, value) end

--- Returns the value corresponding to key in the preference file if it exists.
--- @param key string 
--- @param defaultValue number 
--- @return number 
function UnityEngine.PlayerPrefs.GetInt(key, defaultValue) end

--- Returns the value corresponding to key in the preference file if it exists.
--- @return number 
function UnityEngine.PlayerPrefs.GetInt(key) end

--- Sets the float value of the preference identified by the given key. You can use PlayerPrefs.GetFloat to retrieve this value.
--- @param key string 
--- @param value number 
function UnityEngine.PlayerPrefs.SetFloat(key, value) end

--- Returns the value corresponding to key in the preference file if it exists.
--- @param key string 
--- @param defaultValue number 
--- @return number 
function UnityEngine.PlayerPrefs.GetFloat(key, defaultValue) end

--- Returns the value corresponding to key in the preference file if it exists.
--- @return number 
function UnityEngine.PlayerPrefs.GetFloat(key) end

--- Sets a single string value for the preference identified by the given key. You can use PlayerPrefs.GetString to retrieve this value.
--- @param key string 
--- @param value string 
function UnityEngine.PlayerPrefs.SetString(key, value) end

--- Returns the value corresponding to key in the preference file if it exists.
--- @param key string 
--- @param defaultValue string 
--- @return string 
function UnityEngine.PlayerPrefs.GetString(key, defaultValue) end

--- Returns the value corresponding to key in the preference file if it exists.
--- @return string 
function UnityEngine.PlayerPrefs.GetString(key) end

--- Returns true if the given key exists in PlayerPrefs, otherwise returns false.
--- @param key string 
--- @return boolean 
function UnityEngine.PlayerPrefs.HasKey(key) end

--- Removes the given key from the PlayerPrefs. If the key does not exist, DeleteKey has no impact.
--- @param key string 
function UnityEngine.PlayerPrefs.DeleteKey(key) end

--- Removes all keys and values from the preferences. Use with caution.
function UnityEngine.PlayerPrefs.DeleteAll() end

--- Writes all modified preferences to disk.
function UnityEngine.PlayerPrefs.Save() end

---  Generated By xerysherry