--- @class UnityEngine.DisplayInfo Represents a connected display.
--- @field width number The display width in pixels.
--- @field height number The display height in pixels.
--- @field refreshRate UnityEngine.RefreshRate The current refresh rate of the display.
--- @field workArea UnityEngine.RectInt Specifies the work area rectangle of the display relative to the top left corner. For example, it excludes the area covered by the macOS Dock or the Windows Taskbar.
--- @field name string Human-friendly display name.
UnityEngine.DisplayInfo = {}

--- @return boolean
function UnityEngine.DisplayInfo:Equals(other) end

---  Generated By xerysherry