--- @class UnityEngine.Rendering.ShaderConstantType Options for the shader constant value type.
UnityEngine.Rendering.ShaderConstantType = {
    --- The shader constant is a vector or a scalar (a vector with one column).  The related ShaderData.ConstantInfo stores the number of columns.
    Vector = 0,
    --- The shader constant is a matrix.  The related ShaderData.ConstantInfo stores the number of rows and columns.
    Matrix = 1,
    --- The shader constant is a struct.  The related ShaderData.ConstantInfo stores the struct's size and members.
    Struct = 2,
}

---  Generated By xerysherry