--- @class UnityEngine.Tilemaps.Tile:UnityEngine.Tilemaps.TileBase Class for a default tile in the Tilemap.
--- @field sprite UnityEngine.Sprite property getset
---       Sprite to be rendered at the Tile.
--- @field color UnityEngine.Color property getset
---       Color of the Tile.
--- @field transform UnityEngine.Matrix4x4 property getset
---       Matrix4x4|Transform matrix of the Tile.
--- @field gameObject UnityEngine.GameObject property getset
---       GameObject of the Tile.
--- @field flags UnityEngine.Tilemaps.TileFlags property getset
---       TileFlags of the Tile.
--- @field colliderType UnityEngine.Tilemaps.Tile.ColliderType
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Tilemaps.Tile = {}

function UnityEngine.Tilemaps.Tile:set_sprite(value) end

function UnityEngine.Tilemaps.Tile:set_color(value) end

function UnityEngine.Tilemaps.Tile:set_transform(value) end

function UnityEngine.Tilemaps.Tile:set_gameObject(value) end

function UnityEngine.Tilemaps.Tile:set_flags(value) end

function UnityEngine.Tilemaps.Tile:set_colliderType(value) end

--- Retrieves the tile rendering data for the Tile.
--- @param position UnityEngine.Vector3Int Position of the Tile on the Tilemap.
--- @param tilemap UnityEngine.Tilemaps.ITilemap The Tilemap the tile is present on.
--- @param tileData UnityEngine.Tilemaps.TileData& Data to render the tile. This is filled with Tile, Tile.color and Tile.transform.
function UnityEngine.Tilemaps.Tile:GetTileData(position, tilemap, tileData) end

---  Generated By xerysherry