--- @class UnityEngine.WebCamKind Enum representing the different types of web camera device.
UnityEngine.WebCamKind = {
    --- Wide angle (default) camera.
    WideAngle = 1,
    --- A Telephoto camera device. These devices have a longer focal length than a wide-angle camera.
    Telephoto = 2,
    --- Camera which supports synchronized color and depth data (currently these are only dual back and true depth cameras on latest iOS devices).
    ColorAndDepth = 3,
    --- Ultra wide angle camera. These devices have a shorter focal length than a wide-angle camera.
    UltraWideAngle = 4,
}

---  Generated By xerysherry