--- @class UnityEngine.UI.VertexHelper 
--- @field currentVertCount number
--- @field currentIndexCount number
UnityEngine.UI.VertexHelper = {}

function UnityEngine.UI.VertexHelper:Dispose() end

function UnityEngine.UI.VertexHelper:Clear() end

function UnityEngine.UI.VertexHelper:PopulateUIVertex(vertex, i) end

function UnityEngine.UI.VertexHelper:SetUIVertex(vertex, i) end

function UnityEngine.UI.VertexHelper:FillMesh(mesh) end

function UnityEngine.UI.VertexHelper:AddVert(position, color, uv0, uv1, uv2, uv3, normal, tangent) end

function UnityEngine.UI.VertexHelper:AddVert(position, color, uv0, uv1, normal, tangent) end

function UnityEngine.UI.VertexHelper:AddVert(position, color, uv0) end

function UnityEngine.UI.VertexHelper:AddVert(v) end

function UnityEngine.UI.VertexHelper:AddTriangle(idx0, idx1, idx2) end

function UnityEngine.UI.VertexHelper:AddUIVertexQuad(verts) end

function UnityEngine.UI.VertexHelper:AddUIVertexStream(verts, indices) end

function UnityEngine.UI.VertexHelper:AddUIVertexTriangleStream(verts) end

function UnityEngine.UI.VertexHelper:GetUIVertexStream(stream) end

---  Generated By xerysherry