--- 
---  Defines UxmlTraits for the Style tag.
---  
--- @class UnityEngine.UIElements.UxmlStyleTraits:UnityEngine.UIElements.UxmlTraits
--- @field uxmlChildElementsDescription System.Collections.Generic.IEnumerable`1
--- @field canHaveAnyAttribute boolean
--- @field uxmlAttributesDescription System.Collections.Generic.IEnumerable`1
UnityEngine.UIElements.UxmlStyleTraits = {}

---  Generated By xerysherry