--- 
---  A control that allows the user to pick a choice from a list of options.
---  
--- @class UnityEngine.UIElements.DropdownField:UnityEngine.UIElements.BaseField`1
--- @field text string property get
---       
---        This is the text displayed to the user for the current selection of the popup.
---        
--- @field index number property getset
---       
---        The currently selected index in the popup menu.
---        
--- @field choices string[] property getset
---       
---        The list of choices to display in the popup menu.
---        
--- @field value string property getset
---       
---        The currently selected value in the popup menu.
---        
--- @field labelElement UnityEngine.UIElements.Label
--- @field label string
--- @field showMixedValue boolean
--- @field binding UnityEngine.UIElements.IBinding
--- @field bindingPath string
--- @field viewDataKey string
--- @field userData System.Object
--- @field canGrabFocus boolean
--- @field focusController UnityEngine.UIElements.FocusController
--- @field usageHints UnityEngine.UIElements.UsageHints
--- @field transform UnityEngine.UIElements.ITransform
--- @field layout UnityEngine.Rect
--- @field contentRect UnityEngine.Rect
--- @field worldBound UnityEngine.Rect
--- @field localBound UnityEngine.Rect
--- @field worldTransform UnityEngine.Matrix4x4
--- @field pickingMode UnityEngine.UIElements.PickingMode
--- @field name string
--- @field enabledInHierarchy boolean
--- @field enabledSelf boolean
--- @field visible boolean
--- @field generateVisualContent function
--- @field experimental UnityEngine.UIElements.IExperimentalFeatures
--- @field hierarchy UnityEngine.UIElements.VisualElement.Hierarchy
--- @field cacheAsBitmap boolean
--- @field parent UnityEngine.UIElements.VisualElement
--- @field panel UnityEngine.UIElements.IPanel
--- @field contentContainer UnityEngine.UIElements.VisualElement
--- @field visualTreeAssetSource UnityEngine.UIElements.VisualTreeAsset
--- @field Item UnityEngine.UIElements.VisualElement
--- @field childCount number
--- @field schedule UnityEngine.UIElements.IVisualElementScheduler
--- @field style UnityEngine.UIElements.IStyle
--- @field customStyle UnityEngine.UIElements.ICustomStyle
--- @field styleSheets UnityEngine.UIElements.VisualElementStyleSheetSet
--- @field tooltip string
--- @field resolvedStyle UnityEngine.UIElements.IResolvedStyle
--- @field focusable boolean
--- @field tabIndex number
--- @field delegatesFocus boolean
UnityEngine.UIElements.DropdownField = {}

function UnityEngine.UIElements.DropdownField:set_index(value) end

function UnityEngine.UIElements.DropdownField:set_choices(value) end

function UnityEngine.UIElements.DropdownField:set_value(value) end

--- 
---  Allow changing value without triggering any change event.
---  
--- @param newValue string The new value.
function UnityEngine.UIElements.DropdownField:SetValueWithoutNotify(newValue) end

---  Generated By xerysherry