--- @class UnityEngine.PlatformEffector2D:UnityEngine.Effector2D Applies "platform" behaviour such as one-way collisions etc.
--- @field useOneWay boolean property getset
---       Should the one-way collision behaviour be used?
--- @field useOneWayGrouping boolean property getset
---       Ensures that all contacts controlled by the one-way behaviour act the same.
--- @field useSideFriction boolean property getset
---       Should friction be used on the platform sides?
--- @field useSideBounce boolean property getset
---       Should bounce be used on the platform sides?
--- @field surfaceArc number property getset
---       The angle of an arc that defines the surface of the platform centered of the local 'up' of the effector.
--- @field sideArc number property getset
---       The angle of an arc that defines the sides of the platform centered on the local 'left' and 'right' of the effector. Any collision normals within this arc are considered for the 'side' behaviours.
--- @field rotationalOffset number property getset
---       The rotational offset angle from the local 'up'.
--- @field oneWay boolean property getset
---       Whether to use one-way collision behaviour or not.
--- @field sideFriction boolean property getset
---       Whether friction should be used on the platform sides or not.
--- @field sideBounce boolean property getset
---       Whether bounce should be used on the platform sides or not.
--- @field sideAngleVariance number property getset
---       The angle variance centered on the sides of the platform.  Zero angle only matches sides 90-degree to the platform "top".
--- @field useColliderMask boolean
--- @field colliderMask number
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.PlatformEffector2D = {}

--- @param value boolean 
function UnityEngine.PlatformEffector2D:set_useOneWay(value) end

--- @param value boolean 
function UnityEngine.PlatformEffector2D:set_useOneWayGrouping(value) end

--- @param value boolean 
function UnityEngine.PlatformEffector2D:set_useSideFriction(value) end

--- @param value boolean 
function UnityEngine.PlatformEffector2D:set_useSideBounce(value) end

--- @param value number 
function UnityEngine.PlatformEffector2D:set_surfaceArc(value) end

--- @param value number 
function UnityEngine.PlatformEffector2D:set_sideArc(value) end

--- @param value number 
function UnityEngine.PlatformEffector2D:set_rotationalOffset(value) end

--- @param value boolean 
function UnityEngine.PlatformEffector2D:set_oneWay(value) end

--- @param value boolean 
function UnityEngine.PlatformEffector2D:set_sideFriction(value) end

--- @param value boolean 
function UnityEngine.PlatformEffector2D:set_sideBounce(value) end

--- @param value number 
function UnityEngine.PlatformEffector2D:set_sideAngleVariance(value) end

---  Generated By xerysherry