--- 
---  Style value that can be either a Length or a StyleKeyword.
---  
--- @class UnityEngine.UIElements.StyleLength
--- @field value UnityEngine.UIElements.Length property getset
---       
---        The Length value.
---        
--- @field keyword UnityEngine.UIElements.StyleKeyword property getset
---       
---        The style keyword.
---        
UnityEngine.UIElements.StyleLength = {}

--- @return boolean
function UnityEngine.UIElements.StyleLength.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.UIElements.StyleLength.op_Inequality(lhs, rhs) end

--- @return UnityEngine.UIElements.StyleLength
function UnityEngine.UIElements.StyleLength.op_Implicit(keyword) end

--- @return UnityEngine.UIElements.StyleLength
function UnityEngine.UIElements.StyleLength.op_Implicit(v) end

--- @return UnityEngine.UIElements.StyleLength
function UnityEngine.UIElements.StyleLength.op_Implicit(v) end

function UnityEngine.UIElements.StyleLength:set_value(value) end

function UnityEngine.UIElements.StyleLength:set_keyword(value) end

--- @return boolean
function UnityEngine.UIElements.StyleLength:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.StyleLength:Equals(obj) end

--- @return number
function UnityEngine.UIElements.StyleLength:GetHashCode() end

--- @return string
function UnityEngine.UIElements.StyleLength:ToString() end

---  Generated By xerysherry