--- @class UnityEngine.SpringJoint2D:UnityEngine.AnchoredJoint2D Joint that attempts to keep two Rigidbody2D objects a set distance apart by applying a force between them.
--- @field autoConfigureDistance boolean property getset
---       Should the distance be calculated automatically?
--- @field distance number property getset
---       The distance the spring will try to keep between the two objects.
--- @field dampingRatio number property getset
---       The amount by which the spring force is reduced in proportion to the movement speed.
--- @field frequency number property getset
---       The frequency at which the spring oscillates around the distance distance between the objects.
--- @field anchor UnityEngine.Vector2
--- @field connectedAnchor UnityEngine.Vector2
--- @field autoConfigureConnectedAnchor boolean
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field connectedBody UnityEngine.Rigidbody2D
--- @field enableCollision boolean
--- @field breakForce number
--- @field breakTorque number
--- @field reactionForce UnityEngine.Vector2
--- @field reactionTorque number
--- @field collideConnected boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.SpringJoint2D = {}

--- @param value boolean 
function UnityEngine.SpringJoint2D:set_autoConfigureDistance(value) end

--- @param value number 
function UnityEngine.SpringJoint2D:set_distance(value) end

--- @param value number 
function UnityEngine.SpringJoint2D:set_dampingRatio(value) end

--- @param value number 
function UnityEngine.SpringJoint2D:set_frequency(value) end

---  Generated By xerysherry