--- 
---  Represents a style value that can be either a TransformOrigin or a StyleKeyword.
---  
--- @class UnityEngine.UIElements.StyleTransformOrigin
--- @field value UnityEngine.UIElements.TransformOrigin property getset
---       
---        The TransformOrigin value.
---        
--- @field keyword UnityEngine.UIElements.StyleKeyword property getset
---       
---        The style keyword.
---        
UnityEngine.UIElements.StyleTransformOrigin = {}

--- @return boolean
function UnityEngine.UIElements.StyleTransformOrigin.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.UIElements.StyleTransformOrigin.op_Inequality(lhs, rhs) end

--- @return UnityEngine.UIElements.StyleTransformOrigin
function UnityEngine.UIElements.StyleTransformOrigin.op_Implicit(keyword) end

--- @return UnityEngine.UIElements.StyleTransformOrigin
function UnityEngine.UIElements.StyleTransformOrigin.op_Implicit(v) end

function UnityEngine.UIElements.StyleTransformOrigin:set_value(value) end

function UnityEngine.UIElements.StyleTransformOrigin:set_keyword(value) end

--- @return boolean
function UnityEngine.UIElements.StyleTransformOrigin:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.StyleTransformOrigin:Equals(obj) end

--- @return number
function UnityEngine.UIElements.StyleTransformOrigin:GetHashCode() end

--- @return string
function UnityEngine.UIElements.StyleTransformOrigin:ToString() end

---  Generated By xerysherry