--- @class UnityEngine.AndroidJavaObject AndroidJavaObject is the Unity representation of a generic instance of java.lang.Object.
UnityEngine.AndroidJavaObject = {}

--- IDisposable callback.
function UnityEngine.AndroidJavaObject:Dispose() end

--- Calls a Java method on an object (non-static).
--- @param methodName string Specifies which method to call.
--- @param args UnityEngine.AndroidJavaObject.T[] An array of parameters passed to the method.
function UnityEngine.AndroidJavaObject:Call(methodName, args) end

--- Calls a Java method on an object (non-static).
--- @param methodName string Specifies which method to call.
--- @param args System.Object[] An array of parameters passed to the method.
function UnityEngine.AndroidJavaObject:Call(methodName, args) end

--- Call a static Java method on a class.
--- @param methodName string Specifies which method to call.
--- @param args UnityEngine.AndroidJavaObject.T[] An array of parameters passed to the method.
function UnityEngine.AndroidJavaObject:CallStatic(methodName, args) end

--- Call a static Java method on a class.
--- @param methodName string Specifies which method to call.
--- @param args System.Object[] An array of parameters passed to the method.
function UnityEngine.AndroidJavaObject:CallStatic(methodName, args) end

--- Get the value of a field in an object (non-static).
--- @param fieldName string The name of the field (e.g. int counter; would have fieldName = "counter").
--- @return UnityEngine.AndroidJavaObject.FieldType 
function UnityEngine.AndroidJavaObject:Get(fieldName) end

--- Set the value of a field in an object (non-static).
--- @param fieldName string The name of the field (e.g. int counter; would have fieldName = "counter").
--- @param val UnityEngine.AndroidJavaObject.FieldType The value to assign to the field. It has to match the field type.
function UnityEngine.AndroidJavaObject:Set(fieldName, val) end

--- Get the value of a static field in an object type.
--- @param fieldName string The name of the field (e.g. <i>int counter;</i> would have fieldName = "counter").
--- @return UnityEngine.AndroidJavaObject.FieldType 
function UnityEngine.AndroidJavaObject:GetStatic(fieldName) end

--- Set the value of a static field in an object type.
--- @param fieldName string The name of the field (e.g. int counter; would have fieldName = "counter").
--- @param val UnityEngine.AndroidJavaObject.FieldType The value to assign to the field. It has to match the field type.
function UnityEngine.AndroidJavaObject:SetStatic(fieldName, val) end

--- Retrieves the raw <tt>jobject</tt> pointer to the Java object.
--- 
--- Note: Using raw JNI functions requires advanced knowledge of the Android Java Native Interface (JNI). Please take note.
--- @return System.IntPtr 
function UnityEngine.AndroidJavaObject:GetRawObject() end

--- Retrieves the raw <tt>jclass</tt> pointer to the Java class.
--- 
--- Note: Using raw JNI functions requires advanced knowledge of the Android Java Native Interface (JNI). Please take note.
--- @return System.IntPtr 
function UnityEngine.AndroidJavaObject:GetRawClass() end

--- Creates a clone of the C# object that references the same Java object.
--- @return UnityEngine.AndroidJavaObject A new C# object which references the same Java object as the original instance.
function UnityEngine.AndroidJavaObject:CloneReference() end

--- Calls a Java method on an object (non-static).
--- @param methodName string Specifies which method to call.
--- @param args UnityEngine.AndroidJavaObject.T[] An array of parameters passed to the method.
--- @return UnityEngine.AndroidJavaObject.ReturnType 
function UnityEngine.AndroidJavaObject:Call(methodName, args) end

--- Calls a Java method on an object (non-static).
--- @param methodName string Specifies which method to call.
--- @param args System.Object[] An array of parameters passed to the method.
--- @return UnityEngine.AndroidJavaObject.ReturnType 
function UnityEngine.AndroidJavaObject:Call(methodName, args) end

--- Call a static Java method on a class.
--- @param methodName string Specifies which method to call.
--- @param args UnityEngine.AndroidJavaObject.T[] An array of parameters passed to the method.
--- @return UnityEngine.AndroidJavaObject.ReturnType 
function UnityEngine.AndroidJavaObject:CallStatic(methodName, args) end

--- Call a static Java method on a class.
--- @param methodName string Specifies which method to call.
--- @param args System.Object[] An array of parameters passed to the method.
--- @return UnityEngine.AndroidJavaObject.ReturnType 
function UnityEngine.AndroidJavaObject:CallStatic(methodName, args) end

---  Generated By xerysherry