--- @class UnityEngine.iOS.ADBannerView ADBannerView is a wrapper around the ADBannerView class found in the Apple iAd framework and is only available on iOS.
--- @field loaded boolean property get
---       Checks if banner contents are loaded.
--- @field visible boolean property getset
---       Banner visibility. Initially banner is not visible.
--- @field layout UnityEngine.iOS.ADBannerView.Layout property getset
---       Banner layout.
--- @field position UnityEngine.Vector2 property getset
---       The position of the banner view.
--- @field size UnityEngine.Vector2 property get
---       The size of the banner view.
UnityEngine.iOS.ADBannerView = {}

--- Checks if the banner type is available (e.g. MediumRect is available only starting with ios6).
--- @param type UnityEngine.iOS.ADBannerView.Type 
--- @return boolean 
function UnityEngine.iOS.ADBannerView.IsAvailable(type) end

function UnityEngine.iOS.ADBannerView.add_onBannerWasClicked(value) end

function UnityEngine.iOS.ADBannerView.remove_onBannerWasClicked(value) end

function UnityEngine.iOS.ADBannerView.add_onBannerWasLoaded(value) end

function UnityEngine.iOS.ADBannerView.remove_onBannerWasLoaded(value) end

function UnityEngine.iOS.ADBannerView.add_onBannerFailedToLoad(value) end

function UnityEngine.iOS.ADBannerView.remove_onBannerFailedToLoad(value) end

function UnityEngine.iOS.ADBannerView:set_visible(value) end

function UnityEngine.iOS.ADBannerView:set_layout(value) end

function UnityEngine.iOS.ADBannerView:set_position(value) end

---  Generated By xerysherry