--- @class UnityEngine.SpringJoint:UnityEngine.Joint The spring joint ties together 2 rigid bodies, spring forces will be automatically applied to keep the object at the given distance.
--- @field spring number property getset
---       The spring force used to keep the two objects together.
--- @field damper number property getset
---       The damper force used to dampen the spring force.
--- @field minDistance number property getset
---       The minimum distance between the bodies relative to their initial distance.
--- @field maxDistance number property getset
---       The maximum distance between the bodies relative to their initial distance.
--- @field tolerance number property getset
---       The maximum allowed error between the current spring length and the length defined by minDistance and maxDistance.
--- @field connectedBody UnityEngine.Rigidbody
--- @field connectedArticulationBody UnityEngine.ArticulationBody
--- @field axis UnityEngine.Vector3
--- @field anchor UnityEngine.Vector3
--- @field connectedAnchor UnityEngine.Vector3
--- @field autoConfigureConnectedAnchor boolean
--- @field breakForce number
--- @field breakTorque number
--- @field enableCollision boolean
--- @field enablePreprocessing boolean
--- @field massScale number
--- @field connectedMassScale number
--- @field currentForce UnityEngine.Vector3
--- @field currentTorque UnityEngine.Vector3
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.SpringJoint = {}

--- @param value number 
function UnityEngine.SpringJoint:set_spring(value) end

--- @param value number 
function UnityEngine.SpringJoint:set_damper(value) end

--- @param value number 
function UnityEngine.SpringJoint:set_minDistance(value) end

--- @param value number 
function UnityEngine.SpringJoint:set_maxDistance(value) end

--- @param value number 
function UnityEngine.SpringJoint:set_tolerance(value) end

---  Generated By xerysherry