--- @class UnityEngine.Experimental.AssetBundlePatching.AssetBundleUtility 
UnityEngine.Experimental.AssetBundlePatching.AssetBundleUtility = {}

function UnityEngine.Experimental.AssetBundlePatching.AssetBundleUtility.PatchAssetBundles(bundles, filenames) end

---  Generated By xerysherry