--- @class UnityEngine.Rendering.ShadowDrawingSettings Settings for ScriptableRenderContext.DrawShadows.
--- @field cullingResults UnityEngine.Rendering.CullingResults property getset
---       Culling results to use.
--- @field lightIndex number property getset
---       The index of the shadow-casting light to be rendered.
--- @field useRenderingLayerMaskTest boolean property getset
---       Set this to true to make Unity filter Renderers during shadow rendering. Unity filters Renderers based on the Rendering Layer Mask of the Renderer itself, and the Rendering Layer Mask of each shadow casting Light.
--- @field splitData UnityEngine.Rendering.ShadowSplitData property getset
---       The split data.
--- @field objectsFilter UnityEngine.ShadowObjectsFilter property getset
---       Specifies the filter Unity applies to GameObjects that it renders in the shadow pass.
UnityEngine.Rendering.ShadowDrawingSettings = {}

--- @return boolean
function UnityEngine.Rendering.ShadowDrawingSettings.op_Equality(left, right) end

--- @return boolean
function UnityEngine.Rendering.ShadowDrawingSettings.op_Inequality(left, right) end

function UnityEngine.Rendering.ShadowDrawingSettings:set_cullingResults(value) end

function UnityEngine.Rendering.ShadowDrawingSettings:set_lightIndex(value) end

function UnityEngine.Rendering.ShadowDrawingSettings:set_useRenderingLayerMaskTest(value) end

function UnityEngine.Rendering.ShadowDrawingSettings:set_splitData(value) end

function UnityEngine.Rendering.ShadowDrawingSettings:set_objectsFilter(value) end

--- @return boolean
function UnityEngine.Rendering.ShadowDrawingSettings:Equals(other) end

--- @return boolean
function UnityEngine.Rendering.ShadowDrawingSettings:Equals(obj) end

--- @return number
function UnityEngine.Rendering.ShadowDrawingSettings:GetHashCode() end

---  Generated By xerysherry