--- @class Unity.Collections.LowLevel.Unsafe.NativeContainerAttribute:System.Attribute Allows you to create your own custom native container.
--- @field TypeId System.Object
Unity.Collections.LowLevel.Unsafe.NativeContainerAttribute = {}

---  Generated By xerysherry