--- @class UnityEngine.Rendering.VisibleReflectionProbe Holds data of a visible reflection reflectionProbe.
--- @field texture UnityEngine.Texture property get
---       Probe texture.
--- @field reflectionProbe UnityEngine.ReflectionProbe property get
---       Accessor to ReflectionProbe component.
--- @field bounds UnityEngine.Bounds property getset
---       Probe bounding box.
--- @field localToWorldMatrix UnityEngine.Matrix4x4 property getset
---       Probe transformation matrix.
--- @field hdrData UnityEngine.Vector4 property getset
---       Shader data for probe HDR texture decoding.
--- @field center UnityEngine.Vector3 property getset
---       Probe projection center.
--- @field blendDistance number property getset
---       Probe blending distance.
--- @field importance number property getset
---       Probe importance.
--- @field isBoxProjection boolean property getset
---       Should probe use box projection.
UnityEngine.Rendering.VisibleReflectionProbe = {}

--- @param left UnityEngine.Rendering.VisibleReflectionProbe 
--- @param right UnityEngine.Rendering.VisibleReflectionProbe 
--- @return boolean
function UnityEngine.Rendering.VisibleReflectionProbe.op_Equality(left, right) end

--- @param left UnityEngine.Rendering.VisibleReflectionProbe 
--- @param right UnityEngine.Rendering.VisibleReflectionProbe 
--- @return boolean
function UnityEngine.Rendering.VisibleReflectionProbe.op_Inequality(left, right) end

--- @param value UnityEngine.Bounds 
function UnityEngine.Rendering.VisibleReflectionProbe:set_bounds(value) end

--- @param value UnityEngine.Matrix4x4 
function UnityEngine.Rendering.VisibleReflectionProbe:set_localToWorldMatrix(value) end

--- @param value UnityEngine.Vector4 
function UnityEngine.Rendering.VisibleReflectionProbe:set_hdrData(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.Rendering.VisibleReflectionProbe:set_center(value) end

--- @param value number 
function UnityEngine.Rendering.VisibleReflectionProbe:set_blendDistance(value) end

--- @param value number 
function UnityEngine.Rendering.VisibleReflectionProbe:set_importance(value) end

--- @param value boolean 
function UnityEngine.Rendering.VisibleReflectionProbe:set_isBoxProjection(value) end

--- @param other UnityEngine.Rendering.VisibleReflectionProbe 
--- @return boolean
function UnityEngine.Rendering.VisibleReflectionProbe:Equals(other) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.Rendering.VisibleReflectionProbe:Equals(obj) end

--- @return number
function UnityEngine.Rendering.VisibleReflectionProbe:GetHashCode() end

---  Generated By xerysherry