--- @class UnityEngine.UI.Dropdown:UnityEngine.UI.Selectable 
--- @field template UnityEngine.RectTransform
--- @field captionText UnityEngine.UI.Text
--- @field captionImage UnityEngine.UI.Image
--- @field itemText UnityEngine.UI.Text
--- @field itemImage UnityEngine.UI.Image
--- @field options UnityEngine.UI.Dropdown.OptionData[]
--- @field onValueChanged UnityEngine.UI.Dropdown.DropdownEvent
--- @field alphaFadeSpeed number
--- @field value number
--- @field navigation UnityEngine.UI.Navigation
--- @field transition UnityEngine.UI.Selectable.Transition
--- @field colors UnityEngine.UI.ColorBlock
--- @field spriteState UnityEngine.UI.SpriteState
--- @field animationTriggers UnityEngine.UI.AnimationTriggers
--- @field targetGraphic UnityEngine.UI.Graphic
--- @field interactable boolean
--- @field image UnityEngine.UI.Image
--- @field animator UnityEngine.Animator
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.Dropdown = {}

--- @param value UnityEngine.RectTransform 
function UnityEngine.UI.Dropdown:set_template(value) end

--- @param value UnityEngine.UI.Text 
function UnityEngine.UI.Dropdown:set_captionText(value) end

--- @param value UnityEngine.UI.Image 
function UnityEngine.UI.Dropdown:set_captionImage(value) end

--- @param value UnityEngine.UI.Text 
function UnityEngine.UI.Dropdown:set_itemText(value) end

--- @param value UnityEngine.UI.Image 
function UnityEngine.UI.Dropdown:set_itemImage(value) end

--- @param value UnityEngine.UI.Dropdown.OptionData[] 
function UnityEngine.UI.Dropdown:set_options(value) end

--- @param value UnityEngine.UI.Dropdown.DropdownEvent 
function UnityEngine.UI.Dropdown:set_onValueChanged(value) end

--- @param value number 
function UnityEngine.UI.Dropdown:set_alphaFadeSpeed(value) end

--- @param value number 
function UnityEngine.UI.Dropdown:set_value(value) end

--- @param input number 
function UnityEngine.UI.Dropdown:SetValueWithoutNotify(input) end

function UnityEngine.UI.Dropdown:RefreshShownValue() end

--- @param options UnityEngine.UI.Dropdown.OptionData[] 
function UnityEngine.UI.Dropdown:AddOptions(options) end

--- @param options string[] 
function UnityEngine.UI.Dropdown:AddOptions(options) end

--- @param options UnityEngine.Sprite[] 
function UnityEngine.UI.Dropdown:AddOptions(options) end

function UnityEngine.UI.Dropdown:ClearOptions() end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.UI.Dropdown:OnPointerClick(eventData) end

--- @param eventData UnityEngine.EventSystems.BaseEventData 
function UnityEngine.UI.Dropdown:OnSubmit(eventData) end

--- @param eventData UnityEngine.EventSystems.BaseEventData 
function UnityEngine.UI.Dropdown:OnCancel(eventData) end

function UnityEngine.UI.Dropdown:Show() end

function UnityEngine.UI.Dropdown:Hide() end

---  Generated By xerysherry