--- @class UnityEngine.DetailPrototype Detail prototype used by the Terrain GameObject.
--- @field prototype UnityEngine.GameObject property getset
---       GameObject used by the DetailPrototype.
--- @field prototypeTexture UnityEngine.Texture2D property getset
---       Texture used by the DetailPrototype.
--- @field minWidth number property getset
---       Minimum width of the grass billboards (if render mode is GrassBillboard).
--- @field maxWidth number property getset
---       Maximum width of the grass billboards (if render mode is GrassBillboard).
--- @field minHeight number property getset
---       Minimum height of the grass billboards (if render mode is GrassBillboard).
--- @field maxHeight number property getset
---       Maximum height of the grass billboards (if render mode is GrassBillboard).
--- @field noiseSeed number property getset
---       Specifies the random seed value for detail object placement.
--- @field noiseSpread number property getset
---       Controls the spatial frequency of the noise pattern used to vary the scale and color of the detail objects.
--- @field bendFactor number property getset
---       Bend factor of the detailPrototype.
--- @field holeEdgePadding number property getset
---       Controls how far away detail objects are from the edge of the hole area.
--- @field healthyColor UnityEngine.Color property getset
---       Color when the DetailPrototypes are "healthy".
--- @field dryColor UnityEngine.Color property getset
---       Color when the DetailPrototypes are "dry".
--- @field renderMode UnityEngine.DetailRenderMode property getset
---       Render mode for the DetailPrototype.
--- @field usePrototypeMesh boolean property getset
---       Indicates whether this detail prototype uses the Mesh object from the GameObject specified by prototype.
--- @field useInstancing boolean property getset
---       Indicates whether this detail prototype uses for rendering.
UnityEngine.DetailPrototype = {}

--- @param value UnityEngine.GameObject 
function UnityEngine.DetailPrototype:set_prototype(value) end

--- @param value UnityEngine.Texture2D 
function UnityEngine.DetailPrototype:set_prototypeTexture(value) end

--- @param value number 
function UnityEngine.DetailPrototype:set_minWidth(value) end

--- @param value number 
function UnityEngine.DetailPrototype:set_maxWidth(value) end

--- @param value number 
function UnityEngine.DetailPrototype:set_minHeight(value) end

--- @param value number 
function UnityEngine.DetailPrototype:set_maxHeight(value) end

--- @param value number 
function UnityEngine.DetailPrototype:set_noiseSeed(value) end

--- @param value number 
function UnityEngine.DetailPrototype:set_noiseSpread(value) end

--- @param value number 
function UnityEngine.DetailPrototype:set_bendFactor(value) end

--- @param value number 
function UnityEngine.DetailPrototype:set_holeEdgePadding(value) end

--- @param value UnityEngine.Color 
function UnityEngine.DetailPrototype:set_healthyColor(value) end

--- @param value UnityEngine.Color 
function UnityEngine.DetailPrototype:set_dryColor(value) end

--- @param value UnityEngine.DetailRenderMode 
function UnityEngine.DetailPrototype:set_renderMode(value) end

--- @param value boolean 
function UnityEngine.DetailPrototype:set_usePrototypeMesh(value) end

--- @param value boolean 
function UnityEngine.DetailPrototype:set_useInstancing(value) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.DetailPrototype:Equals(obj) end

--- @return number
function UnityEngine.DetailPrototype:GetHashCode() end

--- Returns true if the detail prototype is valid and the Terrain can accept it.
--- @return boolean 
function UnityEngine.DetailPrototype:Validate() end

--- Returns true if the detail prototype is valid and the Terrain can accept it.
--- @return boolean 
--- @return System.String& Returns a message that indicates the cause of failed validation.
function UnityEngine.DetailPrototype:Validate() end

---  Generated By xerysherry