--- 
---  Element that draws IMGUI content.
---  
--- @class UnityEngine.UIElements.IMGUIContainer:UnityEngine.UIElements.VisualElement
--- @field ussClassName string 
---        USS class name of elements of this type.
---        
--- @field onGUIHandler function property getset
---       
---        The function that's called to render and handle IMGUI events.
---        
--- @field cullingEnabled boolean property getset
---       
---        When this property is set to true, onGUIHandler is not called when the Element is outside the viewport.
---        
--- @field contextType UnityEngine.UIElements.ContextType property getset
---       
---        ContextType of this IMGUIContrainer. Currently only supports ContextType.Editor.
---        
--- @field canGrabFocus boolean
--- @field viewDataKey string
--- @field userData System.Object
--- @field focusController UnityEngine.UIElements.FocusController
--- @field usageHints UnityEngine.UIElements.UsageHints
--- @field transform UnityEngine.UIElements.ITransform
--- @field layout UnityEngine.Rect
--- @field contentRect UnityEngine.Rect
--- @field worldBound UnityEngine.Rect
--- @field localBound UnityEngine.Rect
--- @field worldTransform UnityEngine.Matrix4x4
--- @field pickingMode UnityEngine.UIElements.PickingMode
--- @field name string
--- @field enabledInHierarchy boolean
--- @field enabledSelf boolean
--- @field visible boolean
--- @field generateVisualContent function
--- @field experimental UnityEngine.UIElements.IExperimentalFeatures
--- @field hierarchy UnityEngine.UIElements.VisualElement.Hierarchy
--- @field cacheAsBitmap boolean
--- @field parent UnityEngine.UIElements.VisualElement
--- @field panel UnityEngine.UIElements.IPanel
--- @field contentContainer UnityEngine.UIElements.VisualElement
--- @field visualTreeAssetSource UnityEngine.UIElements.VisualTreeAsset
--- @field Item UnityEngine.UIElements.VisualElement
--- @field childCount number
--- @field schedule UnityEngine.UIElements.IVisualElementScheduler
--- @field style UnityEngine.UIElements.IStyle
--- @field customStyle UnityEngine.UIElements.ICustomStyle
--- @field styleSheets UnityEngine.UIElements.VisualElementStyleSheetSet
--- @field tooltip string
--- @field resolvedStyle UnityEngine.UIElements.IResolvedStyle
--- @field focusable boolean
--- @field tabIndex number
--- @field delegatesFocus boolean
UnityEngine.UIElements.IMGUIContainer = {}

function UnityEngine.UIElements.IMGUIContainer:set_onGUIHandler(value) end

function UnityEngine.UIElements.IMGUIContainer:set_cullingEnabled(value) end

function UnityEngine.UIElements.IMGUIContainer:set_contextType(value) end

--- 
---  Marks layout as dirty to trigger a redraw.
---  
function UnityEngine.UIElements.IMGUIContainer:MarkDirtyLayout() end

function UnityEngine.UIElements.IMGUIContainer:HandleEvent(evt) end

--- 
---  Releases the native memory that this IMGUIContainer instance uses.
---  
function UnityEngine.UIElements.IMGUIContainer:Dispose() end

---  Generated By xerysherry