--- @class UnityEngine.Tilemaps.TilemapCollider2D:UnityEngine.Collider2D Collider for 2D physics representing shapes defined by the corresponding Tilemap.
--- @field maximumTileChangeCount number property getset
---       Maximum number of Tile Changes accumulated before doing a full collider rebuild instead of an incremental rebuild.
--- @field extrusionFactor number property getset
---       The amount of Collider shapes each Tile extrudes to facilitate compositing with neighboring Tiles. This eliminates fine gaps between Tiles when using a CompositeCollider2D. This is calculated in Unity units within world space.
--- @field hasTilemapChanges boolean property get
---       Returns true if there are Tilemap changes that require processing for Collider updates. Returns false otherwise.
--- @field density number
--- @field isTrigger boolean
--- @field usedByEffector boolean
--- @field usedByComposite boolean
--- @field composite UnityEngine.CompositeCollider2D
--- @field offset UnityEngine.Vector2
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field shapeCount number
--- @field bounds UnityEngine.Bounds
--- @field errorState UnityEngine.ColliderErrorState2D
--- @field sharedMaterial UnityEngine.PhysicsMaterial2D
--- @field friction number
--- @field bounciness number
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Tilemaps.TilemapCollider2D = {}

--- @param value number 
function UnityEngine.Tilemaps.TilemapCollider2D:set_maximumTileChangeCount(value) end

--- @param value number 
function UnityEngine.Tilemaps.TilemapCollider2D:set_extrusionFactor(value) end

--- Processes Tilemap changes for Collider updates immediately, if there are any.
function UnityEngine.Tilemaps.TilemapCollider2D:ProcessTilemapChanges() end

---  Generated By xerysherry