--- @class UnityEngine.Events.UnityEventBase Abstract base class for UnityEvents.
UnityEngine.Events.UnityEventBase = {}

--- Given an object, function name, and a list of argument types; find the method that matches.
--- @param obj System.Object Object to search for the method.
--- @param functionName string Function name to search for.
--- @param argumentTypes System.Type[] Argument types for the function.
--- @return System.Reflection.MethodInfo 
function UnityEngine.Events.UnityEventBase.GetValidMethodInfo(obj, functionName, argumentTypes) end

--- Given an object type, function name, and a list of argument types; find the method that matches.
--- @param objectType System.Type Object type to search for the method.
--- @param functionName string Function name to search for.
--- @param argumentTypes System.Type[] Argument types for the function.
--- @return System.Reflection.MethodInfo 
function UnityEngine.Events.UnityEventBase.GetValidMethodInfo(objectType, functionName, argumentTypes) end

--- Get the number of registered persistent listeners.
--- @return number 
function UnityEngine.Events.UnityEventBase:GetPersistentEventCount() end

--- Get the target component of the listener at index index.
--- @param index number Index of the listener to query.
--- @return UnityEngine.Object 
function UnityEngine.Events.UnityEventBase:GetPersistentTarget(index) end

--- Get the target method name of the listener at index index.
--- @param index number Index of the listener to query.
--- @return string 
function UnityEngine.Events.UnityEventBase:GetPersistentMethodName(index) end

--- Modify the execution state of a persistent listener.
--- @param index number Index of the listener to query.
--- @param state UnityEngine.Events.UnityEventCallState State to set.
function UnityEngine.Events.UnityEventBase:SetPersistentListenerState(index, state) end

--- Returns the execution state of a persistent listener.
--- @param index number Index of the listener to query.
--- @return UnityEngine.Events.UnityEventCallState Execution state of the persistent listener.
function UnityEngine.Events.UnityEventBase:GetPersistentListenerState(index) end

--- Remove all non-persisent (ie created from script) listeners  from the event.
function UnityEngine.Events.UnityEventBase:RemoveAllListeners() end

--- @return string
function UnityEngine.Events.UnityEventBase:ToString() end

---  Generated By xerysherry