--- @class UnityEngine.XR.XRDisplaySubsystem.LateLatchNode Type of node to be late latched.
UnityEngine.XR.XRDisplaySubsystem.LateLatchNode = {
    --- Head node type for late latching. This represents the camera node in the pose hierarchy.
    Head = 0,
    --- Left hand node type for late latching. This represents the left hand anchor node in the pose hierarchy.
    LeftHand = 1,
    --- Right hand node type for late latching. This represents the right hand anchor node in the pose hierarchy.
    RightHand = 2,
}

--- @class UnityEngine.XR.XRDisplaySubsystem.LateLatchNode Type of node to be late latched.
UnityEngine.XR.XRDisplaySubsystem.LateLatchNode = {
    --- Head node type for late latching. This represents the camera node in the pose hierarchy.
    Head = 0,
    --- Left hand node type for late latching. This represents the left hand anchor node in the pose hierarchy.
    LeftHand = 1,
    --- Right hand node type for late latching. This represents the right hand anchor node in the pose hierarchy.
    RightHand = 2,
}

---  Generated By xerysherry