--- Represents tile on Windows start screen
--- 
--- @class UnityEngine.WSA.Tile
--- @field main UnityEngine.WSA.Tile property get
---       Returns applications main tile
---       
--- @field id string property get
---       A unique string, identifying secondary tile
--- @field hasUserConsent boolean property get
---       Whether secondary tile was approved (pinned to start screen) or rejected by user.
---       
--- @field exists boolean property get
---       Whether secondary tile is pinned to start screen.
---       
UnityEngine.WSA.Tile = {}

--- Get template XML for tile notification.
--- @param templ UnityEngine.WSA.TileTemplate A template identifier.
--- @return string String, which is an empty XML document to be filled and used for tile notification.
function UnityEngine.WSA.Tile.GetTemplate(templ) end

--- Whether secondary tile is pinned to start screen.
--- @param tileId string An identifier for secondary tile.
--- @return boolean 
function UnityEngine.WSA.Tile.Exists(tileId) end

--- Creates new or updates existing secondary tile.
--- @return UnityEngine.WSA.Tile New Tile object, that can be used for further work with the tile.
function UnityEngine.WSA.Tile.CreateOrUpdateSecondary(data) end

--- Creates new or updates existing secondary tile.
--- @return UnityEngine.WSA.Tile New Tile object, that can be used for further work with the tile.
function UnityEngine.WSA.Tile.CreateOrUpdateSecondary(data, pos) end

--- Creates new or updates existing secondary tile.
--- @return UnityEngine.WSA.Tile New Tile object, that can be used for further work with the tile.
function UnityEngine.WSA.Tile.CreateOrUpdateSecondary(data, area) end

--- Returns the secondary tile, identified by tile id.
--- @param tileId string A tile identifier.
--- @return UnityEngine.WSA.Tile A Tile object or null if secondary tile does not exist (not pinned to start screen and user request is complete).
function UnityEngine.WSA.Tile.GetSecondary(tileId) end

--- Gets all secondary tiles.
--- @return UnityEngine.WSA.Tile[] An array of Tile objects.
function UnityEngine.WSA.Tile.GetSecondaries() end

--- Show a request to unpin secondary tile from start screen.
function UnityEngine.WSA.Tile.DeleteSecondary(tileId) end

--- Show a request to unpin secondary tile from start screen.
function UnityEngine.WSA.Tile.DeleteSecondary(tileId, pos) end

--- Show a request to unpin secondary tile from start screen.
function UnityEngine.WSA.Tile.DeleteSecondary(tileId, area) end

--- Send a notification for tile (update tiles look).
function UnityEngine.WSA.Tile:Update(xml) end

--- Send a notification for tile (update tiles look).
function UnityEngine.WSA.Tile:Update(medium, wide, large, text) end

--- Starts periodic update of a tile.
--- 
--- @param uri string a remote location fromwhere to retrieve tile update
--- @param interval number a time interval in minutes, will be rounded to a value, supported by the system
function UnityEngine.WSA.Tile:PeriodicUpdate(uri, interval) end

--- Stops previously started periodic update of a tile.
function UnityEngine.WSA.Tile:StopPeriodicUpdate() end

--- Sets or updates badge on a tile to an image.
--- @param image string Image identifier.
function UnityEngine.WSA.Tile:UpdateBadgeImage(image) end

--- Set or update a badge on a tile to a number.
--- @param number number Number to be shown on a badge.
function UnityEngine.WSA.Tile:UpdateBadgeNumber(number) end

--- Remove badge from tile.
function UnityEngine.WSA.Tile:RemoveBadge() end

--- Starts periodic update of a  badge on a tile.
--- 
--- @param uri string A remote location from where to retrieve tile update
--- @param interval number A time interval in minutes, will be rounded to a value, supported by the system
function UnityEngine.WSA.Tile:PeriodicBadgeUpdate(uri, interval) end

--- Stops previously started periodic update of a tile.
function UnityEngine.WSA.Tile:StopPeriodicBadgeUpdate() end

--- Show a request to unpin secondary tile from start screen.
function UnityEngine.WSA.Tile:Delete() end

--- Show a request to unpin secondary tile from start screen.
function UnityEngine.WSA.Tile:Delete(pos) end

--- Show a request to unpin secondary tile from start screen.
function UnityEngine.WSA.Tile:Delete(area) end

---  Generated By xerysherry