--- @class Unity.Profiling.ProfilerCategoryFlags Options for determining if a Profiler category is built into Unity by default.
Unity.Profiling.ProfilerCategoryFlags = {
    --- Use this flag to determine that a Profiler category is not built into Unity by default.
    None = 0,
    --- Use this flag to determine that a Profiler category is built into the Unity Editor by default.
    Builtin = 1,
}

---  Generated By xerysherry