--- @class UnityEngine.TerrainUtils.TerrainMap Type for mapping 2D (X,Z) tile coordinates to a Terrain object.
--- @field terrainTiles table<UnityEngine.TerrainUtils.TerrainTileCoord, UnityEngine.Terrain> property get
---       Mapping from TileCoord to Terrain.
UnityEngine.TerrainUtils.TerrainMap = {}

--- Creates a TerrainMap from the neighbors connected to the origin Terrain.
--- @param originTerrain UnityEngine.Terrain Terrain that is given tile coordinate (0,0).
--- @param filter function Filter to apply when populating the map. If null, no filter is applied.
--- @param fullValidation boolean Validate the Terrain map. Default is true.
--- @return UnityEngine.TerrainUtils.TerrainMap The resulting Terrain map. Can return null when no Terrain objects pass the filter.
function UnityEngine.TerrainUtils.TerrainMap.CreateFromConnectedNeighbors(originTerrain, filter, fullValidation) end

--- Creates a TerrainMap from the positions of all active Terrains.
--- @return UnityEngine.TerrainUtils.TerrainMap The resulting Terrain map. Can return null when no Terrain objects pass the filter.
function UnityEngine.TerrainUtils.TerrainMap.CreateFromPlacement(originTerrain, filter, fullValidation) end

--- Creates a TerrainMap from the positions of all active Terrains.
--- @return UnityEngine.TerrainUtils.TerrainMap The resulting Terrain map. Can return null when no Terrain objects pass the filter.
function UnityEngine.TerrainUtils.TerrainMap.CreateFromPlacement(gridOrigin, gridSize, filter, fullValidation) end

--- Retrieves the Terrain object corresponding to the tile coordinates (tileX,tileZ).
--- @param tileX number Tile X coordinate.
--- @param tileZ number Tile Z coordinate.
--- @return UnityEngine.Terrain Returns a valid Terrain object if successful, null otherwise.
function UnityEngine.TerrainUtils.TerrainMap:GetTerrain(tileX, tileZ) end

---  Generated By xerysherry