--- 
---  A min/max slider containing a representation of a range.
---  
--- @class UnityEngine.UIElements.MinMaxSlider:UnityEngine.UIElements.BaseField`1
--- @field ussClassName string 
---        USS class name of elements of this type.
---        
--- @field labelUssClassName string 
---        USS class name of labels in elements of this type.
---        
--- @field inputUssClassName string 
---        USS class name of input elements in elements of this type.
---        
--- @field trackerUssClassName string 
---        USS class name of tracker elements in elements of this type.
---        
--- @field draggerUssClassName string 
---        USS class name of dragger elements in elements of this type.
---        
--- @field minThumbUssClassName string 
---        USS class name of the minimum thumb elements in elements of this type.
---        
--- @field maxThumbUssClassName string 
---        USS class name of the maximum thumb elements in elements of this type.
---        
--- @field minValue number property getset
---       
---        This is the low value of the range represented on the slider.
---        
--- @field maxValue number property getset
---       
---        This is the high value of the range represented on the slider.
---        
--- @field value UnityEngine.Vector2 property getset
---       
---        This is the value of the slider. This is a Vector2 where the x is the lower bound and the y is the higher bound.
---        
--- @field range number property get
---       
---        Returns the range of the low/high limits of the slider.
---        
--- @field lowLimit number property getset
---       
---        This is the low limit of the slider.
---        
--- @field highLimit number property getset
---       
---        This is the high limit of the slider.
---        
--- @field labelElement UnityEngine.UIElements.Label
--- @field label string
--- @field showMixedValue boolean
--- @field binding UnityEngine.UIElements.IBinding
--- @field bindingPath string
--- @field viewDataKey string
--- @field userData System.Object
--- @field canGrabFocus boolean
--- @field focusController UnityEngine.UIElements.FocusController
--- @field usageHints UnityEngine.UIElements.UsageHints
--- @field transform UnityEngine.UIElements.ITransform
--- @field layout UnityEngine.Rect
--- @field contentRect UnityEngine.Rect
--- @field worldBound UnityEngine.Rect
--- @field localBound UnityEngine.Rect
--- @field worldTransform UnityEngine.Matrix4x4
--- @field pickingMode UnityEngine.UIElements.PickingMode
--- @field name string
--- @field enabledInHierarchy boolean
--- @field enabledSelf boolean
--- @field visible boolean
--- @field generateVisualContent function
--- @field experimental UnityEngine.UIElements.IExperimentalFeatures
--- @field hierarchy UnityEngine.UIElements.VisualElement.Hierarchy
--- @field cacheAsBitmap boolean
--- @field parent UnityEngine.UIElements.VisualElement
--- @field panel UnityEngine.UIElements.IPanel
--- @field contentContainer UnityEngine.UIElements.VisualElement
--- @field visualTreeAssetSource UnityEngine.UIElements.VisualTreeAsset
--- @field Item UnityEngine.UIElements.VisualElement
--- @field childCount number
--- @field schedule UnityEngine.UIElements.IVisualElementScheduler
--- @field style UnityEngine.UIElements.IStyle
--- @field customStyle UnityEngine.UIElements.ICustomStyle
--- @field styleSheets UnityEngine.UIElements.VisualElementStyleSheetSet
--- @field tooltip string
--- @field resolvedStyle UnityEngine.UIElements.IResolvedStyle
--- @field focusable boolean
--- @field tabIndex number
--- @field delegatesFocus boolean
UnityEngine.UIElements.MinMaxSlider = {}

function UnityEngine.UIElements.MinMaxSlider:set_minValue(value) end

function UnityEngine.UIElements.MinMaxSlider:set_maxValue(value) end

function UnityEngine.UIElements.MinMaxSlider:set_value(value) end

function UnityEngine.UIElements.MinMaxSlider:SetValueWithoutNotify(newValue) end

function UnityEngine.UIElements.MinMaxSlider:set_lowLimit(value) end

function UnityEngine.UIElements.MinMaxSlider:set_highLimit(value) end

---  Generated By xerysherry