--- @class UnityEngine.HumanPoseHandler Use this class to create, read, and write the HumanPose for a humanoid avatar skeleton hierarchy or an avatar pose.
UnityEngine.HumanPoseHandler = {}

function UnityEngine.HumanPoseHandler:Dispose() end

--- Computes a human pose from the avatar skeleton, stores the pose in the human pose handler, and returns the human pose.
--- @param humanPose UnityEngine.HumanPose& The output human pose. In the human pose, the bodyPosition and bodyRotation are the position and rotation of the approximate center of mass of the humanoid in world space. bodyPosition is normalized: the position is divided by avatar human scale.
function UnityEngine.HumanPoseHandler:GetHumanPose(humanPose) end

--- Stores the specified human pose inside the human pose handler.
--- @param humanPose UnityEngine.HumanPose& The human pose to set. In the human pose, the bodyPosition and bodyRotation are the position and rotation of the approximate center of mass of the humanoid. This is relative to the humanoid root transform and it is normalized: the local position is divided by avatar human scale.
function UnityEngine.HumanPoseHandler:SetHumanPose(humanPose) end

--- Gets the internal human pose stored in the human pose handler.
--- @param humanPose UnityEngine.HumanPose& The output human pose. In the human pose, the bodyPosition and bodyRotation are the position and rotation of the approximate center of mass of the humanoid in world space. bodyPosition is normalized: the position is divided by avatar human scale.
function UnityEngine.HumanPoseHandler:GetInternalHumanPose(humanPose) end

--- Stores the specified human pose as the internal human pose inside the human pose handler.
--- @param humanPose UnityEngine.HumanPose& The human pose to set. In the human pose, the bodyPosition and bodyRotation are the position and rotation of the approximate center of mass of the humanoid. This is relative to the humanoid root transform and it is normalized: the local position is divided by avatar human scale.
function UnityEngine.HumanPoseHandler:SetInternalHumanPose(humanPose) end

--- Gets the internal human pose stored in the human pose handler and converts it to an avatar pose.
--- @param avatarPose Unity.Collections.NativeArray`1 The output avatar pose. The avatar pose is expressed as an array of floats. The floats represent the translation and rotation of the joints as local transforms.
---       Each joint local transform is represented by 3 floats for the translation and 4 floats for the rotation (expressed as a quaternion). The joint transform is stored in the array in the same order as the joint paths in the jointPaths parameter used to construct the human pose handler. For example, if the human pose handler was constructed with 20 joint paths, the avatarPose parameter should be an array of 140 floats.
function UnityEngine.HumanPoseHandler:GetInternalAvatarPose(avatarPose) end

--- Converts an avatar pose to a human pose and stores it as the internal human pose inside the human pose handler.
--- @param avatarPose Unity.Collections.NativeArray`1 The input avatar pose. The avatar pose is expressed as an array of floats. The floats represent the translation and rotation of the joints as local transforms.
---       Each joint local transform is represented by 3 floats for the translation and 4 floats for the rotation (expressed as a quaternion). The joint transform is stored in the array in the same order as the joint paths in the jointPaths parameter used to construct the human pose handler. For example, if the human pose handler was constructed with 20 joint paths, the avatarPose parameter should be an array of 140 floats.
function UnityEngine.HumanPoseHandler:SetInternalAvatarPose(avatarPose) end

---  Generated By xerysherry