--- @class UnityEngine.TextCore.Text.SpriteAsset:UnityEngine.TextCore.Text.TextAsset 
--- @field faceInfo UnityEngine.TextCore.FaceInfo
--- @field spriteSheet UnityEngine.Texture
--- @field spriteCharacterTable UnityEngine.TextCore.Text.SpriteCharacter[]
--- @field spriteCharacterLookupTable table<number, UnityEngine.TextCore.Text.SpriteCharacter>
--- @field spriteGlyphTable UnityEngine.TextCore.Text.SpriteGlyph[]
--- @field version string
--- @field instanceID number
--- @field hashCode number
--- @field material UnityEngine.Material
--- @field materialHashCode number
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
--- @field fallbackSpriteAssets UnityEngine.TextCore.Text.SpriteAsset[]
UnityEngine.TextCore.Text.SpriteAsset = {}

--- @param spriteAsset UnityEngine.TextCore.Text.SpriteAsset 
--- @param unicode number 
--- @param includeFallbacks boolean 
--- @return UnityEngine.TextCore.Text.SpriteAsset
--- @return System.Int32& 
function UnityEngine.TextCore.Text.SpriteAsset.SearchForSpriteByUnicode(spriteAsset, unicode, includeFallbacks) end

--- @param spriteAsset UnityEngine.TextCore.Text.SpriteAsset 
--- @param hashCode number 
--- @param includeFallbacks boolean 
--- @param textSettings UnityEngine.TextCore.Text.TextSettings 
--- @return UnityEngine.TextCore.Text.SpriteAsset
--- @return System.Int32& 
function UnityEngine.TextCore.Text.SpriteAsset.SearchForSpriteByHashCode(spriteAsset, hashCode, includeFallbacks, textSettings) end

function UnityEngine.TextCore.Text.SpriteAsset:UpdateLookupTables() end

--- @param hashCode number 
--- @return number
function UnityEngine.TextCore.Text.SpriteAsset:GetSpriteIndexFromHashcode(hashCode) end

--- @param unicode number 
--- @return number
function UnityEngine.TextCore.Text.SpriteAsset:GetSpriteIndexFromUnicode(unicode) end

--- @param name string 
--- @return number
function UnityEngine.TextCore.Text.SpriteAsset:GetSpriteIndexFromName(name) end

function UnityEngine.TextCore.Text.SpriteAsset:SortGlyphTable() end

---  Generated By xerysherry