--- @class UnityEngine.VFX.VFXParticleSystemInfo This structure provides information data on a particle system.
--- @field aliveCount number Number of alive particles within the particle system, the value is lower than [[VFXParticleSystemInfo._capacity].
--- @field capacity number The capacity (maximum VFXParticleSystemInfo._aliveCount) of the particle system.
--- @field sleeping boolean The sleep state of the particle system.
--- @field bounds UnityEngine.Bounds The rendering bound of this particle system.
UnityEngine.VFX.VFXParticleSystemInfo = {}

---  Generated By xerysherry