--- @class Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility NativeArray Unsafe Utility.
Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility = {}

--- Returns the AtomicSafetyHandle that is used for safety control on the NativeArray.
--- @param array Unity.Collections.NativeArray`1 NativeArray.
--- @return Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle Safety handle.
function Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.GetAtomicSafetyHandle(array) end

--- Sets a new AtomicSafetyHandle for the provided NativeArray.
--- @param array Unity.Collections.NativeArray`1& NativeArray.
--- @param safety Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle Safety handle.
function Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.SetAtomicSafetyHandle(array, safety) end

--- Converts an existing buffer to a NativeArray.
--- @param dataPointer System.Void* Pointer to the preallocated data.
--- @param length number Number of elements. The length of the data in bytes will be computed automatically from this.
--- @param allocator Unity.Collections.Allocator Allocation strategy to use.
--- @return Unity.Collections.NativeArray`1 A new NativeArray, allocated with the given strategy and wrapping the provided data.
function Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.ConvertExistingDataToNativeArray(dataPointer, length, allocator) end

--- Gets the pointer to the memory buffer owner by the NativeArray, performing checks on whether the native array can be written to.
--- @param nativeArray Unity.Collections.NativeArray`1 NativeArray.
--- @return System.Void* NativeArray memory buffer pointer.
function Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.GetUnsafePtr(nativeArray) end

--- Gets a pointer to the memory buffer of the NativeArray or NativeArray.ReadOnly.
--- @param nativeArray Unity.Collections.NativeArray`1 NativeArray.
--- @return System.Void* NativeArray memory buffer pointer.
function Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.GetUnsafeReadOnlyPtr(nativeArray) end

--- Gets a pointer to the memory buffer of the NativeArray or NativeArray.ReadOnly.
--- @param nativeArray Unity.Collections.NativeArray`1.ReadOnly NativeArray.
--- @return System.Void* NativeArray memory buffer pointer.
function Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.GetUnsafeReadOnlyPtr(nativeArray) end

--- Gets the pointer to the data owner by the NativeArray, without performing checks.
--- @param nativeArray Unity.Collections.NativeArray`1 NativeArray.
--- @return System.Void* NativeArray memory buffer pointer.
function Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.GetUnsafeBufferPointerWithoutChecks(nativeArray) end

---  Generated By xerysherry