--- @class UnityEngine.Rendering.RenderStateBlock A set of values that Unity uses to override the GPU's render state.
--- @field blendState UnityEngine.Rendering.BlendState property getset
---       Specifies the new blend state.
--- @field rasterState UnityEngine.Rendering.RasterState property getset
---       Specifies the new raster state.
--- @field depthState UnityEngine.Rendering.DepthState property getset
---       Specifies the new depth state.
--- @field stencilState UnityEngine.Rendering.StencilState property getset
---       Specifies the new stencil state.
--- @field stencilReference number property getset
---       The value to be compared against and/or the value to be written to the buffer, based on the stencil state.
--- @field mask UnityEngine.Rendering.RenderStateMask property getset
---       Specifies which parts of the GPU's render state to override.
UnityEngine.Rendering.RenderStateBlock = {}

--- @param left UnityEngine.Rendering.RenderStateBlock 
--- @param right UnityEngine.Rendering.RenderStateBlock 
--- @return boolean
function UnityEngine.Rendering.RenderStateBlock.op_Equality(left, right) end

--- @param left UnityEngine.Rendering.RenderStateBlock 
--- @param right UnityEngine.Rendering.RenderStateBlock 
--- @return boolean
function UnityEngine.Rendering.RenderStateBlock.op_Inequality(left, right) end

--- @param value UnityEngine.Rendering.BlendState 
function UnityEngine.Rendering.RenderStateBlock:set_blendState(value) end

--- @param value UnityEngine.Rendering.RasterState 
function UnityEngine.Rendering.RenderStateBlock:set_rasterState(value) end

--- @param value UnityEngine.Rendering.DepthState 
function UnityEngine.Rendering.RenderStateBlock:set_depthState(value) end

--- @param value UnityEngine.Rendering.StencilState 
function UnityEngine.Rendering.RenderStateBlock:set_stencilState(value) end

--- @param value number 
function UnityEngine.Rendering.RenderStateBlock:set_stencilReference(value) end

--- @param value UnityEngine.Rendering.RenderStateMask 
function UnityEngine.Rendering.RenderStateBlock:set_mask(value) end

--- @param other UnityEngine.Rendering.RenderStateBlock 
--- @return boolean
function UnityEngine.Rendering.RenderStateBlock:Equals(other) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.Rendering.RenderStateBlock:Equals(obj) end

--- @return number
function UnityEngine.Rendering.RenderStateBlock:GetHashCode() end

---  Generated By xerysherry