--- @class UnityEngineInternal.XR.WSA.RemoteSpeechAccess 
UnityEngineInternal.XR.WSA.RemoteSpeechAccess = {}

--- @param version UnityEngine.XR.WSA.RemoteDeviceVersion 
function UnityEngineInternal.XR.WSA.RemoteSpeechAccess.EnableRemoteSpeech(version) end

function UnityEngineInternal.XR.WSA.RemoteSpeechAccess.DisableRemoteSpeech() end

---  Generated By xerysherry