--- @class UnityEngine.AssetBundleCreateRequest:UnityEngine.AsyncOperation Asynchronous create request for an AssetBundle.
--- @field assetBundle UnityEngine.AssetBundle property get
---       Asset object being loaded (Read Only).
--- @field isDone boolean
--- @field progress number
--- @field priority number
--- @field allowSceneActivation boolean
UnityEngine.AssetBundleCreateRequest = {}

---  Generated By xerysherry