--- @class UnityEngine.SpherecastCommand Use this struct to set up a sphere cast command that is performed asynchronously during a job.
--- @field origin UnityEngine.Vector3 property getset
---       The starting point of the sphere cast in world coordinates.
--- @field radius number property getset
---       The radius of the casting sphere.
--- @field direction UnityEngine.Vector3 property getset
---       The direction of the sphere cast.
--- @field distance number property getset
---       The maximum distance the sphere should check for collisions.
--- @field layerMask number property getset
---       The LayerMask that selectively ignores Colliders when casting a sphere.
UnityEngine.SpherecastCommand = {}

--- Schedules a batch of sphere casts to perform in a job.
--- @param commands Unity.Collections.NativeArray`1 A NaviveArray of SpherecastCommands to perform.
--- @param results Unity.Collections.NativeArray`1 A NavtiveArray of RaycastHit where the result of commands are stored.
--- @param minCommandsPerJob number The minimum number of jobs which should be performed in a single job.
--- @param dependsOn Unity.Jobs.JobHandle A jobHandle of the job that must be completed before performing the sphere casts.
--- @return Unity.Jobs.JobHandle Returns a JobHandle of the job that will perform the sphere casts.
function UnityEngine.SpherecastCommand.ScheduleBatch(commands, results, minCommandsPerJob, dependsOn) end

--- @param value UnityEngine.Vector3 
function UnityEngine.SpherecastCommand:set_origin(value) end

--- @param value number 
function UnityEngine.SpherecastCommand:set_radius(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.SpherecastCommand:set_direction(value) end

--- @param value number 
function UnityEngine.SpherecastCommand:set_distance(value) end

--- @param value number 
function UnityEngine.SpherecastCommand:set_layerMask(value) end

---  Generated By xerysherry