--- @class UnityEngine.ParticleSystemTriggerEventType The different types of particle triggers.
UnityEngine.ParticleSystemTriggerEventType = {
    --- Trigger when particles are inside the collision volume.
    Inside = 0,
    --- Trigger when particles are outside the collision volume.
    Outside = 1,
    --- Trigger when particles enter the collision volume.
    Enter = 2,
    --- Trigger when particles leave the collision volume.
    Exit = 3,
}

---  Generated By xerysherry