--- @class UnityEngine.ParticleSystemJobs.ParticleSystemNativeArray3 A container to hold x, y, and z-axis data for particles.
--- @field Item UnityEngine.Vector3
--- @field x Unity.Collections.NativeArray`1 The x-axis value for each particle.
--- @field y Unity.Collections.NativeArray`1 The y-axis value for each particle.
--- @field z Unity.Collections.NativeArray`1 The z-axis value for each particle.
UnityEngine.ParticleSystemJobs.ParticleSystemNativeArray3 = {}

function UnityEngine.ParticleSystemJobs.ParticleSystemNativeArray3:set_Item(index, value) end

---  Generated By xerysherry