--- @class UnityEngine.AnimatorControllerParameterType The type of the parameter.
UnityEngine.AnimatorControllerParameterType = {
    --- Float type parameter.
    Float = 1,
    --- Int type parameter.
    Int = 3,
    --- Boolean type parameter.
    Bool = 4,
    --- Trigger type parameter.
    Trigger = 9,
}

---  Generated By xerysherry