--- 
---                 Constrains the orientation of an object relative to the position of one or more source objects, such that the object is facing the average position of the sources.
---                 The LookAtConstraint is a simplified Animations.AimConstraint typically used with a Camera.
---             
--- @class UnityEngine.Animations.LookAtConstraint:UnityEngine.Behaviour
--- @field weight number property getset
---       The weight of the constraint component.
--- @field roll number property getset
---       The rotation angle along the z axis of the object. The constraint uses this property to calculate the world up vector when Animations.LookAtConstraint.UseUpObject is false.
--- @field constraintActive boolean property getset
---       Activates or deactivates the constraint.
--- @field locked boolean property getset
---       Locks the offset and rotation at rest.
--- @field rotationAtRest UnityEngine.Vector3 property getset
---       The rotation used when the sources have a total weight of 0.
--- @field rotationOffset UnityEngine.Vector3 property getset
---       Represents an offset from the constrained orientation.
--- @field worldUpObject UnityEngine.Transform property getset
---       The world up object, used to calculate the world up vector when Animations.LookAtConstraint.UseUpObject is true.
--- @field useUpObject boolean property getset
---       Determines how the up vector is calculated.
--- @field sourceCount number property get
---       The number of sources set on the component (Read Only).
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Animations.LookAtConstraint = {}

function UnityEngine.Animations.LookAtConstraint:set_weight(value) end

function UnityEngine.Animations.LookAtConstraint:set_roll(value) end

function UnityEngine.Animations.LookAtConstraint:set_constraintActive(value) end

function UnityEngine.Animations.LookAtConstraint:set_locked(value) end

function UnityEngine.Animations.LookAtConstraint:set_rotationAtRest(value) end

function UnityEngine.Animations.LookAtConstraint:set_rotationOffset(value) end

function UnityEngine.Animations.LookAtConstraint:set_worldUpObject(value) end

function UnityEngine.Animations.LookAtConstraint:set_useUpObject(value) end

--- Gets the list of sources.
--- @param sources UnityEngine.Animations.ConstraintSource[] The list of sources to be filled by the component.
function UnityEngine.Animations.LookAtConstraint:GetSources(sources) end

--- Sets the list of sources on the component.
--- @param sources UnityEngine.Animations.ConstraintSource[] The list of sources to set.
function UnityEngine.Animations.LookAtConstraint:SetSources(sources) end

--- Adds a constraint source.
--- @param source UnityEngine.Animations.ConstraintSource The source object and its weight.
--- @return number Returns the index of the added source.
function UnityEngine.Animations.LookAtConstraint:AddSource(source) end

--- Removes a source from the component.
--- @param index number The index of the source to remove.
function UnityEngine.Animations.LookAtConstraint:RemoveSource(index) end

--- Gets a constraint source by index.
--- @param index number The index of the source.
--- @return UnityEngine.Animations.ConstraintSource Returns the source object and its weight.
function UnityEngine.Animations.LookAtConstraint:GetSource(index) end

--- Sets a source at a specified index.
--- @param index number The index of the source to set.
--- @param source UnityEngine.Animations.ConstraintSource The source object and its weight.
function UnityEngine.Animations.LookAtConstraint:SetSource(index, source) end

---  Generated By xerysherry