--- @class UnityEngine.FrameDebugger Controls the from a script.
--- @field enabled boolean property get
---       Queries whether the is enabled.
UnityEngine.FrameDebugger = {}

---  Generated By xerysherry