--- @class UnityEngine.Rendering.VertexAttribute Possible attribute types that describe a vertex in a Mesh.
UnityEngine.Rendering.VertexAttribute = {
    --- Vertex position.
    Position = 0,
    --- Vertex normal.
    Normal = 1,
    --- Vertex tangent.
    Tangent = 2,
    --- Vertex color.
    Color = 3,
    --- Primary texture coordinate (UV).
    TexCoord0 = 4,
    --- Additional  texture coordinate.
    TexCoord1 = 5,
    --- Additional  texture coordinate.
    TexCoord2 = 6,
    --- Additional  texture coordinate.
    TexCoord3 = 7,
    --- Additional  texture coordinate.
    TexCoord4 = 8,
    --- Additional  texture coordinate.
    TexCoord5 = 9,
    --- Additional  texture coordinate.
    TexCoord6 = 10,
    --- Additional  texture coordinate.
    TexCoord7 = 11,
    --- Bone blend weights for skinned Meshes.
    BlendWeight = 12,
    --- Bone indices for skinned Meshes.
    BlendIndices = 13,
}

---  Generated By xerysherry