--- 
---  A control that allows users to select a single option inside a RadioButtonGroup
---  
--- @class UnityEngine.UIElements.RadioButton:UnityEngine.UIElements.BaseBoolField
--- @field ussClassName string 
---        USS class name for RadioButton elements.
---        
--- @field labelUssClassName string 
---        USS class name for Labels in RadioButton elements.
---        
--- @field inputUssClassName string 
---        USS class name of input elements in RadioButton elements.
---        
--- @field checkmarkBackgroundUssClassName string 
---        USS class name of checkmark background in RadioButton elements.
---        
--- @field checkmarkUssClassName string 
---        USS class name of checkmark in RadioButton elements.
---        
--- @field textUssClassName string 
---        USS class name of Text elements in RadioButton elements.
---        
--- @field value boolean
--- @field text string
--- @field labelElement UnityEngine.UIElements.Label
--- @field label string
--- @field showMixedValue boolean
--- @field binding UnityEngine.UIElements.IBinding
--- @field bindingPath string
--- @field viewDataKey string
--- @field userData System.Object
--- @field canGrabFocus boolean
--- @field focusController UnityEngine.UIElements.FocusController
--- @field usageHints UnityEngine.UIElements.UsageHints
--- @field transform UnityEngine.UIElements.ITransform
--- @field layout UnityEngine.Rect
--- @field contentRect UnityEngine.Rect
--- @field worldBound UnityEngine.Rect
--- @field localBound UnityEngine.Rect
--- @field worldTransform UnityEngine.Matrix4x4
--- @field pickingMode UnityEngine.UIElements.PickingMode
--- @field name string
--- @field enabledInHierarchy boolean
--- @field enabledSelf boolean
--- @field visible boolean
--- @field generateVisualContent function
--- @field experimental UnityEngine.UIElements.IExperimentalFeatures
--- @field hierarchy UnityEngine.UIElements.VisualElement.Hierarchy
--- @field cacheAsBitmap boolean
--- @field parent UnityEngine.UIElements.VisualElement
--- @field panel UnityEngine.UIElements.IPanel
--- @field contentContainer UnityEngine.UIElements.VisualElement
--- @field visualTreeAssetSource UnityEngine.UIElements.VisualTreeAsset
--- @field Item UnityEngine.UIElements.VisualElement
--- @field childCount number
--- @field schedule UnityEngine.UIElements.IVisualElementScheduler
--- @field style UnityEngine.UIElements.IStyle
--- @field customStyle UnityEngine.UIElements.ICustomStyle
--- @field styleSheets UnityEngine.UIElements.VisualElementStyleSheetSet
--- @field tooltip string
--- @field resolvedStyle UnityEngine.UIElements.IResolvedStyle
--- @field focusable boolean
--- @field tabIndex number
--- @field delegatesFocus boolean
UnityEngine.UIElements.RadioButton = {}

function UnityEngine.UIElements.RadioButton:set_value(value) end

function UnityEngine.UIElements.RadioButton:SetSelected(selected) end

function UnityEngine.UIElements.RadioButton:SetValueWithoutNotify(newValue) end

---  Generated By xerysherry