--- @class UnityEngine.EventSystems.EventSystem:UnityEngine.EventSystems.UIBehaviour 
--- @field current UnityEngine.EventSystems.EventSystem
--- @field sendNavigationEvents boolean
--- @field pixelDragThreshold number
--- @field currentInputModule UnityEngine.EventSystems.BaseInputModule
--- @field firstSelectedGameObject UnityEngine.GameObject
--- @field currentSelectedGameObject UnityEngine.GameObject
--- @field lastSelectedGameObject UnityEngine.GameObject
--- @field isFocused boolean
--- @field alreadySelecting boolean
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.EventSystems.EventSystem = {}

--- @param value UnityEngine.EventSystems.EventSystem 
function UnityEngine.EventSystems.EventSystem.set_current(value) end

--- @param activeEventSystem UnityEngine.EventSystems.EventSystem 
--- @param sendEvents boolean 
--- @param createPanelGameObjectsOnStart boolean 
function UnityEngine.EventSystems.EventSystem.SetUITookitEventSystemOverride(activeEventSystem, sendEvents, createPanelGameObjectsOnStart) end

--- @param value boolean 
function UnityEngine.EventSystems.EventSystem:set_sendNavigationEvents(value) end

--- @param value number 
function UnityEngine.EventSystems.EventSystem:set_pixelDragThreshold(value) end

--- @param value UnityEngine.GameObject 
function UnityEngine.EventSystems.EventSystem:set_firstSelectedGameObject(value) end

function UnityEngine.EventSystems.EventSystem:UpdateModules() end

--- @param selected UnityEngine.GameObject 
--- @param pointer UnityEngine.EventSystems.BaseEventData 
function UnityEngine.EventSystems.EventSystem:SetSelectedGameObject(selected, pointer) end

--- @param selected UnityEngine.GameObject 
function UnityEngine.EventSystems.EventSystem:SetSelectedGameObject(selected) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
--- @param raycastResults UnityEngine.EventSystems.RaycastResult[] 
function UnityEngine.EventSystems.EventSystem:RaycastAll(eventData, raycastResults) end

--- @return boolean
function UnityEngine.EventSystems.EventSystem:IsPointerOverGameObject() end

--- @param pointerId number 
--- @return boolean
function UnityEngine.EventSystems.EventSystem:IsPointerOverGameObject(pointerId) end

--- @return string
function UnityEngine.EventSystems.EventSystem:ToString() end

---  Generated By xerysherry