--- @class Unity.Collections.LowLevel.Unsafe.AtomicSafetyErrorType Enumeration of AtomicSafetyHandle errors.
Unity.Collections.LowLevel.Unsafe.AtomicSafetyErrorType = {
    --- Corresponds to an error triggered when the object protected by this AtomicSafetyHandle is accessed on the main thread after it is deallocated.
    Deallocated = 0,
    --- Corresponds to an error triggered when the object protected by this AtomicSafetyHandle is accessed by a worker thread after it is deallocated.
    DeallocatedFromJob = 1,
    --- Corresponds to an error triggered when the object protected by this AtomicSafetyHandle is accessed by a worker thread before it is allocated.
    NotAllocatedFromJob = 2,
}

---  Generated By xerysherry