--- @class UnityEngine.MeshFilter:UnityEngine.Component A class to access the Mesh of the.
--- @field sharedMesh UnityEngine.Mesh property getset
---       Returns the shared mesh of the mesh filter.
--- @field mesh UnityEngine.Mesh property getset
---       Returns the instantiated Mesh assigned to the mesh filter.
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.MeshFilter = {}

--- @param value UnityEngine.Mesh 
function UnityEngine.MeshFilter:set_sharedMesh(value) end

--- @param value UnityEngine.Mesh 
function UnityEngine.MeshFilter:set_mesh(value) end

---  Generated By xerysherry