--- @class UnityEngine.LocalNotification 
--- @field defaultSoundName string
--- @field fireDate System.DateTime
--- @field timeZone string
--- @field repeatInterval UnityEngine.CalendarUnit
--- @field repeatCalendar UnityEngine.CalendarIdentifier
--- @field alertBody string
--- @field alertAction string
--- @field hasAction boolean
--- @field alertLaunchImage string
--- @field applicationIconBadgeNumber number
--- @field soundName string
--- @field userInfo System.Collections.IDictionary
UnityEngine.LocalNotification = {}

--- @param value System.DateTime 
function UnityEngine.LocalNotification:set_fireDate(value) end

--- @param value string 
function UnityEngine.LocalNotification:set_timeZone(value) end

--- @param value UnityEngine.CalendarUnit 
function UnityEngine.LocalNotification:set_repeatInterval(value) end

--- @param value UnityEngine.CalendarIdentifier 
function UnityEngine.LocalNotification:set_repeatCalendar(value) end

--- @param value string 
function UnityEngine.LocalNotification:set_alertBody(value) end

--- @param value string 
function UnityEngine.LocalNotification:set_alertAction(value) end

--- @param value boolean 
function UnityEngine.LocalNotification:set_hasAction(value) end

--- @param value string 
function UnityEngine.LocalNotification:set_alertLaunchImage(value) end

--- @param value number 
function UnityEngine.LocalNotification:set_applicationIconBadgeNumber(value) end

--- @param value string 
function UnityEngine.LocalNotification:set_soundName(value) end

--- @param value System.Collections.IDictionary 
function UnityEngine.LocalNotification:set_userInfo(value) end

---  Generated By xerysherry