--- @class UnityEngine.ParticleSystemSortMode The sorting mode for particle systems.
UnityEngine.ParticleSystemSortMode = {
    --- No sorting.
    None = 0,
    --- Sort based on distance to the camera position. For orthographic cameras, this mode is the same as sorting by depth.
    Distance = 1,
    --- Sort the oldest particles to the front.
    OldestInFront = 2,
    --- Sort the youngest particles to the front.
    YoungestInFront = 3,
    --- Sort based on depth from the camera plane.
    Depth = 4,
}

---  Generated By xerysherry