--- @class UnityEngine.Analytics.AnalyticsEventPriority Analytics event priority.
UnityEngine.Analytics.AnalyticsEventPriority = {
    --- Any current or previous events in the memory queue persist immediately to the filesystem and dispatcher service makes the events available to send to the server. It adds the events to the bottom of the dispatch queue and makes them available to send to the server.
    FlushQueueFlag = 1,
    --- Any current or previous events in the memory queue persist immediately to the filesystem.
    CacheImmediatelyFlag = 2,
    --- Use this flag to send events while in the stop state.
    AllowInStopModeFlag = 4,
    --- Events with this flag are given higher priority compared to others while dispatching to the server.
    SendImmediateFlag = 8,
    --- Events will be stored in the memory queue, and will not persist in the file system.
    NoCachingFlag = 16,
    --- In case of failure to post the event to the server, it will not attempt to send them again.
    NoRetryFlag = 32,
    --- This priority queues events in-memory.
    NormalPriorityEvent = 0,
    --- This priority queues events in-memory and writes them to the filesystem immediately.
    NormalPriorityEvent_WithCaching = 2,
    --- This priority is similar to the Analytics.AnalyticsEventPriority.NormalPriorityEvent, except these events will be stored in the memory queue and will not persist in the file system. In case of failure to post the event to the server, it will not attempt to send them again.
    NormalPriorityEvent_NoRetryNoCaching = 48,
    --- Any current or previous events in the memory queue persist immediately to the filesystem. It adds the events to the bottom of the dispatch queue and makes them available to send to the server.
    HighPriorityEvent = 1,
    --- This priority lets you send events in the stop state, and makes any current or previous events in the memory queue persist immediately to the filesystem. It adds the events to the bottom of the dispatch queue and makes them available to send to the server.
    HighPriorityEvent_InStopMode = 5,
    --- This priority is similar to the Analytics.AnalyticsEventPriority.HighPriorityEvent, except these events are given a highest priority than other events in the disptach queue. It adds the events to the top of the dispatch queue and makes them available to send to the server.
    HighestPriorityEvent = 9,
    --- This priority is similar to the Analytics.AnalyticsEventPriority.HighestPriorityEvent, except these events will be stored in the memory queue and will not persist in the file system. In case of failure to post the event to the server, it will not attempt to send them again.
    HighestPriorityEvent_NoRetryNoCaching = 49,
}

---  Generated By xerysherry