UnityEngine.UI.InputField.InputType = {
    Standard = 0,
    AutoCorrect = 1,
    Password = 2,
}

UnityEngine.UI.InputField.InputType = {
    Standard = 0,
    AutoCorrect = 1,
    Password = 2,
}

---  Generated By xerysherry