--- @class UnityEngine.UI.MaskableGraphic:UnityEngine.UI.Graphic 
--- @field onCullStateChanged UnityEngine.UI.MaskableGraphic.CullStateChangedEvent
--- @field maskable boolean
--- @field isMaskingGraphic boolean
--- @field color UnityEngine.Color
--- @field raycastTarget boolean
--- @field raycastPadding UnityEngine.Vector4
--- @field depth number
--- @field rectTransform UnityEngine.RectTransform
--- @field canvas UnityEngine.Canvas
--- @field canvasRenderer UnityEngine.CanvasRenderer
--- @field defaultMaterial UnityEngine.Material
--- @field material UnityEngine.Material
--- @field materialForRendering UnityEngine.Material
--- @field mainTexture UnityEngine.Texture
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.MaskableGraphic = {}

function UnityEngine.UI.MaskableGraphic:set_onCullStateChanged(value) end

function UnityEngine.UI.MaskableGraphic:set_maskable(value) end

function UnityEngine.UI.MaskableGraphic:set_isMaskingGraphic(value) end

--- @return UnityEngine.Material
function UnityEngine.UI.MaskableGraphic:GetModifiedMaterial(baseMaterial) end

function UnityEngine.UI.MaskableGraphic:Cull(clipRect, validRect) end

function UnityEngine.UI.MaskableGraphic:SetClipRect(clipRect, validRect) end

function UnityEngine.UI.MaskableGraphic:SetClipSoftness(clipSoftness) end

function UnityEngine.UI.MaskableGraphic:ParentMaskStateChanged() end

function UnityEngine.UI.MaskableGraphic:RecalculateClipping() end

function UnityEngine.UI.MaskableGraphic:RecalculateMasking() end

---  Generated By xerysherry