--- @class Unity.IO.LowLevel.Unsafe.ReadHandle You can use this handle to query the status of an asynchronous read operation. Note: To avoid a memory leak, you must call Dispose.
--- @field JobHandle Unity.Jobs.JobHandle property get
---       JobHandle that completes when the read operation completes.
--- @field Status Unity.IO.LowLevel.Unsafe.ReadStatus property get
---       Current state of the read operation.
--- @field ReadCount number property get
---       The number of read commands performed for this read operation. Will return zero until the reads have begun.
Unity.IO.LowLevel.Unsafe.ReadHandle = {}

--- Check if the ReadHandle is valid.
--- @return boolean True if the ReadHandle is valid.
function Unity.IO.LowLevel.Unsafe.ReadHandle:IsValid() end

--- Disposes the ReadHandle. Use this to free up internal resources for reuse.
function Unity.IO.LowLevel.Unsafe.ReadHandle:Dispose() end

--- Cancels the AsyncReadManager.Read operation on this handle.
function Unity.IO.LowLevel.Unsafe.ReadHandle:Cancel() end

--- Returns the total number of bytes read by all the ReadCommand operations the asynchronous file read request.
--- @return number The total number of bytes read by the asynchronous file read request.
function Unity.IO.LowLevel.Unsafe.ReadHandle:GetBytesRead() end

--- Returns the total number of bytes read for a specific ReadCommand index.
--- @param readCommandIndex number The index of the ReadCommand for which to retrieve the number of bytes read.
--- @return number The number of bytes read for the specified ReadCommand.
function Unity.IO.LowLevel.Unsafe.ReadHandle:GetBytesRead(readCommandIndex) end

--- Returns an array containing the number of bytes read by the ReadCommand operations during the asynchronous file read request, where each index corresponds to the ReadCommand index.
--- @return System.UInt64* An unsafe pointer to the array storing the number of bytes read for each ReadCommand in the request.
function Unity.IO.LowLevel.Unsafe.ReadHandle:GetBytesReadArray() end

---  Generated By xerysherry