--- 
---  Collection of StylePropertyName.
---  
--- @class UnityEngine.UIElements.StylePropertyNameCollection
UnityEngine.UIElements.StylePropertyNameCollection = {}

--- 
---  Returns an enumerator that iterates through the StylePropertyNameCollection.
---  
--- @return UnityEngine.UIElements.StylePropertyNameCollection.Enumerator An enumerator that can be used to iterate through the StylePropertyNameCollection.
function UnityEngine.UIElements.StylePropertyNameCollection:GetEnumerator() end

--- 
---   Determines whether a StylePropertyNameCollection contains the specified element.
---  
--- @param stylePropertyName UnityEngine.UIElements.StylePropertyName The element to locate in the <see cref="StylePropertyNameCollection" />.
--- @return boolean true if the StylePropertyNameCollection contains the specified element; otherwise, false.
function UnityEngine.UIElements.StylePropertyNameCollection:Contains(stylePropertyName) end

---  Generated By xerysherry