--- @class UnityEngine.StreamingController:UnityEngine.Behaviour A StreamingController controls the streaming settings for an individual camera location.
--- @field streamingMipmapBias number property getset
---       Offset applied to the mipmap level chosen by the texture streaming system for any textures visible from this camera. This Offset can take either a positive or negative value.
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.StreamingController = {}

function UnityEngine.StreamingController:set_streamingMipmapBias(value) end

--- Initiate preloading of streaming data for this camera.
--- @param timeoutSeconds number Optional timeout before stopping preloading. Set to 0.0f when no timeout is required.
--- @param activateCameraOnTimeout boolean Set to True to activate the connected Camera component when timeout expires.
--- @param disableCameraCuttingFrom UnityEngine.Camera Camera to deactivate on timeout (if Camera.activateCameraOnTime is True). This parameter can be null.
function UnityEngine.StreamingController:SetPreloading(timeoutSeconds, activateCameraOnTimeout, disableCameraCuttingFrom) end

--- Abort preloading.
function UnityEngine.StreamingController:CancelPreloading() end

--- Used to find out whether the StreamingController is currently preloading texture mipmaps.
--- @return boolean True if in a preloading state, otherwise False.
function UnityEngine.StreamingController:IsPreloading() end

---  Generated By xerysherry