--- @class UnityEngine.LightProbeProxyVolume.QualityMode An enum describing the Quality option used by the Light Probe Proxy Volume component.
UnityEngine.LightProbeProxyVolume.QualityMode = {
    --- This option will use only two SH coefficients bands: L0 and L1. The coefficients are sampled from the Light Probe Proxy Volume 3D Texture. Using this option might increase the draw call batch sizes by not having to change the L2 coefficients per Renderer.
    Low = 0,
    --- This option will use L0 and L1 SH coefficients from the Light Probe Proxy Volume 3D Texture. The L2 coefficients are constant per Renderer. By having to provide the L2 coefficients, draw call batches might be broken.
    Normal = 1,
}

--- @class UnityEngine.LightProbeProxyVolume.QualityMode An enum describing the Quality option used by the Light Probe Proxy Volume component.
UnityEngine.LightProbeProxyVolume.QualityMode = {
    --- This option will use only two SH coefficients bands: L0 and L1. The coefficients are sampled from the Light Probe Proxy Volume 3D Texture. Using this option might increase the draw call batch sizes by not having to change the L2 coefficients per Renderer.
    Low = 0,
    --- This option will use L0 and L1 SH coefficients from the Light Probe Proxy Volume 3D Texture. The L2 coefficients are constant per Renderer. By having to provide the L2 coefficients, draw call batches might be broken.
    Normal = 1,
}

---  Generated By xerysherry