--- @class UnityEngine.UI.MaskUtilities 
UnityEngine.UI.MaskUtilities = {}

function UnityEngine.UI.MaskUtilities.Notify2DMaskStateChanged(mask) end

function UnityEngine.UI.MaskUtilities.NotifyStencilStateChanged(mask) end

--- @return UnityEngine.Transform
function UnityEngine.UI.MaskUtilities.FindRootSortOverrideCanvas(start) end

--- @return number
function UnityEngine.UI.MaskUtilities.GetStencilDepth(transform, stopAfter) end

--- @return boolean
function UnityEngine.UI.MaskUtilities.IsDescendantOrSelf(father, child) end

--- @return UnityEngine.UI.RectMask2D
function UnityEngine.UI.MaskUtilities.GetRectMaskForClippable(clippable) end

function UnityEngine.UI.MaskUtilities.GetRectMasksForClip(clipper, masks) end

---  Generated By xerysherry