--- @class UnityEngine.AdditionalCanvasShaderChannels Enum mask of possible shader channel properties that can also be included when the Canvas mesh is created.
UnityEngine.AdditionalCanvasShaderChannels = {
    --- No additional shader parameters are needed.
    None = 0,
    --- Include UV1 on the mesh vertices.
    TexCoord1 = 1,
    --- Include UV2 on the mesh vertices.
    TexCoord2 = 2,
    --- Include UV3 on the mesh vertices.
    TexCoord3 = 4,
    --- Include the normals on the mesh vertices.
    Normal = 8,
    --- Include the Tangent on the mesh vertices.
    Tangent = 16,
}

---  Generated By xerysherry