--- @class UnityEngine.Android.AndroidDevice Interface into Android specific functionality.
--- @field hardwareType UnityEngine.Android.AndroidHardwareType property get
---       When running on a Chrome OS device, hardwareType is set to AndroidHardwareType.ChromeOS. It is set to AndroidHardwareType.Generic in all other cases.
UnityEngine.Android.AndroidDevice = {}

--- Set sustained performance mode. When enabled, sustained performance mode is intended to provide a consistent level of performance for a prolonged amount of time.
--- @param enabled boolean 
function UnityEngine.Android.AndroidDevice.SetSustainedPerformanceMode(enabled) end

---  Generated By xerysherry