--- @class UnityEngine.JointTranslationLimits2D Motion limits of a Rigidbody2D object along a SliderJoint2D.
--- @field min number property getset
---       Minimum distance the Rigidbody2D object can move from the Slider Joint's anchor.
--- @field max number property getset
---       Maximum distance the Rigidbody2D object can move from the Slider Joint's anchor.
UnityEngine.JointTranslationLimits2D = {}

--- @param value number 
function UnityEngine.JointTranslationLimits2D:set_min(value) end

--- @param value number 
function UnityEngine.JointTranslationLimits2D:set_max(value) end

---  Generated By xerysherry