--- @class UnityEngine.SpriteDrawMode SpriteRenderer draw mode.
UnityEngine.SpriteDrawMode = {
    --- Displays the full sprite.
    Simple = 0,
    --- The SpriteRenderer will render the sprite as a 9-slice image where the corners will remain constant and the other sections will scale.
    Sliced = 1,
    --- The SpriteRenderer will render the sprite as a 9-slice image where the corners will remain constant and the other sections will tile.
    Tiled = 2,
}

---  Generated By xerysherry