--- @class UnityEngine.HingeJoint2D:UnityEngine.AnchoredJoint2D Joint that allows a Rigidbody2D object to rotate around a point in space or a point on another object.
--- @field useMotor boolean property getset
---       Should the joint be rotated automatically by a motor torque?
--- @field useLimits boolean property getset
---       Should limits be placed on the range of rotation?
--- @field motor UnityEngine.JointMotor2D property getset
---       Parameters for the motor force applied to the joint.
--- @field limits UnityEngine.JointAngleLimits2D property getset
---       Limit of angular rotation (in degrees) on the joint.
--- @field limitState UnityEngine.JointLimitState2D property get
---       Gets the state of the joint limit.
--- @field referenceAngle number property get
---       The angle (in degrees) referenced between the two bodies used as the constraint for the joint.
--- @field jointAngle number property get
---       The current joint angle (in degrees) with respect to the reference angle.
--- @field jointSpeed number property get
---       The current joint speed.
--- @field anchor UnityEngine.Vector2
--- @field connectedAnchor UnityEngine.Vector2
--- @field autoConfigureConnectedAnchor boolean
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field connectedBody UnityEngine.Rigidbody2D
--- @field enableCollision boolean
--- @field breakForce number
--- @field breakTorque number
--- @field reactionForce UnityEngine.Vector2
--- @field reactionTorque number
--- @field collideConnected boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.HingeJoint2D = {}

--- @param value boolean 
function UnityEngine.HingeJoint2D:set_useMotor(value) end

--- @param value boolean 
function UnityEngine.HingeJoint2D:set_useLimits(value) end

--- @param value UnityEngine.JointMotor2D 
function UnityEngine.HingeJoint2D:set_motor(value) end

--- @param value UnityEngine.JointAngleLimits2D 
function UnityEngine.HingeJoint2D:set_limits(value) end

--- Gets the motor torque of the joint given the specified timestep.
--- @param timeStep number The time to calculate the motor torque for.
--- @return number 
function UnityEngine.HingeJoint2D:GetMotorTorque(timeStep) end

---  Generated By xerysherry