--- @class UnityEngine.ContextMenuItemAttribute:UnityEngine.PropertyAttribute Use this attribute to add a context menu to a field that calls a  named method.
--- @field order number
--- @field TypeId System.Object
--- @field name string The name of the context menu item.
--- @field _function string The name of the function that should be called.
UnityEngine.ContextMenuItemAttribute = {}

---  Generated By xerysherry