--- @class UnityEngine.RectOffset Offsets for rectangles, borders, etc.
--- @field left number property getset
---       Left edge size.
--- @field right number property getset
---       Right edge size.
--- @field top number property getset
---       Top edge size.
--- @field bottom number property getset
---       Bottom edge size.
--- @field horizontal number property get
---       Shortcut for left + right. (Read Only)
--- @field vertical number property get
---       Shortcut for top + bottom. (Read Only)
UnityEngine.RectOffset = {}

--- Returns a formatted string for this RectOffset.
--- @return string 
function UnityEngine.RectOffset:ToString() end

--- Returns a formatted string for this RectOffset.
--- @param format string 
--- @return string 
function UnityEngine.RectOffset:ToString(format) end

--- Returns a formatted string for this RectOffset.
--- @param format string A numeric format string.
--- @param formatProvider System.IFormatProvider An object that specifies culture-specific formatting.
--- @return string 
function UnityEngine.RectOffset:ToString(format, formatProvider) end

--- @param value number 
function UnityEngine.RectOffset:set_left(value) end

--- @param value number 
function UnityEngine.RectOffset:set_right(value) end

--- @param value number 
function UnityEngine.RectOffset:set_top(value) end

--- @param value number 
function UnityEngine.RectOffset:set_bottom(value) end

--- Add the border offsets to a rect.
--- @param rect UnityEngine.Rect 
--- @return UnityEngine.Rect 
function UnityEngine.RectOffset:Add(rect) end

--- Remove the border offsets from a rect.
--- @param rect UnityEngine.Rect 
--- @return UnityEngine.Rect 
function UnityEngine.RectOffset:Remove(rect) end

---  Generated By xerysherry