--- @class Unity.Profiling.ProfilerRecorderOptions ProfilerRecorder lifecycle and collection options.
Unity.Profiling.ProfilerRecorderOptions = {
    None = 0,
    --- Use to start data collection immediately upon ProfilerRecorder initialization.
    StartImmediately = 1,
    --- Use to keep the ProfilerRecorder unmanaged instance running across a Unity domain reload.
    KeepAliveDuringDomainReload = 2,
    --- Use to collect samples only on the thread ProfilerRecorder was initialized on.
    CollectOnlyOnCurrentThread = 4,
    --- Use to allow sample value overwrite when ProfilerRecorder capacity is exceeded.
    WrapAroundWhenCapacityReached = 8,
    --- Use to sum all samples within a frame and collect those as one sample per frame.
    SumAllSamplesInFrame = 16,
    --- Use to indicate that ProfilerRecorder should collect GPU timing instead of CPU.
    GpuRecorder = 64,
    --- Default initialization options. Equivalent to (SumSamplesInFrame | WrapAroundWhenCapacityReached).
    Default = 24,
}

---  Generated By xerysherry