--- 
---  Represents the point of origin where the (Scale, Translate, Rotate) transformations are applied.
---  
--- @class UnityEngine.UIElements.TransformOrigin
--- @field x UnityEngine.UIElements.Length
--- @field y UnityEngine.UIElements.Length
--- @field z number
UnityEngine.UIElements.TransformOrigin = {}

--- 
---  Returns the initial value for the TransformOrigin property.
---  
--- @return UnityEngine.UIElements.TransformOrigin 
function UnityEngine.UIElements.TransformOrigin.Initial() end

--- @return boolean
function UnityEngine.UIElements.TransformOrigin.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.UIElements.TransformOrigin.op_Inequality(lhs, rhs) end

function UnityEngine.UIElements.TransformOrigin:set_x(value) end

function UnityEngine.UIElements.TransformOrigin:set_y(value) end

function UnityEngine.UIElements.TransformOrigin:set_z(value) end

--- @return boolean
function UnityEngine.UIElements.TransformOrigin:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.TransformOrigin:Equals(obj) end

--- @return number
function UnityEngine.UIElements.TransformOrigin:GetHashCode() end

--- @return string
function UnityEngine.UIElements.TransformOrigin:ToString() end

---  Generated By xerysherry