--- @class Unity.Collections.LowLevel.Unsafe.NativeSetThreadIndexAttribute:System.Attribute This attribute can inject a worker thread index into an int on the job struct. This is usually used in the implementation of atomic containers. The index is guaranteed to be unique to any other job that might be running in parallel.
--- @field TypeId System.Object
Unity.Collections.LowLevel.Unsafe.NativeSetThreadIndexAttribute = {}

---  Generated By xerysherry