--- @class UnityEngine.Accessibility.VisionUtility A class containing methods to assist with accessibility for users with different vision capabilities.
UnityEngine.Accessibility.VisionUtility = {}

--- Gets a palette of colors that should be distinguishable for normal vision, deuteranopia, protanopia, and tritanopia.
--- @param palette UnityEngine.Color[] An array of colors to populate with a palette.
--- @param minimumLuminance number Minimum allowable perceived luminance from 0 to 1. A value of 0.2 or greater is recommended for dark backgrounds.
--- @param maximumLuminance number Maximum allowable perceived luminance from 0 to 1. A value of 0.8 or less is recommended for light backgrounds.
--- @return number The number of unambiguous colors in the palette.
function UnityEngine.Accessibility.VisionUtility.GetColorBlindSafePalette(palette, minimumLuminance, maximumLuminance) end

---  Generated By xerysherry