--- 
---  Describes a VisualElement background.
---  
--- @class UnityEngine.UIElements.Background
--- @field texture UnityEngine.Texture2D property getset
---       
---        The texture to display as a background.
---        
--- @field sprite UnityEngine.Sprite property getset
---       
---        The sprite to display as a background.
---        
--- @field renderTexture UnityEngine.RenderTexture property getset
---       
---        The RenderTexture to display as a background.
---        
--- @field vectorImage UnityEngine.UIElements.VectorImage property getset
---       
---        The VectorImage to display as a background.
---        
UnityEngine.UIElements.Background = {}

--- 
---  Creates a background from a Texture2D.
---  
--- @param t UnityEngine.Texture2D The texture to use as a background.
--- @return UnityEngine.UIElements.Background A new background object.
function UnityEngine.UIElements.Background.FromTexture2D(t) end

--- 
---  Creates a background from a RenderTexture.
---  
--- @param rt UnityEngine.RenderTexture The render texture to use as a background.
--- @return UnityEngine.UIElements.Background A new background object.
function UnityEngine.UIElements.Background.FromRenderTexture(rt) end

--- 
---  Creates a background from a Sprite.
---  
--- @param s UnityEngine.Sprite The sprite to use as a background.
--- @return UnityEngine.UIElements.Background A new background object.
function UnityEngine.UIElements.Background.FromSprite(s) end

--- 
---  Creates a background from a VectorImage.
---  
--- @param vi UnityEngine.UIElements.VectorImage The vector image to use as a background.
--- @return UnityEngine.UIElements.Background A new background object.
function UnityEngine.UIElements.Background.FromVectorImage(vi) end

--- @return boolean
function UnityEngine.UIElements.Background.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.UIElements.Background.op_Inequality(lhs, rhs) end

function UnityEngine.UIElements.Background:set_texture(value) end

function UnityEngine.UIElements.Background:set_sprite(value) end

function UnityEngine.UIElements.Background:set_renderTexture(value) end

function UnityEngine.UIElements.Background:set_vectorImage(value) end

--- @return boolean
function UnityEngine.UIElements.Background:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.Background:Equals(obj) end

--- @return number
function UnityEngine.UIElements.Background:GetHashCode() end

--- @return string
function UnityEngine.UIElements.Background:ToString() end

---  Generated By xerysherry