--- @class UnityEngine.Rendering.VirtualTexturing.Procedural Static class representing the Procedural Virtual Texturing system.
UnityEngine.Rendering.VirtualTexturing.Procedural = {}

--- Sets the Procedural Virtual Texturing CPU cache size (in MegaBytes).
--- @param sizeInMegabytes number 
function UnityEngine.Rendering.VirtualTexturing.Procedural.SetCPUCacheSize(sizeInMegabytes) end

--- Gets the Procedural Virtual Texturing CPU cache size.
--- @return number The size of the CPU caches.
function UnityEngine.Rendering.VirtualTexturing.Procedural.GetCPUCacheSize() end

--- Sets the Procedural Virtual Texturing GPU cache settings.
--- @param cacheSettings UnityEngine.Rendering.VirtualTexturing.GPUCacheSetting[] 
function UnityEngine.Rendering.VirtualTexturing.Procedural.SetGPUCacheSettings(cacheSettings) end

--- Gets the Procedural Virtual Texturing GPU cache settings.
--- @return UnityEngine.Rendering.VirtualTexturing.GPUCacheSetting[] An array of GPU cache settings.
function UnityEngine.Rendering.VirtualTexturing.Procedural.GetGPUCacheSettings() end

---  Generated By xerysherry