--- @class UnityEngine.ParticleSystemEmitterVelocityMode Control how a Particle System calculates its velocity.
UnityEngine.ParticleSystemEmitterVelocityMode = {
    --- Calculate the Particle System velocity by using the Transform component.
    Transform = 0,
    --- Calculate the Particle System velocity by using a Rigidbody or Rigidbody2D component, if one exists on the GameObject.
    Rigidbody = 1,
    --- When the Particle System calculates its velocity, it instead uses the custom value set in ParticleSystem.MainModule.emitterVelocity.
    Custom = 2,
}

---  Generated By xerysherry