--- @class Unity.Profiling.LowLevel.Unsafe.ProfilerCategoryDescription Provides information about Profiler category.
--- @field Name string property get
---       Gets Profiler category name as string.
--- @field Id number Profiler category identifier.
--- @field Flags number Profiler category flags.
--- @field Color UnityEngine.Color32 Profiler category color.
--- @field NameUtf8Len number Profiler category name length.
--- @field NameUtf8 System.Byte* Profiler category name pointer.
Unity.Profiling.LowLevel.Unsafe.ProfilerCategoryDescription = {}

---  Generated By xerysherry