--- @class UnityEngine.PhysicsJobOptions2D A set of options that control how physics operates when using the job system to multithread the physics simulation.
--- @field useMultithreading boolean property getset
---       Should physics simulation use multithreading?
--- @field useConsistencySorting boolean property getset
---       Should physics simulation sort multi-threaded results to maintain processing order consistency?
--- @field interpolationPosesPerJob number property getset
---       Controls the minimum number of Rigidbody2D being interpolated in each simulation job.
--- @field newContactsPerJob number property getset
---       Controls the minimum number of new contacts to find in each simulation job.
--- @field collideContactsPerJob number property getset
---       Controls the minimum number of contacts to collide in each simulation job.
--- @field clearFlagsPerJob number property getset
---       Controls the minimum number of flags to be cleared in each simulation job.
--- @field clearBodyForcesPerJob number property getset
---       Controls the minimum number of bodies to be cleared in each simulation job.
--- @field syncDiscreteFixturesPerJob number property getset
---       Controls the minimum number of fixtures to synchronize in the broadphase during discrete island solving in each simulation job.
--- @field syncContinuousFixturesPerJob number property getset
---       Controls the minimum number of fixtures to synchronize in the broadphase during continuous island solving in each simulation job.
--- @field findNearestContactsPerJob number property getset
---       Controls the minimum number of nearest contacts to find in each simulation job.
--- @field updateTriggerContactsPerJob number property getset
---       Controls the minimum number of trigger contacts to update in each simulation job.
--- @field islandSolverCostThreshold number property getset
---       The minimum threshold cost of all bodies, contacts and joints in an island during discrete island solving.
--- @field islandSolverBodyCostScale number property getset
---       Scales the cost of each body during discrete island solving.
--- @field islandSolverContactCostScale number property getset
---       Scales the cost of each contact during discrete island solving.
--- @field islandSolverJointCostScale number property getset
---       Scales the cost of each joint during discrete island solving.
--- @field islandSolverBodiesPerJob number property getset
---       Controls the minimum number of bodies to solve in each simulation job when performing island solving.
--- @field islandSolverContactsPerJob number property getset
---       Controls the minimum number of contacts to solve in each simulation job when performing island solving.
UnityEngine.PhysicsJobOptions2D = {}

function UnityEngine.PhysicsJobOptions2D:set_useMultithreading(value) end

function UnityEngine.PhysicsJobOptions2D:set_useConsistencySorting(value) end

function UnityEngine.PhysicsJobOptions2D:set_interpolationPosesPerJob(value) end

function UnityEngine.PhysicsJobOptions2D:set_newContactsPerJob(value) end

function UnityEngine.PhysicsJobOptions2D:set_collideContactsPerJob(value) end

function UnityEngine.PhysicsJobOptions2D:set_clearFlagsPerJob(value) end

function UnityEngine.PhysicsJobOptions2D:set_clearBodyForcesPerJob(value) end

function UnityEngine.PhysicsJobOptions2D:set_syncDiscreteFixturesPerJob(value) end

function UnityEngine.PhysicsJobOptions2D:set_syncContinuousFixturesPerJob(value) end

function UnityEngine.PhysicsJobOptions2D:set_findNearestContactsPerJob(value) end

function UnityEngine.PhysicsJobOptions2D:set_updateTriggerContactsPerJob(value) end

function UnityEngine.PhysicsJobOptions2D:set_islandSolverCostThreshold(value) end

function UnityEngine.PhysicsJobOptions2D:set_islandSolverBodyCostScale(value) end

function UnityEngine.PhysicsJobOptions2D:set_islandSolverContactCostScale(value) end

function UnityEngine.PhysicsJobOptions2D:set_islandSolverJointCostScale(value) end

function UnityEngine.PhysicsJobOptions2D:set_islandSolverBodiesPerJob(value) end

function UnityEngine.PhysicsJobOptions2D:set_islandSolverContactsPerJob(value) end

---  Generated By xerysherry