--- 
---  Describe an allowed child element for an element.
---  
--- @class UnityEngine.UIElements.UxmlChildElementDescription
--- @field elementName string property get
---       
---        The name of the allowed child element.
---        
--- @field elementNamespace string property get
---       
---        The namespace name of the allowed child element.
---        
UnityEngine.UIElements.UxmlChildElementDescription = {}

---  Generated By xerysherry