--- @class UnityEngine.SceneManagement.Scene Run-time data structure for *.unity file.
--- @field handle number
--- @field path string property get
---       Returns the relative path of the Scene. Like: "AssetsMyScenesMyScene.unity".
--- @field name string property getset
---       Returns the name of the Scene that is currently active in the game or app.
--- @field isLoaded boolean property get
---       Returns true if the Scene is loaded.
--- @field buildIndex number property get
---       Return the index of the Scene in the Build Settings.
--- @field isDirty boolean property get
---       Returns true if the Scene is modifed.
--- @field rootCount number property get
---       The number of root transforms of this Scene.
--- @field isSubScene boolean
UnityEngine.SceneManagement.Scene = {}

--- @param lhs UnityEngine.SceneManagement.Scene 
--- @param rhs UnityEngine.SceneManagement.Scene 
--- @return boolean
function UnityEngine.SceneManagement.Scene.op_Equality(lhs, rhs) end

--- @param lhs UnityEngine.SceneManagement.Scene 
--- @param rhs UnityEngine.SceneManagement.Scene 
--- @return boolean
function UnityEngine.SceneManagement.Scene.op_Inequality(lhs, rhs) end

--- Whether this is a valid Scene.
--- A Scene may be invalid if, for example, you tried to open a Scene that does not exist. In this case, the Scene returned from EditorSceneManager.OpenScene would return False for IsValid.
--- @return boolean Whether this is a valid Scene.
function UnityEngine.SceneManagement.Scene:IsValid() end

--- @param value string 
function UnityEngine.SceneManagement.Scene:set_name(value) end

--- @param value boolean 
function UnityEngine.SceneManagement.Scene:set_isSubScene(value) end

--- Returns all the root game objects in the Scene.
--- @return UnityEngine.GameObject[] An array of game objects.
function UnityEngine.SceneManagement.Scene:GetRootGameObjects() end

--- Returns all the root game objects in the Scene.
--- @param rootGameObjects UnityEngine.GameObject[] A list which is used to return the root game objects.
function UnityEngine.SceneManagement.Scene:GetRootGameObjects(rootGameObjects) end

--- @return number
function UnityEngine.SceneManagement.Scene:GetHashCode() end

--- @param other System.Object 
--- @return boolean
function UnityEngine.SceneManagement.Scene:Equals(other) end

---  Generated By xerysherry