--- @class UnityEngine.Animations.PropertySceneHandle Handle to read a Component property on an object in the Scene.
UnityEngine.Animations.PropertySceneHandle = {}

--- Returns whether or not the handle is valid.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream managing this handle.
--- @return boolean Whether or not the handle is valid.
function UnityEngine.Animations.PropertySceneHandle:IsValid(stream) end

--- Resolves the handle.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream managing this handle.
function UnityEngine.Animations.PropertySceneHandle:Resolve(stream) end

--- Returns whether or not the handle is resolved.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream managing this handle.
--- @return boolean Returns true if the handle is resolved, false otherwise.
function UnityEngine.Animations.PropertySceneHandle:IsResolved(stream) end

--- Gets the float property value from an object in the Scene.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream managing this handle.
--- @return number The float property value.
function UnityEngine.Animations.PropertySceneHandle:GetFloat(stream) end

--- Sets the float property value to an object in the Scene.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream managing this handle.
--- @param value number The new float property value.
function UnityEngine.Animations.PropertySceneHandle:SetFloat(stream, value) end

--- Gets the integer property value from an object in the Scene.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream managing this handle.
--- @return number The integer property value.
function UnityEngine.Animations.PropertySceneHandle:GetInt(stream) end

--- Sets the integer property value to an object in the Scene.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream managing this handle.
--- @param value number The new integer property value.
function UnityEngine.Animations.PropertySceneHandle:SetInt(stream, value) end

--- Gets the boolean property value from an object in the Scene.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream managing this handle.
--- @return boolean The boolean property value.
function UnityEngine.Animations.PropertySceneHandle:GetBool(stream) end

--- Sets the boolean property value to an object in the Scene.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream managing this handle.
--- @param value boolean The new boolean property value.
function UnityEngine.Animations.PropertySceneHandle:SetBool(stream, value) end

---  Generated By xerysherry