--- 
---  Used by manipulators to match events against their requirements.
---  
--- @class UnityEngine.UIElements.ManipulatorActivationFilter
--- @field button UnityEngine.UIElements.MouseButton property getset
---       
---        The button that activates the manipulation.
---        
--- @field modifiers UnityEngine.EventModifiers property getset
---       
---        Any modifier keys (ie. ctrl, alt, ...) that are needed to activate the manipulation.
---        
--- @field clickCount number property getset
---       
---        Number of mouse clicks required to activate the manipulator.
---        
UnityEngine.UIElements.ManipulatorActivationFilter = {}

--- @param filter1 UnityEngine.UIElements.ManipulatorActivationFilter 
--- @param filter2 UnityEngine.UIElements.ManipulatorActivationFilter 
--- @return boolean
function UnityEngine.UIElements.ManipulatorActivationFilter.op_Equality(filter1, filter2) end

--- @param filter1 UnityEngine.UIElements.ManipulatorActivationFilter 
--- @param filter2 UnityEngine.UIElements.ManipulatorActivationFilter 
--- @return boolean
function UnityEngine.UIElements.ManipulatorActivationFilter.op_Inequality(filter1, filter2) end

--- @param value UnityEngine.UIElements.MouseButton 
function UnityEngine.UIElements.ManipulatorActivationFilter:set_button(value) end

--- @param value UnityEngine.EventModifiers 
function UnityEngine.UIElements.ManipulatorActivationFilter:set_modifiers(value) end

--- @param value number 
function UnityEngine.UIElements.ManipulatorActivationFilter:set_clickCount(value) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.UIElements.ManipulatorActivationFilter:Equals(obj) end

--- @param other UnityEngine.UIElements.ManipulatorActivationFilter 
--- @return boolean
function UnityEngine.UIElements.ManipulatorActivationFilter:Equals(other) end

--- @return number
function UnityEngine.UIElements.ManipulatorActivationFilter:GetHashCode() end

--- 
---  Checks whether the current mouse event satisfies the activation requirements.
---  
--- @param e UnityEngine.UIElements.IMouseEvent The mouse event.
--- @return boolean True if the event matches the requirements. False otherwise.
function UnityEngine.UIElements.ManipulatorActivationFilter:Matches(e) end

--- 
---  Checks whether the current mouse event satisfies the activation requirements.
---  
--- @param e UnityEngine.UIElements.IPointerEvent The mouse event.
--- @return boolean True if the event matches the requirements. False otherwise.
function UnityEngine.UIElements.ManipulatorActivationFilter:Matches(e) end

---  Generated By xerysherry