--- @class UnityEngine.HideInInspector:System.Attribute Makes a variable not show up in the inspector but be serialized.
--- @field TypeId System.Object
UnityEngine.HideInInspector = {}

---  Generated By xerysherry