--- @class UnityEngine.Windows.WebCam.VideoCapture.CaptureResultType Contains the result of the capture request.
UnityEngine.Windows.WebCam.VideoCapture.CaptureResultType = {
    --- Specifies that the desired operation was successful.
    Success = 0,
    --- Specifies that an unknown error occurred.
    UnknownError = 1,
}

--- @class UnityEngine.Windows.WebCam.VideoCapture.CaptureResultType Contains the result of the capture request.
UnityEngine.Windows.WebCam.VideoCapture.CaptureResultType = {
    --- Specifies that the desired operation was successful.
    Success = 0,
    --- Specifies that an unknown error occurred.
    UnknownError = 1,
}

---  Generated By xerysherry