--- @class UnityEngine.Experimental.Rendering.FormatUsage Use this format usages to figure out the capabilities of specific GraphicsFormat
UnityEngine.Experimental.Rendering.FormatUsage = {
    --- Use this to create and sample textures.
    Sample = 0,
    --- Use this to sample textures with a linear filter
    Linear = 1,
    --- Use this to create sparse textures
    Sparse = 2,
    --- Use this to create and render to a rendertexture.
    Render = 4,
    --- Use this to blend on a rendertexture.
    Blend = 5,
    --- Use this to get pixel data from a texture.
    GetPixels = 6,
    --- Use this to set pixel data to a texture.
    SetPixels = 7,
    --- Use this to set pixel data to a texture using `SetPixels32`.
    SetPixels32 = 8,
    --- Use this to read back pixels data from a rendertexture.
    ReadPixels = 9,
    --- Use this to perform resource load and store on a texture
    LoadStore = 10,
    --- Use this to create and render to a MSAA 2X rendertexture.
    MSAA2x = 11,
    --- Use this to create and render to a MSAA 4X rendertexture.
    MSAA4x = 12,
    --- Use this to create and render to a MSAA 8X rendertexture.
    MSAA8x = 13,
    --- Use this enumeration to create and render to the Stencil sub element of a RenderTexture.
    StencilSampling = 16,
}

---  Generated By xerysherry