--- 
---  Provides rotation information for visual elements that rotates around the TransformOrigin. Positive values represent clockwise rotation.
---  
--- @class UnityEngine.UIElements.Rotate
--- @field angle UnityEngine.UIElements.Angle property getset
---       
---        The angle applied by the rotation. Positive values represent clockwise rotation and negative values represent counterclockwise rotation.
---        
UnityEngine.UIElements.Rotate = {}

--- 
---  Return a value of Rotate that applies no rotation
---  
--- @return UnityEngine.UIElements.Rotate 
function UnityEngine.UIElements.Rotate.None() end

--- @param lhs UnityEngine.UIElements.Rotate 
--- @param rhs UnityEngine.UIElements.Rotate 
--- @return boolean
function UnityEngine.UIElements.Rotate.op_Equality(lhs, rhs) end

--- @param lhs UnityEngine.UIElements.Rotate 
--- @param rhs UnityEngine.UIElements.Rotate 
--- @return boolean
function UnityEngine.UIElements.Rotate.op_Inequality(lhs, rhs) end

--- @param value UnityEngine.UIElements.Angle 
function UnityEngine.UIElements.Rotate:set_angle(value) end

--- @param other UnityEngine.UIElements.Rotate 
--- @return boolean
function UnityEngine.UIElements.Rotate:Equals(other) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.UIElements.Rotate:Equals(obj) end

--- @return number
function UnityEngine.UIElements.Rotate:GetHashCode() end

--- @return string
function UnityEngine.UIElements.Rotate:ToString() end

---  Generated By xerysherry