--- @class UnityEngine.WebCamTexture:UnityEngine.Texture WebCam Textures are textures onto which the live video input is rendered.
--- @field devices UnityEngine.WebCamDevice[] property get
---       Return a list of available devices.
--- @field isPlaying boolean property get
---       Returns if the camera is currently playing.
--- @field deviceName string property getset
---       Set this to specify the name of the device to use.
--- @field requestedFPS number property getset
---       Set the requested frame rate of the camera device (in frames per second).
--- @field requestedWidth number property getset
---       Set the requested width of the camera device.
--- @field requestedHeight number property getset
---       Set the requested height of the camera device.
--- @field videoRotationAngle number property get
---       Returns an clockwise angle (in degrees), which can be used to rotate a polygon so camera contents are shown in correct orientation.
--- @field videoVerticallyMirrored boolean property get
---       Returns if the texture image is vertically flipped.
--- @field didUpdateThisFrame boolean property get
---       Did the video buffer update this frame?
--- @field autoFocusPoint System.Nullable`1 property getset
---       This property allows you to set/get the auto focus point of the camera. This works only on Android and iOS devices.
--- @field isDepth boolean property get
---       This property is true if the texture is based on depth data.
--- @field mipmapCount number
--- @field graphicsFormat UnityEngine.Experimental.Rendering.GraphicsFormat
--- @field width number
--- @field height number
--- @field dimension UnityEngine.Rendering.TextureDimension
--- @field isReadable boolean
--- @field wrapMode UnityEngine.TextureWrapMode
--- @field wrapModeU UnityEngine.TextureWrapMode
--- @field wrapModeV UnityEngine.TextureWrapMode
--- @field wrapModeW UnityEngine.TextureWrapMode
--- @field filterMode UnityEngine.FilterMode
--- @field anisoLevel number
--- @field mipMapBias number
--- @field texelSize UnityEngine.Vector2
--- @field updateCount number
--- @field imageContentsHash UnityEngine.Hash128
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.WebCamTexture = {}

--- Starts the camera.
function UnityEngine.WebCamTexture:Play() end

--- Pauses the camera.
function UnityEngine.WebCamTexture:Pause() end

--- Stops the camera.
function UnityEngine.WebCamTexture:Stop() end

--- @param value string 
function UnityEngine.WebCamTexture:set_deviceName(value) end

--- @param value number 
function UnityEngine.WebCamTexture:set_requestedFPS(value) end

--- @param value number 
function UnityEngine.WebCamTexture:set_requestedWidth(value) end

--- @param value number 
function UnityEngine.WebCamTexture:set_requestedHeight(value) end

--- Returns pixel color at coordinates (x, y).
--- @param x number X coordinate of the pixel to get.
--- @param y number Y coordinate of the pixel to get.
--- @return UnityEngine.Color Pixel color at the requested coordinate.
function UnityEngine.WebCamTexture:GetPixel(x, y) end

--- Retrieves a copy of the the pixel color data. The colors are represented by Color structs.
--- @return UnityEngine.Color[] An array that contains a copy of the requested pixel colors, represented by Color structs.
function UnityEngine.WebCamTexture:GetPixels() end

--- Get a block of pixel colors.
--- @param x number X coordinate of the block origin.
--- @param y number Y coordinate of the block origin.
--- @param blockWidth number Width of the block.
--- @param blockHeight number Height of the block.
--- @return UnityEngine.Color[] Copy of the block of pixels requested.
function UnityEngine.WebCamTexture:GetPixels(x, y, blockWidth, blockHeight) end

--- Retrieves a copy of the the pixel color data. The colors are represented by Color32 structs.
--- @return UnityEngine.Color32[] An array that contains a copy of the requested pixel colors, represented by Color32 structs.
function UnityEngine.WebCamTexture:GetPixels32() end

--- Retrieves a copy of the the pixel color data. The colors are represented by Color32 structs.
--- @param colors UnityEngine.Color32[] Optional array to receive pixel data.
--- @return UnityEngine.Color32[] An array that contains a copy of the requested pixel colors, represented by Color32 structs.
function UnityEngine.WebCamTexture:GetPixels32(colors) end

--- @param value System.Nullable`1 
function UnityEngine.WebCamTexture:set_autoFocusPoint(value) end

---  Generated By xerysherry