--- @class UnityEngine.ModifiableMassProperties Mass-related modifiable properties of a contact pair.
--- @field inverseMassScale number The inverse mass scaling that the solver should apply to the first body of this contact pair.
--- @field inverseInertiaScale number The inverse inertia scaling that the solver should apply to the first body of this contact pair.
--- @field otherInverseMassScale number The inverse mass scaling that the solver should apply to the second body of this contact pair.
--- @field otherInverseInertiaScale number The inverse inertia scaling that the solver should apply to the second body of this contact pair.
UnityEngine.ModifiableMassProperties = {}

---  Generated By xerysherry