--- @class UnityEngine.ParticleSystemMeshShapeType The mesh emission type.
UnityEngine.ParticleSystemMeshShapeType = {
    --- Emit from the vertices of the mesh.
    Vertex = 0,
    --- Emit from the edges of the mesh.
    Edge = 1,
    --- Emit from the surface of the mesh.
    Triangle = 2,
}

---  Generated By xerysherry