--- @class UnityEngine.Rendering.ShaderKeyword Represents an identifier for a specific code path in a shader.
--- @field name string property get
---       The name of the shader keyword. (Read Only)
--- @field index number property get
---       The index of the shader keyword.
UnityEngine.Rendering.ShaderKeyword = {}

--- Returns the type of global keyword: built-in or user defined.
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return UnityEngine.Rendering.ShaderKeywordType 
function UnityEngine.Rendering.ShaderKeyword.GetGlobalKeywordType(index) end

--- Returns true if the keyword is local.
--- @param keyword UnityEngine.Rendering.ShaderKeyword 
--- @return boolean 
function UnityEngine.Rendering.ShaderKeyword.IsKeywordLocal(keyword) end

--- Gets the type of the keyword.
--- @param shader UnityEngine.Shader 
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return UnityEngine.Rendering.ShaderKeywordType 
function UnityEngine.Rendering.ShaderKeyword.GetKeywordType(shader, index) end

--- Gets the type of the keyword.
--- @param shader UnityEngine.ComputeShader 
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return UnityEngine.Rendering.ShaderKeywordType 
function UnityEngine.Rendering.ShaderKeyword.GetKeywordType(shader, index) end

--- Gets the string name of the global keyword.
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return string 
function UnityEngine.Rendering.ShaderKeyword.GetGlobalKeywordName(index) end

--- Gets the string name of the keyword.
--- @param shader UnityEngine.Shader 
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return string 
function UnityEngine.Rendering.ShaderKeyword.GetKeywordName(shader, index) end

--- Gets the string name of the keyword.
--- @param shader UnityEngine.ComputeShader 
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return string 
function UnityEngine.Rendering.ShaderKeyword.GetKeywordName(shader, index) end

--- Checks whether the global shader keyword exists.
--- @return boolean Returns true if the global shader keyword exists. Otherwise, returns false.
function UnityEngine.Rendering.ShaderKeyword:IsValid() end

--- Checks whether the shader keyword exists in the compute shader you pass in.
--- @param shader UnityEngine.ComputeShader The shader that declares the keyword.
--- @return boolean Returns true if the shader keyword exists. Otherwise, returns false.
function UnityEngine.Rendering.ShaderKeyword:IsValid(shader) end

--- Checks whether the shader keyword exists in the compute shader you pass in.
--- @param shader UnityEngine.Shader The shader that declares the keyword.
--- @return boolean Returns true if the shader keyword exists. Otherwise, returns false.
function UnityEngine.Rendering.ShaderKeyword:IsValid(shader) end

--- @return string
function UnityEngine.Rendering.ShaderKeyword:ToString() end

--- Gets the type of the keyword.
--- @return UnityEngine.Rendering.ShaderKeywordType 
function UnityEngine.Rendering.ShaderKeyword:GetKeywordType() end

--- Gets the string name of the keyword.
--- @return string 
function UnityEngine.Rendering.ShaderKeyword:GetKeywordName() end

--- @return string
function UnityEngine.Rendering.ShaderKeyword:GetName() end

---  Generated By xerysherry