--- @class UnityEngine.NVIDIA.DLSSCommandInitializationData Represent the initialization state of a DLSSContext. You can only use and set this when calling GraphicsDevice.CreateFeature.
--- @field inputRTWidth number property getset
---       The texture input width size of the input buffers in texels.
--- @field inputRTHeight number property getset
---       The texture input height size of the input buffers in texels.
--- @field outputRTWidth number property getset
---       The output buffer width size in texels to upscale to.
--- @field outputRTHeight number property getset
---       The output buffer height size in texels to upscale to.
--- @field quality UnityEngine.NVIDIA.DLSSQuality property getset
---       The quality property for DLSS.
--- @field featureFlags UnityEngine.NVIDIA.DLSSFeatureFlags property getset
---       Bit mask containing feature flags to be used for DLSS.
UnityEngine.NVIDIA.DLSSCommandInitializationData = {}

--- @param value number 
function UnityEngine.NVIDIA.DLSSCommandInitializationData:set_inputRTWidth(value) end

--- @param value number 
function UnityEngine.NVIDIA.DLSSCommandInitializationData:set_inputRTHeight(value) end

--- @param value number 
function UnityEngine.NVIDIA.DLSSCommandInitializationData:set_outputRTWidth(value) end

--- @param value number 
function UnityEngine.NVIDIA.DLSSCommandInitializationData:set_outputRTHeight(value) end

--- @param value UnityEngine.NVIDIA.DLSSQuality 
function UnityEngine.NVIDIA.DLSSCommandInitializationData:set_quality(value) end

--- @param value UnityEngine.NVIDIA.DLSSFeatureFlags 
function UnityEngine.NVIDIA.DLSSCommandInitializationData:set_featureFlags(value) end

--- Helper function. Controls the feature flags used by DLSS. See Also: NVIDIA.DLSSFeatureFlags.
--- @param flag UnityEngine.NVIDIA.DLSSFeatureFlags The feature flag to set or unset.
--- @param value boolean Indicates whether to set or unset the flag.
function UnityEngine.NVIDIA.DLSSCommandInitializationData:SetFlag(flag, value) end

--- Helper function. Gets weither if a DLSS feature is set or unset. See Also: NVIDIA.DLSSFeatureFlags.
--- @param flag UnityEngine.NVIDIA.DLSSFeatureFlags The feature flag to get the state from.
--- @return boolean Indicates whether the feautre state is set or unset.
function UnityEngine.NVIDIA.DLSSCommandInitializationData:GetFlag(flag) end

---  Generated By xerysherry