--- @class UnityEngine.RenderParams Rendering parameters used by various rendering functions.
--- @field layer number property getset
---       Layer used for rendering. to use.
--- @field renderingLayerMask number property getset
---       Renderer layer mask used for rendering.
--- @field rendererPriority number property getset
---       Renderer priority.
--- @field worldBounds UnityEngine.Bounds property getset
---       Defines world space bounds for the geometry. Used to cull and sort the rendered geometry.
--- @field camera UnityEngine.Camera property getset
---       The camera used for rendering. If set to null (default) renders for all cameras.
--- @field motionVectorMode UnityEngine.MotionVectorGenerationMode property getset
---       Motion vector mode used for rendering.
--- @field reflectionProbeUsage UnityEngine.Rendering.ReflectionProbeUsage property getset
---       The type of reflection probe used for rendering.
--- @field material UnityEngine.Material property getset
---       Material used for rendering.
--- @field matProps UnityEngine.MaterialPropertyBlock property getset
---       Material properties used for rendering.
--- @field shadowCastingMode UnityEngine.Rendering.ShadowCastingMode property getset
---       Describes if geometry should cast shadows.
--- @field receiveShadows boolean property getset
---       Descripes if the rendered geometry should receive shadows.
--- @field lightProbeUsage UnityEngine.Rendering.LightProbeUsage property getset
---       The type of light probe usage.
--- @field lightProbeProxyVolume UnityEngine.LightProbeProxyVolume property getset
---       Light Probe Proxy Volume (LPPV) used for rendering.
UnityEngine.RenderParams = {}

function UnityEngine.RenderParams:set_layer(value) end

function UnityEngine.RenderParams:set_renderingLayerMask(value) end

function UnityEngine.RenderParams:set_rendererPriority(value) end

function UnityEngine.RenderParams:set_worldBounds(value) end

function UnityEngine.RenderParams:set_camera(value) end

function UnityEngine.RenderParams:set_motionVectorMode(value) end

function UnityEngine.RenderParams:set_reflectionProbeUsage(value) end

function UnityEngine.RenderParams:set_material(value) end

function UnityEngine.RenderParams:set_matProps(value) end

function UnityEngine.RenderParams:set_shadowCastingMode(value) end

function UnityEngine.RenderParams:set_receiveShadows(value) end

function UnityEngine.RenderParams:set_lightProbeUsage(value) end

function UnityEngine.RenderParams:set_lightProbeProxyVolume(value) end

---  Generated By xerysherry