--- @class UnityEngine.UIElements.PanelEventHandler:UnityEngine.EventSystems.UIBehaviour 
--- @field panel UnityEngine.UIElements.IPanel
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UIElements.PanelEventHandler = {}

function UnityEngine.UIElements.PanelEventHandler:set_panel(value) end

function UnityEngine.UIElements.PanelEventHandler:OnSelect(eventData) end

function UnityEngine.UIElements.PanelEventHandler:OnDeselect(eventData) end

function UnityEngine.UIElements.PanelEventHandler:OnPointerMove(eventData) end

function UnityEngine.UIElements.PanelEventHandler:OnPointerUp(eventData) end

function UnityEngine.UIElements.PanelEventHandler:OnPointerDown(eventData) end

function UnityEngine.UIElements.PanelEventHandler:OnSubmit(eventData) end

function UnityEngine.UIElements.PanelEventHandler:OnCancel(eventData) end

function UnityEngine.UIElements.PanelEventHandler:OnMove(eventData) end

function UnityEngine.UIElements.PanelEventHandler:OnScroll(eventData) end

---  Generated By xerysherry