--- @class UnityEngine.Rendering.BatchVisibility Describes the visibility for a batch.
--- @field offset number Input property specifying the offset into the BatchCullingContext.visibleIndices where the batch's visibile indices start. (readonly).
--- @field instancesCount number Input property specifying the total number of instances in the batch. (readonly).
--- @field visibleCount number Output property that has to be set to the number of visible instances in the batch after culling.
UnityEngine.Rendering.BatchVisibility = {}

---  Generated By xerysherry