--- @class UnityEngine.Windows.Input Provides static methods for Windows specific input manipulation.
UnityEngine.Windows.Input = {}

--- Forwards raw input events to Unity.
--- @param rawInputHeaderIndices System.IntPtr Pointer to array of indices that specify the byte offsets of RAWINPUTHEADER structures in rawInputData.
--- @param rawInputDataIndices System.IntPtr Pointer to array of indices that specify the byte offsets of RAWINPUT::data field in rawInputData.
--- @param indicesCount number Number of RAWINPUT events.
--- @param rawInputData System.IntPtr Pointer to byte array containing RAWINPUT events.
--- @param rawInputDataSize number RawInputData array size in bytes.
function UnityEngine.Windows.Input.ForwardRawInput(rawInputHeaderIndices, rawInputDataIndices, indicesCount, rawInputData, rawInputDataSize) end

--- Forwards raw input events to Unity.
--- @param rawInputHeaderIndices System.UInt32* Pointer to array of indices that specify the byte offsets of RAWINPUTHEADER structures in rawInputData.
--- @param rawInputDataIndices System.UInt32* Pointer to array of indices that specify the byte offsets of RAWINPUT::data field in rawInputData.
--- @param indicesCount number Number of RAWINPUT events.
--- @param rawInputData System.Byte* Pointer to byte array containing RAWINPUT events.
--- @param rawInputDataSize number RawInputData array size in bytes.
function UnityEngine.Windows.Input.ForwardRawInput(rawInputHeaderIndices, rawInputDataIndices, indicesCount, rawInputData, rawInputDataSize) end

---  Generated By xerysherry