--- @class UnityEngine.MeshRenderer:UnityEngine.Renderer Renders meshes inserted by the MeshFilter or TextMesh.
--- @field additionalVertexStreams UnityEngine.Mesh property getset
---       Vertex attributes in this mesh will override or add attributes of the primary mesh in the MeshRenderer.
--- @field enlightenVertexStream UnityEngine.Mesh property getset
---       Vertex attributes in this mesh will override or add attributes of the primary mesh and the additionalVertexStreams in the MeshRenderer.
--- @field subMeshStartIndex number property get
---       Index of the first sub-mesh to use from the Mesh associated with this MeshRenderer (Read Only).
--- @field scaleInLightmap number property getset
---       Specifies the relative lightmap resolution of this object. (Editor only)
--- @field receiveGI UnityEngine.ReceiveGI property getset
---       Determines how the object will receive global illumination. (Editor only)
--- @field stitchLightmapSeams boolean property getset
---       When enabled, seams in baked lightmaps will get smoothed. (Editor only)
--- @field lightmapTilingOffset UnityEngine.Vector4
--- @field lightProbeAnchor UnityEngine.Transform
--- @field castShadows boolean
--- @field motionVectors boolean
--- @field useLightProbes boolean
--- @field bounds UnityEngine.Bounds
--- @field localBounds UnityEngine.Bounds
--- @field enabled boolean
--- @field isVisible boolean
--- @field shadowCastingMode UnityEngine.Rendering.ShadowCastingMode
--- @field receiveShadows boolean
--- @field forceRenderingOff boolean
--- @field staticShadowCaster boolean
--- @field motionVectorGenerationMode UnityEngine.MotionVectorGenerationMode
--- @field lightProbeUsage UnityEngine.Rendering.LightProbeUsage
--- @field reflectionProbeUsage UnityEngine.Rendering.ReflectionProbeUsage
--- @field renderingLayerMask number
--- @field rendererPriority number
--- @field rayTracingMode UnityEngine.Experimental.Rendering.RayTracingMode
--- @field sortingLayerName string
--- @field sortingLayerID number
--- @field sortingOrder number
--- @field allowOcclusionWhenDynamic boolean
--- @field isPartOfStaticBatch boolean
--- @field worldToLocalMatrix UnityEngine.Matrix4x4
--- @field localToWorldMatrix UnityEngine.Matrix4x4
--- @field lightProbeProxyVolumeOverride UnityEngine.GameObject
--- @field probeAnchor UnityEngine.Transform
--- @field lightmapIndex number
--- @field realtimeLightmapIndex number
--- @field lightmapScaleOffset UnityEngine.Vector4
--- @field realtimeLightmapScaleOffset UnityEngine.Vector4
--- @field materials UnityEngine.Material[]
--- @field material UnityEngine.Material
--- @field sharedMaterial UnityEngine.Material
--- @field sharedMaterials UnityEngine.Material[]
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.MeshRenderer = {}

--- @param value UnityEngine.Mesh 
function UnityEngine.MeshRenderer:set_additionalVertexStreams(value) end

--- @param value UnityEngine.Mesh 
function UnityEngine.MeshRenderer:set_enlightenVertexStream(value) end

--- @param value number 
function UnityEngine.MeshRenderer:set_scaleInLightmap(value) end

--- @param value UnityEngine.ReceiveGI 
function UnityEngine.MeshRenderer:set_receiveGI(value) end

--- @param value boolean 
function UnityEngine.MeshRenderer:set_stitchLightmapSeams(value) end

---  Generated By xerysherry