UnityEngine.UI.AspectRatioFitter.AspectMode = {
    None = 0,
    WidthControlsHeight = 1,
    HeightControlsWidth = 2,
    FitInParent = 3,
    EnvelopeParent = 4,
}

UnityEngine.UI.AspectRatioFitter.AspectMode = {
    None = 0,
    WidthControlsHeight = 1,
    HeightControlsWidth = 2,
    FitInParent = 3,
    EnvelopeParent = 4,
}

---  Generated By xerysherry