--- 
---  Describes a MouseButton.
---  
--- @class UnityEngine.UIElements.MouseButton
UnityEngine.UIElements.MouseButton = {
    --- 
    ---  The Left Mouse Button.
    ---  
    LeftMouse = 0,
    --- 
    ---  The Right Mouse Button.
    ---  
    RightMouse = 1,
    --- 
    ---  The Middle Mouse Button.
    ---  
    MiddleMouse = 2,
}

---  Generated By xerysherry