--- @class UnityEngine.BitStream The BitStream class represents seralized variables, packed into a stream.
--- @field isReading boolean property get
---       Is the BitStream currently being read? (Read Only)
--- @field isWriting boolean property get
---       Is the BitStream currently being written? (Read Only)
UnityEngine.BitStream = {}

--- Serializes different types of variables.
--- @param value System.Boolean& 
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
--- @param value System.Char& 
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
--- @param value System.Int16& 
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
--- @param value System.Int32& 
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
--- @param value System.Single& 
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
--- @param value System.Single& 
--- @param maxDelta number 
function UnityEngine.BitStream:Serialize(value, maxDelta) end

--- Serializes different types of variables.
--- @param value UnityEngine.Quaternion& 
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
--- @param value UnityEngine.Quaternion& 
--- @param maxDelta number 
function UnityEngine.BitStream:Serialize(value, maxDelta) end

--- Serializes different types of variables.
--- @param value UnityEngine.Vector3& 
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
--- @param value UnityEngine.Vector3& 
--- @param maxDelta number 
function UnityEngine.BitStream:Serialize(value, maxDelta) end

--- Serializes different types of variables.
--- @param value UnityEngine.NetworkPlayer& 
function UnityEngine.BitStream:Serialize(value) end

--- Serializes different types of variables.
--- @param viewID UnityEngine.NetworkViewID& 
function UnityEngine.BitStream:Serialize(viewID) end

---  Generated By xerysherry