--- @class UnityEngine.UI.FontData 
--- @field defaultFontData UnityEngine.UI.FontData
--- @field font UnityEngine.Font
--- @field fontSize number
--- @field fontStyle UnityEngine.FontStyle
--- @field bestFit boolean
--- @field minSize number
--- @field maxSize number
--- @field alignment UnityEngine.TextAnchor
--- @field alignByGeometry boolean
--- @field richText boolean
--- @field horizontalOverflow UnityEngine.HorizontalWrapMode
--- @field verticalOverflow UnityEngine.VerticalWrapMode
--- @field lineSpacing number
UnityEngine.UI.FontData = {}

--- @param value UnityEngine.Font 
function UnityEngine.UI.FontData:set_font(value) end

--- @param value number 
function UnityEngine.UI.FontData:set_fontSize(value) end

--- @param value UnityEngine.FontStyle 
function UnityEngine.UI.FontData:set_fontStyle(value) end

--- @param value boolean 
function UnityEngine.UI.FontData:set_bestFit(value) end

--- @param value number 
function UnityEngine.UI.FontData:set_minSize(value) end

--- @param value number 
function UnityEngine.UI.FontData:set_maxSize(value) end

--- @param value UnityEngine.TextAnchor 
function UnityEngine.UI.FontData:set_alignment(value) end

--- @param value boolean 
function UnityEngine.UI.FontData:set_alignByGeometry(value) end

--- @param value boolean 
function UnityEngine.UI.FontData:set_richText(value) end

--- @param value UnityEngine.HorizontalWrapMode 
function UnityEngine.UI.FontData:set_horizontalOverflow(value) end

--- @param value UnityEngine.VerticalWrapMode 
function UnityEngine.UI.FontData:set_verticalOverflow(value) end

--- @param value number 
function UnityEngine.UI.FontData:set_lineSpacing(value) end

---  Generated By xerysherry