--- @class UnityEngine.StaticBatchingUtility StaticBatchingUtility can prepare your objects to take advantage of Unity's static batching.
UnityEngine.StaticBatchingUtility = {}

--- Combines all children GameObjects of the staticBatchRoot for static batching.
--- @param staticBatchRoot UnityEngine.GameObject The GameObject that should become the root of the combined batch.
function UnityEngine.StaticBatchingUtility.Combine(staticBatchRoot) end

--- SCombines all GameObjects in gos for static batching and treats staticBatchRoot as the root.
--- @param gos UnityEngine.GameObject[] The GameObjects to prepare for static batching.
--- @param staticBatchRoot UnityEngine.GameObject The GameObject that should become the root of the combined batch.
function UnityEngine.StaticBatchingUtility.Combine(gos, staticBatchRoot) end

---  Generated By xerysherry