--- @class UnityEngine.WSA.Cursor Cursor API for Windows Store Apps.
UnityEngine.WSA.Cursor = {}

--- Set a custom cursor.
--- @param id number The cursor resource id.
function UnityEngine.WSA.Cursor.SetCustomCursor(id) end

---  Generated By xerysherry