--- @class UnityEngine.JsonUtility Utility functions for working with JSON data.
UnityEngine.JsonUtility = {}

--- Generate a JSON representation of the public fields of an object.
--- @return string The object's data in JSON format.
function UnityEngine.JsonUtility.ToJson(obj) end

--- Generate a JSON representation of the public fields of an object.
--- @param obj System.Object The object to convert to JSON form.
--- @param prettyPrint boolean If true, format the output for readability. If false, format the output for minimum size. Default is false.
--- @return string The object's data in JSON format.
function UnityEngine.JsonUtility.ToJson(obj, prettyPrint) end

--- Create an object from its JSON representation.
--- @param json string The JSON representation of the object.
--- @return UnityEngine.JsonUtility.T An instance of the object.
function UnityEngine.JsonUtility.FromJson(json) end

--- Create an object from its JSON representation.
--- @param json string The JSON representation of the object.
--- @param type System.Type The type of object represented by the Json.
--- @return System.Object An instance of the object.
function UnityEngine.JsonUtility.FromJson(json, type) end

--- Overwrite data in an object by reading from its JSON representation.
--- @param json string The JSON representation of the object.
--- @param objectToOverwrite System.Object The object that should be overwritten.
function UnityEngine.JsonUtility.FromJsonOverwrite(json, objectToOverwrite) end

---  Generated By xerysherry