--- @class UnityEngine.DynamicGI Allows to control the dynamic Global Illumination.
--- @field indirectScale number property getset
---       Allows for scaling the contribution coming from real-time & baked lightmaps.
---       
---       Note: this value can be set in the Lighting Window UI and it is serialized, that is not the case for other properties in this class.
--- @field updateThreshold number property getset
---       Threshold for limiting updates of Enlighten Realtime Global Illumination. The unit of measurement is "percentage intensity change".
--- @field materialUpdateTimeSlice number property getset
---       The number of milliseconds that can be spent on material updates.
--- @field synchronousMode boolean property getset
---       When enabled, new dynamic Global Illumination output is shown in each frame.
--- @field isConverged boolean property get
---       Is precomputed Enlighten Realtime Global Illumination output converged?
UnityEngine.DynamicGI = {}

--- @param value number 
function UnityEngine.DynamicGI.set_indirectScale(value) end

--- @param value number 
function UnityEngine.DynamicGI.set_updateThreshold(value) end

--- @param value number 
function UnityEngine.DynamicGI.set_materialUpdateTimeSlice(value) end

--- Allows to set an emissive color for a given renderer quickly, without the need to render the emissive input for the entire system.
--- @param renderer UnityEngine.Renderer The Renderer that should get a new color.
--- @param color UnityEngine.Color The emissive Color.
function UnityEngine.DynamicGI.SetEmissive(renderer, color) end

--- Allows overriding the distant environment lighting for Enlighten Realtime Global Illumination, without changing the Skybox Material.
--- @param input number[] Array of float values to be used for Enlighten Realtime Global Illumination environment lighting.
function UnityEngine.DynamicGI.SetEnvironmentData(input) end

--- @param value boolean 
function UnityEngine.DynamicGI.set_synchronousMode(value) end

--- Schedules an update of the environment cubemap.
function UnityEngine.DynamicGI.UpdateEnvironment() end

--- Schedules an update of the albedo and emissive textures of a system that contains the renderer or the terrain.
--- @param renderer UnityEngine.Renderer 
function UnityEngine.DynamicGI.UpdateMaterials(renderer) end

--- Schedules an update of the albedo and emissive textures of a system that contains the renderer or the terrain.
--- @param renderer UnityEngine.Object 
function UnityEngine.DynamicGI.UpdateMaterials(renderer) end

--- Schedules an update of the albedo and emissive textures of a system that contains the renderer or the terrain.
--- @param renderer UnityEngine.Object 
--- @param x number 
--- @param y number 
--- @param width number 
--- @param height number 
function UnityEngine.DynamicGI.UpdateMaterials(renderer, x, y, width, height) end

---  Generated By xerysherry