--- @class UnityEngine.Rendering.VirtualTexturing.Resolver Class responsable for virtual texturing feedback analysis.
--- @field CurrentWidth number property get
---       Width of the texture that the internal buffers can hold.
--- @field CurrentHeight number property get
---       >Height of the texture that the internal buffers can hold.
UnityEngine.Rendering.VirtualTexturing.Resolver = {}

--- Disposes this object.
function UnityEngine.Rendering.VirtualTexturing.Resolver:Dispose() end

--- Update the internal buffers.
--- @param width number Width of the texture passed in during Process.
--- @param height number Height of the texture passed in during Process.
function UnityEngine.Rendering.VirtualTexturing.Resolver:UpdateSize(width, height) end

--- Process the passed in feedback texture.
--- @param cmd UnityEngine.Rendering.CommandBuffer 
--- @param rt UnityEngine.Rendering.RenderTargetIdentifier 
function UnityEngine.Rendering.VirtualTexturing.Resolver:Process(cmd, rt) end

--- Process the passed in feedback texture.
--- @param cmd UnityEngine.Rendering.CommandBuffer The commandbuffer used to schedule processing.
--- @param rt UnityEngine.Rendering.RenderTargetIdentifier Texture containing the feedback data.
--- @param x number X position of the subrect that is processed.
--- @param width number Width of the subrect that is processed.
--- @param y number Y position of the subrect that is processed.
--- @param height number Height of the subrect that is processed.
--- @param mip number Miplevel of the texture to process.
--- @param slice number Arrayslice of the texture to process.
function UnityEngine.Rendering.VirtualTexturing.Resolver:Process(cmd, rt, x, width, y, height, mip, slice) end

---  Generated By xerysherry