--- @class UnityEngine.TextGenerator Class that can be used to generate text for rendering.
--- @field characterCountVisible number property get
---       The number of characters that have been generated and are included in the visible lines.
--- @field verts System.Collections.Generic.IList`1 property get
---       Array of generated vertices.
--- @field characters System.Collections.Generic.IList`1 property get
---       Array of generated characters.
--- @field lines System.Collections.Generic.IList`1 property get
---       Information about each generated text line.
--- @field rectExtents UnityEngine.Rect property get
---       Extents of the generated text in rect format.
--- @field vertexCount number property get
---       Number of vertices generated.
--- @field characterCount number property get
---       The number of characters that have been generated.
--- @field lineCount number property get
---       Number of text lines generated.
--- @field fontSizeUsedForBestFit number property get
---       The size of the font that was found if using best fit mode.
UnityEngine.TextGenerator = {}

--- Mark the text generator as invalid. This will force a full text generation the next time Populate is called.
function UnityEngine.TextGenerator:Invalidate() end

--- Populate the given List with UICharInfo.
--- @param characters UnityEngine.UICharInfo[] List to populate.
function UnityEngine.TextGenerator:GetCharacters(characters) end

--- Populate the given list with UILineInfo.
--- @param lines UnityEngine.UILineInfo[] List to populate.
function UnityEngine.TextGenerator:GetLines(lines) end

--- Populate the given list with generated Vertices.
--- @param vertices UnityEngine.UIVertex[] List to populate.
function UnityEngine.TextGenerator:GetVertices(vertices) end

--- Given a string and settings, returns the preferred width for a container that would hold this text.
--- @param str string Generation text.
--- @param settings UnityEngine.TextGenerationSettings Settings for generation.
--- @return number Preferred width.
function UnityEngine.TextGenerator:GetPreferredWidth(str, settings) end

--- Given a string and settings, returns the preferred height for a container that would hold this text.
--- @param str string Generation text.
--- @param settings UnityEngine.TextGenerationSettings Settings for generation.
--- @return number Preferred height.
function UnityEngine.TextGenerator:GetPreferredHeight(str, settings) end

--- Will generate the vertices and other data for the given string with the given settings.
--- @param str string String to generate.
--- @param settings UnityEngine.TextGenerationSettings Generation settings.
--- @param context UnityEngine.GameObject The object used as context of the error log message, if necessary.
--- @return boolean True if the generation is a success, false otherwise.
function UnityEngine.TextGenerator:PopulateWithErrors(str, settings, context) end

--- Will generate the vertices and other data for the given string with the given settings.
--- @param str string String to generate.
--- @param settings UnityEngine.TextGenerationSettings Settings.
--- @return boolean 
function UnityEngine.TextGenerator:Populate(str, settings) end

--- Returns the current UIVertex array.
--- @return UnityEngine.UIVertex[] Vertices.
function UnityEngine.TextGenerator:GetVerticesArray() end

--- Returns the current UICharInfo.
--- @return UnityEngine.UICharInfo[] Character information.
function UnityEngine.TextGenerator:GetCharactersArray() end

--- Returns the current UILineInfo.
--- @return UnityEngine.UILineInfo[] Line information.
function UnityEngine.TextGenerator:GetLinesArray() end

---  Generated By xerysherry