--- @class UnityEngine.AssetBundleRequest:UnityEngine.ResourceRequest Asynchronous load request from an AssetBundle.
--- @field asset UnityEngine.Object property get
---       Asset object being loaded (Read Only).
--- @field allAssets UnityEngine.Object[] property get
---       Asset objects with sub assets being loaded. (Read Only)
--- @field isDone boolean
--- @field progress number
--- @field priority number
--- @field allowSceneActivation boolean
UnityEngine.AssetBundleRequest = {}

---  Generated By xerysherry