--- 
---  Style value that can be either a Cursor or a StyleKeyword.
---  
--- @class UnityEngine.UIElements.StyleCursor
--- @field value UnityEngine.UIElements.Cursor property getset
---       
---        The Cursor value.
---        
--- @field keyword UnityEngine.UIElements.StyleKeyword property getset
---       
---        The style keyword.
---        
UnityEngine.UIElements.StyleCursor = {}

--- @return boolean
function UnityEngine.UIElements.StyleCursor.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.UIElements.StyleCursor.op_Inequality(lhs, rhs) end

--- @return UnityEngine.UIElements.StyleCursor
function UnityEngine.UIElements.StyleCursor.op_Implicit(keyword) end

--- @return UnityEngine.UIElements.StyleCursor
function UnityEngine.UIElements.StyleCursor.op_Implicit(v) end

function UnityEngine.UIElements.StyleCursor:set_value(value) end

function UnityEngine.UIElements.StyleCursor:set_keyword(value) end

--- @return boolean
function UnityEngine.UIElements.StyleCursor:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.StyleCursor:Equals(obj) end

--- @return number
function UnityEngine.UIElements.StyleCursor:GetHashCode() end

--- @return string
function UnityEngine.UIElements.StyleCursor:ToString() end

---  Generated By xerysherry