--- 
---  Configurations of the ScrollView to influence the layout of its contents and how scrollbars appear.
---  ScrollView.mode
---  
--- @class UnityEngine.UIElements.ScrollViewMode
UnityEngine.UIElements.ScrollViewMode = {
    --- 
    ---  Configure ScrollView for vertical scrolling.
    ---  
    Vertical = 0,
    --- 
    ---  Configure ScrollView for horizontal scrolling.
    ---  
    Horizontal = 1,
    --- 
    ---  Configure ScrollView for vertical and horizontal scrolling.
    ---  
    VerticalAndHorizontal = 2,
}

---  Generated By xerysherry