--- @class UnityEngine.Jobs.IJobParallelForTransformExtensions Extension methods for IJobParallelForTransform.
UnityEngine.Jobs.IJobParallelForTransformExtensions = {}

--- Schedule an IJobParallelForTransform job with read-write access to the transform data. This method parallelizes access to transforms in different hierarchies. Transforms with a shared root object are always processed on the same thread.
--- @param jobData UnityEngine.Jobs.IJobParallelForTransformExtensions.T The job to schedule.
--- @param transforms UnityEngine.Jobs.TransformAccessArray The TransformAccessArray to run this job on.
--- @param dependsOn Unity.Jobs.JobHandle A JobHandle containing any jobs that must finish executing before this job begins. (Combine multiple jobs with JobHandle.CombineDependencies). Use dependencies to ensure that two jobs reading or writing to the same data do not run in parallel.
--- @return Unity.Jobs.JobHandle The handle identifying the scheduled job. Can be used as a dependency for a later job or ensure completion on the main thread.
function UnityEngine.Jobs.IJobParallelForTransformExtensions.Schedule(jobData, transforms, dependsOn) end

--- Schedule an IJobParallelForTransform job with read-only access to the transform data. This method provides better parallelization because it can read all transforms in parallel instead of just parallelizing over different hierarchies.
--- @param jobData UnityEngine.Jobs.IJobParallelForTransformExtensions.T The job to schedule.
--- @param transforms UnityEngine.Jobs.TransformAccessArray The TransformAccessArray to run this job on.
--- @param batchSize number Granularity in which workstealing is performed. A value of 32 means the job queue will steal 32 iterations and then perform them in an efficient inner loop.
--- @param dependsOn Unity.Jobs.JobHandle A JobHandle containing any jobs that must finish executing before this job begins. (Combine multiple jobs with JobHandle.CombineDependencies). Use dependencies to ensure that two jobs reading or writing to the same data do not run in parallel.
--- @return Unity.Jobs.JobHandle The handle identifying the scheduled job. Can be used as a dependency for a later job or ensure completion on the main thread.
function UnityEngine.Jobs.IJobParallelForTransformExtensions.ScheduleReadOnly(jobData, transforms, batchSize, dependsOn) end

--- Run an IJobParallelForTransform job with read-only access to the transform data. This method makes the job run on the calling thread instead of spreading it out over multiple threads.
--- @param jobData UnityEngine.Jobs.IJobParallelForTransformExtensions.T 
--- @param transforms UnityEngine.Jobs.TransformAccessArray 
function UnityEngine.Jobs.IJobParallelForTransformExtensions.RunReadOnly(jobData, transforms) end

---  Generated By xerysherry