--- @class UnityEngine.ParticleSystemRenderSpace How particles are aligned when rendered.
UnityEngine.ParticleSystemRenderSpace = {
    --- Particles face the camera plane.
    View = 0,
    --- Particles align with the world.
    World = 1,
    --- Particles align with their local transform.
    Local = 2,
    --- Particles face the eye position.
    Facing = 3,
    --- Particles are aligned to their direction of travel.
    Velocity = 4,
}

---  Generated By xerysherry