--- @class UnityEngine.U2D.SpriteShapeMetaData Additional data about the shape's control point. This is useful during tessellation of the shape.
--- @field height number The height of the tessellated edge.
--- @field bevelCutoff number The threshold of the angle that decides if it should be tessellated as a curve or a corner.
--- @field bevelSize number The radius of the curve to be tessellated.
--- @field spriteIndex number The Sprite to be used for a particular edge.
--- @field corner boolean True will indicate that this point should be tessellated as a corner or a continuous line otherwise.
UnityEngine.U2D.SpriteShapeMetaData = {}

---  Generated By xerysherry