--- @class UnityEngine.Rendering.AttachmentDescriptor A declaration of a single color or depth rendering surface to be attached into a RenderPass.
--- @field loadAction UnityEngine.Rendering.RenderBufferLoadAction property getset
---       The load action to be used on this attachment when the RenderPass starts.
--- @field storeAction UnityEngine.Rendering.RenderBufferStoreAction property getset
---       The store action to use with this attachment when the RenderPass ends. Only used when either ConfigureTarget or ConfigureResolveTarget has been called.
--- @field graphicsFormat UnityEngine.Experimental.Rendering.GraphicsFormat property getset
---       The GraphicsFormat of this attachment. To use in place of format.
--- @field format UnityEngine.RenderTextureFormat property getset
---       The format of this attachment.
--- @field loadStoreTarget UnityEngine.Rendering.RenderTargetIdentifier property getset
---       The surface to use as the backing storage for this AttachmentDescriptor.
--- @field resolveTarget UnityEngine.Rendering.RenderTargetIdentifier property getset
---       When the renderpass that uses this attachment ends, resolve the MSAA surface into the given target.
--- @field clearColor UnityEngine.Color property getset
---       The currently assigned clear color for this attachment. Default is black.
--- @field clearDepth number property getset
---       Currently assigned depth clear value for this attachment. Default value is 1.0.
--- @field clearStencil number property getset
---       Currently assigned stencil clear value for this attachment. Default is 0.
UnityEngine.Rendering.AttachmentDescriptor = {}

--- @return boolean
function UnityEngine.Rendering.AttachmentDescriptor.op_Equality(left, right) end

--- @return boolean
function UnityEngine.Rendering.AttachmentDescriptor.op_Inequality(left, right) end

function UnityEngine.Rendering.AttachmentDescriptor:set_loadAction(value) end

function UnityEngine.Rendering.AttachmentDescriptor:set_storeAction(value) end

function UnityEngine.Rendering.AttachmentDescriptor:set_graphicsFormat(value) end

function UnityEngine.Rendering.AttachmentDescriptor:set_format(value) end

function UnityEngine.Rendering.AttachmentDescriptor:set_loadStoreTarget(value) end

function UnityEngine.Rendering.AttachmentDescriptor:set_resolveTarget(value) end

function UnityEngine.Rendering.AttachmentDescriptor:set_clearColor(value) end

function UnityEngine.Rendering.AttachmentDescriptor:set_clearDepth(value) end

function UnityEngine.Rendering.AttachmentDescriptor:set_clearStencil(value) end

--- Binds this AttachmentDescriptor to the given target surface.
function UnityEngine.Rendering.AttachmentDescriptor:ConfigureTarget(target, loadExistingContents, storeResults) end

--- When the renderpass that uses this attachment ends, resolve the MSAA surface into the given target.
function UnityEngine.Rendering.AttachmentDescriptor:ConfigureResolveTarget(target) end

--- When the RenderPass starts, clear this attachment into the color or depth/stencil values given (depending on the format of this attachment). Changes loadAction to RenderBufferLoadAction.Clear.
function UnityEngine.Rendering.AttachmentDescriptor:ConfigureClear(clearColor, clearDepth, clearStencil) end

--- @return boolean
function UnityEngine.Rendering.AttachmentDescriptor:Equals(other) end

--- @return boolean
function UnityEngine.Rendering.AttachmentDescriptor:Equals(obj) end

--- @return number
function UnityEngine.Rendering.AttachmentDescriptor:GetHashCode() end

---  Generated By xerysherry