--- @class UnityEngine.RectTransformUtility Utility class containing helper methods for working with  RectTransform.
UnityEngine.RectTransformUtility = {}

--- Convert a given point in screen space into a pixel correct point.
--- @param point UnityEngine.Vector2 
--- @param elementTransform UnityEngine.Transform 
--- @param canvas UnityEngine.Canvas 
--- @return UnityEngine.Vector2 Pixel adjusted point.
function UnityEngine.RectTransformUtility.PixelAdjustPoint(point, elementTransform, canvas) end

--- Given a rect transform, return the corner points in pixel accurate coordinates.
--- @param rectTransform UnityEngine.RectTransform 
--- @param canvas UnityEngine.Canvas 
--- @return UnityEngine.Rect Pixel adjusted rect.
function UnityEngine.RectTransformUtility.PixelAdjustRect(rectTransform, canvas) end

--- Does the RectTransform contain the screen point as seen from the given camera?
--- @return boolean True if the point is inside the rectangle.
function UnityEngine.RectTransformUtility.RectangleContainsScreenPoint(rect, screenPoint) end

--- Does the RectTransform contain the screen point as seen from the given camera?
--- @param rect UnityEngine.RectTransform The RectTransform to test with.
--- @param screenPoint UnityEngine.Vector2 The screen point to test.
--- @param cam UnityEngine.Camera The camera from which the test is performed from. (Optional)
--- @return boolean True if the point is inside the rectangle.
function UnityEngine.RectTransformUtility.RectangleContainsScreenPoint(rect, screenPoint, cam) end

--- Does the RectTransform contain the screen point as seen from the given camera?
--- @return boolean True if the point is inside the rectangle.
function UnityEngine.RectTransformUtility.RectangleContainsScreenPoint(rect, screenPoint, cam, offset) end

--- Transform a screen space point to a position in world space that is on the plane of the given RectTransform.
--- @return boolean Returns true if the plane of the RectTransform is hit, regardless of whether the point is inside the rectangle.
function UnityEngine.RectTransformUtility.ScreenPointToWorldPointInRectangle(rect, screenPoint, cam) end

--- Transform a screen space point to a position in the local space of a RectTransform that is on the plane of its rectangle.
--- @return boolean Returns true if the plane of the RectTransform is hit, regardless of whether the point is inside the rectangle.
function UnityEngine.RectTransformUtility.ScreenPointToLocalPointInRectangle(rect, screenPoint, cam) end

--- @return UnityEngine.Ray
function UnityEngine.RectTransformUtility.ScreenPointToRay(cam, screenPos) end

--- @return UnityEngine.Vector2
function UnityEngine.RectTransformUtility.WorldToScreenPoint(cam, worldPoint) end

--- @return UnityEngine.Bounds
function UnityEngine.RectTransformUtility.CalculateRelativeRectTransformBounds(root, child) end

--- @return UnityEngine.Bounds
function UnityEngine.RectTransformUtility.CalculateRelativeRectTransformBounds(trans) end

--- Flips the alignment of the RectTransform along the horizontal or vertical axis, and optionally its children as well.
function UnityEngine.RectTransformUtility.FlipLayoutOnAxis(rect, axis, keepPositioning, recursive) end

--- Flips the horizontal and vertical axes of the RectTransform size and alignment, and optionally its children as well.
--- @param rect UnityEngine.RectTransform The RectTransform to flip.
--- @param keepPositioning boolean Flips around the pivot if true. Flips within the parent rect if false.
--- @param recursive boolean Flip the children as well?
function UnityEngine.RectTransformUtility.FlipLayoutAxes(rect, keepPositioning, recursive) end

---  Generated By xerysherry