--- @class UnityEngine.TextCore.Text.TextStyleSheet:UnityEngine.ScriptableObject 
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.TextCore.Text.TextStyleSheet = {}

--- @return UnityEngine.TextCore.Text.TextStyle
function UnityEngine.TextCore.Text.TextStyleSheet:GetStyle(hashCode) end

--- @return UnityEngine.TextCore.Text.TextStyle
function UnityEngine.TextCore.Text.TextStyleSheet:GetStyle(name) end

function UnityEngine.TextCore.Text.TextStyleSheet:RefreshStyles() end

---  Generated By xerysherry