--- 
---  Determines how intermediate values are calculated for a transition.
---  
--- @class UnityEngine.UIElements.EasingFunction
--- @field mode UnityEngine.UIElements.EasingMode property getset
---       
---        The value of the EasingMode.
---        
UnityEngine.UIElements.EasingFunction = {}

--- @return UnityEngine.UIElements.EasingFunction
function UnityEngine.UIElements.EasingFunction.op_Implicit(easingMode) end

--- @return boolean
function UnityEngine.UIElements.EasingFunction.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.UIElements.EasingFunction.op_Inequality(lhs, rhs) end

function UnityEngine.UIElements.EasingFunction:set_mode(value) end

--- @return boolean
function UnityEngine.UIElements.EasingFunction:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.EasingFunction:Equals(obj) end

--- @return string
function UnityEngine.UIElements.EasingFunction:ToString() end

--- @return number
function UnityEngine.UIElements.EasingFunction:GetHashCode() end

---  Generated By xerysherry