--- @class UnityEngine.LightProbeProxyVolume.DataFormat The texture data format used by the Light Probe Proxy Volume 3D texture.
UnityEngine.LightProbeProxyVolume.DataFormat = {
    --- A 16-bit half floating-point format is used for the Light Probe Proxy Volume 3D texture.
    HalfFloat = 0,
    --- A 32-bit floating-point format is used for the Light Probe Proxy Volume 3D texture.
    Float = 1,
}

---  Generated By xerysherry