--- @class UnityEngine.CreateAssetMenuAttribute:System.Attribute Mark a ScriptableObject-derived type to be automatically listed in the Assets/Create submenu, so that instances of the type can be easily created and stored in the project as ".asset" files.
--- @field menuName string property getset
---       The display name for this type shown in the Assets/Create menu.
--- @field fileName string property getset
---       The default file name used by newly created instances of this type.
--- @field order number property getset
---       The position of the menu item within the Assets/Create menu.
--- @field TypeId System.Object
UnityEngine.CreateAssetMenuAttribute = {}

--- @param value string 
function UnityEngine.CreateAssetMenuAttribute:set_menuName(value) end

--- @param value string 
function UnityEngine.CreateAssetMenuAttribute:set_fileName(value) end

--- @param value number 
function UnityEngine.CreateAssetMenuAttribute:set_order(value) end

---  Generated By xerysherry