--- @class UnityEngine.AndroidJavaException:System.Exception 
--- @field StackTrace string
--- @field Message string
--- @field Data System.Collections.IDictionary
--- @field InnerException System.Exception
--- @field TargetSite System.Reflection.MethodBase
--- @field HelpLink string
--- @field Source string
--- @field HResult number
UnityEngine.AndroidJavaException = {}

---  Generated By xerysherry