--- @class UnityEngine.AssetBundleLoadResult The result of an Asset Bundle Load or Recompress Operation.
UnityEngine.AssetBundleLoadResult = {
    --- The operation completed successfully.
    Success = 0,
    --- The operation was cancelled.
    Cancelled = 1,
    --- The decompressed Asset data did not match the precomputed CRC. This may suggest that the AssetBundle did not download correctly.
    NotMatchingCrc = 2,
    --- The Asset Bundle was not successfully cached.
    FailedCache = 3,
    --- This does not appear to be a valid Asset Bundle.
    NotValidAssetBundle = 4,
    --- The Asset Bundle does not contain any serialized data. It may be empty, or corrupt.
    NoSerializedData = 5,
    --- The AssetBundle is incompatible with this version of Unity.
    NotCompatible = 6,
    --- The Asset Bundle is already loaded.
    AlreadyLoaded = 7,
    --- Failed to read the Asset Bundle file.
    FailedRead = 8,
    --- Failed to decompress the Asset Bundle.
    FailedDecompression = 9,
    --- Failed to write to the file system.
    FailedWrite = 10,
    --- The target path given for the Recompression operation could not be deleted for swap with recompressed bundle file.
    FailedDeleteRecompressionTarget = 11,
    --- The target path given for the Recompression operation is an Archive that is currently loaded.
    RecompressionTargetIsLoaded = 12,
    --- The target path given for the Recompression operation exists but is not an Archive container.
    RecompressionTargetExistsButNotArchive = 13,
}

---  Generated By xerysherry