--- @class UnityEngine.Rendering.CommandBufferExtensions Static class providing extension methods for CommandBuffer.
UnityEngine.Rendering.CommandBufferExtensions = {}

--- Adds a command to put a given render target into fast GPU memory.
function UnityEngine.Rendering.CommandBufferExtensions.SwitchIntoFastMemory(cmd, rid, fastMemoryFlags, residency, copyContents) end

--- Adds a command to remove a given render target from fast GPU memory.
function UnityEngine.Rendering.CommandBufferExtensions.SwitchOutOfFastMemory(cmd, rid, copyContents) end

---  Generated By xerysherry