--- @class UnityEngine.ADBannerView 
--- @field loaded boolean
--- @field visible boolean
--- @field layout UnityEngine.ADBannerView.Layout
--- @field position UnityEngine.Vector2
--- @field size UnityEngine.Vector2
UnityEngine.ADBannerView = {}

function UnityEngine.ADBannerView.add_onBannerWasClicked(value) end

function UnityEngine.ADBannerView.remove_onBannerWasClicked(value) end

function UnityEngine.ADBannerView.add_onBannerWasLoaded(value) end

function UnityEngine.ADBannerView.remove_onBannerWasLoaded(value) end

--- @return boolean
function UnityEngine.ADBannerView.IsAvailable(type) end

function UnityEngine.ADBannerView:set_visible(value) end

function UnityEngine.ADBannerView:set_layout(value) end

function UnityEngine.ADBannerView:set_position(value) end

---  Generated By xerysherry