--- 
---  A collection of static methods that provide simple World, Screen, and Panel coordinate transformations.
---  
--- @class UnityEngine.UIElements.RuntimePanelUtils
UnityEngine.UIElements.RuntimePanelUtils = {}

--- 
---  Transforms a screen absolute position to its equivalent local coordinate on given panel.
---  <param name="panel">The local coordinates reference panel.<param>
---  <param name="screenPosition">The screen position to transform.<param>
---  <returns>A position in panel coordinates that corresponds to the provided screen position.</returns>
---  
--- @param panel UnityEngine.UIElements.IPanel 
--- @param screenPosition UnityEngine.Vector2 
--- @return UnityEngine.Vector2 
function UnityEngine.UIElements.RuntimePanelUtils.ScreenToPanel(panel, screenPosition) end

--- 
---  Transforms a world absolute position to its equivalent local coordinate on given panel,
---  using provided camera for internal WorldToScreen transformation.
---  <param name="panel">The local coordinates reference panel.<param>
---  <param name="worldPosition">The world position to transform.<param>
---  <param name="camera">The Camera used for internal WorldToScreen transformation.<param>
---  <returns>A position in panel coordinates that corresponds to the provided world position.<returns>
---  
--- @param panel UnityEngine.UIElements.IPanel 
--- @param worldPosition UnityEngine.Vector3 
--- @param camera UnityEngine.Camera 
--- @return UnityEngine.Vector2 
function UnityEngine.UIElements.RuntimePanelUtils.CameraTransformWorldToPanel(panel, worldPosition, camera) end

--- 
---  Transforms a world position and size (in world units) to their equivalent local position and size
---  on given panel, using provided camera for internal WorldToScreen transformation.
---  <param name="panel">The local coordinates reference panel.<param>
---  <param name="worldPosition">The world position to transform.<param>
---  <param name="worldSize">The world size to transform. The object in the panel will appear to have
---  that size when compared to other 3D objects at neighboring positions.<param>
---  <param name="camera">The Camera used for internal WorldToScreen transformation.<param>
---  <returns>A (position, size) Rect in panel coordinates that corresponds to the provided world position
---  and size.</returns>
---  
--- @param panel UnityEngine.UIElements.IPanel 
--- @param worldPosition UnityEngine.Vector3 
--- @param worldSize UnityEngine.Vector2 
--- @param camera UnityEngine.Camera 
--- @return UnityEngine.Rect 
function UnityEngine.UIElements.RuntimePanelUtils.CameraTransformWorldToPanelRect(panel, worldPosition, worldSize, camera) end

--- 
---  Resets the dynamic atlas of the panel. Textured elements will be repainted.
---  
--- @param panel UnityEngine.UIElements.IPanel 
function UnityEngine.UIElements.RuntimePanelUtils.ResetDynamicAtlas(panel) end

--- 
---  Notifies the dynamic atlas of the panel that the content of the provided texture has changed. If the dynamic
---  atlas contains the texture, it will update it.
---  
--- @param panel UnityEngine.UIElements.IPanel The current panel
--- @param texture UnityEngine.Texture2D The texture whose content has changed.
function UnityEngine.UIElements.RuntimePanelUtils.SetTextureDirty(panel, texture) end

---  Generated By xerysherry