--- @class UnityEngine.Rendering.LocalKeywordSpace Represents the local keyword space of a Shader or ComputeShader.
--- @field keywords UnityEngine.Rendering.LocalKeyword[] property get
---       An array containing all Rendering.LocalKeyword structs in this local keyword space. (Read Only)
--- @field keywordNames string[] property get
---       An array containing the names of all local shader keywords in this local keyword space. (Read Only)
--- @field keywordCount number property get
---       The number of local shader keywords in this local keyword space. (Read Only)
UnityEngine.Rendering.LocalKeywordSpace = {}

--- @return boolean
function UnityEngine.Rendering.LocalKeywordSpace.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.Rendering.LocalKeywordSpace.op_Inequality(lhs, rhs) end

--- Searches for a local shader keyword with a given name in the keyword space.
--- @param name string The name of the shader keyword to search for.
--- @return UnityEngine.Rendering.LocalKeyword Returns a valid Rendering.LocalKeyword if it's present in the keyword space. Otherwise, returns an invalid Rendering.LocalKeyword.
function UnityEngine.Rendering.LocalKeywordSpace:FindKeyword(name) end

--- @return boolean
function UnityEngine.Rendering.LocalKeywordSpace:Equals(o) end

--- @return boolean
function UnityEngine.Rendering.LocalKeywordSpace:Equals(rhs) end

--- @return number
function UnityEngine.Rendering.LocalKeywordSpace:GetHashCode() end

---  Generated By xerysherry