--- @class UnityEngine.TextCore.Text.TextEventManager 
--- @field MATERIAL_PROPERTY_EVENT UnityEngine.TextCore.Text.FastAction`2
--- @field FONT_PROPERTY_EVENT UnityEngine.TextCore.Text.FastAction`2
--- @field SPRITE_ASSET_PROPERTY_EVENT UnityEngine.TextCore.Text.FastAction`2
--- @field TEXTMESHPRO_PROPERTY_EVENT UnityEngine.TextCore.Text.FastAction`2
--- @field DRAG_AND_DROP_MATERIAL_EVENT UnityEngine.TextCore.Text.FastAction`3
--- @field TEXT_STYLE_PROPERTY_EVENT UnityEngine.TextCore.Text.FastAction`1
--- @field COLOR_GRADIENT_PROPERTY_EVENT UnityEngine.TextCore.Text.FastAction`1
--- @field TMP_SETTINGS_PROPERTY_EVENT UnityEngine.TextCore.Text.FastAction
--- @field RESOURCE_LOAD_EVENT UnityEngine.TextCore.Text.FastAction
--- @field TEXTMESHPRO_UGUI_PROPERTY_EVENT UnityEngine.TextCore.Text.FastAction`2
--- @field OnPreRenderObject_Event UnityEngine.TextCore.Text.FastAction
--- @field TEXT_CHANGED_EVENT UnityEngine.TextCore.Text.FastAction`1
UnityEngine.TextCore.Text.TextEventManager = {}

function UnityEngine.TextCore.Text.TextEventManager.ON_PRE_RENDER_OBJECT_CHANGED() end

--- @param isChanged boolean 
--- @param mat UnityEngine.Material 
function UnityEngine.TextCore.Text.TextEventManager.ON_MATERIAL_PROPERTY_CHANGED(isChanged, mat) end

--- @param isChanged boolean 
--- @param font UnityEngine.Object 
function UnityEngine.TextCore.Text.TextEventManager.ON_FONT_PROPERTY_CHANGED(isChanged, font) end

--- @param isChanged boolean 
--- @param obj UnityEngine.Object 
function UnityEngine.TextCore.Text.TextEventManager.ON_SPRITE_ASSET_PROPERTY_CHANGED(isChanged, obj) end

--- @param isChanged boolean 
--- @param obj UnityEngine.Object 
function UnityEngine.TextCore.Text.TextEventManager.ON_TEXTMESHPRO_PROPERTY_CHANGED(isChanged, obj) end

--- @param sender UnityEngine.GameObject 
--- @param currentMaterial UnityEngine.Material 
--- @param newMaterial UnityEngine.Material 
function UnityEngine.TextCore.Text.TextEventManager.ON_DRAG_AND_DROP_MATERIAL_CHANGED(sender, currentMaterial, newMaterial) end

--- @param isChanged boolean 
function UnityEngine.TextCore.Text.TextEventManager.ON_TEXT_STYLE_PROPERTY_CHANGED(isChanged) end

--- @param gradient UnityEngine.Object 
function UnityEngine.TextCore.Text.TextEventManager.ON_COLOR_GRADIENT_PROPERTY_CHANGED(gradient) end

--- @param obj UnityEngine.Object 
function UnityEngine.TextCore.Text.TextEventManager.ON_TEXT_CHANGED(obj) end

function UnityEngine.TextCore.Text.TextEventManager.ON_TMP_SETTINGS_CHANGED() end

function UnityEngine.TextCore.Text.TextEventManager.ON_RESOURCES_LOADED() end

--- @param isChanged boolean 
--- @param obj UnityEngine.Object 
function UnityEngine.TextCore.Text.TextEventManager.ON_TEXTMESHPRO_UGUI_PROPERTY_CHANGED(isChanged, obj) end

---  Generated By xerysherry