--- 
---  This structure holds information used during UXML template instantiation.
---  
--- @class UnityEngine.UIElements.CreationContext
--- @field Default UnityEngine.UIElements.CreationContext
--- @field target UnityEngine.UIElements.VisualElement property get
---       
---        The element into which the visualTreeAsset is being cloned or instantiated.
---        VisualTreeAsset.CloneTree()
---        VisualTreeAsset.Instantiate()
---        
--- @field visualTreeAsset UnityEngine.UIElements.VisualTreeAsset property get
---       
---        The target UXML file to clone or instantiate.
---        
--- @field slotInsertionPoints table<string, UnityEngine.UIElements.VisualElement>
UnityEngine.UIElements.CreationContext = {}

--- @param context1 UnityEngine.UIElements.CreationContext 
--- @param context2 UnityEngine.UIElements.CreationContext 
--- @return boolean
function UnityEngine.UIElements.CreationContext.op_Equality(context1, context2) end

--- @param context1 UnityEngine.UIElements.CreationContext 
--- @param context2 UnityEngine.UIElements.CreationContext 
--- @return boolean
function UnityEngine.UIElements.CreationContext.op_Inequality(context1, context2) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.UIElements.CreationContext:Equals(obj) end

--- @param other UnityEngine.UIElements.CreationContext 
--- @return boolean
function UnityEngine.UIElements.CreationContext:Equals(other) end

--- @return number
function UnityEngine.UIElements.CreationContext:GetHashCode() end

---  Generated By xerysherry