--- 
---  Describes a VisualElement font.
---  
--- @class UnityEngine.UIElements.FontDefinition
--- @field font UnityEngine.Font property getset
---       
---        Font to use to display text. You cannot set this and FontDefinition.fontAsset at the same time.
---        
--- @field fontAsset UnityEngine.TextCore.Text.FontAsset property getset
---       
---        SDF font to use to display text. You cannot set this and FontDefinition.font at the same time.
---        
UnityEngine.UIElements.FontDefinition = {}

--- 
---  Create a FontDefinition from Font.
---  
--- @param f UnityEngine.Font The font to use to display text.
--- @return UnityEngine.UIElements.FontDefinition A new FontDefinition object.
function UnityEngine.UIElements.FontDefinition.FromFont(f) end

--- 
---  Create a FontDefinition from FontAsset.
---  
--- @param f UnityEngine.TextCore.Text.FontAsset The SDF font to use to display text.
--- @return UnityEngine.UIElements.FontDefinition A new FontDefinition object.
function UnityEngine.UIElements.FontDefinition.FromSDFFont(f) end

--- @return boolean
function UnityEngine.UIElements.FontDefinition.op_Equality(left, right) end

--- @return boolean
function UnityEngine.UIElements.FontDefinition.op_Inequality(left, right) end

function UnityEngine.UIElements.FontDefinition:set_font(value) end

function UnityEngine.UIElements.FontDefinition:set_fontAsset(value) end

--- @return string
function UnityEngine.UIElements.FontDefinition:ToString() end

--- @return boolean
function UnityEngine.UIElements.FontDefinition:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.FontDefinition:Equals(obj) end

--- @return number
function UnityEngine.UIElements.FontDefinition:GetHashCode() end

---  Generated By xerysherry