--- @class UnityEngine.SubsystemsImplementation.SubsystemProvider A provider that supplies data to a subsystem, generally for platform-specific implementations.
--- @field running boolean
UnityEngine.SubsystemsImplementation.SubsystemProvider = {}

---  Generated By xerysherry