--- @class UnityEngine.TextCore.Text.FastAction 
UnityEngine.TextCore.Text.FastAction = {}

function UnityEngine.TextCore.Text.FastAction:Add(rhs) end

function UnityEngine.TextCore.Text.FastAction:Remove(rhs) end

function UnityEngine.TextCore.Text.FastAction:Call() end

---  Generated By xerysherry