--- 
---  A VisualElement representing a source texture.
---  
--- @class UnityEngine.UIElements.Image:UnityEngine.UIElements.VisualElement
--- @field ussClassName string 
---        USS class name of elements of this type.
---        
--- @field image UnityEngine.Texture property getset
---       
---        The texture to display in this image.
---        
--- @field sprite UnityEngine.Sprite property getset
---       
---        The sprite to display in this image.
---        
--- @field vectorImage UnityEngine.UIElements.VectorImage property getset
---       
---        The VectorImage to display in this image.
---        
--- @field sourceRect UnityEngine.Rect property getset
---       
---        The source rectangle inside the texture relative to the top left corner.
---        
--- @field uv UnityEngine.Rect property getset
---       
---        The base texture coordinates of the Image relative to the bottom left corner.
---        
--- @field scaleMode UnityEngine.ScaleMode property getset
---       
---        ScaleMode used to display the Image.
---        
--- @field tintColor UnityEngine.Color property getset
---       
---        Tinting color for this Image.
---        
--- @field viewDataKey string
--- @field userData System.Object
--- @field canGrabFocus boolean
--- @field focusController UnityEngine.UIElements.FocusController
--- @field usageHints UnityEngine.UIElements.UsageHints
--- @field transform UnityEngine.UIElements.ITransform
--- @field layout UnityEngine.Rect
--- @field contentRect UnityEngine.Rect
--- @field worldBound UnityEngine.Rect
--- @field localBound UnityEngine.Rect
--- @field worldTransform UnityEngine.Matrix4x4
--- @field pickingMode UnityEngine.UIElements.PickingMode
--- @field name string
--- @field enabledInHierarchy boolean
--- @field enabledSelf boolean
--- @field visible boolean
--- @field generateVisualContent function
--- @field experimental UnityEngine.UIElements.IExperimentalFeatures
--- @field hierarchy UnityEngine.UIElements.VisualElement.Hierarchy
--- @field cacheAsBitmap boolean
--- @field parent UnityEngine.UIElements.VisualElement
--- @field panel UnityEngine.UIElements.IPanel
--- @field contentContainer UnityEngine.UIElements.VisualElement
--- @field visualTreeAssetSource UnityEngine.UIElements.VisualTreeAsset
--- @field Item UnityEngine.UIElements.VisualElement
--- @field childCount number
--- @field schedule UnityEngine.UIElements.IVisualElementScheduler
--- @field style UnityEngine.UIElements.IStyle
--- @field customStyle UnityEngine.UIElements.ICustomStyle
--- @field styleSheets UnityEngine.UIElements.VisualElementStyleSheetSet
--- @field tooltip string
--- @field resolvedStyle UnityEngine.UIElements.IResolvedStyle
--- @field focusable boolean
--- @field tabIndex number
--- @field delegatesFocus boolean
UnityEngine.UIElements.Image = {}

--- @param value UnityEngine.Texture 
function UnityEngine.UIElements.Image:set_image(value) end

--- @param value UnityEngine.Sprite 
function UnityEngine.UIElements.Image:set_sprite(value) end

--- @param value UnityEngine.UIElements.VectorImage 
function UnityEngine.UIElements.Image:set_vectorImage(value) end

--- @param value UnityEngine.Rect 
function UnityEngine.UIElements.Image:set_sourceRect(value) end

--- @param value UnityEngine.Rect 
function UnityEngine.UIElements.Image:set_uv(value) end

--- @param value UnityEngine.ScaleMode 
function UnityEngine.UIElements.Image:set_scaleMode(value) end

--- @param value UnityEngine.Color 
function UnityEngine.UIElements.Image:set_tintColor(value) end

---  Generated By xerysherry