--- 
---  Contains timing information of scheduler events.
---  
--- @class UnityEngine.UIElements.TimerState
--- @field start number property getset
---       
---        Start time in milliseconds, or last callback time for repeatable IScheduledItem.
---        
--- @field now number property getset
---       
---        Current time in milliseconds.
---        
--- @field deltaTime number property get
---       
---        Time difference in milliseconds between now and the previous callback.
---        
UnityEngine.UIElements.TimerState = {}

--- @return boolean
function UnityEngine.UIElements.TimerState.op_Equality(state1, state2) end

--- @return boolean
function UnityEngine.UIElements.TimerState.op_Inequality(state1, state2) end

function UnityEngine.UIElements.TimerState:set_start(value) end

function UnityEngine.UIElements.TimerState:set_now(value) end

--- 
---  Compare this object with another object and return true if they are equal.
---  
--- @param obj System.Object The object to compare with.
--- @return boolean True if the objects are equal.
function UnityEngine.UIElements.TimerState:Equals(obj) end

--- 
---  Compare this object with another object and return true if they are equal.
---  
--- @param other UnityEngine.UIElements.TimerState The object to compare with.
--- @return boolean True if the objects are equal.
function UnityEngine.UIElements.TimerState:Equals(other) end

--- @return number
function UnityEngine.UIElements.TimerState:GetHashCode() end

---  Generated By xerysherry