--- @class UnityEngine.ParticleSystemVertexStreams All possible Particle System vertex shader inputs.
UnityEngine.ParticleSystemVertexStreams = {
    --- The world space position of each particle.
    Position = 1,
    --- The normal of each particle.
    Normal = 2,
    --- Tangent vectors for normal mapping.
    Tangent = 4,
    --- The color of each particle.
    Color = 8,
    --- The texture coordinates of each particle.
    UV = 16,
    --- With the TextureSheetAnimationModule enabled, this contains the UVs for the second texture frame, the blend factor for each particle, and the raw frame, allowing for blending of frames.
    UV2BlendAndFrame = 32,
    --- The center position of each particle, with the vertex ID of each particle, from 0-3, stored in the w component.
    CenterAndVertexID = 64,
    --- The size of each particle.
    Size = 128,
    --- The rotation of each particle.
    Rotation = 256,
    --- The 3D velocity of each particle.
    Velocity = 512,
    --- Alive time as a 0-1 value in the X component, and Total Lifetime in the Y component.
    --- To get the current particle age, simply multiply X by Y.
    Lifetime = 1024,
    --- The first stream of custom data, supplied from script.
    Custom1 = 2048,
    --- The second stream of custom data, supplied from script.
    Custom2 = 4096,
    --- 4 random numbers. The first 3 are deterministic and assigned once when each particle is born, but the 4th value will change during the lifetime of the particle.
    Random = 8192,
    --- A mask with no vertex streams enabled.
    None = 0,
    --- A mask with all vertex streams enabled.
    All = 2147483647,
}

---  Generated By xerysherry