--- @class UnityEngine.Android.AndroidAssetPacks Provides methods for handling Android asset packs.
--- @field coreUnityAssetPacksDownloaded boolean property get
---       Checks if all core Unity asset packs are downloaded.
UnityEngine.Android.AndroidAssetPacks = {}

--- Gets the name of every core Unity asset pack built for this application that use either the fast-follow or on-demand delivery type.
--- @return string[] Returns an array of asset pack names for core Unity asset packs with the fast-follow or on-demand delivery type. If Unity did not create any core asset packs for this application with previously mentioned delivery types, or if the PlayCore plugin is missing, this returns an empty array.
function UnityEngine.Android.AndroidAssetPacks.GetCoreUnityAssetPackNames() end

--- Queries the state of Android asset packs.
--- @param assetPackNames string[] The array of names of the Android asset packs to query the state of.
--- @param callback function The callback method to get the result. Unity raises this callback once when the query is complete and the callback receives the state of queried Android asset packs. The callback method must have two parameters:
---       
---       * A ulong type parameter which indicates the total size of the queried asset packs.
---       * An array of AndroidAssetPackState which contains the state of each queried asset pack.
---       
---       
function UnityEngine.Android.AndroidAssetPacks.GetAssetPackStateAsync(assetPackNames, callback) end

--- Queries the state of Android asset packs.
--- @param assetPackNames string[] The array of names of the Android asset packs to query the state of.
--- @return UnityEngine.Android.GetAssetPackStateAsyncOperation Returns an object that represents the query operation. If you yield this object inside a coroutine, the coroutine pauses until the operation is complete.
function UnityEngine.Android.AndroidAssetPacks.GetAssetPackStateAsync(assetPackNames) end

--- Downloads Android asset packs.
--- @param assetPackNames string[] The array of names of Android asset packs to download.
--- @param callback function The callback method to inform about download progress. It gets called multiple times for each asset pack during its download. The callback method must have a parameter of AndroidAssetPackInfo type.
---       The default value is null.
function UnityEngine.Android.AndroidAssetPacks.DownloadAssetPackAsync(assetPackNames, callback) end

--- Downloads Android asset packs.
--- @param assetPackNames string[] The array of names of Android asset packs to download.
--- @return UnityEngine.Android.DownloadAssetPackAsyncOperation Returns an object that represents the download operation. If you yield this object inside a coroutine, the coroutine pauses until the operation is complete.
function UnityEngine.Android.AndroidAssetPacks.DownloadAssetPackAsync(assetPackNames) end

--- Requests to use mobile data to download Android asset packs.
--- @param callback function The callback method to get the result. The callback method must have an AndroidAssetPackUseMobileDataRequestResult parameter. This contains the value that indicates the end user's choice. The application raises this callback a single time after the end user submits their decision.
function UnityEngine.Android.AndroidAssetPacks.RequestToUseMobileDataAsync(callback) end

--- Requests to use mobile data to download Android asset packs.
--- @return UnityEngine.Android.RequestToUseMobileDataAsyncOperation Returns an object that represents the request operation. If you yield this object inside a coroutine, the coroutine pauses until the operation is complete.
function UnityEngine.Android.AndroidAssetPacks.RequestToUseMobileDataAsync() end

--- Gets the full path to the location where the device stores the assets for the Android asset pack.
--- @param assetPackName string The name of the Android asset pack to get path.
--- @return string Returns the full path to the location where the device stores the assets for the Android asset pack. If the asset pack you specify is not on the device, or if it does not use the fast-follow or on-demand delivery type, this returns an empty string.
function UnityEngine.Android.AndroidAssetPacks.GetAssetPackPath(assetPackName) end

--- Cancels Android asset pack downloads.
--- @param assetPackNames string[] The array of names of the Android asset packs to cancel the download for.
function UnityEngine.Android.AndroidAssetPacks.CancelAssetPackDownload(assetPackNames) end

--- Removes Android asset pack.
--- @param assetPackName string The name of the Android asset pack to remove.
function UnityEngine.Android.AndroidAssetPacks.RemoveAssetPack(assetPackName) end

---  Generated By xerysherry