--- @class UnityEngine.Experimental.Animations.AnimationPlayableOutputExtensions Static class providing experimental extension methods for AnimationPlayableOutput .
UnityEngine.Experimental.Animations.AnimationPlayableOutputExtensions = {}

--- Gets the stream source of the specified AnimationPlayableOutput.
--- @param output UnityEngine.Animations.AnimationPlayableOutput The AnimationPlayableOutput instance that calls this method.
--- @return UnityEngine.Experimental.Animations.AnimationStreamSource Returns the AnimationStreamSource of the output.
function UnityEngine.Experimental.Animations.AnimationPlayableOutputExtensions.GetAnimationStreamSource(output) end

--- Sets the stream source for the specified AnimationPlayableOutput.
--- @param output UnityEngine.Animations.AnimationPlayableOutput The AnimationPlayableOutput instance that calls this method.
--- @param streamSource UnityEngine.Experimental.Animations.AnimationStreamSource The AnimationStreamSource to apply on this output.
function UnityEngine.Experimental.Animations.AnimationPlayableOutputExtensions.SetAnimationStreamSource(output, streamSource) end

--- Gets the priority index of the specified AnimationPlayableOutput.
--- @param output UnityEngine.Animations.AnimationPlayableOutput The AnimationPlayableOutput instance that calls this method.
--- @return number Returns the sorting order of the output.
function UnityEngine.Experimental.Animations.AnimationPlayableOutputExtensions.GetSortingOrder(output) end

--- Sets the sorting order for the specified AnimationPlayableOutput.
--- @param output UnityEngine.Animations.AnimationPlayableOutput The AnimationPlayableOutput instance that calls this method.
--- @param sortingOrder number The sorting order to apply to this output.
function UnityEngine.Experimental.Animations.AnimationPlayableOutputExtensions.SetSortingOrder(output, sortingOrder) end

---  Generated By xerysherry