--- @class UnityEngine.ParticleSystemAnimationTimeMode Control how animation frames are selected.
UnityEngine.ParticleSystemAnimationTimeMode = {
    --- Select animation frames based on the particle ages.
    Lifetime = 0,
    --- Select animation frames based on the particle speeds.
    Speed = 1,
    --- Select animation frames sequentially at a constant rate of the specified frames per second.
    FPS = 2,
}

---  Generated By xerysherry