--- @class UnityEngine.Networking.Types.SourceID Identifies a specific game instance.
UnityEngine.Networking.Types.SourceID = {
    --- Invalid SourceID.
    Invalid = 18446744073709551615,
}

---  Generated By xerysherry