--- @class UnityEngine.Assertions.AssertionException:System.Exception An exception that is thrown on a failure. Assertions.Assert._raiseExceptions needs to be set to true.
--- @field Message string
--- @field Data System.Collections.IDictionary
--- @field InnerException System.Exception
--- @field TargetSite System.Reflection.MethodBase
--- @field StackTrace string
--- @field HelpLink string
--- @field Source string
--- @field HResult number
UnityEngine.Assertions.AssertionException = {}

---  Generated By xerysherry