--- @class Unity.IO.LowLevel.Unsafe.AsyncReadManagerMetrics.Flags Flags controlling the behaviour of AsyncReadManagerMetrics.GetMetrics and AsyncReadManagerMetrics.GetCurrentSummaryMetrics.
Unity.IO.LowLevel.Unsafe.AsyncReadManagerMetrics.Flags = {
    --- Pass no flags.
    None = 0,
    --- Clear metrics for completed read requests after returning.
    ClearOnRead = 1,
}

--- @class Unity.IO.LowLevel.Unsafe.AsyncReadManagerMetrics.Flags Flags controlling the behaviour of AsyncReadManagerMetrics.GetMetrics and AsyncReadManagerMetrics.GetCurrentSummaryMetrics.
Unity.IO.LowLevel.Unsafe.AsyncReadManagerMetrics.Flags = {
    --- Pass no flags.
    None = 0,
    --- Clear metrics for completed read requests after returning.
    ClearOnRead = 1,
}

---  Generated By xerysherry