--- @class UnityEngine.HumanBodyBones Human Body Bones.
UnityEngine.HumanBodyBones = {
    --- This is the Hips bone.
    Hips = 0,
    --- This is the Left Upper Leg bone.
    LeftUpperLeg = 1,
    --- This is the Right Upper Leg bone.
    RightUpperLeg = 2,
    --- This is the Left Knee bone.
    LeftLowerLeg = 3,
    --- This is the Right Knee bone.
    RightLowerLeg = 4,
    --- This is the Left Ankle bone.
    LeftFoot = 5,
    --- This is the Right Ankle bone.
    RightFoot = 6,
    --- This is the first Spine bone.
    Spine = 7,
    --- This is the Chest bone.
    Chest = 8,
    --- This is the Upper Chest bone.
    UpperChest = 54,
    --- This is the Neck bone.
    Neck = 9,
    --- This is the Head bone.
    Head = 10,
    --- This is the Left Shoulder bone.
    LeftShoulder = 11,
    --- This is the Right Shoulder bone.
    RightShoulder = 12,
    --- This is the Left Upper Arm bone.
    LeftUpperArm = 13,
    --- This is the Right Upper Arm bone.
    RightUpperArm = 14,
    --- This is the Left Elbow bone.
    LeftLowerArm = 15,
    --- This is the Right Elbow bone.
    RightLowerArm = 16,
    --- This is the Left Wrist bone.
    LeftHand = 17,
    --- This is the Right Wrist bone.
    RightHand = 18,
    --- This is the Left Toes bone.
    LeftToes = 19,
    --- This is the Right Toes bone.
    RightToes = 20,
    --- This is the Left Eye bone.
    LeftEye = 21,
    --- This is the Right Eye bone.
    RightEye = 22,
    --- This is the Jaw bone.
    Jaw = 23,
    --- This is the left thumb 1st phalange.
    LeftThumbProximal = 24,
    --- This is the left thumb 2nd phalange.
    LeftThumbIntermediate = 25,
    --- This is the left thumb 3rd phalange.
    LeftThumbDistal = 26,
    --- This is the left index 1st phalange.
    LeftIndexProximal = 27,
    --- This is the left index 2nd phalange.
    LeftIndexIntermediate = 28,
    --- This is the left index 3rd phalange.
    LeftIndexDistal = 29,
    --- This is the left middle 1st phalange.
    LeftMiddleProximal = 30,
    --- This is the left middle 2nd phalange.
    LeftMiddleIntermediate = 31,
    --- This is the left middle 3rd phalange.
    LeftMiddleDistal = 32,
    --- This is the left ring 1st phalange.
    LeftRingProximal = 33,
    --- This is the left ring 2nd phalange.
    LeftRingIntermediate = 34,
    --- This is the left ring 3rd phalange.
    LeftRingDistal = 35,
    --- This is the left little 1st phalange.
    LeftLittleProximal = 36,
    --- This is the left little 2nd phalange.
    LeftLittleIntermediate = 37,
    --- This is the left little 3rd phalange.
    LeftLittleDistal = 38,
    --- This is the right thumb 1st phalange.
    RightThumbProximal = 39,
    --- This is the right thumb 2nd phalange.
    RightThumbIntermediate = 40,
    --- This is the right thumb 3rd phalange.
    RightThumbDistal = 41,
    --- This is the right index 1st phalange.
    RightIndexProximal = 42,
    --- This is the right index 2nd phalange.
    RightIndexIntermediate = 43,
    --- This is the right index 3rd phalange.
    RightIndexDistal = 44,
    --- This is the right middle 1st phalange.
    RightMiddleProximal = 45,
    --- This is the right middle 2nd phalange.
    RightMiddleIntermediate = 46,
    --- This is the right middle 3rd phalange.
    RightMiddleDistal = 47,
    --- This is the right ring 1st phalange.
    RightRingProximal = 48,
    --- This is the right ring 2nd phalange.
    RightRingIntermediate = 49,
    --- This is the right ring 3rd phalange.
    RightRingDistal = 50,
    --- This is the right little 1st phalange.
    RightLittleProximal = 51,
    --- This is the right little 2nd phalange.
    RightLittleIntermediate = 52,
    --- This is the right little 3rd phalange.
    RightLittleDistal = 53,
    --- This is the Last bone index delimiter.
    LastBone = 55,
}

---  Generated By xerysherry