--- @class UnityEngine.RigidbodyConstraints2D Use these flags to constrain motion of the Rigidbody2D.
UnityEngine.RigidbodyConstraints2D = {
    --- No constraints.
    None = 0,
    --- Freeze motion along the X-axis.
    FreezePositionX = 1,
    --- Freeze motion along the Y-axis.
    FreezePositionY = 2,
    --- Freeze rotation along the Z-axis.
    FreezeRotation = 4,
    --- Freeze motion along the X-axis and Y-axis.
    FreezePosition = 3,
    --- Freeze rotation and motion along all axes.
    FreezeAll = 7,
}

---  Generated By xerysherry