--- @class UnityEngine.Rendering.VideoShadersIncludeMode Video shaders mode used by Rendering.GraphicsSettings.
UnityEngine.Rendering.VideoShadersIncludeMode = {
    --- Exclude video shaders from builds. This effectively disables video functionality.
    Never = 0,
    --- Include video shaders in builds when referenced by scenes.
    Referenced = 1,
    --- Include video shaders in builds (default).
    Always = 2,
}

---  Generated By xerysherry