--- @class UnityEngine.Animations.AnimationMixerPlayable An implementation of IPlayable that controls an animation mixer.
--- @field Null UnityEngine.Animations.AnimationMixerPlayable property get
---       Returns an invalid AnimationMixerPlayable.
UnityEngine.Animations.AnimationMixerPlayable = {}

--- Creates an AnimationMixerPlayable in the PlayableGraph.
--- @param graph UnityEngine.Playables.PlayableGraph The PlayableGraph that will contain the new AnimationMixerPlayable.
--- @param inputCount number The number of inputs that the mixer will update.
--- @param normalizeWeights boolean NormalizeWeights is obsolete. It has no effect and will be removed.
--- @return UnityEngine.Animations.AnimationMixerPlayable Returns a new AnimationMixerPlayable linked to the PlayableGraph.
function UnityEngine.Animations.AnimationMixerPlayable.Create(graph, inputCount, normalizeWeights) end

--- Creates an AnimationMixerPlayable in the PlayableGraph.
--- @param graph UnityEngine.Playables.PlayableGraph The PlayableGraph that will contain the new AnimationMixerPlayable.
--- @param inputCount number The number of inputs that the mixer will update.
--- @return UnityEngine.Animations.AnimationMixerPlayable Returns a new AnimationMixerPlayable linked to the PlayableGraph.
function UnityEngine.Animations.AnimationMixerPlayable.Create(graph, inputCount) end

--- @return UnityEngine.Playables.Playable
function UnityEngine.Animations.AnimationMixerPlayable.op_Implicit(playable) end

--- @return UnityEngine.Animations.AnimationMixerPlayable
function UnityEngine.Animations.AnimationMixerPlayable.op_Explicit(playable) end

--- @return UnityEngine.Playables.PlayableHandle
function UnityEngine.Animations.AnimationMixerPlayable:GetHandle() end

--- @return boolean
function UnityEngine.Animations.AnimationMixerPlayable:Equals(other) end

---  Generated By xerysherry