--- @class UnityEngine.LensFlare:UnityEngine.Behaviour Script interface for a.
--- @field brightness number property getset
---       The strength of the flare.
--- @field fadeSpeed number property getset
---       The fade speed of the flare.
--- @field color UnityEngine.Color property getset
---       The color of the flare.
--- @field flare UnityEngine.Flare property getset
---       The to use.
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.LensFlare = {}

function UnityEngine.LensFlare:set_brightness(value) end

function UnityEngine.LensFlare:set_fadeSpeed(value) end

function UnityEngine.LensFlare:set_color(value) end

function UnityEngine.LensFlare:set_flare(value) end

---  Generated By xerysherry