--- 
---  A Foldout control is a collapsible section of a user interface. When toggled, it expands or collapses, which hides or reveals the elements it contains.
---  
--- @class UnityEngine.UIElements.Foldout:UnityEngine.UIElements.BindableElement
--- @field ussClassName string 
---        The USS class name for Foldout elements.
---        
--- @field toggleUssClassName string 
---        The USS class name of Toggle sub-elements in Foldout elements.
---        
--- @field contentUssClassName string 
---        The USS class name for the content element in a Foldout.
---        
--- @field contentContainer UnityEngine.UIElements.VisualElement property get
---       
---        This element contains the elements that are shown or hidden when you toggle the Foldout.
---        
--- @field text string property getset
---       
---        This is the text of the toggle's label.
---        
--- @field value boolean property getset
---       
---        This is the state of the Foldout's toggle. It is true if the Foldout is open and its contents are
---        visible, and false if the Foldout is closed, and its contents are hidden.
---        
--- @field binding UnityEngine.UIElements.IBinding
--- @field bindingPath string
--- @field viewDataKey string
--- @field userData System.Object
--- @field canGrabFocus boolean
--- @field focusController UnityEngine.UIElements.FocusController
--- @field usageHints UnityEngine.UIElements.UsageHints
--- @field transform UnityEngine.UIElements.ITransform
--- @field layout UnityEngine.Rect
--- @field contentRect UnityEngine.Rect
--- @field worldBound UnityEngine.Rect
--- @field localBound UnityEngine.Rect
--- @field worldTransform UnityEngine.Matrix4x4
--- @field pickingMode UnityEngine.UIElements.PickingMode
--- @field name string
--- @field enabledInHierarchy boolean
--- @field enabledSelf boolean
--- @field visible boolean
--- @field generateVisualContent function
--- @field experimental UnityEngine.UIElements.IExperimentalFeatures
--- @field hierarchy UnityEngine.UIElements.VisualElement.Hierarchy
--- @field cacheAsBitmap boolean
--- @field parent UnityEngine.UIElements.VisualElement
--- @field panel UnityEngine.UIElements.IPanel
--- @field visualTreeAssetSource UnityEngine.UIElements.VisualTreeAsset
--- @field Item UnityEngine.UIElements.VisualElement
--- @field childCount number
--- @field schedule UnityEngine.UIElements.IVisualElementScheduler
--- @field style UnityEngine.UIElements.IStyle
--- @field customStyle UnityEngine.UIElements.ICustomStyle
--- @field styleSheets UnityEngine.UIElements.VisualElementStyleSheetSet
--- @field tooltip string
--- @field resolvedStyle UnityEngine.UIElements.IResolvedStyle
--- @field focusable boolean
--- @field tabIndex number
--- @field delegatesFocus boolean
UnityEngine.UIElements.Foldout = {}

--- @param value string 
function UnityEngine.UIElements.Foldout:set_text(value) end

--- @param value boolean 
function UnityEngine.UIElements.Foldout:set_value(value) end

--- 
---  Sets the value of the Foldout's Toggle sub-element, but does not notify the rest of the hierarchy of the change.
---  
--- @param newValue boolean The new value of the foldout
function UnityEngine.UIElements.Foldout:SetValueWithoutNotify(newValue) end

---  Generated By xerysherry