--- @class UnityEngine.Android.AndroidAssetPackError Values that indicate the type of Android asset pack error when the status is either AndroidAssetPackStatus.Failed or AndroidAssetPackStatus.Unknown.
UnityEngine.Android.AndroidAssetPackError = {
    --- Indicates that there is no error.
    NoError = 0,
    --- Indicates that this application is unavailable in the Google's Play Store.
    AppUnavailable = -1,
    --- Indicates that the requested Android asset pack is not available in the Google Play Store.
    PackUnavailable = -2,
    --- Indicates that the request was invalid.
    InvalidRequest = -3,
    --- Indicates that the requested download is not found.
    DownloadNotFound = -4,
    --- Indicates that the Asset Delivery API is not available.
    ApiNotAvailable = -5,
    --- Indicates that the Android asset pack is not accessible because there was an error related to the network connection.
    NetworkError = -6,
    --- Indicates that the application does not have permission to download asset packs under the current device circumstances.
    AccessDenied = -7,
    --- Indicates that there is not enough storage space on the device to download the Android asset pack.
    InsufficientStorage = -10,
    --- Indicates that the device does not have the Play Store application installed or has an unofficial version.
    PlayStoreNotFound = -11,
    --- Indicates that the app requested to use mobile data while there were no Android asset packs waiting for WiFi.
    NetworkUnrestricted = -12,
    --- Indicates that the end user does not own the application on the device.
    AppNotOwned = -13,
    --- Indicates that unknown error occured while downloading an asset pack.
    InternalError = -100,
}

---  Generated By xerysherry