--- 
---  Represents a style sheet that's assembled from other style sheets.
---  
--- @class UnityEngine.UIElements.ThemeStyleSheet:UnityEngine.UIElements.StyleSheet
--- @field importedWithErrors boolean
--- @field importedWithWarnings boolean
--- @field contentHash number
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UIElements.ThemeStyleSheet = {}

---  Generated By xerysherry