--- @class UnityEngine.iOS.DeviceGeneration iOS device generation.
UnityEngine.iOS.DeviceGeneration = {
    Unknown = 0,
    --- iPhone, first generation.
    iPhone = 1,
    --- iPhone, second generation.
    iPhone3G = 2,
    --- iPhone, third generation.
    iPhone3GS = 3,
    --- iPod Touch, first generation.
    iPodTouch1Gen = 4,
    --- iPod Touch, second generation.
    iPodTouch2Gen = 5,
    --- iPod Touch, third generation.
    iPodTouch3Gen = 6,
    --- iPad, first generation.
    iPad1Gen = 7,
    --- iPhone, fourth generation.
    iPhone4 = 8,
    --- iPod Touch, fourth generation.
    iPodTouch4Gen = 9,
    --- iPad, second generation.
    iPad2Gen = 10,
    --- iPhone, fifth generation.
    iPhone4S = 11,
    --- iPad, third generation.
    iPad3Gen = 12,
    --- iPhone5.
    iPhone5 = 13,
    --- iPod Touch, fifth generation.
    iPodTouch5Gen = 14,
    --- iPad Mini, first generation.
    iPadMini1Gen = 15,
    --- iPad, fourth generation.
    iPad4Gen = 16,
    --- iPhone 5C.
    iPhone5C = 17,
    --- iPhone 5S.
    iPhone5S = 18,
    --- iPad Air.
    iPadAir1 = 19,
    --- iPad Mini, second generation.
    iPadMini2Gen = 20,
    --- iPhone 6.
    iPhone6 = 21,
    --- iPhone 6 plus.
    iPhone6Plus = 22,
    --- iPad Mini, third generation.
    iPadMini3Gen = 23,
    --- iPad Air 2.
    iPadAir2 = 24,
    --- iPhone 6S.
    iPhone6S = 25,
    --- iPhone 6S Plus.
    iPhone6SPlus = 26,
    --- iPad Pro 12.9", first generation.
    iPadPro1Gen = 27,
    --- iPad Mini, fourth generation.
    iPadMini4Gen = 28,
    --- iPhone SE, first generation.
    iPhoneSE1Gen = 29,
    --- iPad Pro 9.7", first generation.
    iPadPro10Inch1Gen = 30,
    --- iPhone 7.
    iPhone7 = 31,
    --- iPhone 7 Plus.
    iPhone7Plus = 32,
    --- iPod Touch, sixth generation.
    iPodTouch6Gen = 33,
    --- iPad, fifth generation.
    iPad5Gen = 34,
    --- iPad Pro 12.9", second generation.
    iPadPro2Gen = 35,
    --- iPad Pro 10.5", second generation 10" iPad.
    iPadPro10Inch2Gen = 36,
    --- iPhone 8.
    iPhone8 = 37,
    --- iPhone 8 Plus.
    iPhone8Plus = 38,
    --- iPhone X.
    iPhoneX = 39,
    --- iPhone XS.
    iPhoneXS = 40,
    --- iPhone XSMax.
    iPhoneXSMax = 41,
    --- iPhone XR.
    iPhoneXR = 42,
    --- iPad Pro 11", first generation.
    iPadPro11Inch = 43,
    --- iPad Pro 12.9", third generation.
    iPadPro3Gen = 44,
    --- iPad, sixth generation.
    iPad6Gen = 45,
    --- iPad Air, third generation.
    iPadAir3Gen = 46,
    --- iPad Mini, fifth generation.
    iPadMini5Gen = 47,
    --- iPhone 11.
    iPhone11 = 48,
    --- iPhone 11 Pro.
    iPhone11Pro = 49,
    --- iPhone 11 Pro Max.
    iPhone11ProMax = 50,
    --- iPod Touch, seventh generation.
    iPodTouch7Gen = 51,
    --- iPad, seventh generation.
    iPad7Gen = 52,
    --- iPhone SE, second generation.
    iPhoneSE2Gen = 53,
    --- iPad Pro 11", second generation.
    iPadPro11Inch2Gen = 54,
    --- iPad Pro 12.9", fourth generation.
    iPadPro4Gen = 55,
    --- iPhone 12 Mini.
    iPhone12Mini = 56,
    --- iPhone 12.
    iPhone12 = 57,
    --- iPhone 12 Pro.
    iPhone12Pro = 58,
    --- iPhone 12 Pro Max.
    iPhone12ProMax = 59,
    --- iPad, eighth generation.
    iPad8Gen = 60,
    --- iPad Air, fourth generation.
    iPadAir4Gen = 61,
    --- iPad, ninth generation.
    iPad9Gen = 62,
    --- iPad Mini, sixth generation.
    iPadMini6Gen = 63,
    --- iPhone 13.
    iPhone13 = 64,
    --- iPhone 13 Mini.
    iPhone13Mini = 65,
    --- iPhone 13 Pro.
    iPhone13Pro = 66,
    --- iPhone 13 Pro Max.
    iPhone13ProMax = 67,
    --- iPad Pro 12.9", fifth generation.
    iPadPro5Gen = 68,
    --- iPad Pro 11", third generation.
    iPadPro11Inch3Gen = 69,
    --- Yet unknown iPhone.
    iPhoneUnknown = 10001,
    --- Yet unknown iPad.
    iPadUnknown = 10002,
    --- Yet unknown iPod Touch.
    iPodTouchUnknown = 10003,
}

---  Generated By xerysherry