--- @class UnityEngine.UI.LayoutElement:UnityEngine.EventSystems.UIBehaviour 
--- @field ignoreLayout boolean
--- @field minWidth number
--- @field minHeight number
--- @field preferredWidth number
--- @field preferredHeight number
--- @field flexibleWidth number
--- @field flexibleHeight number
--- @field layoutPriority number
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.LayoutElement = {}

--- @param value boolean 
function UnityEngine.UI.LayoutElement:set_ignoreLayout(value) end

function UnityEngine.UI.LayoutElement:CalculateLayoutInputHorizontal() end

function UnityEngine.UI.LayoutElement:CalculateLayoutInputVertical() end

--- @param value number 
function UnityEngine.UI.LayoutElement:set_minWidth(value) end

--- @param value number 
function UnityEngine.UI.LayoutElement:set_minHeight(value) end

--- @param value number 
function UnityEngine.UI.LayoutElement:set_preferredWidth(value) end

--- @param value number 
function UnityEngine.UI.LayoutElement:set_preferredHeight(value) end

--- @param value number 
function UnityEngine.UI.LayoutElement:set_flexibleWidth(value) end

--- @param value number 
function UnityEngine.UI.LayoutElement:set_flexibleHeight(value) end

--- @param value number 
function UnityEngine.UI.LayoutElement:set_layoutPriority(value) end

---  Generated By xerysherry