--- @class UnityEngine.Windows.Speech.DictationRecognizer DictationRecognizer listens to speech input and attempts to determine what phrase was uttered.
--- @field Status UnityEngine.Windows.Speech.SpeechSystemStatus property get
---       Indicates the status of dictation recognizer.
--- @field AutoSilenceTimeoutSeconds number property getset
---       The time length in seconds before dictation recognizer session ends due to lack of audio input.
--- @field InitialSilenceTimeoutSeconds number property getset
---       The time length in seconds before dictation recognizer session ends due to lack of audio input in case there was no audio heard in the current session.
UnityEngine.Windows.Speech.DictationRecognizer = {}

function UnityEngine.Windows.Speech.DictationRecognizer:add_DictationHypothesis(value) end

function UnityEngine.Windows.Speech.DictationRecognizer:remove_DictationHypothesis(value) end

function UnityEngine.Windows.Speech.DictationRecognizer:add_DictationResult(value) end

function UnityEngine.Windows.Speech.DictationRecognizer:remove_DictationResult(value) end

function UnityEngine.Windows.Speech.DictationRecognizer:add_DictationComplete(value) end

function UnityEngine.Windows.Speech.DictationRecognizer:remove_DictationComplete(value) end

function UnityEngine.Windows.Speech.DictationRecognizer:add_DictationError(value) end

function UnityEngine.Windows.Speech.DictationRecognizer:remove_DictationError(value) end

function UnityEngine.Windows.Speech.DictationRecognizer:set_AutoSilenceTimeoutSeconds(value) end

function UnityEngine.Windows.Speech.DictationRecognizer:set_InitialSilenceTimeoutSeconds(value) end

--- Starts the dictation recognization session. Dictation recognizer can only be started if PhraseRecognitionSystem is not running.
function UnityEngine.Windows.Speech.DictationRecognizer:Start() end

--- Stops the dictation recognization session.
function UnityEngine.Windows.Speech.DictationRecognizer:Stop() end

--- Disposes the resources this dictation recognizer uses.
function UnityEngine.Windows.Speech.DictationRecognizer:Dispose() end

---  Generated By xerysherry