--- @class UnityEngine.SliderJoint2D:UnityEngine.AnchoredJoint2D Joint that restricts the motion of a Rigidbody2D object to a single line.
--- @field autoConfigureAngle boolean property getset
---       Should the angle be calculated automatically?
--- @field angle number property getset
---       The angle of the line in space (in degrees).
--- @field useMotor boolean property getset
---       Should a motor force be applied automatically to the Rigidbody2D?
--- @field useLimits boolean property getset
---       Should motion limits be used?
--- @field motor UnityEngine.JointMotor2D property getset
---       Parameters for a motor force that is applied automatically to the Rigibody2D along the line.
--- @field limits UnityEngine.JointTranslationLimits2D property getset
---       Restrictions on how far the joint can slide in each direction along the line.
--- @field limitState UnityEngine.JointLimitState2D property get
---       Gets the state of the joint limit.
--- @field referenceAngle number property get
---       The angle (in degrees) referenced between the two bodies used as the constraint for the joint.
--- @field jointTranslation number property get
---       The current joint translation.
--- @field jointSpeed number property get
---       The current joint speed.
--- @field anchor UnityEngine.Vector2
--- @field connectedAnchor UnityEngine.Vector2
--- @field autoConfigureConnectedAnchor boolean
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field connectedBody UnityEngine.Rigidbody2D
--- @field enableCollision boolean
--- @field breakForce number
--- @field breakTorque number
--- @field reactionForce UnityEngine.Vector2
--- @field reactionTorque number
--- @field collideConnected boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.SliderJoint2D = {}

--- @param value boolean 
function UnityEngine.SliderJoint2D:set_autoConfigureAngle(value) end

--- @param value number 
function UnityEngine.SliderJoint2D:set_angle(value) end

--- @param value boolean 
function UnityEngine.SliderJoint2D:set_useMotor(value) end

--- @param value boolean 
function UnityEngine.SliderJoint2D:set_useLimits(value) end

--- @param value UnityEngine.JointMotor2D 
function UnityEngine.SliderJoint2D:set_motor(value) end

--- @param value UnityEngine.JointTranslationLimits2D 
function UnityEngine.SliderJoint2D:set_limits(value) end

--- Gets the motor force of the joint given the specified timestep.
--- @param timeStep number The time to calculate the motor force for.
--- @return number 
function UnityEngine.SliderJoint2D:GetMotorForce(timeStep) end

---  Generated By xerysherry