--- 
---  Specifies how the text Element treats hidden overflow content.
---  
--- @class UnityEngine.UIElements.TextOverflow
UnityEngine.UIElements.TextOverflow = {
    --- 
    ---  The Element clips overflow content and hides it. This is the default value.
    ---  
    Clip = 0,
    --- 
    ---  The Element clips overflow content and hides it, but displays an ellipsis ("...") to indicate that clipped content exists.
    ---  
    Ellipsis = 1,
}

---  Generated By xerysherry