--- @class UnityEngine.Rendering.VirtualTexturing.EditorHelpers 
UnityEngine.Rendering.VirtualTexturing.EditorHelpers = {}

--- @return boolean
function UnityEngine.Rendering.VirtualTexturing.EditorHelpers.ValidateTextureStack(textures) end

--- @return UnityEngine.Experimental.Rendering.GraphicsFormat[]
function UnityEngine.Rendering.VirtualTexturing.EditorHelpers.QuerySupportedFormats() end

---  Generated By xerysherry