--- @class UnityEngine.Camera.RenderRequestOutputSpace Defines in which space render requests will be be outputted.
UnityEngine.Camera.RenderRequestOutputSpace = {
    --- RenderRequests will be rendered in screenspace from the perspective of the camera.
    ScreenSpace = -1,
    --- RenderRequests will be outputted in UV 0 space of the rendered mesh.
    UV0 = 0,
    --- RenderRequests will be outputted in UV 1 space of the rendered mesh.
    UV1 = 1,
    --- RenderRequests will be outputted in UV 2 space of the rendered mesh.
    UV2 = 2,
    --- RenderRequests will be outputted in UV 3 space of the rendered mesh.
    UV3 = 3,
    --- RenderRequests will be outputted in UV 4 space of the rendered mesh.
    UV4 = 4,
    --- RenderRequests will be outputted in UV 5 space of the rendered mesh.
    UV5 = 5,
    --- RenderRequests will be outputted in UV 6 space of the rendered mesh.
    UV6 = 6,
    --- RenderRequests will be outputted in UV 7 space of the rendered mesh.
    UV7 = 7,
    --- RenderRequests will be outputted in UV 8 space of the rendered mesh.
    UV8 = 8,
}

--- @class UnityEngine.Camera.RenderRequestOutputSpace Defines in which space render requests will be be outputted.
UnityEngine.Camera.RenderRequestOutputSpace = {
    --- RenderRequests will be rendered in screenspace from the perspective of the camera.
    ScreenSpace = -1,
    --- RenderRequests will be outputted in UV 0 space of the rendered mesh.
    UV0 = 0,
    --- RenderRequests will be outputted in UV 1 space of the rendered mesh.
    UV1 = 1,
    --- RenderRequests will be outputted in UV 2 space of the rendered mesh.
    UV2 = 2,
    --- RenderRequests will be outputted in UV 3 space of the rendered mesh.
    UV3 = 3,
    --- RenderRequests will be outputted in UV 4 space of the rendered mesh.
    UV4 = 4,
    --- RenderRequests will be outputted in UV 5 space of the rendered mesh.
    UV5 = 5,
    --- RenderRequests will be outputted in UV 6 space of the rendered mesh.
    UV6 = 6,
    --- RenderRequests will be outputted in UV 7 space of the rendered mesh.
    UV7 = 7,
    --- RenderRequests will be outputted in UV 8 space of the rendered mesh.
    UV8 = 8,
}

---  Generated By xerysherry