--- @class UnityEngine.TextCore.Text.FontAsset:UnityEngine.TextCore.Text.TextAsset 
--- @field sourceFontFile UnityEngine.Font
--- @field atlasPopulationMode UnityEngine.TextCore.Text.AtlasPopulationMode
--- @field faceInfo UnityEngine.TextCore.FaceInfo
--- @field fontWeightTable UnityEngine.TextCore.Text.FontWeightPair[]
--- @field glyphTable UnityEngine.TextCore.Glyph[]
--- @field glyphLookupTable table<number, UnityEngine.TextCore.Glyph>
--- @field characterTable UnityEngine.TextCore.Text.Character[]
--- @field characterLookupTable table<number, UnityEngine.TextCore.Text.Character>
--- @field atlasTexture UnityEngine.Texture2D
--- @field atlasTextures UnityEngine.Texture2D[]
--- @field atlasTextureCount number
--- @field isMultiAtlasTexturesEnabled boolean
--- @field atlasWidth number
--- @field atlasHeight number
--- @field atlasPadding number
--- @field atlasRenderMode UnityEngine.TextCore.LowLevel.GlyphRenderMode
--- @field fontFeatureTable UnityEngine.TextCore.Text.FontFeatureTable
--- @field fallbackFontAssetTable UnityEngine.TextCore.Text.FontAsset[]
--- @field fontAssetCreationEditorSettings UnityEngine.TextCore.Text.FontAssetCreationEditorSettings
--- @field regularStyleWeight number
--- @field regularStyleSpacing number
--- @field boldStyleWeight number
--- @field boldStyleSpacing number
--- @field italicStyleSlant number
--- @field tabMultiple number
--- @field version string
--- @field instanceID number
--- @field hashCode number
--- @field material UnityEngine.Material
--- @field materialHashCode number
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.TextCore.Text.FontAsset = {}

--- @return UnityEngine.TextCore.Text.FontAsset
function UnityEngine.TextCore.Text.FontAsset.CreateFontAsset(familyName, styleName, pointSize) end

--- @return UnityEngine.TextCore.Text.FontAsset
function UnityEngine.TextCore.Text.FontAsset.CreateFontAsset(font) end

--- @return UnityEngine.TextCore.Text.FontAsset
function UnityEngine.TextCore.Text.FontAsset.CreateFontAsset(font, samplingPointSize, atlasPadding, renderMode, atlasWidth, atlasHeight, atlasPopulationMode, enableMultiAtlasSupport) end

--- @return string
function UnityEngine.TextCore.Text.FontAsset.GetCharacters(fontAsset) end

--- @return number[]
function UnityEngine.TextCore.Text.FontAsset.GetCharactersArray(fontAsset) end

function UnityEngine.TextCore.Text.FontAsset:set_atlasPopulationMode(value) end

function UnityEngine.TextCore.Text.FontAsset:set_faceInfo(value) end

function UnityEngine.TextCore.Text.FontAsset:set_atlasTextures(value) end

function UnityEngine.TextCore.Text.FontAsset:set_isMultiAtlasTexturesEnabled(value) end

function UnityEngine.TextCore.Text.FontAsset:set_fallbackFontAssetTable(value) end

function UnityEngine.TextCore.Text.FontAsset:set_fontAssetCreationEditorSettings(value) end

function UnityEngine.TextCore.Text.FontAsset:set_regularStyleWeight(value) end

function UnityEngine.TextCore.Text.FontAsset:set_regularStyleSpacing(value) end

function UnityEngine.TextCore.Text.FontAsset:set_boldStyleWeight(value) end

function UnityEngine.TextCore.Text.FontAsset:set_boldStyleSpacing(value) end

function UnityEngine.TextCore.Text.FontAsset:set_italicStyleSlant(value) end

function UnityEngine.TextCore.Text.FontAsset:set_tabMultiple(value) end

function UnityEngine.TextCore.Text.FontAsset:ReadFontAssetDefinition() end

--- @return boolean
function UnityEngine.TextCore.Text.FontAsset:HasCharacter(character) end

--- @return boolean
function UnityEngine.TextCore.Text.FontAsset:HasCharacter(character, searchFallbacks, tryAddCharacter) end

--- @return boolean
function UnityEngine.TextCore.Text.FontAsset:HasCharacters(text) end

--- @return boolean
function UnityEngine.TextCore.Text.FontAsset:HasCharacters(text, searchFallbacks, tryAddCharacter) end

--- @return boolean
function UnityEngine.TextCore.Text.FontAsset:HasCharacters(text) end

--- @return boolean
function UnityEngine.TextCore.Text.FontAsset:TryAddCharacters(unicodes, includeFontFeatures) end

--- @return boolean
function UnityEngine.TextCore.Text.FontAsset:TryAddCharacters(unicodes, includeFontFeatures) end

--- @return boolean
function UnityEngine.TextCore.Text.FontAsset:TryAddCharacters(characters, includeFontFeatures) end

--- @return boolean
function UnityEngine.TextCore.Text.FontAsset:TryAddCharacters(characters, includeFontFeatures) end

function UnityEngine.TextCore.Text.FontAsset:ClearFontAssetData(setAtlasSizeToZero) end

---  Generated By xerysherry