--- @class UnityEngine.BuoyancyEffector2D:UnityEngine.Effector2D Applies forces to simulate buoyancy, fluid-flow and fluid drag.
--- @field surfaceLevel number property getset
---       Defines an arbitrary horizontal line that represents the fluid surface level.
--- @field density number property getset
---       The density of the fluid used to calculate the buoyancy forces.
--- @field linearDrag number property getset
---       A force applied to slow linear movement of any Collider2D in contact with the effector.
--- @field angularDrag number property getset
---       A force applied to slow angular movement of any Collider2D in contact with the effector.
--- @field flowAngle number property getset
---       The angle of the force used to similate fluid flow.
--- @field flowMagnitude number property getset
---       The magnitude of the force used to similate fluid flow.
--- @field flowVariation number property getset
---       The random variation of the force used to similate fluid flow.
--- @field useColliderMask boolean
--- @field colliderMask number
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.BuoyancyEffector2D = {}

--- @param value number 
function UnityEngine.BuoyancyEffector2D:set_surfaceLevel(value) end

--- @param value number 
function UnityEngine.BuoyancyEffector2D:set_density(value) end

--- @param value number 
function UnityEngine.BuoyancyEffector2D:set_linearDrag(value) end

--- @param value number 
function UnityEngine.BuoyancyEffector2D:set_angularDrag(value) end

--- @param value number 
function UnityEngine.BuoyancyEffector2D:set_flowAngle(value) end

--- @param value number 
function UnityEngine.BuoyancyEffector2D:set_flowMagnitude(value) end

--- @param value number 
function UnityEngine.BuoyancyEffector2D:set_flowVariation(value) end

---  Generated By xerysherry