--- @class UnityEngine.Playables.PlayableOutput See: Playables.IPlayableOutput.
--- @field Null UnityEngine.Playables.PlayableOutput property get
---       Returns an invalid PlayableOutput.
UnityEngine.Playables.PlayableOutput = {}

--- @return UnityEngine.Playables.PlayableOutputHandle
function UnityEngine.Playables.PlayableOutput:GetHandle() end

--- @return boolean
function UnityEngine.Playables.PlayableOutput:IsPlayableOutputOfType() end

--- @return System.Type
function UnityEngine.Playables.PlayableOutput:GetPlayableOutputType() end

--- @return boolean
function UnityEngine.Playables.PlayableOutput:Equals(other) end

---  Generated By xerysherry