--- @class UnityEngine.U2D.SpriteAtlas:UnityEngine.Object Sprite Atlas is an asset created within Unity. It is part of the built-in sprite packing solution.
--- @field isVariant boolean property get
---       Return true if this SpriteAtlas is a variant.
--- @field tag string property get
---       Get the tag of this SpriteAtlas.
--- @field spriteCount number property get
---       Get the total number of Sprite packed into this atlas.
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.U2D.SpriteAtlas = {}

--- Return true if Sprite is packed into this SpriteAtlas.
--- @param sprite UnityEngine.Sprite 
--- @return boolean 
function UnityEngine.U2D.SpriteAtlas:CanBindTo(sprite) end

--- @return boolean
function UnityEngine.U2D.SpriteAtlas:IsPlaceholder() end

--- Clone the first Sprite in this atlas that matches the name packed in this atlas and return it.
--- @param name string The name of the Sprite.
--- @return UnityEngine.Sprite 
function UnityEngine.U2D.SpriteAtlas:GetSprite(name) end

--- Clone all the Sprite in this atlas and fill them into the supplied array.
--- @param sprites UnityEngine.Sprite[] Array of Sprite that will be filled.
--- @return number The size of the returned array.
function UnityEngine.U2D.SpriteAtlas:GetSprites(sprites) end

--- Clone all the Sprite matching the name in this atlas and fill them into the supplied array.
--- @param sprites UnityEngine.Sprite[] Array of Sprite that will be filled.
--- @param name string The name of the Sprite.
--- @return number 
function UnityEngine.U2D.SpriteAtlas:GetSprites(sprites, name) end

---  Generated By xerysherry