--- @class UnityEngine.UI.CanvasScaler:UnityEngine.EventSystems.UIBehaviour 
--- @field uiScaleMode UnityEngine.UI.CanvasScaler.ScaleMode
--- @field referencePixelsPerUnit number
--- @field scaleFactor number
--- @field referenceResolution UnityEngine.Vector2
--- @field screenMatchMode UnityEngine.UI.CanvasScaler.ScreenMatchMode
--- @field matchWidthOrHeight number
--- @field physicalUnit UnityEngine.UI.CanvasScaler.Unit
--- @field fallbackScreenDPI number
--- @field defaultSpriteDPI number
--- @field dynamicPixelsPerUnit number
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.CanvasScaler = {}

function UnityEngine.UI.CanvasScaler:set_uiScaleMode(value) end

function UnityEngine.UI.CanvasScaler:set_referencePixelsPerUnit(value) end

function UnityEngine.UI.CanvasScaler:set_scaleFactor(value) end

function UnityEngine.UI.CanvasScaler:set_referenceResolution(value) end

function UnityEngine.UI.CanvasScaler:set_screenMatchMode(value) end

function UnityEngine.UI.CanvasScaler:set_matchWidthOrHeight(value) end

function UnityEngine.UI.CanvasScaler:set_physicalUnit(value) end

function UnityEngine.UI.CanvasScaler:set_fallbackScreenDPI(value) end

function UnityEngine.UI.CanvasScaler:set_defaultSpriteDPI(value) end

function UnityEngine.UI.CanvasScaler:set_dynamicPixelsPerUnit(value) end

---  Generated By xerysherry