--- @class UnityEngine.ScaleMode Scaling mode to draw textures with.
UnityEngine.ScaleMode = {
    --- Stretches the texture to fill the complete rectangle passed in to GUI.DrawTexture.
    StretchToFill = 0,
    --- Scales the texture, maintaining aspect ratio, so it completely covers the position rectangle passed to GUI.DrawTexture. If the texture is being draw to a rectangle with a different aspect ratio than the original, the image is cropped.
    ScaleAndCrop = 1,
    --- Scales the texture, maintaining aspect ratio, so it completely fits withing the position rectangle passed to GUI.DrawTexture.
    ScaleToFit = 2,
}

---  Generated By xerysherry