--- 
---  A class that represents the vertex and index data allocated for drawing the content of a VisualElement.
---  
--- @class UnityEngine.UIElements.MeshWriteData
--- @field vertexCount number property get
---       
---        The number of vertices successfully allocated for VisualElement content drawing.
---        
--- @field indexCount number property get
---       
---        The number of indices successfully allocated for VisualElement content drawing.
---        
--- @field uvRegion UnityEngine.Rect property get
---       
---        A rectangle describing the UV region holding the texture passed to MeshGenerationContext.Allocate.
---        
UnityEngine.UIElements.MeshWriteData = {}

--- 
---  Assigns the value of the next vertex of the allocated vertices list.
---  
--- @param vertex UnityEngine.UIElements.Vertex The value of the next vertex.
function UnityEngine.UIElements.MeshWriteData:SetNextVertex(vertex) end

--- 
---  Assigns the value of the next index of the allocated indices list.
---  
--- @param index number The value of the next index.
function UnityEngine.UIElements.MeshWriteData:SetNextIndex(index) end

--- 
---  Fills the values of the allocated vertices with values copied directly from an array.
---  When this method is called, it is not possible to use SetNextVertex to fill the allocated vertices array.
---  
--- @param vertices UnityEngine.UIElements.Vertex[] The array of vertices to copy from. The length of the array must match the allocated vertex count.
function UnityEngine.UIElements.MeshWriteData:SetAllVertices(vertices) end

--- 
---  Fills the values of the allocated vertices with values copied directly from an array.
---  When this method is called, it is not possible to use SetNextVertex to fill the allocated vertices array.
---  
--- @param vertices Unity.Collections.NativeSlice`1 The array of vertices to copy from. The length of the array must match the allocated vertex count.
function UnityEngine.UIElements.MeshWriteData:SetAllVertices(vertices) end

--- 
---  Fills the values of the allocated indices with values copied directly from an array. Each 3 consecutive indices form a single triangle.
---  
--- @param indices number[] The array of indices to copy from. The length of the array must match the allocated index count.
function UnityEngine.UIElements.MeshWriteData:SetAllIndices(indices) end

--- 
---  Fills the values of the allocated indices with values copied directly from an array. Each 3 consecutive indices form a single triangle.
---  
--- @param indices Unity.Collections.NativeSlice`1 The array of indices to copy from. The length of the array must match the allocated index count.
function UnityEngine.UIElements.MeshWriteData:SetAllIndices(indices) end

---  Generated By xerysherry