--- @class UnityEngine.iOS.NotificationType Specifies local and remote notification types.
UnityEngine.iOS.NotificationType = {
    --- No notification types specified.
    None = 0,
    --- Notification is a badge shown above the application's icon.
    Badge = 1,
    --- Notification is an alert sound.
    Sound = 2,
    --- Notification is an alert message.
    Alert = 4,
}

---  Generated By xerysherry