--- @class UnityEngine.U2D.SpriteBone Stores a set of information that describes the bind pose of this Sprite.
--- @field name string property getset
---       The name of the bone. This is useful when recreating bone hierarchy at editor or runtime. You can also use this as a way of resolving the bone path when a Sprite is bound to a more complex or richer hierarchy.
--- @field guid string property getset
---       The Unique GUID of this bone.
--- @field position UnityEngine.Vector3 property getset
---       The position in local space of this bone.
--- @field rotation UnityEngine.Quaternion property getset
---       The rotation of this bone in local space.
--- @field length number property getset
---       The length of the bone. This is important for the leaf bones to describe their length without needing another bone as the terminal bone.
--- @field parentId number property getset
---       The ID of the parent of this bone.
--- @field color UnityEngine.Color32 property getset
---       Shows the color set for the bone in the Editor.
UnityEngine.U2D.SpriteBone = {}

--- @param value string 
function UnityEngine.U2D.SpriteBone:set_name(value) end

--- @param value string 
function UnityEngine.U2D.SpriteBone:set_guid(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.U2D.SpriteBone:set_position(value) end

--- @param value UnityEngine.Quaternion 
function UnityEngine.U2D.SpriteBone:set_rotation(value) end

--- @param value number 
function UnityEngine.U2D.SpriteBone:set_length(value) end

--- @param value number 
function UnityEngine.U2D.SpriteBone:set_parentId(value) end

--- @param value UnityEngine.Color32 
function UnityEngine.U2D.SpriteBone:set_color(value) end

---  Generated By xerysherry