--- @class UnityEngine.Animations.CustomStreamPropertyType The type of custom stream property to create using BindCustomStreamProperty
UnityEngine.Animations.CustomStreamPropertyType = {
    --- A float value.
    Float = 5,
    --- A boolean value.
    Bool = 6,
    --- An integer value.
    Int = 10,
}

---  Generated By xerysherry