--- @class UnityEngine.ShadowResolution Default shadow resolution.
UnityEngine.ShadowResolution = {
    --- Low shadow map resolution.
    Low = 0,
    --- Medium shadow map resolution.
    Medium = 1,
    --- High shadow map resolution.
    High = 2,
    --- Very high shadow map resolution.
    VeryHigh = 3,
}

---  Generated By xerysherry