--- @class UnityEngine.TextCore.Text.TextStyle 
--- @field NormalStyle UnityEngine.TextCore.Text.TextStyle
--- @field name string
--- @field hashCode number
--- @field styleOpeningDefinition string
--- @field styleClosingDefinition string
--- @field styleOpeningTagArray number[]
--- @field styleClosingTagArray number[]
UnityEngine.TextCore.Text.TextStyle = {}

function UnityEngine.TextCore.Text.TextStyle:set_name(value) end

function UnityEngine.TextCore.Text.TextStyle:set_hashCode(value) end

function UnityEngine.TextCore.Text.TextStyle:RefreshStyle() end

---  Generated By xerysherry