--- @class UnityEngine.Joint:UnityEngine.Component Joint is the base class for all joints.
--- @field connectedBody UnityEngine.Rigidbody property getset
---       A reference to another rigidbody this joint connects to.
--- @field connectedArticulationBody UnityEngine.ArticulationBody property getset
---       A reference to an articulation body this joint connects to.
--- @field axis UnityEngine.Vector3 property getset
---       The Direction of the axis around which the body is constrained.
--- @field anchor UnityEngine.Vector3 property getset
---       The Position of the anchor around which the joints motion is constrained.
--- @field connectedAnchor UnityEngine.Vector3 property getset
---       Position of the anchor relative to the connected Rigidbody.
--- @field autoConfigureConnectedAnchor boolean property getset
---       Should the connectedAnchor be calculated automatically?
--- @field breakForce number property getset
---       The force that needs to be applied for this joint to break.
--- @field breakTorque number property getset
---       The torque that needs to be applied for this joint to break. To be able to break, a joint must be _Locked_ or _Limited_ on the axis of rotation where the torque is being applied. This means that some joints cannot break, such as an unconstrained Configurable Joint.
--- @field enableCollision boolean property getset
---       Enable collision between bodies connected with the joint.
--- @field enablePreprocessing boolean property getset
---       Toggle preprocessing for this joint.
--- @field massScale number property getset
---       The scale to apply to the inverse mass and inertia tensor of the body prior to solving the constraints.
--- @field connectedMassScale number property getset
---       The scale to apply to the inverse mass and inertia tensor of the connected body prior to solving the constraints.
--- @field currentForce UnityEngine.Vector3 property get
---       The force applied by the solver to satisfy all constraints.
--- @field currentTorque UnityEngine.Vector3 property get
---       The torque applied by the solver to satisfy all constraints.
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Joint = {}

function UnityEngine.Joint:set_connectedBody(value) end

function UnityEngine.Joint:set_connectedArticulationBody(value) end

function UnityEngine.Joint:set_axis(value) end

function UnityEngine.Joint:set_anchor(value) end

function UnityEngine.Joint:set_connectedAnchor(value) end

function UnityEngine.Joint:set_autoConfigureConnectedAnchor(value) end

function UnityEngine.Joint:set_breakForce(value) end

function UnityEngine.Joint:set_breakTorque(value) end

function UnityEngine.Joint:set_enableCollision(value) end

function UnityEngine.Joint:set_enablePreprocessing(value) end

function UnityEngine.Joint:set_massScale(value) end

function UnityEngine.Joint:set_connectedMassScale(value) end

---  Generated By xerysherry