--- @class UnityEngine.ConstantForce2D:UnityEngine.PhysicsUpdateBehaviour2D Applies both linear and angular (torque) forces continuously to the rigidbody each physics update.
--- @field force UnityEngine.Vector2 property getset
---       The linear force applied to the rigidbody each physics update.
--- @field relativeForce UnityEngine.Vector2 property getset
---       The linear force, relative to the rigid-body coordinate system, applied each physics update.
--- @field torque number property getset
---       The torque applied to the rigidbody each physics update.
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.ConstantForce2D = {}

--- @param value UnityEngine.Vector2 
function UnityEngine.ConstantForce2D:set_force(value) end

--- @param value UnityEngine.Vector2 
function UnityEngine.ConstantForce2D:set_relativeForce(value) end

--- @param value number 
function UnityEngine.ConstantForce2D:set_torque(value) end

---  Generated By xerysherry