--- @class UnityEngine.AI.NavMeshData:UnityEngine.Object Contains and represents NavMesh data.
--- @field sourceBounds UnityEngine.Bounds property get
---       Returns the bounding volume of the input geometry used to build this NavMesh (Read Only).
--- @field position UnityEngine.Vector3 property getset
---       Gets or sets the world space position of the NavMesh data.
--- @field rotation UnityEngine.Quaternion property getset
---       Gets or sets the orientation of the NavMesh data.
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.AI.NavMeshData = {}

function UnityEngine.AI.NavMeshData:set_position(value) end

function UnityEngine.AI.NavMeshData:set_rotation(value) end

---  Generated By xerysherry