--- @class UnityEngine.HostData This is the data structure for holding individual host information.
--- @field useNat boolean property getset
---       Does this server require NAT punchthrough?
--- @field gameType string property getset
---       The type of the game (like "MyUniqueGameType").
--- @field gameName string property getset
---       The name of the game (like John Doe's Game).
--- @field connectedPlayers number property getset
---       Currently connected players.
--- @field playerLimit number property getset
---       Maximum players limit.
--- @field ip string[] property getset
---       Server IP address.
--- @field port number property getset
---       Server port.
--- @field passwordProtected boolean property getset
---       Does the server require a password?
--- @field comment string property getset
---       A miscellaneous comment (can hold data).
--- @field guid string property getset
---       The GUID of the host, needed when connecting with NAT punchthrough.
UnityEngine.HostData = {}

--- @param value boolean 
function UnityEngine.HostData:set_useNat(value) end

--- @param value string 
function UnityEngine.HostData:set_gameType(value) end

--- @param value string 
function UnityEngine.HostData:set_gameName(value) end

--- @param value number 
function UnityEngine.HostData:set_connectedPlayers(value) end

--- @param value number 
function UnityEngine.HostData:set_playerLimit(value) end

--- @param value string[] 
function UnityEngine.HostData:set_ip(value) end

--- @param value number 
function UnityEngine.HostData:set_port(value) end

--- @param value boolean 
function UnityEngine.HostData:set_passwordProtected(value) end

--- @param value string 
function UnityEngine.HostData:set_comment(value) end

--- @param value string 
function UnityEngine.HostData:set_guid(value) end

---  Generated By xerysherry