--- 
---  VisualElementExtensions is a set of extension methods useful for VisualElement.
---  
--- @class UnityEngine.UIElements.VisualElementExtensions
UnityEngine.UIElements.VisualElementExtensions = {}

--- 
---  Aligns a VisualElement's left, top, right and bottom edges with the corresponding edges of its parent.
---  
--- @param elem UnityEngine.UIElements.VisualElement The element to be aligned with its parent
function UnityEngine.UIElements.VisualElementExtensions.StretchToParentSize(elem) end

--- 
---  Aligns a VisualElement's left and right edges with the corresponding edges of its parent.
---  
--- @param elem UnityEngine.UIElements.VisualElement The element to be aligned with its parent
function UnityEngine.UIElements.VisualElementExtensions.StretchToParentWidth(elem) end

--- 
---  Add a manipulator associated to a VisualElement.
---  
--- @param ele UnityEngine.UIElements.VisualElement VisualElement associated to the manipulator.
--- @param manipulator UnityEngine.UIElements.IManipulator Manipulator to be added to the VisualElement.
function UnityEngine.UIElements.VisualElementExtensions.AddManipulator(ele, manipulator) end

--- 
---  Remove a manipulator associated to a VisualElement.
---  
--- @param ele UnityEngine.UIElements.VisualElement VisualElement associated to the manipulator.
--- @param manipulator UnityEngine.UIElements.IManipulator Manipulator to be removed from the VisualElement.
function UnityEngine.UIElements.VisualElementExtensions.RemoveManipulator(ele, manipulator) end

--- 
---  Transforms a point from the world space to the local space of the element.
---  
--- @param ele UnityEngine.UIElements.VisualElement The element to use as a reference for the local space.
--- @param p UnityEngine.Vector2 The point to transform, in world space.
--- @return UnityEngine.Vector2 A point in the local space of the element.
function UnityEngine.UIElements.VisualElementExtensions.WorldToLocal(ele, p) end

--- 
---  Transforms a point from the local space of the element to the world space.
---  
--- @param ele UnityEngine.UIElements.VisualElement The element to use as a reference for the local space.
--- @param p UnityEngine.Vector2 The point to transform, in local space.
--- @return UnityEngine.Vector2 A point in the world space.
function UnityEngine.UIElements.VisualElementExtensions.LocalToWorld(ele, p) end

--- 
---  Transforms a rectangle from the world space to the local space of the element.
---  
--- @param ele UnityEngine.UIElements.VisualElement The element to use as a reference for the local space.
--- @param r UnityEngine.Rect The rectangle to transform, in world space.
--- @return UnityEngine.Rect A rectangle in the local space of the element.
function UnityEngine.UIElements.VisualElementExtensions.WorldToLocal(ele, r) end

--- 
---  Transforms a rectangle from the local space of the element to the world space.
---  
--- @param ele UnityEngine.UIElements.VisualElement The element to use as a reference for the local space.
--- @param r UnityEngine.Rect The rectangle to transform, in local space.
--- @return UnityEngine.Rect A rectangle in the world space.
function UnityEngine.UIElements.VisualElementExtensions.LocalToWorld(ele, r) end

--- 
---  Transforms a point from the local space of an element to the local space of another element.
---  
--- @param src UnityEngine.UIElements.VisualElement The element to use as a reference as the source local space.
--- @param dest UnityEngine.UIElements.VisualElement The element to use as a reference as the destination local space.
--- @param point UnityEngine.Vector2 The point to transform, in the local space of the source element.
--- @return UnityEngine.Vector2 A point in the local space of destination element.
function UnityEngine.UIElements.VisualElementExtensions.ChangeCoordinatesTo(src, dest, point) end

--- 
---  Transforms a rectangle from the local space of an element to the local space of another element.
---  
--- @param src UnityEngine.UIElements.VisualElement The element to use as a reference as the source local space.
--- @param dest UnityEngine.UIElements.VisualElement The element to use as a reference as the destination local space.
--- @param rect UnityEngine.Rect The rectangle to transform, in the local space of the source element.
--- @return UnityEngine.Rect A rectangle in the local space of destination element.
function UnityEngine.UIElements.VisualElementExtensions.ChangeCoordinatesTo(src, dest, rect) end

---  Generated By xerysherry