--- @class UnityEngine.TerrainUtils.TerrainTileCoord Specifies a set of 2D tile coordinates.
--- @field tileX number Tile X coordinate.
--- @field tileZ number Tile Z coordinate.
UnityEngine.TerrainUtils.TerrainTileCoord = {}

---  Generated By xerysherry