--- @class UnityEngine.Jobs.TransformAccess Position, rotation and scale of an object.
--- @field position UnityEngine.Vector3 property getset
---       The position of the transform in world space.
--- @field rotation UnityEngine.Quaternion property getset
---       The rotation of the transform in world space stored as a Quaternion.
--- @field localPosition UnityEngine.Vector3 property getset
---       The position of the transform relative to the parent.
--- @field localRotation UnityEngine.Quaternion property getset
---       The rotation of the transform relative to the parent transform's rotation.
--- @field localScale UnityEngine.Vector3 property getset
---       The scale of the transform relative to the parent.
--- @field localToWorldMatrix UnityEngine.Matrix4x4 property get
---       Matrix that transforms a point from local space into world space (Read Only).
--- @field worldToLocalMatrix UnityEngine.Matrix4x4 property get
---       Matrix that transforms a point from world space into local space (Read Only).
--- @field isValid boolean property get
---       Use this to determine whether this instance refers to a valid Transform.
UnityEngine.Jobs.TransformAccess = {}

function UnityEngine.Jobs.TransformAccess:set_position(value) end

function UnityEngine.Jobs.TransformAccess:set_rotation(value) end

function UnityEngine.Jobs.TransformAccess:set_localPosition(value) end

function UnityEngine.Jobs.TransformAccess:set_localRotation(value) end

function UnityEngine.Jobs.TransformAccess:set_localScale(value) end

---  Generated By xerysherry