--- @class UnityEngine.XR.XRNodeState 
--- @field uniqueID number property getset
---       The unique identifier of the tracked node.
--- @field nodeType UnityEngine.XR.XRNode property getset
---       The type of the tracked node as specified in XR.XRNode.
--- @field tracked boolean property getset
---       
---                 Set to true if the node is presently being tracked by the underlying XR system,
---       and false if the node is not presently being tracked by the underlying XR system.
--- @field position UnityEngine.Vector3 property set
---       Sets the vector representing the current position of the tracked node.
--- @field rotation UnityEngine.Quaternion property set
---       Sets the quaternion representing the current rotation of the tracked node.
--- @field velocity UnityEngine.Vector3 property set
---       Sets the vector representing the current velocity of the tracked node.
--- @field angularVelocity UnityEngine.Vector3 property set
---       Sets the vector representing the current angular velocity of the tracked node.
--- @field acceleration UnityEngine.Vector3 property set
---       Sets the vector representing the current acceleration of the tracked node.
--- @field angularAcceleration UnityEngine.Vector3 property set
---       Sets the vector representing the current angular acceleration of the tracked node.
UnityEngine.XR.XRNodeState = {}

--- @param value number 
function UnityEngine.XR.XRNodeState:set_uniqueID(value) end

--- @param value UnityEngine.XR.XRNode 
function UnityEngine.XR.XRNodeState:set_nodeType(value) end

--- @param value boolean 
function UnityEngine.XR.XRNodeState:set_tracked(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.XR.XRNodeState:set_position(value) end

--- @param value UnityEngine.Quaternion 
function UnityEngine.XR.XRNodeState:set_rotation(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.XR.XRNodeState:set_velocity(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.XR.XRNodeState:set_angularVelocity(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.XR.XRNodeState:set_acceleration(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.XR.XRNodeState:set_angularAcceleration(value) end

--- Attempt to retrieve a vector representing the current position of the tracked node.
--- @return boolean True if the position was set in the output parameter. False if the position is not available due to limitations of the underlying platform or if the node is not presently tracked.
--- @return UnityEngine.Vector3& 
function UnityEngine.XR.XRNodeState:TryGetPosition() end

--- Attempt to retrieve a quaternion representing the current rotation of the tracked node.
--- @return boolean True if the rotation was set in the output parameter. False if the rotation is not available due to limitations of the underlying platform or if the node is not presently tracked.
--- @return UnityEngine.Quaternion& 
function UnityEngine.XR.XRNodeState:TryGetRotation() end

--- Attempt to retrieve a vector representing the current velocity of the tracked node.
--- @return boolean True if the velocity was set in the output parameter. False if the velocity is not available due to limitations of the underlying platform or if the node is not presently tracked.
--- @return UnityEngine.Vector3& 
function UnityEngine.XR.XRNodeState:TryGetVelocity() end

--- Attempt to retrieve a Vector3 representing the current angular velocity of the tracked node.
--- @return boolean True if the angular velocity was set in the output parameter. False if the angular velocity is not available due to limitations of the underlying platform or if the node is not presently tracked.
--- @return UnityEngine.Vector3& 
function UnityEngine.XR.XRNodeState:TryGetAngularVelocity() end

--- Attempt to retrieve a vector representing the current acceleration of the tracked node.
--- @return boolean True if the acceleration was set in the output parameter. False if the acceleration is not available due to limitations of the underlying platform or if the node is not presently tracked.
--- @return UnityEngine.Vector3& 
function UnityEngine.XR.XRNodeState:TryGetAcceleration() end

--- Attempt to retrieve a Vector3 representing the current angular acceleration of the tracked node.
--- @return boolean True if the angular acceleration was set in the output parameter. False if the angular acceleration is not available due to limitations of the underlying platform or if the node is not presently tracked.
--- @return UnityEngine.Vector3& 
function UnityEngine.XR.XRNodeState:TryGetAngularAcceleration() end

---  Generated By xerysherry