--- @class UnityEngine.Time Provides an interface to get time information from Unity.
--- @field time number property get
---       The time at the beginning of this frame (Read Only).
--- @field timeAsDouble number property get
---       The double precision time at the beginning of this frame (Read Only). This is the time in seconds since the start of the game.
--- @field timeSinceLevelLoad number property get
---       The time since this frame started (Read Only). This is the time in seconds since the last non-additive scene has finished loading.
--- @field timeSinceLevelLoadAsDouble number property get
---       The double precision time since this frame started (Read Only). This is the time in seconds since the last non-additive scene has finished loading.
--- @field deltaTime number property get
---       The interval in seconds from the last frame to the current one (Read Only).
--- @field fixedTime number property get
---       The time since the last MonoBehaviour.FixedUpdate started (Read Only). This is the time in seconds since the start of the game.
--- @field fixedTimeAsDouble number property get
---       The double precision time since the last MonoBehaviour.FixedUpdate started (Read Only). This is the time in seconds since the start of the game.
--- @field unscaledTime number property get
---       The timeScale-independent time for this frame (Read Only). This is the time in seconds since the start of the game.
--- @field unscaledTimeAsDouble number property get
---       The double precision timeScale-independent time for this frame (Read Only). This is the time in seconds since the start of the game.
--- @field fixedUnscaledTime number property get
---       The timeScale-independent time at the beginning of the last MonoBehaviour.FixedUpdate phase (Read Only). This is the time in seconds since the start of the game.
--- @field fixedUnscaledTimeAsDouble number property get
---       The double precision timeScale-independent time at the beginning of the last MonoBehaviour.FixedUpdate (Read Only). This is the time in seconds since the start of the game.
--- @field unscaledDeltaTime number property get
---       The timeScale-independent interval in seconds from the last frame to the current one (Read Only).
--- @field fixedUnscaledDeltaTime number property get
---       The timeScale-independent interval in seconds from the last MonoBehaviour.FixedUpdate phase to the current one (Read Only).
--- @field fixedDeltaTime number property getset
---       The interval in seconds at which physics and other fixed frame rate updates (like MonoBehaviour's MonoBehaviour.FixedUpdate) are performed.
--- @field maximumDeltaTime number property getset
---       The maximum value of Time.deltaTime in any given frame. This is a time in seconds that limits the increase of Time.time between two frames.
--- @field smoothDeltaTime number property get
---       A smoothed out Time.deltaTime (Read Only).
--- @field maximumParticleDeltaTime number property getset
---       The maximum time a frame can spend on particle updates. If the frame takes longer than this, then updates are split into multiple smaller updates.
--- @field timeScale number property getset
---       The scale at which time passes.
--- @field frameCount number property get
---       The total number of frames since the start of the game (Read Only).
--- @field renderedFrameCount number
--- @field realtimeSinceStartup number property get
---       The real time in seconds since the game started (Read Only).
--- @field realtimeSinceStartupAsDouble number property get
---       The real time in seconds since the game started (Read Only). Double precision version of Time.realtimeSinceStartup. 
--- @field captureDeltaTime number property getset
---       Slows your application’s playback time to allow Unity to save screenshots in between frames.
--- @field captureFramerate number property getset
---       The reciprocal of Time.captureDeltaTime.
--- @field inFixedTimeStep boolean property get
---       Returns true if called inside a fixed time step callback (like MonoBehaviour's MonoBehaviour.FixedUpdate), otherwise returns false.
UnityEngine.Time = {}

--- @param value number 
function UnityEngine.Time.set_fixedDeltaTime(value) end

--- @param value number 
function UnityEngine.Time.set_maximumDeltaTime(value) end

--- @param value number 
function UnityEngine.Time.set_maximumParticleDeltaTime(value) end

--- @param value number 
function UnityEngine.Time.set_timeScale(value) end

--- @param value number 
function UnityEngine.Time.set_captureDeltaTime(value) end

--- @param value number 
function UnityEngine.Time.set_captureFramerate(value) end

---  Generated By xerysherry