--- 
---  Represents a distance value.
---  
--- @class UnityEngine.UIElements.Length
--- @field value number property getset
---       
---        The length value.
---        
--- @field unit UnityEngine.UIElements.LengthUnit property getset
---       
---        The unit of the value property.
---        
UnityEngine.UIElements.Length = {}

--- 
---  Creates a percentage Length from a float.
---  
--- @param value number 
--- @return UnityEngine.UIElements.Length The created length.
function UnityEngine.UIElements.Length.Percent(value) end

--- @return UnityEngine.UIElements.Length
function UnityEngine.UIElements.Length.op_Implicit(value) end

--- @return boolean
function UnityEngine.UIElements.Length.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.UIElements.Length.op_Inequality(lhs, rhs) end

function UnityEngine.UIElements.Length:set_value(value) end

function UnityEngine.UIElements.Length:set_unit(value) end

--- @return boolean
function UnityEngine.UIElements.Length:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.Length:Equals(obj) end

--- @return number
function UnityEngine.UIElements.Length:GetHashCode() end

--- @return string
function UnityEngine.UIElements.Length:ToString() end

---  Generated By xerysherry