--- @class UnityEngine.NetworkConnectionError Possible status messages returned by Network.Connect and in MonoBehaviour.OnFailedToConnect|OnFailedToConnect in case the error was not immediate.
UnityEngine.NetworkConnectionError = {
}

---  Generated By xerysherry