--- @class Unity.Profiling.ProfilerMarkerDataUnit Options for Profiler marker data unit types.
Unity.Profiling.ProfilerMarkerDataUnit = {
    --- Use to display data value as string if ProfilerMarkerDataTypes.String16 or as a simple number without any unit abbreviations. Also use Undefined in combination with ProfilerMarkerDataTypes.Blob8 which won't be visualized.
    Undefined = 0,
    --- Display data value as a time, specified in nanoseconds.
    TimeNanoseconds = 1,
    --- Display data value as a size, specified in bytes.
    Bytes = 2,
    --- Display data value as a simple number without any unit abbreviations.
    Count = 3,
    --- Display data value as a percentage value with % postfix.
    Percent = 4,
    --- Display data value as a frequency, specified in hertz.
    FrequencyHz = 5,
}

---  Generated By xerysherry