--- @class UnityEngine.Touch Structure describing the status of a finger touching the screen.
--- @field fingerId number property getset
---       The unique index for the touch.
--- @field position UnityEngine.Vector2 property getset
---       The position of the touch in screen space pixel coordinates.
--- @field rawPosition UnityEngine.Vector2 property getset
---       The first position of the touch contact in screen space pixel coordinates.
--- @field deltaPosition UnityEngine.Vector2 property getset
---       The position delta since last change in pixel coordinates.
--- @field deltaTime number property getset
---       Amount of time that has passed since the last recorded change in Touch values.
--- @field tapCount number property getset
---       Number of taps.
--- @field phase UnityEngine.TouchPhase property getset
---       Describes the phase of the touch.
--- @field pressure number property getset
---       The current amount of pressure being applied to a touch.  1.0f is considered to be the pressure of an average touch.  If Input.touchPressureSupported returns false, the value of this property will always be 1.0f.
--- @field maximumPossiblePressure number property getset
---       The maximum possible pressure value for a platform.  If Input.touchPressureSupported returns false, the value of this property will always be 1.0f.
--- @field type UnityEngine.TouchType property getset
---       A value that indicates whether a touch was of Direct, Indirect (or remote), or Stylus type.
--- @field altitudeAngle number property getset
---       Value of 0 radians indicates that the stylus is parallel to the surface, pi/2 indicates that it is perpendicular.
--- @field azimuthAngle number property getset
---       Value of 0 radians indicates that the stylus is pointed along the x-axis of the device.
--- @field radius number property getset
---       An estimated value of the radius of a touch.  Add radiusVariance to get the maximum touch size, subtract it to get the minimum touch size.
--- @field radiusVariance number property getset
---       This value determines the accuracy of the touch radius. Add this value to the radius to get the maximum touch size, subtract it to get the minimum touch size.
UnityEngine.Touch = {}

--- @param value number 
function UnityEngine.Touch:set_fingerId(value) end

--- @param value UnityEngine.Vector2 
function UnityEngine.Touch:set_position(value) end

--- @param value UnityEngine.Vector2 
function UnityEngine.Touch:set_rawPosition(value) end

--- @param value UnityEngine.Vector2 
function UnityEngine.Touch:set_deltaPosition(value) end

--- @param value number 
function UnityEngine.Touch:set_deltaTime(value) end

--- @param value number 
function UnityEngine.Touch:set_tapCount(value) end

--- @param value UnityEngine.TouchPhase 
function UnityEngine.Touch:set_phase(value) end

--- @param value number 
function UnityEngine.Touch:set_pressure(value) end

--- @param value number 
function UnityEngine.Touch:set_maximumPossiblePressure(value) end

--- @param value UnityEngine.TouchType 
function UnityEngine.Touch:set_type(value) end

--- @param value number 
function UnityEngine.Touch:set_altitudeAngle(value) end

--- @param value number 
function UnityEngine.Touch:set_azimuthAngle(value) end

--- @param value number 
function UnityEngine.Touch:set_radius(value) end

--- @param value number 
function UnityEngine.Touch:set_radiusVariance(value) end

---  Generated By xerysherry