--- @class UnityEngine.LineAlignment Control the direction lines face, when using the LineRenderer or TrailRenderer.
UnityEngine.LineAlignment = {
    --- Lines face the camera.
    View = 0,
    --- Lines face the Z axis of the Transform Component.
    TransformZ = 1,
}

---  Generated By xerysherry