--- @class UnityEngine.RenderTextureReadWrite Color space conversion mode of a RenderTexture.
UnityEngine.RenderTextureReadWrite = {
    --- Default color space conversion based on project settings.
    Default = 0,
    --- Render texture contains linear (non-color) data; don't perform color conversions on it.
    Linear = 1,
    --- Render texture contains sRGB (color) data, perform Linear<->sRGB conversions on it.
    sRGB = 2,
}

---  Generated By xerysherry