--- @class UnityEngine.Networking.PlayerConnection.MessageEventArgs Arguments passed to Action callbacks registered in PlayerConnection.
--- @field playerId number The Player ID that the data is received from.
--- @field data number[] Data that is received.
UnityEngine.Networking.PlayerConnection.MessageEventArgs = {}

---  Generated By xerysherry