--- Destination of Frame Capture
--- This is a wrapper for MTLCaptureDestination.
--- @class UnityEngine.Apple.FrameCaptureDestination
UnityEngine.Apple.FrameCaptureDestination = {
    --- Capture in XCode itself.
    DevTools = 1,
    --- Capture to a GPU Trace document.
    GPUTraceDocument = 2,
}

---  Generated By xerysherry