--- @class UnityEngine.Cursor Cursor API for setting the cursor (mouse pointer).
--- @field visible boolean property getset
---       Determines whether the hardware pointer is visible or not.
--- @field lockState UnityEngine.CursorLockMode property getset
---       Determines whether the hardware pointer is locked to the center of the view, constrained to the window, or not constrained at all.
UnityEngine.Cursor = {}

--- Specify a custom cursor that you wish to use as a cursor.
--- @param texture UnityEngine.Texture2D The texture to use for the cursor. To use a texture, you must first import it with `Read/Write`enabled. Alternatively, you can use the default cursor import setting. If you created your cursor texture from code, it must be in RGBA32 format, have alphaIsTransparency enabled, and have no mip chain. To use the default cursor, set the texture to `Null`.
--- @param hotspot UnityEngine.Vector2 The offset from the top left of the texture to use as the target point (must be within the bounds of the cursor).
--- @param cursorMode UnityEngine.CursorMode Allow this cursor to render as a hardware cursor on supported platforms, or force software cursor.
function UnityEngine.Cursor.SetCursor(texture, hotspot, cursorMode) end

function UnityEngine.Cursor.set_visible(value) end

function UnityEngine.Cursor.set_lockState(value) end

---  Generated By xerysherry