--- @class JetBrains.Annotations.CollectionAccessAttribute:System.Attribute 
--- @field CollectionAccessType JetBrains.Annotations.CollectionAccessType
--- @field TypeId System.Object
JetBrains.Annotations.CollectionAccessAttribute = {}

---  Generated By xerysherry