--- @class UnityEngine.CubemapFace Cubemap face.
UnityEngine.CubemapFace = {
    --- Cubemap face is unknown or unspecified.
    Unknown = -1,
    --- Right facing side (+x).
    PositiveX = 0,
    --- Left facing side (-x).
    NegativeX = 1,
    --- Upwards facing side (+y).
    PositiveY = 2,
    --- Downward facing side (-y).
    NegativeY = 3,
    --- Forward facing side (+z).
    PositiveZ = 4,
    --- Backward facing side (-z).
    NegativeZ = 5,
}

---  Generated By xerysherry