--- @class UnityEngine.UI.CanvasScaler.ScaleMode
UnityEngine.UI.CanvasScaler.ScaleMode = {
    ConstantPixelSize = 0,
    ScaleWithScreenSize = 1,
    ConstantPhysicalSize = 2,
}

---  Generated By xerysherry