UnityEngine.UI.InputField.LineType = {
    SingleLine = 0,
    MultiLineSubmit = 1,
    MultiLineNewline = 2,
}

UnityEngine.UI.InputField.LineType = {
    SingleLine = 0,
    MultiLineSubmit = 1,
    MultiLineNewline = 2,
}

---  Generated By xerysherry