--- @class UnityEngine.UIElements.IMGUIContainer:UnityEngine.UIElements.VisualElement Element that draws IMGUI content.
--- @field ussClassName string USS class name of elements of this type.
--- @field onGUIHandler function property getset
---       The function that is called to render and handle IMGUI events.
--- @field contextType UnityEngine.UIElements.ContextType property getset
---       ContextType of this IMGUIContrainer. Currently only supports ContextType.Editor.
--- @field canGrabFocus boolean
--- @field viewDataKey string
--- @field userData System.Object
--- @field focusController UnityEngine.UIElements.FocusController
--- @field usageHints UnityEngine.UIElements.UsageHints
--- @field transform UnityEngine.UIElements.ITransform
--- @field layout UnityEngine.Rect
--- @field contentRect UnityEngine.Rect
--- @field worldBound UnityEngine.Rect
--- @field localBound UnityEngine.Rect
--- @field worldTransform UnityEngine.Matrix4x4
--- @field pickingMode UnityEngine.UIElements.PickingMode
--- @field name string
--- @field enabledInHierarchy boolean
--- @field enabledSelf boolean
--- @field visible boolean
--- @field generateVisualContent function
--- @field experimental UnityEngine.UIElements.IExperimentalFeatures
--- @field hierarchy UnityEngine.UIElements.VisualElement.Hierarchy
--- @field cacheAsBitmap boolean
--- @field parent UnityEngine.UIElements.VisualElement
--- @field panel UnityEngine.UIElements.IPanel
--- @field contentContainer UnityEngine.UIElements.VisualElement
--- @field Item UnityEngine.UIElements.VisualElement
--- @field childCount number
--- @field schedule UnityEngine.UIElements.IVisualElementScheduler
--- @field style UnityEngine.UIElements.IStyle
--- @field customStyle UnityEngine.UIElements.ICustomStyle
--- @field resolvedStyle UnityEngine.UIElements.IResolvedStyle
--- @field styleSheets UnityEngine.UIElements.VisualElementStyleSheetSet
--- @field tooltip string
--- @field focusable boolean
--- @field tabIndex number
--- @field delegatesFocus boolean
UnityEngine.UIElements.IMGUIContainer = {}

--- @param value function 
function UnityEngine.UIElements.IMGUIContainer:set_onGUIHandler(value) end

--- @param value UnityEngine.UIElements.ContextType 
function UnityEngine.UIElements.IMGUIContainer:set_contextType(value) end

--- Marks layout as dirty to trigger a redraw.
function UnityEngine.UIElements.IMGUIContainer:MarkDirtyLayout() end

--- @param evt UnityEngine.UIElements.EventBase 
function UnityEngine.UIElements.IMGUIContainer:HandleEvent(evt) end

function UnityEngine.UIElements.IMGUIContainer:Dispose() end

---  Generated By xerysherry