--- @class UnityEngine.AudioRolloffMode Rolloff modes that a 3D sound can have in an audio source.
UnityEngine.AudioRolloffMode = {
    --- Use this mode when you want a real-world rolloff.
    Logarithmic = 0,
    --- Use this mode when you want to lower the volume of your sound over the distance.
    Linear = 1,
    --- Use this when you want to use a custom rolloff.
    Custom = 2,
}

---  Generated By xerysherry