--- @class UnityEngine.EventSystems.BaseInput:UnityEngine.EventSystems.UIBehaviour 
--- @field compositionString string
--- @field imeCompositionMode UnityEngine.IMECompositionMode
--- @field compositionCursorPos UnityEngine.Vector2
--- @field mousePresent boolean
--- @field mousePosition UnityEngine.Vector2
--- @field mouseScrollDelta UnityEngine.Vector2
--- @field touchSupported boolean
--- @field touchCount number
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.EventSystems.BaseInput = {}

function UnityEngine.EventSystems.BaseInput:set_imeCompositionMode(value) end

function UnityEngine.EventSystems.BaseInput:set_compositionCursorPos(value) end

--- @return boolean
function UnityEngine.EventSystems.BaseInput:GetMouseButtonDown(button) end

--- @return boolean
function UnityEngine.EventSystems.BaseInput:GetMouseButtonUp(button) end

--- @return boolean
function UnityEngine.EventSystems.BaseInput:GetMouseButton(button) end

--- @return UnityEngine.Touch
function UnityEngine.EventSystems.BaseInput:GetTouch(index) end

--- @return number
function UnityEngine.EventSystems.BaseInput:GetAxisRaw(axisName) end

--- @return boolean
function UnityEngine.EventSystems.BaseInput:GetButtonDown(buttonName) end

---  Generated By xerysherry