--- @class UnityEngine.AvatarTarget Target.
UnityEngine.AvatarTarget = {
    --- The root, the position of the game object.
    Root = 0,
    --- The body, center of mass.
    Body = 1,
    --- The left foot.
    LeftFoot = 2,
    --- The right foot.
    RightFoot = 3,
    --- The left hand.
    LeftHand = 4,
    --- The right hand.
    RightHand = 5,
}

---  Generated By xerysherry