--- @class UnityEngine.GUIText 
--- @field text boolean
--- @field material UnityEngine.Material
--- @field font UnityEngine.Font
--- @field alignment UnityEngine.TextAlignment
--- @field anchor UnityEngine.TextAnchor
--- @field lineSpacing number
--- @field tabSize number
--- @field fontSize number
--- @field fontStyle UnityEngine.FontStyle
--- @field richText boolean
--- @field color UnityEngine.Color
--- @field pixelOffset UnityEngine.Vector2
UnityEngine.GUIText = {}

function UnityEngine.GUIText:set_text(value) end

function UnityEngine.GUIText:set_material(value) end

function UnityEngine.GUIText:set_font(value) end

function UnityEngine.GUIText:set_alignment(value) end

function UnityEngine.GUIText:set_anchor(value) end

function UnityEngine.GUIText:set_lineSpacing(value) end

function UnityEngine.GUIText:set_tabSize(value) end

function UnityEngine.GUIText:set_fontSize(value) end

function UnityEngine.GUIText:set_fontStyle(value) end

function UnityEngine.GUIText:set_richText(value) end

function UnityEngine.GUIText:set_color(value) end

function UnityEngine.GUIText:set_pixelOffset(value) end

---  Generated By xerysherry