--- @class Unity.IO.LowLevel.Unsafe.ReadStatus State of the read operation.
Unity.IO.LowLevel.Unsafe.ReadStatus = {
    --- All the ReadCommand operations completed successfully.
    Complete = 0,
    --- The read operation is in progress.
    InProgress = 1,
    --- One or more of the ReadCommand operations failed.
    Failed = 2,
}

---  Generated By xerysherry