--- @class UnityEngine.UnityAPICompatibilityVersionAttribute:System.Attribute Declares an assembly to be compatible (API wise) with a specific Unity API. Used by internal tools to avoid processing the assembly in order to decide whether assemblies may be using old Unity API.
--- @field version string property get
---       Version of Unity API.
--- @field TypeId System.Object
UnityEngine.UnityAPICompatibilityVersionAttribute = {}

---  Generated By xerysherry