--- @class UnityEngine.U2D.SpriteShapeUtility A static class that helps tessellate a SpriteShape mesh.
UnityEngine.U2D.SpriteShapeUtility = {}

--- Generate a mesh based on input parameters.
--- @return number[] 
function UnityEngine.U2D.SpriteShapeUtility.Generate(mesh, shapeParams, points, metaData, angleRange, sprites, corners) end

--- Generate a mesh based on input parameters.
function UnityEngine.U2D.SpriteShapeUtility.GenerateSpriteShape(renderer, shapeParams, points, metaData, angleRange, sprites, corners) end

---  Generated By xerysherry