--- @class UnityEngine.FrameTiming Struct containing basic FrameTimings and accompanying relevant data.
--- @field cpuTimePresentCalled number This is the CPU clock time at the point Present was called for the current frame.
--- @field cpuFrameTime number The CPU time for a given frame, in ms.
--- @field cpuTimeFrameComplete number This is the CPU clock time at the point GPU finished rendering the frame and interrupted the CPU.
--- @field gpuFrameTime number The GPU time for a given frame, in ms.
--- @field heightScale number This was the height scale factor of the Dynamic Resolution system(if used) for the given frame and the linked frame timings.
--- @field widthScale number This was the width scale factor of the Dynamic Resolution system(if used) for the given frame and the linked frame timings.
--- @field syncInterval number This was the vsync mode for the given frame and the linked frame timings.
UnityEngine.FrameTiming = {}

---  Generated By xerysherry