--- @class UnityEngine.ScreenCapture.StereoScreenCaptureMode Enumeration specifying the eye texture to capture when using ScreenCapture.CaptureScreenshot and when stereo rendering is enabled.
UnityEngine.ScreenCapture.StereoScreenCaptureMode = {
    --- The Left Eye is captured. This is the default setting for the CaptureScreenshot method.
    LeftEye = 1,
    --- The Right Eye is captured.
    RightEye = 2,
    --- Both the left and right eyes are captured and composited into one image.
    BothEyes = 3,
}

--- @class UnityEngine.ScreenCapture.StereoScreenCaptureMode Enumeration specifying the eye texture to capture when using ScreenCapture.CaptureScreenshot and when stereo rendering is enabled.
UnityEngine.ScreenCapture.StereoScreenCaptureMode = {
    --- The Left Eye is captured. This is the default setting for the CaptureScreenshot method.
    LeftEye = 1,
    --- The Right Eye is captured.
    RightEye = 2,
    --- Both the left and right eyes are captured and composited into one image.
    BothEyes = 3,
}

---  Generated By xerysherry