--- @class UnityEngine.Internal.VR.VRTestMock 
UnityEngine.Internal.VR.VRTestMock = {}

function UnityEngine.Internal.VR.VRTestMock.Reset() end

--- @param nodeType UnityEngine.XR.XRNode 
function UnityEngine.Internal.VR.VRTestMock.AddTrackedDevice(nodeType) end

--- @param nodeType UnityEngine.XR.XRNode 
--- @param position UnityEngine.Vector3 
--- @param rotation UnityEngine.Quaternion 
function UnityEngine.Internal.VR.VRTestMock.UpdateTrackedDevice(nodeType, position, rotation) end

--- @param position UnityEngine.Vector3 
--- @param rotation UnityEngine.Quaternion 
function UnityEngine.Internal.VR.VRTestMock.UpdateLeftEye(position, rotation) end

--- @param position UnityEngine.Vector3 
--- @param rotation UnityEngine.Quaternion 
function UnityEngine.Internal.VR.VRTestMock.UpdateRightEye(position, rotation) end

--- @param position UnityEngine.Vector3 
--- @param rotation UnityEngine.Quaternion 
function UnityEngine.Internal.VR.VRTestMock.UpdateCenterEye(position, rotation) end

--- @param position UnityEngine.Vector3 
--- @param rotation UnityEngine.Quaternion 
function UnityEngine.Internal.VR.VRTestMock.UpdateHead(position, rotation) end

--- @param position UnityEngine.Vector3 
--- @param rotation UnityEngine.Quaternion 
function UnityEngine.Internal.VR.VRTestMock.UpdateLeftHand(position, rotation) end

--- @param position UnityEngine.Vector3 
--- @param rotation UnityEngine.Quaternion 
function UnityEngine.Internal.VR.VRTestMock.UpdateRightHand(position, rotation) end

--- @param controllerName string 
function UnityEngine.Internal.VR.VRTestMock.AddController(controllerName) end

--- @param controllerName string 
--- @param axis number 
--- @param value number 
function UnityEngine.Internal.VR.VRTestMock.UpdateControllerAxis(controllerName, axis, value) end

--- @param controllerName string 
--- @param button number 
--- @param pressed boolean 
function UnityEngine.Internal.VR.VRTestMock.UpdateControllerButton(controllerName, button, pressed) end

---  Generated By xerysherry