--- @class UnityEngine.Networking.UnityWebRequestMultimedia Helpers for downloading multimedia files using UnityWebRequest.
UnityEngine.Networking.UnityWebRequestMultimedia = {}

--- Create a UnityWebRequest to download an audio clip via HTTP GET and create an AudioClip based on the retrieved data.
--- @param uri string The URI of the audio clip to download.
--- @param audioType UnityEngine.AudioType The type of audio encoding for the downloaded audio clip. See AudioType.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest properly configured to download an audio clip and convert it to an AudioClip.
function UnityEngine.Networking.UnityWebRequestMultimedia.GetAudioClip(uri, audioType) end

--- Create a UnityWebRequest to download an audio clip via HTTP GET and create an AudioClip based on the retrieved data.
--- @param uri System.Uri The URI of the audio clip to download.
--- @param audioType UnityEngine.AudioType The type of audio encoding for the downloaded audio clip. See AudioType.
--- @return UnityEngine.Networking.UnityWebRequest A UnityWebRequest properly configured to download an audio clip and convert it to an AudioClip.
function UnityEngine.Networking.UnityWebRequestMultimedia.GetAudioClip(uri, audioType) end

--- MovieTexture has been removed. Use VideoPlayer instead.
--- @param uri string 
--- @return UnityEngine.Networking.UnityWebRequest 
function UnityEngine.Networking.UnityWebRequestMultimedia.GetMovieTexture(uri) end

--- MovieTexture has been removed. Use VideoPlayer instead.
--- @param uri System.Uri 
--- @return UnityEngine.Networking.UnityWebRequest 
function UnityEngine.Networking.UnityWebRequestMultimedia.GetMovieTexture(uri) end

---  Generated By xerysherry