--- @class UnityEngine.UIElements.GeometryChangedEvent:UnityEngine.UIElements.EventBase`1 Event sent after layout calculations, when the position or the dimension of an element changes. This event cannot be cancelled, it does not trickle down, and it does not bubble up.
--- @field oldRect UnityEngine.Rect property get
---       The old dimensions of the element.
--- @field newRect UnityEngine.Rect property get
---       The new dimensions of the element.
--- @field eventTypeId number
--- @field timestamp number
--- @field bubbles boolean
--- @field tricklesDown boolean
--- @field target UnityEngine.UIElements.IEventHandler
--- @field isPropagationStopped boolean
--- @field isImmediatePropagationStopped boolean
--- @field isDefaultPrevented boolean
--- @field propagationPhase UnityEngine.UIElements.PropagationPhase
--- @field currentTarget UnityEngine.UIElements.IEventHandler
--- @field dispatch boolean
--- @field imguiEvent UnityEngine.Event
--- @field originalMousePosition UnityEngine.Vector2
UnityEngine.UIElements.GeometryChangedEvent = {}

--- Gets an event from the event pool and initializes the event with the specified values. Use this method instead of instancing new events. Use Dispose() to release events back to the event pool.
--- @param oldRect UnityEngine.Rect The old dimensions of the element.
--- @param newRect UnityEngine.Rect The new dimensions of the element.
--- @return UnityEngine.UIElements.GeometryChangedEvent An initialized event.
function UnityEngine.UIElements.GeometryChangedEvent.GetPooled(oldRect, newRect) end

---  Generated By xerysherry