--- @class UnityEngine.Rendering.ShadowDrawingSettings Settings for ScriptableRenderContext.DrawShadows.
--- @field cullingResults UnityEngine.Rendering.CullingResults property getset
---       Culling results to use.
--- @field lightIndex number property getset
---       The index of the shadow-casting light to be rendered.
--- @field useRenderingLayerMaskTest boolean property getset
---       Set this to true to make Unity filter Renderers during shadow rendering. Unity filters Renderers based on the Rendering Layer Mask of the Renderer itself, and the Rendering Layer Mask of each shadow casting Light.
--- @field splitData UnityEngine.Rendering.ShadowSplitData property getset
---       The split data.
UnityEngine.Rendering.ShadowDrawingSettings = {}

--- @param left UnityEngine.Rendering.ShadowDrawingSettings 
--- @param right UnityEngine.Rendering.ShadowDrawingSettings 
--- @return boolean
function UnityEngine.Rendering.ShadowDrawingSettings.op_Equality(left, right) end

--- @param left UnityEngine.Rendering.ShadowDrawingSettings 
--- @param right UnityEngine.Rendering.ShadowDrawingSettings 
--- @return boolean
function UnityEngine.Rendering.ShadowDrawingSettings.op_Inequality(left, right) end

--- @param value UnityEngine.Rendering.CullingResults 
function UnityEngine.Rendering.ShadowDrawingSettings:set_cullingResults(value) end

--- @param value number 
function UnityEngine.Rendering.ShadowDrawingSettings:set_lightIndex(value) end

--- @param value boolean 
function UnityEngine.Rendering.ShadowDrawingSettings:set_useRenderingLayerMaskTest(value) end

--- @param value UnityEngine.Rendering.ShadowSplitData 
function UnityEngine.Rendering.ShadowDrawingSettings:set_splitData(value) end

--- @param other UnityEngine.Rendering.ShadowDrawingSettings 
--- @return boolean
function UnityEngine.Rendering.ShadowDrawingSettings:Equals(other) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.Rendering.ShadowDrawingSettings:Equals(obj) end

--- @return number
function UnityEngine.Rendering.ShadowDrawingSettings:GetHashCode() end

---  Generated By xerysherry