--- @class UnityEngine.Rendering.ShaderKeyword Identifier of a specific code path in a shader.
--- @field index number property get
---       The index of the shader keyword.
UnityEngine.Rendering.ShaderKeyword = {}

--- Returns the string name of the global keyword.
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return string 
function UnityEngine.Rendering.ShaderKeyword.GetGlobalKeywordName(index) end

--- Returns the type of global keyword: built-in or user defined.
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return UnityEngine.Rendering.ShaderKeywordType 
function UnityEngine.Rendering.ShaderKeyword.GetGlobalKeywordType(index) end

--- Returns true if the keyword is local.
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return boolean 
function UnityEngine.Rendering.ShaderKeyword.IsKeywordLocal(index) end

--- Returns the string name of the keyword.
--- @param shader UnityEngine.Shader 
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return string 
function UnityEngine.Rendering.ShaderKeyword.GetKeywordName(shader, index) end

--- Returns the type of keyword: built-in or user defined.
--- @param shader UnityEngine.Shader 
--- @param index UnityEngine.Rendering.ShaderKeyword 
--- @return UnityEngine.Rendering.ShaderKeywordType 
function UnityEngine.Rendering.ShaderKeyword.GetKeywordType(shader, index) end

--- Returns true if the keyword has been imported by Unity.
--- @return boolean 
function UnityEngine.Rendering.ShaderKeyword:IsValid() end

--- Returns the type of keyword: built-in or user defined.
--- @return UnityEngine.Rendering.ShaderKeywordType 
function UnityEngine.Rendering.ShaderKeyword:GetKeywordType() end

--- Returns the string name of the keyword.
--- @return string 
function UnityEngine.Rendering.ShaderKeyword:GetKeywordName() end

--- @return string
function UnityEngine.Rendering.ShaderKeyword:GetName() end

---  Generated By xerysherry