--- @class UnityEngine.UI.RawImage:UnityEngine.UI.MaskableGraphic 
--- @field mainTexture UnityEngine.Texture
--- @field texture UnityEngine.Texture
--- @field uvRect UnityEngine.Rect
--- @field onCullStateChanged UnityEngine.UI.MaskableGraphic.CullStateChangedEvent
--- @field maskable boolean
--- @field isMaskingGraphic boolean
--- @field color UnityEngine.Color
--- @field raycastTarget boolean
--- @field depth number
--- @field rectTransform UnityEngine.RectTransform
--- @field canvas UnityEngine.Canvas
--- @field canvasRenderer UnityEngine.CanvasRenderer
--- @field defaultMaterial UnityEngine.Material
--- @field material UnityEngine.Material
--- @field materialForRendering UnityEngine.Material
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.RawImage = {}

function UnityEngine.UI.RawImage:set_texture(value) end

function UnityEngine.UI.RawImage:set_uvRect(value) end

function UnityEngine.UI.RawImage:SetNativeSize() end

---  Generated By xerysherry