--- @class UnityEngine.RectInt A 2D Rectangle defined by x, y, width, height with integers.
--- @field x number property getset
---       Left coordinate of the rectangle.
--- @field y number property getset
---       Top coordinate of the rectangle.
--- @field center UnityEngine.Vector2 property get
---       Center coordinate of the rectangle.
--- @field min UnityEngine.Vector2Int property getset
---       Lower left corner of the rectangle.
--- @field max UnityEngine.Vector2Int property getset
---       Upper right corner of the rectangle.
--- @field width number property getset
---       Width of the rectangle.
--- @field height number property getset
---       Height of the rectangle.
--- @field xMin number property getset
---       Returns the minimum X value of the RectInt.
--- @field yMin number property getset
---       Returns the minimum Y value of the RectInt.
--- @field xMax number property getset
---       Returns the maximum X value of the RectInt.
--- @field yMax number property getset
---       Returns the maximum Y value of the RectInt.
--- @field position UnityEngine.Vector2Int property getset
---       Returns the position (x, y) of the RectInt.
--- @field size UnityEngine.Vector2Int property getset
---       Returns the width and height of the RectInt.
--- @field allPositionsWithin UnityEngine.RectInt.PositionEnumerator property get
---       A RectInt.PositionCollection that contains all positions within the RectInt.
UnityEngine.RectInt = {}

--- @param value number 
function UnityEngine.RectInt:set_x(value) end

--- @param value number 
function UnityEngine.RectInt:set_y(value) end

--- @param value UnityEngine.Vector2Int 
function UnityEngine.RectInt:set_min(value) end

--- @param value UnityEngine.Vector2Int 
function UnityEngine.RectInt:set_max(value) end

--- @param value number 
function UnityEngine.RectInt:set_width(value) end

--- @param value number 
function UnityEngine.RectInt:set_height(value) end

--- @param value number 
function UnityEngine.RectInt:set_xMin(value) end

--- @param value number 
function UnityEngine.RectInt:set_yMin(value) end

--- @param value number 
function UnityEngine.RectInt:set_xMax(value) end

--- @param value number 
function UnityEngine.RectInt:set_yMax(value) end

--- @param value UnityEngine.Vector2Int 
function UnityEngine.RectInt:set_position(value) end

--- @param value UnityEngine.Vector2Int 
function UnityEngine.RectInt:set_size(value) end

--- Sets the bounds to the min and max value of the rect.
--- @param minPosition UnityEngine.Vector2Int 
--- @param maxPosition UnityEngine.Vector2Int 
function UnityEngine.RectInt:SetMinMax(minPosition, maxPosition) end

--- Clamps the position and size of the RectInt to the given bounds.
--- @param bounds UnityEngine.RectInt Bounds to clamp the RectInt.
function UnityEngine.RectInt:ClampToBounds(bounds) end

--- Returns true if the given position is within the RectInt.
--- @param position UnityEngine.Vector2Int Position to check.
--- @return boolean Whether the position is within the RectInt.
function UnityEngine.RectInt:Contains(position) end

--- RectInts overlap if each RectInt Contains a shared point.
--- @param other UnityEngine.RectInt Other rectangle to test overlapping with.
--- @return boolean True if the other rectangle overlaps this one.
function UnityEngine.RectInt:Overlaps(other) end

--- Returns the x, y, width and height of the RectInt.
--- @return string 
function UnityEngine.RectInt:ToString() end

--- Returns true if the given RectInt is equal to this RectInt.
--- @param other UnityEngine.RectInt 
--- @return boolean 
function UnityEngine.RectInt:Equals(other) end

---  Generated By xerysherry