--- @class UnityEngine.Video.VideoClip:UnityEngine.Object A container for video data.
--- @field originalPath string property get
---       The video clip path in the project's assets. (Read Only).
--- @field frameCount number property get
---       The length of the VideoClip in frames. (Read Only).
--- @field frameRate number property get
---       The frame rate of the clip in frames/second. (Read Only).
--- @field length number property get
---       The length of the video clip in seconds. (Read Only).
--- @field width number property get
---       The width of the images in the video clip in pixels. (Read Only).
--- @field height number property get
---       The height of the images in the video clip in pixels. (Read Only).
--- @field pixelAspectRatioNumerator number property get
---       Numerator of the pixel aspect ratio (num:den). (Read Only).
--- @field pixelAspectRatioDenominator number property get
---       Denominator of the pixel aspect ratio (num:den). (Read Only).
--- @field sRGB boolean property get
---       Whether the imported clip contains sRGB color data (Read Only).
--- @field audioTrackCount number property get
---       Number of audio tracks in the clip.
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Video.VideoClip = {}

--- The number of channels in the audio track.  E.g. 2 for a stereo track.
--- @param audioTrackIdx number Index of the audio queried audio track.
--- @return number The number of channels.
function UnityEngine.Video.VideoClip:GetAudioChannelCount(audioTrackIdx) end

--- Get the audio track sampling rate in Hertz.
--- @param audioTrackIdx number Index of the audio queried audio track.
--- @return number The sampling rate in Hertz.
function UnityEngine.Video.VideoClip:GetAudioSampleRate(audioTrackIdx) end

--- Get the audio track language.  Can be unknown.
--- @param audioTrackIdx number Index of the audio queried audio track.
--- @return string The abbreviated name of the language.
function UnityEngine.Video.VideoClip:GetAudioLanguage(audioTrackIdx) end

---  Generated By xerysherry