--- @class UnityEngine.ExecuteInEditMode:System.Attribute Makes all instances of a script execute in Edit Mode.
--- @field TypeId System.Object
UnityEngine.ExecuteInEditMode = {}

---  Generated By xerysherry