--- @class UnityEngine.UnityException:System.SystemException 
--- @field Message string
--- @field Data System.Collections.IDictionary
--- @field InnerException System.Exception
--- @field TargetSite System.Reflection.MethodBase
--- @field StackTrace string
--- @field HelpLink string
--- @field Source string
--- @field HResult number
UnityEngine.UnityException = {}

---  Generated By xerysherry