--- @class UnityEngine.TextCore.FaceInfo A structure that contains information about a given typeface and for a specific point size.
--- @field familyName string property getset
---       The name of the font typeface also known as family name.
--- @field styleName string property getset
---       The style name of the typeface which defines both the visual style and weight of the typeface.
--- @field pointSize number property getset
---       The point size used for sampling the typeface.
--- @field scale number property getset
---       The relative scale of the typeface.
--- @field lineHeight number property getset
---       The line height represents the distance between consecutive lines of text.
--- @field ascentLine number property getset
---       The Ascent line is typically located at the top of the tallest glyph in the typeface.
--- @field capLine number property getset
---       The Cap line is typically located at the top of capital letters.
--- @field meanLine number property getset
---       The Mean line is typically located at the top of lowercase letters.
--- @field baseline number property getset
---       The Baseline is an imaginary line upon which all glyphs appear to rest on.
--- @field descentLine number property getset
---       The Descent line is typically located at the bottom of the glyph with the lowest descender in the typeface.
--- @field superscriptOffset number property getset
---       The position of characters using superscript.
--- @field superscriptSize number property getset
---       The relative size / scale of superscript characters.
--- @field subscriptOffset number property getset
---       The position of characters using subscript.
--- @field subscriptSize number property getset
---       The relative size / scale of subscript characters.
--- @field underlineOffset number property getset
---       The position of the underline.
--- @field underlineThickness number property getset
---       The thickness of the underline.
--- @field strikethroughOffset number property getset
---       The position of the strikethrough.
--- @field strikethroughThickness number property getset
---       The thickness of the strikethrough.
--- @field tabWidth number property getset
---       The width of the tab character.
UnityEngine.TextCore.FaceInfo = {}

function UnityEngine.TextCore.FaceInfo:set_familyName(value) end

function UnityEngine.TextCore.FaceInfo:set_styleName(value) end

function UnityEngine.TextCore.FaceInfo:set_pointSize(value) end

function UnityEngine.TextCore.FaceInfo:set_scale(value) end

function UnityEngine.TextCore.FaceInfo:set_lineHeight(value) end

function UnityEngine.TextCore.FaceInfo:set_ascentLine(value) end

function UnityEngine.TextCore.FaceInfo:set_capLine(value) end

function UnityEngine.TextCore.FaceInfo:set_meanLine(value) end

function UnityEngine.TextCore.FaceInfo:set_baseline(value) end

function UnityEngine.TextCore.FaceInfo:set_descentLine(value) end

function UnityEngine.TextCore.FaceInfo:set_superscriptOffset(value) end

function UnityEngine.TextCore.FaceInfo:set_superscriptSize(value) end

function UnityEngine.TextCore.FaceInfo:set_subscriptOffset(value) end

function UnityEngine.TextCore.FaceInfo:set_subscriptSize(value) end

function UnityEngine.TextCore.FaceInfo:set_underlineOffset(value) end

function UnityEngine.TextCore.FaceInfo:set_underlineThickness(value) end

function UnityEngine.TextCore.FaceInfo:set_strikethroughOffset(value) end

function UnityEngine.TextCore.FaceInfo:set_strikethroughThickness(value) end

function UnityEngine.TextCore.FaceInfo:set_tabWidth(value) end

--- Compares the information in this FaceInfo structure with the information in the given FaceInfo structure to determine whether they have the same values.
--- @param other UnityEngine.TextCore.FaceInfo The FaceInfo structure to compare this FaceInfo structure with.
--- @return boolean Returns true if the FaceInfo structures have the same values. False if not.
function UnityEngine.TextCore.FaceInfo:Compare(other) end

---  Generated By xerysherry