--- @class UnityEngine.AndroidJavaClass:UnityEngine.AndroidJavaObject AndroidJavaClass is the Unity representation of a generic instance of java.lang.Class.
UnityEngine.AndroidJavaClass = {}

---  Generated By xerysherry