--- @class UnityEngine.XR.WSA.Input.HoldCanceledEventArgs Contains fields that are relevant when a user cancels a hold gesture.
--- @field source UnityEngine.XR.WSA.Input.InteractionSource property get
---       The InteractionSource (hand, controller, or user's voice) that canceled the hold gesture.
--- @field sourcePose UnityEngine.XR.WSA.Input.InteractionSourcePose property get
---       Represents pose data of the input source, such as a hand or controller, when the gesture occurred.
--- @field headPose UnityEngine.Pose property get
---       Head pose of the user at the time of the gesture.
UnityEngine.XR.WSA.Input.HoldCanceledEventArgs = {}

---  Generated By xerysherry