--- @class UnityEngine.Animations.TransformSceneHandle Handle to read position, rotation and scale of an object in the Scene.
UnityEngine.Animations.TransformSceneHandle = {}

--- Returns whether this is a valid handle.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @return boolean Whether this is a valid handle.
function UnityEngine.Animations.TransformSceneHandle:IsValid(stream) end

--- Gets the position of the transform in world space.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @return UnityEngine.Vector3 The position of the transform in world space.
function UnityEngine.Animations.TransformSceneHandle:GetPosition(stream) end

--- Sets the position of the transform in world space.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @param position UnityEngine.Vector3 The position of the transform in world space.
function UnityEngine.Animations.TransformSceneHandle:SetPosition(stream, position) end

--- Gets the position of the transform relative to the parent.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @return UnityEngine.Vector3 The position of the transform relative to the parent.
function UnityEngine.Animations.TransformSceneHandle:GetLocalPosition(stream) end

--- Sets the position of the transform relative to the parent.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @param position UnityEngine.Vector3 The position of the transform relative to the parent.
function UnityEngine.Animations.TransformSceneHandle:SetLocalPosition(stream, position) end

--- Gets the rotation of the transform in world space.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @return UnityEngine.Quaternion The rotation of the transform in world space.
function UnityEngine.Animations.TransformSceneHandle:GetRotation(stream) end

--- Sets the rotation of the transform in world space.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @param rotation UnityEngine.Quaternion The rotation of the transform in world space.
function UnityEngine.Animations.TransformSceneHandle:SetRotation(stream, rotation) end

--- Gets the rotation of the transform relative to the parent.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @return UnityEngine.Quaternion The rotation of the transform relative to the parent.
function UnityEngine.Animations.TransformSceneHandle:GetLocalRotation(stream) end

--- Sets the rotation of the transform relative to the parent.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @param rotation UnityEngine.Quaternion The rotation of the transform relative to the parent.
function UnityEngine.Animations.TransformSceneHandle:SetLocalRotation(stream, rotation) end

--- Gets the scale of the transform relative to the parent.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @return UnityEngine.Vector3 The scale of the transform relative to the parent.
function UnityEngine.Animations.TransformSceneHandle:GetLocalScale(stream) end

--- Gets the position, rotation and scale of the transform relative to the parent.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @return UnityEngine.Vector3& The position of the transform relative to the parent.
--- @return UnityEngine.Quaternion& The rotation of the transform relative to the parent.
--- @return UnityEngine.Vector3& The scale of the transform relative to the parent.
function UnityEngine.Animations.TransformSceneHandle:GetLocalTRS(stream) end

--- Gets the position and scaled rotation of the transform in world space.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @return UnityEngine.Vector3& The position of the transform in world space.
--- @return UnityEngine.Quaternion& The rotation of the transform in world space.
function UnityEngine.Animations.TransformSceneHandle:GetGlobalTR(stream) end

--- Sets the scale of the transform relative to the parent.
--- @param stream UnityEngine.Animations.AnimationStream The AnimationStream that manages this handle.
--- @param scale UnityEngine.Vector3 The scale of the transform relative to the parent.
function UnityEngine.Animations.TransformSceneHandle:SetLocalScale(stream, scale) end

---  Generated By xerysherry