--- @class UnityEngine.ParticleSystemTrailTextureMode Choose how textures are applied to Particle Trails.
UnityEngine.ParticleSystemTrailTextureMode = {
    --- Map the texture once along the entire length of the trail.
    Stretch = 0,
    --- Repeat the texture along the trail. To set the tiling rate, use Material.SetTextureScale.
    Tile = 1,
    --- Map the texture once along the entire length of the trail, assuming all vertices are evenly spaced.
    DistributePerSegment = 2,
    --- Repeat the texture along the trail, repeating at a rate of once per trail segment. To adjust the tiling rate, use Material.SetTextureScale.
    RepeatPerSegment = 3,
}

---  Generated By xerysherry