--- @class UnityEngine.VRTextureUsage This enum describes how the RenderTexture is used as a VR eye texture. Instead of using the values of this enum manually, use the value returned by XR.XRSettings.eyeTextureDesc|eyeTextureDesc or other VR functions returning a RenderTextureDescriptor.
UnityEngine.VRTextureUsage = {
    --- The RenderTexture is not a VR eye texture. No special rendering behavior will occur.
    None = 0,
    --- This texture corresponds to a single eye on a stereoscopic display.
    OneEye = 1,
    --- This texture corresponds to two eyes on a stereoscopic display. This will be taken into account when using Graphics.Blit and other rendering functions.
    TwoEyes = 2,
    --- The texture used by an external XR provider.  The provider is responsible for defining the texture's layout and use.
    DeviceSpecific = 3,
}

---  Generated By xerysherry