--- @class UnityEngine.SocialPlatforms.Impl.LocalUser:UnityEngine.SocialPlatforms.Impl.UserProfile 
--- @field friends UnityEngine.SocialPlatforms.IUserProfile[]
--- @field authenticated boolean
--- @field underage boolean
--- @field userName string
--- @field id string
--- @field gameId string
--- @field isFriend boolean
--- @field state UnityEngine.SocialPlatforms.UserState
--- @field image UnityEngine.Texture2D
UnityEngine.SocialPlatforms.Impl.LocalUser = {}

function UnityEngine.SocialPlatforms.Impl.LocalUser:Authenticate(callback) end

function UnityEngine.SocialPlatforms.Impl.LocalUser:Authenticate(callback) end

function UnityEngine.SocialPlatforms.Impl.LocalUser:LoadFriends(callback) end

function UnityEngine.SocialPlatforms.Impl.LocalUser:SetFriends(friends) end

function UnityEngine.SocialPlatforms.Impl.LocalUser:SetAuthenticated(value) end

function UnityEngine.SocialPlatforms.Impl.LocalUser:SetUnderage(value) end

---  Generated By xerysherry