--- @class UnityEngine.UIElements.UsageHints Offers a set of values that describe the intended usage patterns of a specific VisualElement.
UnityEngine.UIElements.UsageHints = {
    --- No particular hints applicable.
    None = 0,
    --- Marks a VisualElement that changes its transformation often (i.e. position, rotation or scale).
    --- When specified, this flag hints the system to optimize rendering of the VisualElement for recurring transformation changes. The VisualElement's vertex transformation will be done by the GPU when possible on the target platform.
    --- Please note that the number of VisualElements to which this hint effectively applies can be limited by target platform capabilities. For such platforms, it is recommended to prioritize use of this hint to only the VisualElements with the highest frequency of transformation changes.
    DynamicTransform = 1,
    --- Marks a VisualElement that hosts many children with DynamicTransform applied on them.
    --- A common use-case of this hint is a VisualElement that represents a "viewport" within which there are many DynamicTransform VisualElements that can move individually in addition to the "viewport" element also often changing its transformation. However, if the contents of the aforementioned "viewport" element are mostly static (not moving) then it is enough to use the DynamicTransform hint on that element instead of GroupTransform.
    --- Internally, an element hinted with GroupTransform will force a separate draw batch with its world transformation value, but in the same time it will avoid changing the transforms of all its descendants whenever a transformation change occurs on the GroupTransform element.
    GroupTransform = 2,
}

---  Generated By xerysherry