--- @class UnityEngine.Animations.RotationConstraint:UnityEngine.Behaviour Constrains the rotation of an object relative to the rotation of one or more source objects.
--- @field weight number property getset
---       The weight of the constraint component.
--- @field rotationAtRest UnityEngine.Vector3 property getset
---       The rotation used when the sources have a total weight of 0.
--- @field rotationOffset UnityEngine.Vector3 property getset
---       The offset from the constrained rotation.
--- @field rotationAxis UnityEngine.Animations.Axis property getset
---       The axes affected by the RotationConstraint.
--- @field constraintActive boolean property getset
---       Activates or deactivates the constraint.
--- @field locked boolean property getset
---       Locks the offset and rotation at rest.
--- @field sourceCount number property get
---       The number of sources set on the component (read-only).
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Animations.RotationConstraint = {}

--- @param value number 
function UnityEngine.Animations.RotationConstraint:set_weight(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.Animations.RotationConstraint:set_rotationAtRest(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.Animations.RotationConstraint:set_rotationOffset(value) end

--- @param value UnityEngine.Animations.Axis 
function UnityEngine.Animations.RotationConstraint:set_rotationAxis(value) end

--- @param value boolean 
function UnityEngine.Animations.RotationConstraint:set_constraintActive(value) end

--- @param value boolean 
function UnityEngine.Animations.RotationConstraint:set_locked(value) end

--- Gets the list of sources.
--- @param sources UnityEngine.Animations.ConstraintSource[] The list of sources to be filled by the component.
function UnityEngine.Animations.RotationConstraint:GetSources(sources) end

--- Sets the list of sources on the component.
--- @param sources UnityEngine.Animations.ConstraintSource[] The list of sources to set.
function UnityEngine.Animations.RotationConstraint:SetSources(sources) end

--- Adds a constraint source.
--- @param source UnityEngine.Animations.ConstraintSource The source object and its weight.
--- @return number Returns the index of the added source.
function UnityEngine.Animations.RotationConstraint:AddSource(source) end

--- Removes a source from the component.
--- @param index number The index of the source to remove.
function UnityEngine.Animations.RotationConstraint:RemoveSource(index) end

--- Gets a constraint source by index.
--- @param index number The index of the source.
--- @return UnityEngine.Animations.ConstraintSource The source object and its weight.
function UnityEngine.Animations.RotationConstraint:GetSource(index) end

--- Sets a source at a specified index.
--- @param index number The index of the source to set.
--- @param source UnityEngine.Animations.ConstraintSource The source object and its weight.
function UnityEngine.Animations.RotationConstraint:SetSource(index, source) end

---  Generated By xerysherry