--- @class UnityEngine.Windows.Speech.SpeechSystemStatus Represents the current status of the speech recognition system or a dictation recognizer.
UnityEngine.Windows.Speech.SpeechSystemStatus = {
    --- Speech recognition system is stopped.
    Stopped = 0,
    --- Speech recognition system is running.
    Running = 1,
    --- Speech recognition system has encountered an error and is in an indeterminate state.
    Failed = 2,
}

---  Generated By xerysherry