--- @class UnityEngine.VR.VRNodeState 
--- @field uniqueID number
--- @field nodeType UnityEngine.VR.VRNode
--- @field tracked boolean
--- @field position UnityEngine.Vector3
--- @field rotation UnityEngine.Quaternion
--- @field velocity UnityEngine.Vector3
--- @field angularVelocity UnityEngine.Vector3
--- @field acceleration UnityEngine.Vector3
--- @field angularAcceleration UnityEngine.Vector3
UnityEngine.VR.VRNodeState = {}

function UnityEngine.VR.VRNodeState:set_uniqueID(value) end

function UnityEngine.VR.VRNodeState:set_nodeType(value) end

function UnityEngine.VR.VRNodeState:set_tracked(value) end

function UnityEngine.VR.VRNodeState:set_position(value) end

function UnityEngine.VR.VRNodeState:set_rotation(value) end

function UnityEngine.VR.VRNodeState:set_velocity(value) end

function UnityEngine.VR.VRNodeState:set_angularVelocity(value) end

function UnityEngine.VR.VRNodeState:set_acceleration(value) end

function UnityEngine.VR.VRNodeState:set_angularAcceleration(value) end

--- @return boolean
function UnityEngine.VR.VRNodeState:TryGetPosition() end

--- @return boolean
function UnityEngine.VR.VRNodeState:TryGetRotation() end

--- @return boolean
function UnityEngine.VR.VRNodeState:TryGetVelocity() end

--- @return boolean
function UnityEngine.VR.VRNodeState:TryGetAngularVelocity() end

--- @return boolean
function UnityEngine.VR.VRNodeState:TryGetAcceleration() end

--- @return boolean
function UnityEngine.VR.VRNodeState:TryGetAngularAcceleration() end

---  Generated By xerysherry