--- @class UnityEngine.Experimental.Rendering.GraphicsDeviceSettings 
--- @field waitForPresentSyncPoint UnityEngine.Experimental.Rendering.WaitForPresentSyncPoint
--- @field graphicsJobsSyncPoint UnityEngine.Experimental.Rendering.GraphicsJobsSyncPoint
UnityEngine.Experimental.Rendering.GraphicsDeviceSettings = {}

function UnityEngine.Experimental.Rendering.GraphicsDeviceSettings.set_waitForPresentSyncPoint(value) end

function UnityEngine.Experimental.Rendering.GraphicsDeviceSettings.set_graphicsJobsSyncPoint(value) end

---  Generated By xerysherry