--- @class UnityEngine.Experimental.GlobalIllumination.LinearColor Contains normalized linear color values for red, green, blue in the range of 0 to 1, and an additional intensity value.
--- @field red number property getset
---       The red color value in the range of 0.0 to 1.0.
--- @field green number property getset
---       The green color value in the range of 0.0 to 1.0.
--- @field blue number property getset
---       The blue color value in the range of 0.0 to 1.0.
--- @field intensity number property getset
---       The intensity value used to scale the red, green and blue values.
UnityEngine.Experimental.GlobalIllumination.LinearColor = {}

--- Converts a Light's color value to a normalized linear color value, automatically handling gamma conversion if necessary.
--- @param color UnityEngine.Color Light color.
--- @param intensity number Light intensity.
--- @return UnityEngine.Experimental.GlobalIllumination.LinearColor Returns the normalized linear color value.
function UnityEngine.Experimental.GlobalIllumination.LinearColor.Convert(color, intensity) end

--- Returns a black color.
--- @return UnityEngine.Experimental.GlobalIllumination.LinearColor Returns a black color.
function UnityEngine.Experimental.GlobalIllumination.LinearColor.Black() end

function UnityEngine.Experimental.GlobalIllumination.LinearColor:set_red(value) end

function UnityEngine.Experimental.GlobalIllumination.LinearColor:set_green(value) end

function UnityEngine.Experimental.GlobalIllumination.LinearColor:set_blue(value) end

function UnityEngine.Experimental.GlobalIllumination.LinearColor:set_intensity(value) end

---  Generated By xerysherry