--- @class UnityEngine.DrivenRectTransformTracker A component can be designed to drive a RectTransform. The DrivenRectTransformTracker struct is used to specify which RectTransforms it is driving.
UnityEngine.DrivenRectTransformTracker = {}

--- Stop recording undo actions from driven RectTransforms.
function UnityEngine.DrivenRectTransformTracker.StopRecordingUndo() end

--- Resume recording undo of driven RectTransforms.
function UnityEngine.DrivenRectTransformTracker.StartRecordingUndo() end

--- Add a RectTransform to be driven.
--- @param driver UnityEngine.Object The object to drive properties.
--- @param rectTransform UnityEngine.RectTransform The RectTransform to be driven.
--- @param drivenProperties UnityEngine.DrivenTransformProperties The properties to be driven.
function UnityEngine.DrivenRectTransformTracker:Add(driver, rectTransform, drivenProperties) end

--- Clear the list of RectTransforms being driven.
function UnityEngine.DrivenRectTransformTracker:Clear(revertValues) end

--- Clear the list of RectTransforms being driven.
function UnityEngine.DrivenRectTransformTracker:Clear() end

---  Generated By xerysherry