--- @class UnityEngine.UIElements.UxmlEnumeration:UnityEngine.UIElements.UxmlTypeRestriction Restricts the value of an attribute to be taken from a list of values.
--- @field values System.Collections.Generic.IEnumerable`1 property getset
---       The list of values the attribute can take.
UnityEngine.UIElements.UxmlEnumeration = {}

--- @param value System.Collections.Generic.IEnumerable`1 
function UnityEngine.UIElements.UxmlEnumeration:set_values(value) end

--- Indicates whether the current UxmlEnumeration object is equal to another object of the same type.
--- @param other UnityEngine.UIElements.UxmlTypeRestriction The object to compare with.
--- @return boolean True if the otheer object is equal to this one.
function UnityEngine.UIElements.UxmlEnumeration:Equals(other) end

---  Generated By xerysherry