--- @class UnityEngineInternal.GenericStack:System.Collections.Stack 
--- @field Count number
--- @field IsSynchronized boolean
--- @field SyncRoot System.Object
UnityEngineInternal.GenericStack = {}

---  Generated By xerysherry