--- @class UnityEngine.CustomRenderTextureUpdateMode Frequency of update or initialization of a Custom Render Texture.
UnityEngine.CustomRenderTextureUpdateMode = {
    --- Initialization/Update will occur once at load time and then can be triggered again by script.
    OnLoad = 0,
    --- Initialization/Update will occur at every frame.
    Realtime = 1,
    --- Initialization/Update will only occur when triggered by the script.
    OnDemand = 2,
}

---  Generated By xerysherry