--- @class UnityEngine.Networking.GlobalConfig Defines global paramters for network library.
--- @field ThreadAwakeTimeout number property getset
---       Defines (1) for select reactor, minimum time period, when system will check if there are any messages for send (2) for fixrate reactor, minimum interval of time, when system will check for sending and receiving messages.
--- @field ReactorModel UnityEngine.Networking.ReactorModel property getset
---       Defines reactor model for the network library.
--- @field ReactorMaximumReceivedMessages number property getset
---       This property determines the initial size of the queue that holds messages received by Unity Multiplayer before they are processed.
--- @field ReactorMaximumSentMessages number property getset
---       Defines the initial size of the send queue. Messages are placed in this queue ready to be sent in packets to their destination.
--- @field MaxPacketSize number property getset
---       Defines maximum possible packet size in bytes for all network connections.
--- @field MaxHosts number property getset
---       Defines how many hosts you can use. Default Value = 16. Max value = 128.
--- @field ThreadPoolSize number property getset
---       Defines how many worker threads are available to handle incoming and outgoing messages.
--- @field MinTimerTimeout number property getset
---       Defines the minimum timeout in milliseconds recognised by the system. The default value is 1 ms.
--- @field MaxTimerTimeout number property getset
---       Defines the maximum timeout in milliseconds for any configuration. The default value is 12 seconds (12000ms).
--- @field MinNetSimulatorTimeout number property getset
---       Deprecated. Defines the minimal timeout for network simulator. You cannot set up any delay less than this value. See Also: MinTimerTimeout.
--- @field MaxNetSimulatorTimeout number property getset
---       Deprecated. Defines maximum delay for network simulator. See Also: MaxTimerTimeout.
--- @field NetworkEventAvailable function property getset
---       Defines the callback delegate which you can use to get a notification when the host (defined by hostID) has a network event. The callback is called for all event types except Networking.NetworkEventType.Nothing.
---       
---       See Also: Networking.NetworkEventType
--- @field ConnectionReadyForSend function property getset
---       Defines the callback delegate which you can use to get a notification when a connection is ready to send data.
UnityEngine.Networking.GlobalConfig = {}

--- @param value number 
function UnityEngine.Networking.GlobalConfig:set_ThreadAwakeTimeout(value) end

--- @param value UnityEngine.Networking.ReactorModel 
function UnityEngine.Networking.GlobalConfig:set_ReactorModel(value) end

--- @param value number 
function UnityEngine.Networking.GlobalConfig:set_ReactorMaximumReceivedMessages(value) end

--- @param value number 
function UnityEngine.Networking.GlobalConfig:set_ReactorMaximumSentMessages(value) end

--- @param value number 
function UnityEngine.Networking.GlobalConfig:set_MaxPacketSize(value) end

--- @param value number 
function UnityEngine.Networking.GlobalConfig:set_MaxHosts(value) end

--- @param value number 
function UnityEngine.Networking.GlobalConfig:set_ThreadPoolSize(value) end

--- @param value number 
function UnityEngine.Networking.GlobalConfig:set_MinTimerTimeout(value) end

--- @param value number 
function UnityEngine.Networking.GlobalConfig:set_MaxTimerTimeout(value) end

--- @param value number 
function UnityEngine.Networking.GlobalConfig:set_MinNetSimulatorTimeout(value) end

--- @param value number 
function UnityEngine.Networking.GlobalConfig:set_MaxNetSimulatorTimeout(value) end

--- @param value function 
function UnityEngine.Networking.GlobalConfig:set_NetworkEventAvailable(value) end

--- @param value function 
function UnityEngine.Networking.GlobalConfig:set_ConnectionReadyForSend(value) end

---  Generated By xerysherry