--- @class UnityEngine.WaitWhile:UnityEngine.CustomYieldInstruction Suspends the coroutine execution until the supplied delegate evaluates to false.
--- @field keepWaiting boolean
--- @field Current System.Object
UnityEngine.WaitWhile = {}

---  Generated By xerysherry