--- @class UnityEngine.XR.TrackingSpaceType Represents the size of physical space available for XR.
UnityEngine.XR.TrackingSpaceType = {
    --- Represents a small space where movement may be constrained or positional tracking is unavailable.
    Stationary = 0,
    --- Represents a space large enough for free movement.
    RoomScale = 1,
}

---  Generated By xerysherry