--- @class Unity.Collections.LowLevel.Unsafe.NativeSetClassTypeToNullOnScheduleAttribute:System.Attribute When this attribute is applied to a field in a job struct, the managed reference to the class will be set to null on the copy of the job struct that is passed to the job.
--- @field TypeId System.Object
Unity.Collections.LowLevel.Unsafe.NativeSetClassTypeToNullOnScheduleAttribute = {}

---  Generated By xerysherry