--- @class UnityEngine.MovieTexture:UnityEngine.Texture MovieTexture has been removed. Use VideoPlayer instead.
--- @field audioClip UnityEngine.AudioClip property get
---       MovieTexture has been removed. Use VideoPlayer instead.
--- @field loop boolean property getset
---       MovieTexture has been removed. Use VideoPlayer instead.
--- @field isPlaying boolean property get
---       MovieTexture has been removed. Use VideoPlayer instead.
--- @field isReadyToPlay boolean property get
---       MovieTexture has been removed. Use VideoPlayer instead.
--- @field duration number property get
---       MovieTexture has been removed. Use VideoPlayer instead.
--- @field mipmapCount number
--- @field graphicsFormat UnityEngine.Experimental.Rendering.GraphicsFormat
--- @field width number
--- @field height number
--- @field dimension UnityEngine.Rendering.TextureDimension
--- @field isReadable boolean
--- @field wrapMode UnityEngine.TextureWrapMode
--- @field wrapModeU UnityEngine.TextureWrapMode
--- @field wrapModeV UnityEngine.TextureWrapMode
--- @field wrapModeW UnityEngine.TextureWrapMode
--- @field filterMode UnityEngine.FilterMode
--- @field anisoLevel number
--- @field mipMapBias number
--- @field texelSize UnityEngine.Vector2
--- @field updateCount number
--- @field imageContentsHash UnityEngine.Hash128
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.MovieTexture = {}

--- MovieTexture has been removed. Use VideoPlayer instead.
function UnityEngine.MovieTexture:Play() end

--- MovieTexture has been removed. Use VideoPlayer instead.
function UnityEngine.MovieTexture:Stop() end

--- MovieTexture has been removed. Use VideoPlayer instead.
function UnityEngine.MovieTexture:Pause() end

--- @param value boolean 
function UnityEngine.MovieTexture:set_loop(value) end

---  Generated By xerysherry