--- @class UnityEngine.XR.MeshInfo Contains state information related to a tracked mesh.
--- @field MeshId UnityEngine.XR.MeshId property getset
---       The MeshId of the tracked mesh.
--- @field ChangeState UnityEngine.XR.MeshChangeState property getset
---       The change state (e.g., Added, Removed) of the tracked mesh.
--- @field PriorityHint number property getset
---       A hint that can be used to determine when this mesh should be processed.
UnityEngine.XR.MeshInfo = {}

--- @param lhs UnityEngine.XR.MeshInfo 
--- @param rhs UnityEngine.XR.MeshInfo 
--- @return boolean
function UnityEngine.XR.MeshInfo.op_Equality(lhs, rhs) end

--- @param lhs UnityEngine.XR.MeshInfo 
--- @param rhs UnityEngine.XR.MeshInfo 
--- @return boolean
function UnityEngine.XR.MeshInfo.op_Inequality(lhs, rhs) end

--- @param value UnityEngine.XR.MeshId 
function UnityEngine.XR.MeshInfo:set_MeshId(value) end

--- @param value UnityEngine.XR.MeshChangeState 
function UnityEngine.XR.MeshInfo:set_ChangeState(value) end

--- @param value number 
function UnityEngine.XR.MeshInfo:set_PriorityHint(value) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.XR.MeshInfo:Equals(obj) end

--- @param other UnityEngine.XR.MeshInfo 
--- @return boolean
function UnityEngine.XR.MeshInfo:Equals(other) end

--- @return number
function UnityEngine.XR.MeshInfo:GetHashCode() end

---  Generated By xerysherry