--- @class UnityEngine.XR.WSA.HolographicRemoting he Holographic Remoting interface allows you to connect an application to a remote holographic device, and stream data between the application and that device.
--- @field ConnectionState UnityEngine.XR.WSA.HolographicStreamerConnectionState property get
---       Whether the app is displaying protected content.
UnityEngine.XR.WSA.HolographicRemoting = {}

--- @param clientName string 
--- @param maxBitRate number 
function UnityEngine.XR.WSA.HolographicRemoting.Connect(clientName, maxBitRate) end

--- @param clientName string 
--- @param maxBitRate number 
--- @param deviceVersion UnityEngine.XR.WSA.RemoteDeviceVersion 
function UnityEngine.XR.WSA.HolographicRemoting.Connect(clientName, maxBitRate, deviceVersion) end

function UnityEngine.XR.WSA.HolographicRemoting.Disconnect() end

---  Generated By xerysherry