--- @class UnityEngine.BoxcastCommand Use this struct to set up a box cast command to be performed asynchronously during a job.
--- @field center UnityEngine.Vector3 property getset
---       Center of the box.
--- @field halfExtents UnityEngine.Vector3 property getset
---       Half the size of the box in each dimension.
--- @field orientation UnityEngine.Quaternion property getset
---       Rotation of the box.
--- @field direction UnityEngine.Vector3 property getset
---       The direction in which to sweep the box.
--- @field distance number property getset
---       The maximum distance of the sweep.
--- @field layerMask number property getset
---       A LayerMask that is used to selectively ignore Colliders when casting a box.
UnityEngine.BoxcastCommand = {}

--- Schedules a batch of boxcasts to be performed in a job.
--- @param commands Unity.Collections.NativeArray`1 A NativeArray of the BoxcastCommand to perform.
--- @param results Unity.Collections.NativeArray`1 A NativeArray of RaycastHit where the result of commands are stored.
--- @param minCommandsPerJob number The minimum number of jobs which should be performed in a single job.
--- @param dependsOn Unity.Jobs.JobHandle A JobHandle of a job that must be completed before performing the box casts.
--- @return Unity.Jobs.JobHandle Returns a JobHandle of the job that will perform the box casts.
function UnityEngine.BoxcastCommand.ScheduleBatch(commands, results, minCommandsPerJob, dependsOn) end

function UnityEngine.BoxcastCommand:set_center(value) end

function UnityEngine.BoxcastCommand:set_halfExtents(value) end

function UnityEngine.BoxcastCommand:set_orientation(value) end

function UnityEngine.BoxcastCommand:set_direction(value) end

function UnityEngine.BoxcastCommand:set_distance(value) end

function UnityEngine.BoxcastCommand:set_layerMask(value) end

---  Generated By xerysherry