--- @class UnityEngine.UIElements.StyleInt Style value that can be either an integer or a StyleKeyword.
--- @field value number property getset
---       The integer value.
--- @field keyword UnityEngine.UIElements.StyleKeyword property getset
---       The style keyword.
UnityEngine.UIElements.StyleInt = {}

--- @return boolean
function UnityEngine.UIElements.StyleInt.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.UIElements.StyleInt.op_Inequality(lhs, rhs) end

--- @return UnityEngine.UIElements.StyleInt
function UnityEngine.UIElements.StyleInt.op_Implicit(keyword) end

--- @return UnityEngine.UIElements.StyleInt
function UnityEngine.UIElements.StyleInt.op_Implicit(v) end

function UnityEngine.UIElements.StyleInt:set_value(value) end

function UnityEngine.UIElements.StyleInt:set_keyword(value) end

--- @return boolean
function UnityEngine.UIElements.StyleInt:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.StyleInt:Equals(obj) end

--- @return number
function UnityEngine.UIElements.StyleInt:GetHashCode() end

--- @return string
function UnityEngine.UIElements.StyleInt:ToString() end

---  Generated By xerysherry