--- @class UnityEngine.LegDof Enumeration of all the muscles in a leg.
UnityEngine.LegDof = {
    --- The upper leg front-back muscle.
    UpperLegFrontBack = 0,
    --- The upper leg in-out muscle.
    UpperLegInOut = 1,
    --- The upper leg roll in-out muscle.
    UpperLegRollInOut = 2,
    --- The leg close-open muscle.
    LegCloseOpen = 3,
    --- The leg roll in-out muscle.
    LegRollInOut = 4,
    --- The foot close-open muscle.
    FootCloseOpen = 5,
    --- The foot in-out muscle.
    FootInOut = 6,
    --- The toes up-down muscle.
    ToesUpDown = 7,
    --- The last value of the LegDof enum.
    LastLegDof = 8,
}

---  Generated By xerysherry