--- @class UnityEngine.RigidbodyType2D The physical behaviour type of the Rigidbody2D.
UnityEngine.RigidbodyType2D = {
    --- Sets the Rigidbody2D to have dynamic behaviour.
    Dynamic = 0,
    --- Sets the Rigidbody2D to have kinematic behaviour.
    Kinematic = 1,
    --- Sets the Rigidbody2D to have static behaviour.
    Static = 2,
}

---  Generated By xerysherry