--- @class UnityEngine.VFX.VFXManager Use this class to set a number of properties that control VisualEffect behavior within your Unity Project.
--- @field fixedTimeStep number property getset
---       The fixed interval in which the frame rate updates. The tick rate is in seconds.
--- @field maxDeltaTime number property getset
---       The maximum allowed delta time for an update interval. This limit affects fixedDeltaTime and deltaTime. The tick rate is in seconds.
UnityEngine.VFX.VFXManager = {}

--- @return UnityEngine.VFX.VisualEffect[]
function UnityEngine.VFX.VFXManager.GetComponents() end

function UnityEngine.VFX.VFXManager.set_fixedTimeStep(value) end

function UnityEngine.VFX.VFXManager.set_maxDeltaTime(value) end

--- Use this method to prepare and process per-Camera VFX commands for this frame.
--- @param cam UnityEngine.Camera The Camera to prepare for processing VFX commands.
function UnityEngine.VFX.VFXManager.ProcessCamera(cam) end

--- Use this method to prepare per-Camera VFX commands for this frame.
--- @param cam UnityEngine.Camera The Camera to prepare for processing VFX commands.
function UnityEngine.VFX.VFXManager.PrepareCamera(cam) end

--- Use this method to process per-Camera VFX commands for the current frame.
--- @param cam UnityEngine.Camera The Camera to process the VFX commands for.
--- @param cmd UnityEngine.Rendering.CommandBuffer The CommandBuffer to push commands to (can be null).
function UnityEngine.VFX.VFXManager.ProcessCameraCommand(cam, cmd) end

--- Queries which buffers the VFX Manager needs for the given Camera.
--- @param cam UnityEngine.Camera The Camera for which to query needed buffers.
--- @return UnityEngine.VFX.VFXCameraBufferTypes A list of all needed buffer flags.
function UnityEngine.VFX.VFXManager.IsCameraBufferNeeded(cam) end

--- Use this method to set the buffer of a given type for this Camera. This allows the VFX Manager to use the buffer.
--- @param cam UnityEngine.Camera The Camera to set the buffer for.
--- @param type UnityEngine.VFX.VFXCameraBufferTypes The type of buffer to set.
--- @param buffer UnityEngine.Texture The buffer to set.
--- @param x number X offset of the viewport in the buffer.
--- @param y number Y offset of the viewport in the buffer.
--- @param width number Width of the viewport in the buffer.
--- @param height number Height of the viewport in the buffer.
function UnityEngine.VFX.VFXManager.SetCameraBuffer(cam, type, buffer, x, y, width, height) end

---  Generated By xerysherry