--- @class UnityEngine.Pose Representation of a Position, and a Rotation in 3D Space
--- @field identity UnityEngine.Pose property get
---       Shorthand for pose which represents zero position, and an identity rotation.
--- @field forward UnityEngine.Vector3 property get
---       Returns the forward vector of the pose.
--- @field right UnityEngine.Vector3 property get
---       Returns the right vector of the pose.
--- @field up UnityEngine.Vector3 property get
---       Returns the up vector of the pose.
--- @field position UnityEngine.Vector3 The position component of the pose.
--- @field rotation UnityEngine.Quaternion The rotation component of the pose.
UnityEngine.Pose = {}

--- @param a UnityEngine.Pose 
--- @param b UnityEngine.Pose 
--- @return boolean
function UnityEngine.Pose.op_Equality(a, b) end

--- @param a UnityEngine.Pose 
--- @param b UnityEngine.Pose 
--- @return boolean
function UnityEngine.Pose.op_Inequality(a, b) end

--- @return string
function UnityEngine.Pose:ToString() end

--- @param format string 
--- @return string
function UnityEngine.Pose:ToString(format) end

--- Transforms the current pose into the local space of the provided pose.
--- @param lhs UnityEngine.Pose 
--- @return UnityEngine.Pose 
function UnityEngine.Pose:GetTransformedBy(lhs) end

--- Transforms the current pose into the local space of the provided pose.
--- @param lhs UnityEngine.Transform 
--- @return UnityEngine.Pose 
function UnityEngine.Pose:GetTransformedBy(lhs) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.Pose:Equals(obj) end

--- @param other UnityEngine.Pose 
--- @return boolean
function UnityEngine.Pose:Equals(other) end

--- @return number
function UnityEngine.Pose:GetHashCode() end

---  Generated By xerysherry