--- @class UnityEngine.Rendering.SplashScreen Provides an interface to the Unity splash screen.
--- @field isFinished boolean property get
---       Returns true once the splash screen has finished. This is once all logos have been shown for their specified duration.
UnityEngine.Rendering.SplashScreen = {}

--- Initializes the splash screen so it is ready to begin drawing. Call this before you start calling Rendering.SplashScreen.Draw. Internally this function resets the timer and prepares the logos for drawing.
function UnityEngine.Rendering.SplashScreen.Begin() end

--- Stop the SplashScreen rendering.
--- @param stopBehavior UnityEngine.Rendering.SplashScreen.StopBehavior 
function UnityEngine.Rendering.SplashScreen.Stop(stopBehavior) end

--- Immediately draws the splash screen. Ensure you have called Rendering.SplashScreen.Begin before you start calling this.
function UnityEngine.Rendering.SplashScreen.Draw() end

---  Generated By xerysherry