--- @class UnityEngine.Playables.AnimationPlayableUtilities Implements high-level utility methods to simplify use of the Playable API with Animations.
UnityEngine.Playables.AnimationPlayableUtilities = {}

--- Plays the Playable on  the given Animator.
--- @param animator UnityEngine.Animator Target Animator.
--- @param playable UnityEngine.Playables.Playable The Playable that will be played.
--- @param graph UnityEngine.Playables.PlayableGraph The Graph that owns the Playable.
function UnityEngine.Playables.AnimationPlayableUtilities.Play(animator, playable, graph) end

--- Creates a PlayableGraph to be played on the given Animator. An AnimationClipPlayable is also created for the given AnimationClip.
--- @param animator UnityEngine.Animator Target Animator.
--- @param clip UnityEngine.AnimationClip The AnimationClip to create an AnimationClipPlayable for.
--- @return UnityEngine.Animations.AnimationClipPlayable A handle to the newly-created AnimationClipPlayable.
--- @return UnityEngine.Playables.PlayableGraph& The created PlayableGraph.
function UnityEngine.Playables.AnimationPlayableUtilities.PlayClip(animator, clip) end

--- Creates a PlayableGraph to be played on the given Animator. An AnimationMixerPlayable is also created.
--- @param animator UnityEngine.Animator Target Animator.
--- @param inputCount number The input count for the AnimationMixerPlayable.
--- @return UnityEngine.Animations.AnimationMixerPlayable A handle to the newly-created AnimationMixerPlayable.
--- @return UnityEngine.Playables.PlayableGraph& The created PlayableGraph.
function UnityEngine.Playables.AnimationPlayableUtilities.PlayMixer(animator, inputCount) end

--- Creates a PlayableGraph to be played on the given Animator. An AnimationLayerMixerPlayable is also created.
--- @param animator UnityEngine.Animator Target Animator.
--- @param inputCount number The input count for the AnimationLayerMixerPlayable. Defines the number of layers.
--- @return UnityEngine.Animations.AnimationLayerMixerPlayable A handle to the newly-created AnimationLayerMixerPlayable.
--- @return UnityEngine.Playables.PlayableGraph& The created PlayableGraph.
function UnityEngine.Playables.AnimationPlayableUtilities.PlayLayerMixer(animator, inputCount) end

--- Creates a PlayableGraph to be played on the given Animator. An AnimatorControllerPlayable is also created for the given RuntimeAnimatorController.
--- @param animator UnityEngine.Animator Target Animator.
--- @param controller UnityEngine.RuntimeAnimatorController The RuntimeAnimatorController to create an AnimatorControllerPlayable for.
--- @return UnityEngine.Animations.AnimatorControllerPlayable A handle to the newly-created AnimatorControllerPlayable.
--- @return UnityEngine.Playables.PlayableGraph& The created PlayableGraph.
function UnityEngine.Playables.AnimationPlayableUtilities.PlayAnimatorController(animator, controller) end

---  Generated By xerysherry