--- @class UnityEngine.XR.Bone A tracked bone on the device at an XR.XRNode in the XR input subsystem.
UnityEngine.XR.Bone = {}

--- @return boolean
function UnityEngine.XR.Bone.op_Equality(a, b) end

--- @return boolean
function UnityEngine.XR.Bone.op_Inequality(a, b) end

--- Gets the world position of the bone
--- @return boolean true if the rotation was retrieved, false otherwise.
--- @return UnityEngine.Vector3& Vector3 to receive the position of the bone in Unity world space.
function UnityEngine.XR.Bone:TryGetPosition() end

--- Gets the world rotation of the bone.
--- @return boolean true if the rotation was retrieved, false otherwise.
--- @return UnityEngine.Quaternion& Quaternion to receive the rotation of the bone in Unity world space.
function UnityEngine.XR.Bone:TryGetRotation() end

--- Gets the parent of this bone.
--- @return boolean true if the rotation was retrieved, false otherwise.
--- @return UnityEngine.XR.Bone& Bone struct that receives the parent bone of this bone.
function UnityEngine.XR.Bone:TryGetParentBone() end

--- Get the child bones of this bone.
--- @param childBones UnityEngine.XR.Bone[] A list of bones that will be filled out with the children bones of this bone.
--- @return boolean true if bone can be queried for child bones; otherwise false.
function UnityEngine.XR.Bone:TryGetChildBones(childBones) end

--- @return boolean
function UnityEngine.XR.Bone:Equals(obj) end

--- @return boolean
function UnityEngine.XR.Bone:Equals(other) end

--- @return number
function UnityEngine.XR.Bone:GetHashCode() end

---  Generated By xerysherry