--- @class UnityEngine.SharedBetweenAnimatorsAttribute:System.Attribute SharedBetweenAnimatorsAttribute is an attribute that specify that this StateMachineBehaviour should be instantiate only once and shared among all Animator instance. This attribute reduce the memory footprint for each controller instance.
--- @field TypeId System.Object
UnityEngine.SharedBetweenAnimatorsAttribute = {}

---  Generated By xerysherry