--- @class UnityEngine.BoxCollider:UnityEngine.Collider A box-shaped primitive collider.
--- @field center UnityEngine.Vector3 property getset
---       The center of the box, measured in the object's local space.
--- @field size UnityEngine.Vector3 property getset
---       The size of the box, measured in the object's local space.
--- @field extents UnityEngine.Vector3
--- @field enabled boolean
--- @field attachedRigidbody UnityEngine.Rigidbody
--- @field isTrigger boolean
--- @field contactOffset number
--- @field bounds UnityEngine.Bounds
--- @field sharedMaterial UnityEngine.PhysicMaterial
--- @field material UnityEngine.PhysicMaterial
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.BoxCollider = {}

function UnityEngine.BoxCollider:set_center(value) end

function UnityEngine.BoxCollider:set_size(value) end

function UnityEngine.BoxCollider:set_extents(value) end

---  Generated By xerysherry