--- @class UnityEngine.XR.WSA.Input.InteractionSourceKind Specifies the kind of an interaction source.
UnityEngine.XR.WSA.Input.InteractionSourceKind = {
    --- The interaction source is of a kind not known in this version of the API.
    Other = 0,
    --- The interaction source is one of the user's hands.
    Hand = 1,
    --- The interaction source is the user's speech.
    Voice = 2,
    --- The interaction source is of a kind not known in this version of the API.
    Controller = 3,
}

---  Generated By xerysherry