--- @class UnityEngine.AudioChorusFilter:UnityEngine.Behaviour The Audio Chorus Filter takes an Audio Clip and processes it creating a chorus effect.
--- @field dryMix number property getset
---       Volume of original signal to pass to output. 0.0 to 1.0. Default = 0.5.
--- @field wetMix1 number property getset
---       Volume of 1st chorus tap. 0.0 to 1.0. Default = 0.5.
--- @field wetMix2 number property getset
---       Volume of 2nd chorus tap. This tap is 90 degrees out of phase of the first tap. 0.0 to 1.0. Default = 0.5.
--- @field wetMix3 number property getset
---       Volume of 3rd chorus tap. This tap is 90 degrees out of phase of the second tap. 0.0 to 1.0. Default = 0.5.
--- @field delay number property getset
---       Chorus delay in ms. 0.1 to 100.0. Default = 40.0 ms.
--- @field rate number property getset
---       Chorus modulation rate in hz. 0.0 to 20.0. Default = 0.8 hz.
--- @field depth number property getset
---       Chorus modulation depth. 0.0 to 1.0. Default = 0.03.
--- @field feedback number property getset
---       Chorus feedback. Controls how much of the wet signal gets fed back into the chorus buffer. 0.0 to 1.0. Default = 0.0.
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.AudioChorusFilter = {}

--- @param value number 
function UnityEngine.AudioChorusFilter:set_dryMix(value) end

--- @param value number 
function UnityEngine.AudioChorusFilter:set_wetMix1(value) end

--- @param value number 
function UnityEngine.AudioChorusFilter:set_wetMix2(value) end

--- @param value number 
function UnityEngine.AudioChorusFilter:set_wetMix3(value) end

--- @param value number 
function UnityEngine.AudioChorusFilter:set_delay(value) end

--- @param value number 
function UnityEngine.AudioChorusFilter:set_rate(value) end

--- @param value number 
function UnityEngine.AudioChorusFilter:set_depth(value) end

--- @param value number 
function UnityEngine.AudioChorusFilter:set_feedback(value) end

---  Generated By xerysherry