--- @class UnityEngine.VR.VRSettings 
--- @field enabled boolean
--- @field isDeviceActive boolean
--- @field showDeviceView boolean
--- @field renderScale number
--- @field eyeTextureWidth number
--- @field eyeTextureHeight number
--- @field renderViewportScale number
--- @field occlusionMaskScale number
--- @field loadedDevice UnityEngine.VR.VRDeviceType
--- @field loadedDeviceName string
--- @field supportedDevices string[]
UnityEngine.VR.VRSettings = {}

--- @param value boolean 
function UnityEngine.VR.VRSettings.set_enabled(value) end

--- @param value boolean 
function UnityEngine.VR.VRSettings.set_showDeviceView(value) end

--- @param value number 
function UnityEngine.VR.VRSettings.set_renderScale(value) end

--- @param value number 
function UnityEngine.VR.VRSettings.set_renderViewportScale(value) end

--- @param value number 
function UnityEngine.VR.VRSettings.set_occlusionMaskScale(value) end

--- @param value UnityEngine.VR.VRDeviceType 
function UnityEngine.VR.VRSettings.set_loadedDevice(value) end

--- @param deviceName string 
function UnityEngine.VR.VRSettings.LoadDeviceByName(deviceName) end

--- @param prioritizedDeviceNameList string[] 
function UnityEngine.VR.VRSettings.LoadDeviceByName(prioritizedDeviceNameList) end

---  Generated By xerysherry