--- @class UnityEngine.UISystemProfilerApi 
UnityEngine.UISystemProfilerApi = {}

--- @param type UnityEngine.UISystemProfilerApi.SampleType 
function UnityEngine.UISystemProfilerApi.BeginSample(type) end

--- @param type UnityEngine.UISystemProfilerApi.SampleType 
function UnityEngine.UISystemProfilerApi.EndSample(type) end

--- @param name string 
--- @param obj UnityEngine.Object 
function UnityEngine.UISystemProfilerApi.AddMarker(name, obj) end

---  Generated By xerysherry