--- @class UnityEngine.iOS.ADBannerView.Layout Specifies how banner should be layed out on screen.
UnityEngine.iOS.ADBannerView.Layout = {
    --- Traditional Banner: align to screen top.
    Top = 0,
    --- Traditional Banner: align to screen bottom.
    Bottom = 1,
    --- Rect Banner: place in top-left corner.
    TopLeft = 0,
    --- Rect Banner: place in top-right corner.
    TopRight = 4,
    --- Rect Banner: align to screen top, placing at the center.
    TopCenter = 8,
    --- Rect Banner: place in bottom-left corner.
    BottomLeft = 1,
    --- Rect Banner: place in bottom-right corner.
    BottomRight = 5,
    --- Rect Banner: align to screen bottom, placing at the center.
    BottomCenter = 9,
    --- Rect Banner: align to screen left, placing at the center.
    CenterLeft = 2,
    --- Rect Banner: align to screen right, placing at the center.
    CenterRight = 6,
    --- Rect Banner: place exactly at screen center.
    Center = 10,
    --- Completely manual positioning.
    Manual = -1,
}

--- @class UnityEngine.iOS.ADBannerView.Layout Specifies how banner should be layed out on screen.
UnityEngine.iOS.ADBannerView.Layout = {
    --- Traditional Banner: align to screen top.
    Top = 0,
    --- Traditional Banner: align to screen bottom.
    Bottom = 1,
    --- Rect Banner: place in top-left corner.
    TopLeft = 0,
    --- Rect Banner: place in top-right corner.
    TopRight = 4,
    --- Rect Banner: align to screen top, placing at the center.
    TopCenter = 8,
    --- Rect Banner: place in bottom-left corner.
    BottomLeft = 1,
    --- Rect Banner: place in bottom-right corner.
    BottomRight = 5,
    --- Rect Banner: align to screen bottom, placing at the center.
    BottomCenter = 9,
    --- Rect Banner: align to screen left, placing at the center.
    CenterLeft = 2,
    --- Rect Banner: align to screen right, placing at the center.
    CenterRight = 6,
    --- Rect Banner: place exactly at screen center.
    Center = 10,
    --- Completely manual positioning.
    Manual = -1,
}

---  Generated By xerysherry