--- @class UnityEngine.TextCore.LowLevel.GlyphRenderMode The rendering modes used by the Font Engine to render glyphs.
UnityEngine.TextCore.LowLevel.GlyphRenderMode = {
    --- Renders a bitmap representation of the glyph from an 8-bit or antialiased image of the glyph outline with hinting.
    SMOOTH_HINTED = 4121,
    --- Renders a bitmap representation of the glyph from an 8-bit or antialiased image of the glyph outline with no hinting.
    SMOOTH = 4117,
    --- Renders a bitmap representation of the glyph from a binary (1-bit monochrome) image of the glyph outline with hinting.
    RASTER_HINTED = 4122,
    --- Renders a bitmap representation of the glyph from a binary (1-bit monochrome) image of the glyph outline with no hinting.
    RASTER = 4118,
    --- Renders a signed distance field (SDF) representation of the glyph from a binary (1-bit monochrome) image of the glyph outline with no hinting.
    SDF = 4134,
    --- Renders a signed distance field (SDF) representation of the glyph from a binary (1-bit monochrome) image of the glyph outline with no hinting.
    SDF8 = 8230,
    --- Renders a signed distance field (SDF) representation of the glyph from a binary (1-bit monochrome) image of the glyph outline with no hinting.
    SDF16 = 16422,
    --- Renders a signed distance field (SDF) representation of the glyph from a binary (1-bit monochrome) image of the glyph outline with no hinting.
    SDF32 = 32806,
    --- Renders a signed distance field (SDF) representation of the glyph from an 8-bit or antialiased image of the glyph outline with hinting.
    SDFAA_HINTED = 4169,
    --- Renders a signed distance field (SDF) representation of the glyph from an 8-bit or antialiased image of the glyph outline with no hinting.
    SDFAA = 4165,
}

---  Generated By xerysherry