--- @class UnityEngine.Experimental.Playables.TextureMixerPlayable An implementation of IPlayable that allows mixing two textures.
UnityEngine.Experimental.Playables.TextureMixerPlayable = {}

--- Creates a TextureMixerPlayable in the PlayableGraph.
--- @param graph UnityEngine.Playables.PlayableGraph The PlayableGraph object that will own the TextureMixerPlayable.
--- @return UnityEngine.Experimental.Playables.TextureMixerPlayable A TextureMixerPlayable linked to the PlayableGraph.
function UnityEngine.Experimental.Playables.TextureMixerPlayable.Create(graph) end

--- @param playable UnityEngine.Experimental.Playables.TextureMixerPlayable 
--- @return UnityEngine.Playables.Playable
function UnityEngine.Experimental.Playables.TextureMixerPlayable.op_Implicit(playable) end

--- @param playable UnityEngine.Playables.Playable 
--- @return UnityEngine.Experimental.Playables.TextureMixerPlayable
function UnityEngine.Experimental.Playables.TextureMixerPlayable.op_Explicit(playable) end

--- @return UnityEngine.Playables.PlayableHandle
function UnityEngine.Experimental.Playables.TextureMixerPlayable:GetHandle() end

--- @param other UnityEngine.Experimental.Playables.TextureMixerPlayable 
--- @return boolean
function UnityEngine.Experimental.Playables.TextureMixerPlayable:Equals(other) end

---  Generated By xerysherry