--- @class UnityEngine.AvatarBuilder Class to build avatars from user scripts.
UnityEngine.AvatarBuilder = {}

--- Create a humanoid avatar.
--- @param go UnityEngine.GameObject Root object of your transform hierachy. It must be the top most gameobject when you create the avatar.
--- @param humanDescription UnityEngine.HumanDescription Humanoid description of the avatar.
--- @return UnityEngine.Avatar Returns the Avatar, you must always always check the avatar is valid before using it with Avatar.isValid.
function UnityEngine.AvatarBuilder.BuildHumanAvatar(go, humanDescription) end

--- Create a new generic avatar.
--- @param go UnityEngine.GameObject Root object of your transform hierarchy.
--- @param rootMotionTransformName string Transform name of the root motion transform. If empty no root motion is defined and you must take care of avatar movement yourself.
--- @return UnityEngine.Avatar 
function UnityEngine.AvatarBuilder.BuildGenericAvatar(go, rootMotionTransformName) end

---  Generated By xerysherry