--- @class UnityEngine.AudioSettings Controls the global audio settings from script.
--- @field driverCaps UnityEngine.AudioSpeakerMode
--- @field driverCapabilities UnityEngine.AudioSpeakerMode property get
---       Returns the speaker mode capability of the current audio driver. (Read Only)
--- @field speakerMode UnityEngine.AudioSpeakerMode property getset
---       Gets the current speaker mode. Default is 2 channel stereo.
--- @field dspTime number property get
---       Returns the current time of the audio system.
--- @field outputSampleRate number property getset
---       Get the mixer's current output rate.
UnityEngine.AudioSettings = {}

--- @param value UnityEngine.AudioSpeakerMode 
function UnityEngine.AudioSettings.set_speakerMode(value) end

--- @param value number 
function UnityEngine.AudioSettings.set_outputSampleRate(value) end

--- Get the mixer's buffer size in samples.
--- @return System.Int32& Is the length of each buffer in the ringbuffer.
--- @return System.Int32& Is number of buffers.
function UnityEngine.AudioSettings.GetDSPBufferSize() end

--- @param bufferLength number 
--- @param numBuffers number 
function UnityEngine.AudioSettings.SetDSPBufferSize(bufferLength, numBuffers) end

--- Returns an array with the names of all the available spatializer plugins.
--- @return string[] An array of spatializer names.
function UnityEngine.AudioSettings.GetSpatializerPluginNames() end

--- Returns the name of the spatializer selected on the currently-running platform.
--- @return string The spatializer plugin name.
function UnityEngine.AudioSettings.GetSpatializerPluginName() end

--- Sets the spatializer plugin for all platform groups. If a null or empty string is passed in, the existing spatializer plugin will be cleared.
--- @param pluginName string The spatializer plugin name.
function UnityEngine.AudioSettings.SetSpatializerPluginName(pluginName) end

--- Returns the current configuration of the audio device and system. The values in the struct may then be modified and reapplied via AudioSettings.Reset.
--- @return UnityEngine.AudioConfiguration The new configuration to be applied.
function UnityEngine.AudioSettings.GetConfiguration() end

--- Performs a change of the device configuration. In response to this the AudioSettings.OnAudioConfigurationChanged delegate is invoked with the argument deviceWasChanged=false. It cannot be guaranteed that the exact settings specified can be used, but the an attempt is made to use the closest match supported by the system.
--- @param config UnityEngine.AudioConfiguration The new configuration to be used.
--- @return boolean True if all settings could be successfully applied.
function UnityEngine.AudioSettings.Reset(config) end

--- @param value function 
function UnityEngine.AudioSettings.add_OnAudioConfigurationChanged(value) end

--- @param value function 
function UnityEngine.AudioSettings.remove_OnAudioConfigurationChanged(value) end

---  Generated By xerysherry