--- @class Unity.Collections.LowLevel.Unsafe.NativeContainerNeedsThreadIndexAttribute:System.Attribute 
--- @field TypeId System.Object
Unity.Collections.LowLevel.Unsafe.NativeContainerNeedsThreadIndexAttribute = {}

---  Generated By xerysherry