--- @class UnityEngine.UIElements.ContextualMenuManipulator:UnityEngine.UIElements.MouseManipulator Manipulator that displays a contextual menu when the user clicks the right mouse button or presses the menu key on the keyboard.
--- @field activators UnityEngine.UIElements.ManipulatorActivationFilter[]
--- @field target UnityEngine.UIElements.VisualElement
UnityEngine.UIElements.ContextualMenuManipulator = {}

---  Generated By xerysherry