--- @class UnityEngine.Rendering.PassType Shader pass type for Unity's lighting pipeline.
UnityEngine.Rendering.PassType = {
    --- Regular shader pass that does not interact with lighting.
    Normal = 0,
    --- Legacy vertex-lit shader pass.
    Vertex = 1,
    --- Legacy vertex-lit shader pass, with mobile lightmaps.
    VertexLM = 2,
    --- Forward rendering base pass.
    ForwardBase = 4,
    --- Forward rendering additive pixel light pass.
    ForwardAdd = 5,
    --- Legacy deferred lighting (light pre-pass) base pass.
    LightPrePassBase = 6,
    --- Legacy deferred lighting (light pre-pass) final pass.
    LightPrePassFinal = 7,
    --- Shadow caster & depth texure shader pass.
    ShadowCaster = 8,
    --- Deferred Shading shader pass.
    Deferred = 10,
    --- Shader pass used to generate the albedo and emissive values used as input to lightmapping.
    Meta = 11,
    --- Motion vector render pass.
    MotionVectors = 12,
    --- Custom scriptable pipeline.
    ScriptableRenderPipeline = 13,
    --- Custom scriptable pipeline when lightmode is set to default unlit or no light mode is set.
    ScriptableRenderPipelineDefaultUnlit = 14,
}

---  Generated By xerysherry