--- @class UnityEngine.SocialPlatforms.Impl.Achievement 
--- @field id string
--- @field percentCompleted number
--- @field completed boolean
--- @field hidden boolean
--- @field lastReportedDate System.DateTime
UnityEngine.SocialPlatforms.Impl.Achievement = {}

--- @return string
function UnityEngine.SocialPlatforms.Impl.Achievement:ToString() end

function UnityEngine.SocialPlatforms.Impl.Achievement:ReportProgress(callback) end

function UnityEngine.SocialPlatforms.Impl.Achievement:SetCompleted(value) end

function UnityEngine.SocialPlatforms.Impl.Achievement:SetHidden(value) end

function UnityEngine.SocialPlatforms.Impl.Achievement:SetLastReportedDate(date) end

function UnityEngine.SocialPlatforms.Impl.Achievement:set_id(value) end

function UnityEngine.SocialPlatforms.Impl.Achievement:set_percentCompleted(value) end

---  Generated By xerysherry