--- @class UnityEngine.DetailRenderMode Render mode for detail prototypes.
UnityEngine.DetailRenderMode = {
    --- The detail prototype will be rendered as billboards that are always facing the camera.
    GrassBillboard = 0,
    --- Will show the prototype using diffuse shading.
    VertexLit = 1,
    --- The detail prototype will use the grass shader.
    Grass = 2,
}

---  Generated By xerysherry