--- @class UnityEngine.RenderTextureFormat Format of a RenderTexture.
UnityEngine.RenderTextureFormat = {
    --- Color render texture format, 8 bits per channel.
    ARGB32 = 0,
    --- A depth render texture format.
    Depth = 1,
    --- Color render texture format, 16 bit floating point per channel.
    ARGBHalf = 2,
    --- A native shadowmap render texture format.
    Shadowmap = 3,
    --- Color render texture format.
    RGB565 = 4,
    --- Color render texture format, 4 bit per channel.
    ARGB4444 = 5,
    --- Color render texture format, 1 bit for Alpha channel, 5 bits for Red, Green and Blue channels.
    ARGB1555 = 6,
    --- Default color render texture format: will be chosen accordingly to Frame Buffer format and Platform.
    Default = 7,
    --- Color render texture format. 10 bits for colors, 2 bits for alpha.
    ARGB2101010 = 8,
    --- Default HDR color render texture format: will be chosen accordingly to Frame Buffer format and Platform.
    DefaultHDR = 9,
    --- Four color render texture format, 16 bits per channel, fixed point, unsigned normalized.
    ARGB64 = 10,
    --- Color render texture format, 32 bit floating point per channel.
    ARGBFloat = 11,
    --- Two color (RG) render texture format, 32 bit floating point per channel.
    RGFloat = 12,
    --- Two color (RG) render texture format, 16 bit floating point per channel.
    RGHalf = 13,
    --- Scalar (R) render texture format, 32 bit floating point.
    RFloat = 14,
    --- Scalar (R) render texture format, 16 bit floating point.
    RHalf = 15,
    --- Single channel (R) render texture format, 8 bit integer.
    R8 = 16,
    --- Four channel (ARGB) render texture format, 32 bit signed integer per channel.
    ARGBInt = 17,
    --- Two channel (RG) render texture format, 32 bit signed integer per channel.
    RGInt = 18,
    --- Scalar (R) render texture format, 32 bit signed integer.
    RInt = 19,
    --- Color render texture format, 8 bits per channel.
    BGRA32 = 20,
    --- Color render texture format. R and G channels are 11 bit floating point, B channel is 10 bit floating point.
    RGB111110Float = 22,
    --- Two color (RG) render texture format, 16 bits per channel, fixed point, unsigned normalized.
    RG32 = 23,
    --- Four channel (RGBA) render texture format, 16 bit unsigned integer per channel.
    RGBAUShort = 24,
    --- Two channel (RG) render texture format, 8 bits per channel.
    RG16 = 25,
    --- Color render texture format, 10 bit per channel, extended range.
    BGRA10101010_XR = 26,
    --- Color render texture format, 10 bit per channel, extended range.
    BGR101010_XR = 27,
    --- Single channel (R) render texture format, 16 bit integer.
    R16 = 28,
}

---  Generated By xerysherry