--- @class UnityEngine.AnimatorCullingMode Culling mode for the Animator.
UnityEngine.AnimatorCullingMode = {
    --- Always animate the entire character. Object is animated even when offscreen.
    AlwaysAnimate = 0,
    --- Retarget, IK and write of Transforms are disabled when renderers are not visible.
    CullUpdateTransforms = 1,
    --- Animation is completely disabled when renderers are not visible.
    CullCompletely = 2,
}

---  Generated By xerysherry