--- @class UnityEngine.XR.WSA.Persistence.WorldAnchorStore The storage object for persisted WorldAnchors.
--- @field anchorCount number property get
---       (Read Only) Gets the number of persisted world anchors in this WorldAnchorStore.
UnityEngine.XR.WSA.Persistence.WorldAnchorStore = {}

--- Gets the WorldAnchorStore instance.
--- @param onCompleted function The handler to be called when the WorldAnchorStore is loaded.
function UnityEngine.XR.WSA.Persistence.WorldAnchorStore.GetAsync(onCompleted) end

--- Saves the provided WorldAnchor with the provided identifier. If the identifier is already in use, the method will return false.
--- @param id string The identifier to save the anchor with. This needs to be unique for your app.
--- @param anchor UnityEngine.XR.WSA.WorldAnchor The anchor to save.
--- @return boolean Whether or not the save was successful. Will return false if the id conflicts with another already saved anchor's id.
function UnityEngine.XR.WSA.Persistence.WorldAnchorStore:Save(id, anchor) end

--- Loads a WorldAnchor from disk for given identifier and attaches it to the GameObject. If the GameObject has a WorldAnchor, that WorldAnchor will be updated. If the anchor is not found, null will be returned and the GameObject and any existing WorldAnchor attached to it will not be modified.
--- @param id string The identifier of the WorldAnchor to load.
--- @param go UnityEngine.GameObject The object to attach the WorldAnchor to if found.
--- @return UnityEngine.XR.WSA.WorldAnchor The WorldAnchor loaded by the identifier or null if not found.
function UnityEngine.XR.WSA.Persistence.WorldAnchorStore:Load(id, go) end

--- Deletes a persisted WorldAnchor from the store.
--- @param id string The identifier of the WorldAnchor to delete.
--- @return boolean Whether or not the WorldAnchor was found and deleted.
function UnityEngine.XR.WSA.Persistence.WorldAnchorStore:Delete(id) end

--- Clears all persisted WorldAnchors.
function UnityEngine.XR.WSA.Persistence.WorldAnchorStore:Clear() end

--- Gets all of the identifiers of the currently persisted WorldAnchors.
--- @param ids string[] A target array to receive the identifiers of the currently persisted world anchors.
--- @return number The number of identifiers stored in the target array.
function UnityEngine.XR.WSA.Persistence.WorldAnchorStore:GetAllIds(ids) end

--- Gets all of the identifiers of the currently persisted WorldAnchors.
--- @return string[] An array of string identifiers.
function UnityEngine.XR.WSA.Persistence.WorldAnchorStore:GetAllIds() end

--- Cleans up the WorldAnchorStore and releases memory.
function UnityEngine.XR.WSA.Persistence.WorldAnchorStore:Dispose() end

---  Generated By xerysherry