--- @class UnityEngine.Windows.WebCam.PhotoCaptureFrame Contains information captured from the web camera.
--- @field dataLength number property get
---       The length of the raw IMFMediaBuffer which contains the image captured.
--- @field hasLocationData boolean property get
---       Specifies whether or not spatial data was captured.
--- @field pixelFormat UnityEngine.Windows.WebCam.CapturePixelFormat property get
---       The raw image data pixel format.
UnityEngine.Windows.WebCam.PhotoCaptureFrame = {}

--- This method will return the camera to world matrix at the time the photo was captured if location data if available.
--- @return boolean True if a valid matrix is returned or false otherwise.  This will be false if the frame has no location data.
--- @return UnityEngine.Matrix4x4& A matrix to be populated by the Camera to world Matrix.
function UnityEngine.Windows.WebCam.PhotoCaptureFrame:TryGetCameraToWorldMatrix() end

--- This method will return the projection matrix at the time the photo was captured if location data if available.
--- @return boolean True if a valid matrix is returned or false otherwise.  This will be false if the frame has no location data.
--- @return UnityEngine.Matrix4x4& 
function UnityEngine.Windows.WebCam.PhotoCaptureFrame:TryGetProjectionMatrix() end

--- This method will return the projection matrix at the time the photo was captured if location data if available.
--- @param nearClipPlane number The near clip plane distance.
--- @param farClipPlane number The far clip plane distance.
--- @return boolean True if a valid matrix is returned or false otherwise.  This will be false if the frame has no location data.
--- @return UnityEngine.Matrix4x4& A matrix to be populated by the Projection Matrix.
function UnityEngine.Windows.WebCam.PhotoCaptureFrame:TryGetProjectionMatrix(nearClipPlane, farClipPlane) end

--- This method will copy the captured image data into a user supplied texture for use in Unity.
--- @param targetTexture UnityEngine.Texture2D The target texture that the captured image data will be copied to.
function UnityEngine.Windows.WebCam.PhotoCaptureFrame:UploadImageDataToTexture(targetTexture) end

--- Provides a COM pointer to the native IMFMediaBuffer that contains the image data.
--- @return System.IntPtr A native COM pointer to the IMFMediaBuffer which contains the image data.
function UnityEngine.Windows.WebCam.PhotoCaptureFrame:GetUnsafePointerToBuffer() end

--- Will copy the raw IMFMediaBuffer image data into a byte list.
--- @param byteBuffer number[] The destination byte list to which the raw captured image data will be copied to.
function UnityEngine.Windows.WebCam.PhotoCaptureFrame:CopyRawImageDataIntoBuffer(byteBuffer) end

--- Disposes the PhotoCaptureFrame and any resources it uses.
function UnityEngine.Windows.WebCam.PhotoCaptureFrame:Dispose() end

---  Generated By xerysherry