--- @class UnityEngine.UI.Graphic:UnityEngine.EventSystems.UIBehaviour 
--- @field defaultGraphicMaterial UnityEngine.Material
--- @field color UnityEngine.Color
--- @field raycastTarget boolean
--- @field depth number
--- @field rectTransform UnityEngine.RectTransform
--- @field canvas UnityEngine.Canvas
--- @field canvasRenderer UnityEngine.CanvasRenderer
--- @field defaultMaterial UnityEngine.Material
--- @field material UnityEngine.Material
--- @field materialForRendering UnityEngine.Material
--- @field mainTexture UnityEngine.Texture
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.Graphic = {}

--- @param value UnityEngine.Color 
function UnityEngine.UI.Graphic:set_color(value) end

--- @param value boolean 
function UnityEngine.UI.Graphic:set_raycastTarget(value) end

function UnityEngine.UI.Graphic:SetAllDirty() end

function UnityEngine.UI.Graphic:SetLayoutDirty() end

function UnityEngine.UI.Graphic:SetVerticesDirty() end

function UnityEngine.UI.Graphic:SetMaterialDirty() end

--- @param value UnityEngine.Material 
function UnityEngine.UI.Graphic:set_material(value) end

function UnityEngine.UI.Graphic:OnCullingChanged() end

--- @param update UnityEngine.UI.CanvasUpdate 
function UnityEngine.UI.Graphic:Rebuild(update) end

function UnityEngine.UI.Graphic:LayoutComplete() end

function UnityEngine.UI.Graphic:GraphicUpdateComplete() end

function UnityEngine.UI.Graphic:OnRebuildRequested() end

function UnityEngine.UI.Graphic:SetNativeSize() end

--- @param sp UnityEngine.Vector2 
--- @param eventCamera UnityEngine.Camera 
--- @return boolean
function UnityEngine.UI.Graphic:Raycast(sp, eventCamera) end

--- @param point UnityEngine.Vector2 
--- @return UnityEngine.Vector2
function UnityEngine.UI.Graphic:PixelAdjustPoint(point) end

--- @return UnityEngine.Rect
function UnityEngine.UI.Graphic:GetPixelAdjustedRect() end

--- @param targetColor UnityEngine.Color 
--- @param duration number 
--- @param ignoreTimeScale boolean 
--- @param useAlpha boolean 
function UnityEngine.UI.Graphic:CrossFadeColor(targetColor, duration, ignoreTimeScale, useAlpha) end

--- @param targetColor UnityEngine.Color 
--- @param duration number 
--- @param ignoreTimeScale boolean 
--- @param useAlpha boolean 
--- @param useRGB boolean 
function UnityEngine.UI.Graphic:CrossFadeColor(targetColor, duration, ignoreTimeScale, useAlpha, useRGB) end

--- @param alpha number 
--- @param duration number 
--- @param ignoreTimeScale boolean 
function UnityEngine.UI.Graphic:CrossFadeAlpha(alpha, duration, ignoreTimeScale) end

--- @param action function 
function UnityEngine.UI.Graphic:RegisterDirtyLayoutCallback(action) end

--- @param action function 
function UnityEngine.UI.Graphic:UnregisterDirtyLayoutCallback(action) end

--- @param action function 
function UnityEngine.UI.Graphic:RegisterDirtyVerticesCallback(action) end

--- @param action function 
function UnityEngine.UI.Graphic:UnregisterDirtyVerticesCallback(action) end

--- @param action function 
function UnityEngine.UI.Graphic:RegisterDirtyMaterialCallback(action) end

--- @param action function 
function UnityEngine.UI.Graphic:UnregisterDirtyMaterialCallback(action) end

---  Generated By xerysherry