--- @class UnityEngine.EventSystems.EventTrigger:UnityEngine.MonoBehaviour 
--- @field delegates UnityEngine.EventSystems.EventTrigger.Entry[]
--- @field triggers UnityEngine.EventSystems.EventTrigger.Entry[]
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.EventSystems.EventTrigger = {}

--- @param value UnityEngine.EventSystems.EventTrigger.Entry[] 
function UnityEngine.EventSystems.EventTrigger:set_delegates(value) end

--- @param value UnityEngine.EventSystems.EventTrigger.Entry[] 
function UnityEngine.EventSystems.EventTrigger:set_triggers(value) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnPointerEnter(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnPointerExit(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnDrag(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnDrop(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnPointerDown(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnPointerUp(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnPointerClick(eventData) end

--- @param eventData UnityEngine.EventSystems.BaseEventData 
function UnityEngine.EventSystems.EventTrigger:OnSelect(eventData) end

--- @param eventData UnityEngine.EventSystems.BaseEventData 
function UnityEngine.EventSystems.EventTrigger:OnDeselect(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnScroll(eventData) end

--- @param eventData UnityEngine.EventSystems.AxisEventData 
function UnityEngine.EventSystems.EventTrigger:OnMove(eventData) end

--- @param eventData UnityEngine.EventSystems.BaseEventData 
function UnityEngine.EventSystems.EventTrigger:OnUpdateSelected(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnInitializePotentialDrag(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnBeginDrag(eventData) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.EventSystems.EventTrigger:OnEndDrag(eventData) end

--- @param eventData UnityEngine.EventSystems.BaseEventData 
function UnityEngine.EventSystems.EventTrigger:OnSubmit(eventData) end

--- @param eventData UnityEngine.EventSystems.BaseEventData 
function UnityEngine.EventSystems.EventTrigger:OnCancel(eventData) end

---  Generated By xerysherry