--- @class UnityEngine.SocialPlatforms.Impl.UserProfile 
--- @field userName string
--- @field id string
--- @field gameId string
--- @field isFriend boolean
--- @field state UnityEngine.SocialPlatforms.UserState
--- @field image UnityEngine.Texture2D
UnityEngine.SocialPlatforms.Impl.UserProfile = {}

--- @return string
function UnityEngine.SocialPlatforms.Impl.UserProfile:ToString() end

--- @param name string 
function UnityEngine.SocialPlatforms.Impl.UserProfile:SetUserName(name) end

--- @param id string 
function UnityEngine.SocialPlatforms.Impl.UserProfile:SetUserID(id) end

--- @param id string 
function UnityEngine.SocialPlatforms.Impl.UserProfile:SetUserGameID(id) end

--- @param image UnityEngine.Texture2D 
function UnityEngine.SocialPlatforms.Impl.UserProfile:SetImage(image) end

--- @param value boolean 
function UnityEngine.SocialPlatforms.Impl.UserProfile:SetIsFriend(value) end

--- @param state UnityEngine.SocialPlatforms.UserState 
function UnityEngine.SocialPlatforms.Impl.UserProfile:SetState(state) end

---  Generated By xerysherry