--- @class UnityEngine.Rendering.SubMeshDescriptor Contains information about a single sub-mesh of a Mesh.
--- @field bounds UnityEngine.Bounds property getset
---       Bounding box of vertices in local space.
--- @field topology UnityEngine.MeshTopology property getset
---       Face topology of this sub-mesh.
--- @field indexStart number property getset
---       Starting point inside the whole Mesh index buffer where the face index data is found.
--- @field indexCount number property getset
---       Index count for this sub-mesh face data.
--- @field baseVertex number property getset
---       Offset that is added to each value in the index buffer, to compute the final vertex index.
--- @field firstVertex number property getset
---       First vertex in the index buffer for this sub-mesh.
--- @field vertexCount number property getset
---       Number of vertices used by the index buffer of this sub-mesh.
UnityEngine.Rendering.SubMeshDescriptor = {}

function UnityEngine.Rendering.SubMeshDescriptor:set_bounds(value) end

function UnityEngine.Rendering.SubMeshDescriptor:set_topology(value) end

function UnityEngine.Rendering.SubMeshDescriptor:set_indexStart(value) end

function UnityEngine.Rendering.SubMeshDescriptor:set_indexCount(value) end

function UnityEngine.Rendering.SubMeshDescriptor:set_baseVertex(value) end

function UnityEngine.Rendering.SubMeshDescriptor:set_firstVertex(value) end

function UnityEngine.Rendering.SubMeshDescriptor:set_vertexCount(value) end

--- @return string
function UnityEngine.Rendering.SubMeshDescriptor:ToString() end

---  Generated By xerysherry