--- @class UnityEngine.UI.ScrollRect.ScrollbarVisibility
UnityEngine.UI.ScrollRect.ScrollbarVisibility = {
    Permanent = 0,
    AutoHide = 1,
    AutoHideAndExpandViewport = 2,
}

---  Generated By xerysherry