--- @class UnityEngine.DeviceOrientation Describes physical orientation of the device as determined by the OS.
UnityEngine.DeviceOrientation = {
    --- The orientation of the device cannot be determined.
    Unknown = 0,
    --- The device is in portrait mode, with the device held upright and the home button at the bottom.
    Portrait = 1,
    --- The device is in portrait mode but upside down, with the device held upright and the home button at the top.
    PortraitUpsideDown = 2,
    --- The device is in landscape mode, with the device held upright and the home button on the right side.
    LandscapeLeft = 3,
    --- The device is in landscape mode, with the device held upright and the home button on the left side.
    LandscapeRight = 4,
    --- The device is held parallel to the ground with the screen facing upwards.
    FaceUp = 5,
    --- The device is held parallel to the ground with the screen facing downwards.
    FaceDown = 6,
}

---  Generated By xerysherry