--- @class UnityEngine.TouchScreenKeyboardType Enumeration of the different types of supported touchscreen keyboards.
UnityEngine.TouchScreenKeyboardType = {
    --- The default keyboard layout of the target platform.
    Default = 0,
    --- Keyboard with standard ASCII keys.
    ASCIICapable = 1,
    --- Keyboard with numbers and punctuation mark keys.
    NumbersAndPunctuation = 2,
    --- Keyboard with keys for URL entry.
    URL = 3,
    --- Keyboard with standard numeric keys.
    NumberPad = 4,
    --- Keyboard with a layout suitable for typing telephone numbers.
    PhonePad = 5,
    --- Keyboard with alphanumeric keys.
    NamePhonePad = 6,
    --- Keyboard with additional keys suitable for typing email addresses.
    EmailAddress = 7,
    --- Keyboard with symbol keys often used on social media, such as Twitter.
    Social = 9,
    --- Keyboard with the "." key beside the space key, suitable for typing search terms.
    Search = 10,
    --- Keyboard with numbers and a decimal point.
    DecimalPad = 11,
}

---  Generated By xerysherry