--- @class UnityEngine.ParticleSystemSubEmitterProperties The properties of sub-emitter particles.
UnityEngine.ParticleSystemSubEmitterProperties = {
    --- When spawning new particles, do not inherit any properties from the parent particles.
    InheritNothing = 0,
    --- When spawning new particles, inherit all available properties from the parent particles.
    InheritEverything = 31,
    --- When spawning new particles, multiply the start color by the color of the parent particles.
    InheritColor = 1,
    --- When spawning new particles, multiply the start size by the size of the parent particles.
    InheritSize = 2,
    --- When spawning new particles, add the start rotation to the rotation of the parent particles.
    InheritRotation = 4,
    --- New particles will have a shorter lifespan, the closer their parent particles are to death.
    InheritLifetime = 8,
    --- When spawning new particles, use the duration and age properties from the parent system, when sampling MainModule curves in the Sub-Emitter.
    InheritDuration = 16,
}

---  Generated By xerysherry