--- @class UnityEngine.Rendering.CameraProperties Camera related properties in CullingParameters.
UnityEngine.Rendering.CameraProperties = {}

--- @param left UnityEngine.Rendering.CameraProperties 
--- @param right UnityEngine.Rendering.CameraProperties 
--- @return boolean
function UnityEngine.Rendering.CameraProperties.op_Equality(left, right) end

--- @param left UnityEngine.Rendering.CameraProperties 
--- @param right UnityEngine.Rendering.CameraProperties 
--- @return boolean
function UnityEngine.Rendering.CameraProperties.op_Inequality(left, right) end

--- Get a shadow culling plane.
--- @param index number Plane index (up to 5).
--- @return UnityEngine.Plane Shadow culling plane.
function UnityEngine.Rendering.CameraProperties:GetShadowCullingPlane(index) end

--- Set a shadow culling plane.
--- @param index number Plane index (up to 5).
--- @param plane UnityEngine.Plane Shadow culling plane.
function UnityEngine.Rendering.CameraProperties:SetShadowCullingPlane(index, plane) end

--- Get a camera culling plane.
--- @param index number Plane index (up to 5).
--- @return UnityEngine.Plane Camera culling plane.
function UnityEngine.Rendering.CameraProperties:GetCameraCullingPlane(index) end

--- Set a camera culling plane.
--- @param index number Plane index (up to 5).
--- @param plane UnityEngine.Plane Camera culling plane.
function UnityEngine.Rendering.CameraProperties:SetCameraCullingPlane(index, plane) end

--- @param other UnityEngine.Rendering.CameraProperties 
--- @return boolean
function UnityEngine.Rendering.CameraProperties:Equals(other) end

--- @param obj System.Object 
--- @return boolean
function UnityEngine.Rendering.CameraProperties:Equals(obj) end

--- @return number
function UnityEngine.Rendering.CameraProperties:GetHashCode() end

---  Generated By xerysherry