--- @class UnityEngine.UI.GraphicRaycaster:UnityEngine.EventSystems.BaseRaycaster 
--- @field sortOrderPriority number
--- @field renderOrderPriority number
--- @field ignoreReversedGraphics boolean
--- @field blockingObjects UnityEngine.UI.GraphicRaycaster.BlockingObjects
--- @field eventCamera UnityEngine.Camera
--- @field priority number
--- @field rootRaycaster UnityEngine.EventSystems.BaseRaycaster
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.GraphicRaycaster = {}

function UnityEngine.UI.GraphicRaycaster:set_ignoreReversedGraphics(value) end

function UnityEngine.UI.GraphicRaycaster:set_blockingObjects(value) end

function UnityEngine.UI.GraphicRaycaster:Raycast(eventData, resultAppendList) end

---  Generated By xerysherry