--- @class UnityEngine.UIElements.Cursor Script interface for VisualElement cursor style property IStyle.cursor.
--- @field texture UnityEngine.Texture2D property getset
---       The texture to use for the cursor style. To use a texture as a cursor, import the texture with "Read/Write enabled" in the texture importer (or using the "Cursor" defaults).
--- @field hotspot UnityEngine.Vector2 property getset
---       The offset from the top left of the texture to use as the target point (must be within the bounds of the cursor).
UnityEngine.UIElements.Cursor = {}

--- @return boolean
function UnityEngine.UIElements.Cursor.op_Equality(style1, style2) end

--- @return boolean
function UnityEngine.UIElements.Cursor.op_Inequality(style1, style2) end

function UnityEngine.UIElements.Cursor:set_texture(value) end

function UnityEngine.UIElements.Cursor:set_hotspot(value) end

--- @return boolean
function UnityEngine.UIElements.Cursor:Equals(obj) end

--- @return boolean
function UnityEngine.UIElements.Cursor:Equals(other) end

--- @return number
function UnityEngine.UIElements.Cursor:GetHashCode() end

--- @return string
function UnityEngine.UIElements.Cursor:ToString() end

---  Generated By xerysherry