--- @class UnityEngine.Video.VideoSource Source of the video content for a VideoPlayer.
UnityEngine.Video.VideoSource = {
    --- Use the current clip as the video content source.
    VideoClip = 0,
    --- Use the current URL as the video content source.
    Url = 1,
}

---  Generated By xerysherry