--- @class UnityEngine.SceneManagement.CreateSceneParameters This struct collects all the CreateScene parameters in to a single place.
--- @field localPhysicsMode UnityEngine.SceneManagement.LocalPhysicsMode property getset
---       See SceneManagement.LocalPhysicsMode.
UnityEngine.SceneManagement.CreateSceneParameters = {}

--- @param value UnityEngine.SceneManagement.LocalPhysicsMode 
function UnityEngine.SceneManagement.CreateSceneParameters:set_localPhysicsMode(value) end

---  Generated By xerysherry