--- @class UnityEngine.Networking.HostTopology Class defines network topology for host (socket opened by Networking.NetworkTransport.AddHost function). This topology defines: (1) how many connection with default config will be supported and (2) what will be special connections (connections with config different from default).
--- @field DefaultConfig UnityEngine.Networking.ConnectionConfig property get
---       Defines config for default connections in the topology.
--- @field MaxDefaultConnections number property get
---       Defines how many connection with default config be permitted.
--- @field SpecialConnectionConfigsCount number property get
---       Returns count of special connection added to topology.
--- @field SpecialConnectionConfigs UnityEngine.Networking.ConnectionConfig[] property get
---       List of special connection configs.
--- @field ReceivedMessagePoolSize number property getset
---       Defines the maximum number of messages that each host can hold in its pool of received messages. The default size is 128.
--- @field SentMessagePoolSize number property getset
---       Defines the maximum number of messages that each host can hold in its pool of messages waiting to be sent. The default size is 128.
--- @field MessagePoolSizeGrowthFactor number
UnityEngine.Networking.HostTopology = {}

--- Return reference to special connection config. Parameters of this config can be changed.
--- @param i number Config id.
--- @return UnityEngine.Networking.ConnectionConfig Connection config.
function UnityEngine.Networking.HostTopology:GetSpecialConnectionConfig(i) end

function UnityEngine.Networking.HostTopology:set_ReceivedMessagePoolSize(value) end

function UnityEngine.Networking.HostTopology:set_SentMessagePoolSize(value) end

function UnityEngine.Networking.HostTopology:set_MessagePoolSizeGrowthFactor(value) end

--- Add special connection to topology (for example if you need to keep connection to standalone chat server you will need to use this function). Returned id should be use as one of parameters (with ip and port) to establish connection to this server.
--- @param config UnityEngine.Networking.ConnectionConfig Connection config for special connection.
--- @return number Id of this connection. You should use this id when you call Networking.NetworkTransport.Connect.
function UnityEngine.Networking.HostTopology:AddSpecialConnectionConfig(config) end

---  Generated By xerysherry