--- @class UnityEngine.UIElements.VisualElementExtensions VisualElementExtensions is a set of extension methods useful for VisualElement.
UnityEngine.UIElements.VisualElementExtensions = {}

--- @param ele UnityEngine.UIElements.VisualElement 
--- @param p UnityEngine.Vector2 
--- @return UnityEngine.Vector2
function UnityEngine.UIElements.VisualElementExtensions.WorldToLocal(ele, p) end

--- @param ele UnityEngine.UIElements.VisualElement 
--- @param p UnityEngine.Vector2 
--- @return UnityEngine.Vector2
function UnityEngine.UIElements.VisualElementExtensions.LocalToWorld(ele, p) end

--- @param ele UnityEngine.UIElements.VisualElement 
--- @param r UnityEngine.Rect 
--- @return UnityEngine.Rect
function UnityEngine.UIElements.VisualElementExtensions.WorldToLocal(ele, r) end

--- @param ele UnityEngine.UIElements.VisualElement 
--- @param r UnityEngine.Rect 
--- @return UnityEngine.Rect
function UnityEngine.UIElements.VisualElementExtensions.LocalToWorld(ele, r) end

--- @param src UnityEngine.UIElements.VisualElement 
--- @param dest UnityEngine.UIElements.VisualElement 
--- @param point UnityEngine.Vector2 
--- @return UnityEngine.Vector2
function UnityEngine.UIElements.VisualElementExtensions.ChangeCoordinatesTo(src, dest, point) end

--- @param src UnityEngine.UIElements.VisualElement 
--- @param dest UnityEngine.UIElements.VisualElement 
--- @param rect UnityEngine.Rect 
--- @return UnityEngine.Rect
function UnityEngine.UIElements.VisualElementExtensions.ChangeCoordinatesTo(src, dest, rect) end

--- @param elem UnityEngine.UIElements.VisualElement 
function UnityEngine.UIElements.VisualElementExtensions.StretchToParentSize(elem) end

--- The given VisualElement's left and right edges will be aligned with the corresponding edges of the parent element.
--- @param elem UnityEngine.UIElements.VisualElement 
function UnityEngine.UIElements.VisualElementExtensions.StretchToParentWidth(elem) end

--- Add a manipulator associated to a VisualElement.
--- @param ele UnityEngine.UIElements.VisualElement VisualElement associated to the manipulator.
--- @param manipulator UnityEngine.UIElements.IManipulator Manipulator to be added to the VisualElement.
function UnityEngine.UIElements.VisualElementExtensions.AddManipulator(ele, manipulator) end

--- Remove a manipulator associated to a VisualElement.
--- @param ele UnityEngine.UIElements.VisualElement VisualElement associated to the manipulator.
--- @param manipulator UnityEngine.UIElements.IManipulator Manipulator to be removed from the VisualElement.
function UnityEngine.UIElements.VisualElementExtensions.RemoveManipulator(ele, manipulator) end

---  Generated By xerysherry