--- @class UnityEngine.TextCore.LowLevel.GlyphPackingMode The modes available when packing glyphs into an atlas texture.
UnityEngine.TextCore.LowLevel.GlyphPackingMode = {
    --- Place the glyph against the short side of a free space to minimize the length of the shorter leftover side.
    BestShortSideFit = 0,
    --- Place the glyph against the longer side of a free space to minimize the length of the longer leftover side.
    BestLongSideFit = 1,
    --- Place the glyph into the smallest free space available in which it can fit.
    BestAreaFit = 2,
    --- Place the glyph into available free space in a Tetris like fashion.
    BottomLeftRule = 3,
    --- Place the glyph into the available free space by trying to maximize the contact point between it and other glyphs.
    ContactPointRule = 4,
}

---  Generated By xerysherry