--- @class UnityEngine.FrictionJoint2D:UnityEngine.AnchoredJoint2D Applies both force and torque to reduce both the linear and angular velocities to zero.
--- @field maxForce number property getset
---       The maximum force that can be generated when trying to maintain the friction joint constraint.
--- @field maxTorque number property getset
---       The maximum torque that can be generated when trying to maintain the friction joint constraint.
--- @field anchor UnityEngine.Vector2
--- @field connectedAnchor UnityEngine.Vector2
--- @field autoConfigureConnectedAnchor boolean
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field connectedBody UnityEngine.Rigidbody2D
--- @field enableCollision boolean
--- @field breakForce number
--- @field breakTorque number
--- @field reactionForce UnityEngine.Vector2
--- @field reactionTorque number
--- @field collideConnected boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.FrictionJoint2D = {}

function UnityEngine.FrictionJoint2D:set_maxForce(value) end

function UnityEngine.FrictionJoint2D:set_maxTorque(value) end

---  Generated By xerysherry