--- @class UnityEngine.iOS.CalendarUnit Specify calendrical units.
UnityEngine.iOS.CalendarUnit = {
    --- Specifies the era unit.
    Era = 2,
    --- Specifies the year unit.
    Year = 4,
    --- Specifies the month unit.
    Month = 8,
    --- Specifies the day unit.
    Day = 16,
    --- Specifies the hour unit.
    Hour = 32,
    --- Specifies the minute unit.
    Minute = 64,
    --- Specifies the second unit.
    Second = 128,
    --- Specifies the week unit.
    Week = 256,
    --- Specifies the weekday unit.
    Weekday = 512,
    --- Specifies the ordinal weekday unit.
    WeekdayOrdinal = 1024,
    --- Specifies the quarter of the calendar.
    Quarter = 2048,
}

---  Generated By xerysherry