--- @class UnityEngine.GUIText 
--- @field text boolean
--- @field material UnityEngine.Material
--- @field font UnityEngine.Font
--- @field alignment UnityEngine.TextAlignment
--- @field anchor UnityEngine.TextAnchor
--- @field lineSpacing number
--- @field tabSize number
--- @field fontSize number
--- @field fontStyle UnityEngine.FontStyle
--- @field richText boolean
--- @field color UnityEngine.Color
--- @field pixelOffset UnityEngine.Vector2
UnityEngine.GUIText = {}

--- @param value boolean 
function UnityEngine.GUIText:set_text(value) end

--- @param value UnityEngine.Material 
function UnityEngine.GUIText:set_material(value) end

--- @param value UnityEngine.Font 
function UnityEngine.GUIText:set_font(value) end

--- @param value UnityEngine.TextAlignment 
function UnityEngine.GUIText:set_alignment(value) end

--- @param value UnityEngine.TextAnchor 
function UnityEngine.GUIText:set_anchor(value) end

--- @param value number 
function UnityEngine.GUIText:set_lineSpacing(value) end

--- @param value number 
function UnityEngine.GUIText:set_tabSize(value) end

--- @param value number 
function UnityEngine.GUIText:set_fontSize(value) end

--- @param value UnityEngine.FontStyle 
function UnityEngine.GUIText:set_fontStyle(value) end

--- @param value boolean 
function UnityEngine.GUIText:set_richText(value) end

--- @param value UnityEngine.Color 
function UnityEngine.GUIText:set_color(value) end

--- @param value UnityEngine.Vector2 
function UnityEngine.GUIText:set_pixelOffset(value) end

---  Generated By xerysherry