--- @class UnityEngine.Rendering.BuiltinRenderTextureType Built-in temporary render textures produced during camera's rendering.
UnityEngine.Rendering.BuiltinRenderTextureType = {
    --- A globally set property name.
    PropertyName = -4,
    --- The raw RenderBuffer pointer to be used.
    BufferPtr = -3,
    --- The given RenderTexture.
    RenderTexture = -2,
    BindableTexture = -1,
    None = 0,
    --- Currently active render target.
    CurrentActive = 1,
    --- Target texture of currently rendering camera.
    CameraTarget = 2,
    --- Camera's depth texture.
    Depth = 3,
    --- Camera's depth+normals texture.
    DepthNormals = 4,
    --- Resolved depth buffer from deferred.
    ResolvedDepth = 5,
    --- Deferred lighting (normals+specular) G-buffer.
    PrepassNormalsSpec = 7,
    --- Deferred lighting light buffer.
    PrepassLight = 8,
    --- Deferred lighting HDR specular light buffer (Xbox 360 only).
    PrepassLightSpec = 9,
    --- Deferred shading G-buffer #0 (typically diffuse color).
    GBuffer0 = 10,
    --- Deferred shading G-buffer #1 (typically specular + roughness).
    GBuffer1 = 11,
    --- Deferred shading G-buffer #2 (typically normals).
    GBuffer2 = 12,
    --- Deferred shading G-buffer #3 (typically emission/lighting).
    GBuffer3 = 13,
    --- Reflections gathered from default reflection and reflections probes.
    Reflections = 14,
    --- Motion Vectors generated when the camera has motion vectors enabled.
    MotionVectors = 15,
    --- Deferred shading G-buffer #4 (typically occlusion mask for static lights if any).
    GBuffer4 = 16,
    --- G-buffer #5 Available.
    GBuffer5 = 17,
    --- G-buffer #6 Available.
    GBuffer6 = 18,
    --- G-buffer #7 Available.
    GBuffer7 = 19,
}

---  Generated By xerysherry