--- @class UnityEngine.UIElements.MouseManipulator:UnityEngine.UIElements.Manipulator MouseManipulators have a list of activation filters.
--- @field activators UnityEngine.UIElements.ManipulatorActivationFilter[] property get
---       List of Activationfilters.
--- @field target UnityEngine.UIElements.VisualElement
UnityEngine.UIElements.MouseManipulator = {}

---  Generated By xerysherry