--- Represents a toast notification in Windows Store Apps.
--- 
--- @class UnityEngine.WSA.Toast
--- @field arguments string property getset
---       Arguments to be passed for application when toast notification is activated.
--- @field activated boolean property get
---       true if toast was activated by user.
--- @field dismissed boolean property get
---       true if toast notification was dismissed (for any reason).
--- @field dismissedByUser boolean property get
---       true if toast notification was explicitly dismissed by user.
UnityEngine.WSA.Toast = {}

--- Get template XML for toast notification.
--- 
--- @param templ UnityEngine.WSA.ToastTemplate A template identifier.
--- @return string string, which is an empty XML document to be filled and used for toast notification.
function UnityEngine.WSA.Toast.GetTemplate(templ) end

--- Create toast notification.
--- @param xml string 
--- @return UnityEngine.WSA.Toast A toast object for further work with created notification or null, if creation of toast failed.
function UnityEngine.WSA.Toast.Create(xml) end

--- Create toast notification.
--- @param image string 
--- @param text string 
--- @return UnityEngine.WSA.Toast A toast object for further work with created notification or null, if creation of toast failed.
function UnityEngine.WSA.Toast.Create(image, text) end

--- @param value string 
function UnityEngine.WSA.Toast:set_arguments(value) end

--- Show toast notification.
function UnityEngine.WSA.Toast:Show() end

--- Hide displayed toast notification.
function UnityEngine.WSA.Toast:Hide() end

---  Generated By xerysherry