--- Represents a string as an int for efficient lookup and comparison. Use this for common PropertyNames.
--- 
--- Internally stores just an int to represent the string. A PropertyName can be created from a string but can not be converted back to a string. The same string always results in the same int representing that string. Thus this is a very efficient string representation in both memory and speed when all you need is comparison.
--- 
--- PropertyName is serializable.
--- 
--- ToString() is only implemented for debugging purposes in the editor it returns "theName:3737" in the player it returns "Unknown:3737".
--- @class UnityEngine.PropertyName
UnityEngine.PropertyName = {}

--- Indicates whether the specified PropertyName is an Empty string.
--- @param prop UnityEngine.PropertyName 
--- @return boolean 
function UnityEngine.PropertyName.IsNullOrEmpty(prop) end

--- @return boolean
function UnityEngine.PropertyName.op_Equality(lhs, rhs) end

--- @return boolean
function UnityEngine.PropertyName.op_Inequality(lhs, rhs) end

--- @return UnityEngine.PropertyName
function UnityEngine.PropertyName.op_Implicit(name) end

--- @return UnityEngine.PropertyName
function UnityEngine.PropertyName.op_Implicit(id) end

--- Returns the hash code for this PropertyName.
--- @return number 
function UnityEngine.PropertyName:GetHashCode() end

--- Determines whether this instance and a specified object, which must also be a PropertyName object, have the same value.
--- @param other System.Object 
--- @return boolean 
function UnityEngine.PropertyName:Equals(other) end

--- Determines whether this instance and a specified object, which must also be a PropertyName object, have the same value.
--- @param other UnityEngine.PropertyName 
--- @return boolean 
function UnityEngine.PropertyName:Equals(other) end

--- For debugging purposes only. Returns the string value representing the string in the Editor.
--- Returns "UnityEngine.PropertyName" in the player.
--- @return string 
function UnityEngine.PropertyName:ToString() end

---  Generated By xerysherry