--- @class UnityEngine.ColorUtility A collection of common color functions.
UnityEngine.ColorUtility = {}

--- Attempts to convert a html color string.
--- @param htmlString string Case insensitive html string to be converted into a color.
--- @return boolean True if the string was successfully converted else false.
--- @return UnityEngine.Color& The converted color.
function UnityEngine.ColorUtility.TryParseHtmlString(htmlString) end

--- Returns the color as a hexadecimal string in the format "RRGGBB".
--- @param color UnityEngine.Color The color to be converted.
--- @return string Hexadecimal string representing the color.
function UnityEngine.ColorUtility.ToHtmlStringRGB(color) end

--- Returns the color as a hexadecimal string in the format "RRGGBBAA".
--- @param color UnityEngine.Color The color to be converted.
--- @return string Hexadecimal string representing the color.
function UnityEngine.ColorUtility.ToHtmlStringRGBA(color) end

---  Generated By xerysherry