--- @class UnityEngine.XR.XRSettings Global XR related settings.
--- @field enabled boolean property getset
---       Globally enables or disables XR for the application.
--- @field gameViewRenderMode UnityEngine.XR.GameViewRenderMode property getset
---       Sets the render mode for the XR device. The render mode controls how the view of the XR device renders in the Game view and in the main window on a host PC.
--- @field isDeviceActive boolean property get
---       Read-only value that can be used to determine if the XR device is active.
--- @field showDeviceView boolean property getset
---       This property has been deprecated. Use XRSettings.gameViewRenderMode instead.
--- @field renderScale number property getset
---       This field has been deprecated. Use XRSettings.eyeTextureResolutionScale instead.
--- @field eyeTextureResolutionScale number property getset
---       Controls the actual size of eye textures as a multiplier of the device's default resolution.
--- @field eyeTextureWidth number property get
---       The current width of an eye texture for the loaded device.
--- @field eyeTextureHeight number property get
---       The current height of an eye texture for the loaded device.
--- @field eyeTextureDesc UnityEngine.RenderTextureDescriptor property get
---       Fetch the eye texture RenderTextureDescriptor from the active stereo device.
--- @field deviceEyeTextureDimension UnityEngine.Rendering.TextureDimension property get
---       Fetch the device eye texture dimension from the active stereo device.
--- @field renderViewportScale number property getset
---       Controls how much of the allocated eye texture should be used for rendering.
--- @field occlusionMaskScale number property getset
---       A scale applied to the standard occulsion mask for each platform.
--- @field useOcclusionMesh boolean property getset
---       Specifies whether or not the occlusion mesh should be used when rendering. Enabled by default.
--- @field loadedDeviceName string property get
---       Type of XR device that is currently loaded.
--- @field supportedDevices string[] property get
---       Returns a list of supported XR devices that were included at build time.
--- @field stereoRenderingMode UnityEngine.XR.XRSettings.StereoRenderingMode property get
---       The stereo rendering mode that is currently in use.
UnityEngine.XR.XRSettings = {}

--- @param value boolean 
function UnityEngine.XR.XRSettings.set_enabled(value) end

--- @param value UnityEngine.XR.GameViewRenderMode 
function UnityEngine.XR.XRSettings.set_gameViewRenderMode(value) end

--- @param value boolean 
function UnityEngine.XR.XRSettings.set_showDeviceView(value) end

--- @param value number 
function UnityEngine.XR.XRSettings.set_renderScale(value) end

--- @param value number 
function UnityEngine.XR.XRSettings.set_eyeTextureResolutionScale(value) end

--- @param value number 
function UnityEngine.XR.XRSettings.set_renderViewportScale(value) end

--- @param value number 
function UnityEngine.XR.XRSettings.set_occlusionMaskScale(value) end

--- @param value boolean 
function UnityEngine.XR.XRSettings.set_useOcclusionMesh(value) end

--- Loads the requested device at the beginning of the next frame.
--- @param deviceName string 
function UnityEngine.XR.XRSettings.LoadDeviceByName(deviceName) end

--- Loads the requested device at the beginning of the next frame.
--- @param prioritizedDeviceNameList string[] 
function UnityEngine.XR.XRSettings.LoadDeviceByName(prioritizedDeviceNameList) end

---  Generated By xerysherry