--- @class UnityEngine.RemoteConfigSettings 
UnityEngine.RemoteConfigSettings = {}

--- @return boolean
function UnityEngine.RemoteConfigSettings.QueueConfig(name, param, ver, prefix) end

--- @return boolean
function UnityEngine.RemoteConfigSettings.SendDeviceInfoInConfigRequest() end

function UnityEngine.RemoteConfigSettings.AddSessionTag(tag) end

function UnityEngine.RemoteConfigSettings:add_Updated(value) end

function UnityEngine.RemoteConfigSettings:remove_Updated(value) end

function UnityEngine.RemoteConfigSettings:Dispose() end

function UnityEngine.RemoteConfigSettings:ForceUpdate() end

--- @return boolean
function UnityEngine.RemoteConfigSettings:WasLastUpdatedFromServer() end

--- @return number
function UnityEngine.RemoteConfigSettings:GetInt(key) end

--- @return number
function UnityEngine.RemoteConfigSettings:GetInt(key, defaultValue) end

--- @return number
function UnityEngine.RemoteConfigSettings:GetLong(key) end

--- @return number
function UnityEngine.RemoteConfigSettings:GetLong(key, defaultValue) end

--- @return number
function UnityEngine.RemoteConfigSettings:GetFloat(key) end

--- @return number
function UnityEngine.RemoteConfigSettings:GetFloat(key, defaultValue) end

--- @return string
function UnityEngine.RemoteConfigSettings:GetString(key) end

--- @return string
function UnityEngine.RemoteConfigSettings:GetString(key, defaultValue) end

--- @return boolean
function UnityEngine.RemoteConfigSettings:GetBool(key) end

--- @return boolean
function UnityEngine.RemoteConfigSettings:GetBool(key, defaultValue) end

--- @return boolean
function UnityEngine.RemoteConfigSettings:HasKey(key) end

--- @return number
function UnityEngine.RemoteConfigSettings:GetCount() end

--- @return string[]
function UnityEngine.RemoteConfigSettings:GetKeys() end

--- @return UnityEngine.RemoteConfigSettings.T
function UnityEngine.RemoteConfigSettings:GetObject(key) end

--- @return System.Object
function UnityEngine.RemoteConfigSettings:GetObject(type, key) end

--- @return System.Object
function UnityEngine.RemoteConfigSettings:GetObject(key, defaultValue) end

--- @return System.Collections.Generic.IDictionary`2
function UnityEngine.RemoteConfigSettings:GetDictionary(key) end

---  Generated By xerysherry