--- @class UnityEngine.Playables.DataStreamType Describes the type of information that flows in and out of a Playable. This also specifies that this Playable is connectable to others of the same type.
UnityEngine.Playables.DataStreamType = {
    --- Describes that the information flowing in and out of the Playable is of Animation type.
    Animation = 0,
    --- Describes that the information flowing in and out of the Playable is of Audio type.
    Audio = 1,
    --- Describes that the information flowing in and out of the Playable is of type Texture.
    Texture = 2,
    --- Describes that the Playable does not have any particular type. This is use for Playables that execute script code, or that create their own playable graphs, such as the Sequence.
    None = 3,
}

---  Generated By xerysherry