--- @class UnityEngine.ProceduralTexture:UnityEngine.Texture Deprecated feature, no longer available
--- @field hasAlpha boolean property get
---       Deprecated feature, no longer available
--- @field format UnityEngine.TextureFormat property get
---       Deprecated feature, no longer available
--- @field mipmapCount number
--- @field graphicsFormat UnityEngine.Experimental.Rendering.GraphicsFormat
--- @field width number
--- @field height number
--- @field dimension UnityEngine.Rendering.TextureDimension
--- @field isReadable boolean
--- @field wrapMode UnityEngine.TextureWrapMode
--- @field wrapModeU UnityEngine.TextureWrapMode
--- @field wrapModeV UnityEngine.TextureWrapMode
--- @field wrapModeW UnityEngine.TextureWrapMode
--- @field filterMode UnityEngine.FilterMode
--- @field anisoLevel number
--- @field mipMapBias number
--- @field texelSize UnityEngine.Vector2
--- @field updateCount number
--- @field imageContentsHash UnityEngine.Hash128
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.ProceduralTexture = {}

--- Deprecated feature, no longer available
--- @return UnityEngine.ProceduralOutputType 
function UnityEngine.ProceduralTexture:GetProceduralOutputType() end

--- Deprecated feature, no longer available
--- @param x number 
--- @param y number 
--- @param blockWidth number 
--- @param blockHeight number 
--- @return UnityEngine.Color32[] 
function UnityEngine.ProceduralTexture:GetPixels32(x, y, blockWidth, blockHeight) end

---  Generated By xerysherry