--- @class UnityEngine.Time The interface to get time information from Unity.
--- @field time number property get
---       The time at the beginning of this frame (Read Only). This is the time in seconds since the start of the game.
--- @field timeSinceLevelLoad number property get
---       The time this frame has started (Read Only). This is the time in seconds since the last level has been loaded.
--- @field deltaTime number property get
---       The completion time in seconds since the last frame (Read Only).
--- @field fixedTime number property get
---       The time the latest MonoBehaviour.FixedUpdate has started (Read Only). This is the time in seconds since the start of the game.
--- @field unscaledTime number property get
---       The timeScale-independant time for this frame (Read Only). This is the time in seconds since the start of the game.
--- @field fixedUnscaledTime number property get
---       The TimeScale-independant time the latest MonoBehaviour.FixedUpdate has started (Read Only). This is the time in seconds since the start of the game.
--- @field unscaledDeltaTime number property get
---       The timeScale-independent interval in seconds from the last frame to the current one (Read Only).
--- @field fixedUnscaledDeltaTime number property get
---       The timeScale-independent interval in seconds from the last fixed frame to the current one (Read Only).
--- @field fixedDeltaTime number property getset
---       The interval in seconds at which physics and other fixed frame rate updates (like MonoBehaviour's MonoBehaviour.FixedUpdate) are performed.
--- @field maximumDeltaTime number property getset
---       The maximum time a frame can take. Physics and other fixed frame rate updates (like MonoBehaviour's MonoBehaviour.FixedUpdate) will be performed only for this duration of time per frame.
--- @field smoothDeltaTime number property get
---       A smoothed out Time.deltaTime (Read Only).
--- @field maximumParticleDeltaTime number property getset
---       The maximum time a frame can spend on particle updates. If the frame takes longer than this, then updates are split into multiple smaller updates.
--- @field timeScale number property getset
---       The scale at which time passes. This can be used for slow motion effects.
--- @field frameCount number property get
---       The total number of frames that have passed (Read Only).
--- @field renderedFrameCount number
--- @field realtimeSinceStartup number property get
---       The real time in seconds since the game started (Read Only).
--- @field captureDeltaTime number property getset
---       Slows game playback time to allow screenshots to be saved between frames.
--- @field captureFramerate number property getset
---       The reciprocal of Time.captureDeltaTime.
--- @field inFixedTimeStep boolean property get
---       Returns true if called inside a fixed time step callback (like MonoBehaviour's MonoBehaviour.FixedUpdate), otherwise returns false.
UnityEngine.Time = {}

--- @param value number 
function UnityEngine.Time.set_fixedDeltaTime(value) end

--- @param value number 
function UnityEngine.Time.set_maximumDeltaTime(value) end

--- @param value number 
function UnityEngine.Time.set_maximumParticleDeltaTime(value) end

--- @param value number 
function UnityEngine.Time.set_timeScale(value) end

--- @param value number 
function UnityEngine.Time.set_captureDeltaTime(value) end

--- @param value number 
function UnityEngine.Time.set_captureFramerate(value) end

---  Generated By xerysherry