--- @class UnityEngine.Social Generic access to the Social API.
--- @field Active UnityEngine.SocialPlatforms.ISocialPlatform property getset
---       This is the currently active social platform. 
--- @field localUser UnityEngine.SocialPlatforms.ILocalUser property get
---       The local user (potentially not logged in).
UnityEngine.Social = {}

--- @param value UnityEngine.SocialPlatforms.ISocialPlatform 
function UnityEngine.Social.set_Active(value) end

--- Load the user profiles accociated with the given array of user IDs.
--- @param userIDs string[] 
--- @param callback function 
function UnityEngine.Social.LoadUsers(userIDs, callback) end

--- Reports the progress of an achievement.
--- @param achievementID string 
--- @param progress number 
--- @param callback function 
function UnityEngine.Social.ReportProgress(achievementID, progress, callback) end

--- Loads the achievement descriptions accociated with this application.
--- @param callback function 
function UnityEngine.Social.LoadAchievementDescriptions(callback) end

--- Load the achievements the logged in user has already achieved or reported progress on.
--- @param callback function 
function UnityEngine.Social.LoadAchievements(callback) end

--- Report a score to a specific leaderboard.
--- @param score number 
--- @param board string 
--- @param callback function 
function UnityEngine.Social.ReportScore(score, board, callback) end

--- Load a default set of scores from the given leaderboard.
--- @param leaderboardID string 
--- @param callback function 
function UnityEngine.Social.LoadScores(leaderboardID, callback) end

--- Create an ILeaderboard instance.
--- @return UnityEngine.SocialPlatforms.ILeaderboard 
function UnityEngine.Social.CreateLeaderboard() end

--- Create an IAchievement instance.
--- @return UnityEngine.SocialPlatforms.IAchievement 
function UnityEngine.Social.CreateAchievement() end

--- Show a default/system view of the games achievements.
function UnityEngine.Social.ShowAchievementsUI() end

--- Show a default/system view of the games leaderboards.
function UnityEngine.Social.ShowLeaderboardUI() end

---  Generated By xerysherry