--- @class UnityEngine.ParticleCollisionEvent Information about a particle collision.
--- @field collider UnityEngine.Component property get
---       The Collider for the GameObject struck by the particles.
--- @field intersection UnityEngine.Vector3 property get
---       Intersection point of the collision in world coordinates.
--- @field normal UnityEngine.Vector3 property get
---       Geometry normal at the intersection point of the collision.
--- @field velocity UnityEngine.Vector3 property get
---       Incident velocity at the intersection point of the collision.
--- @field colliderComponent UnityEngine.Component property get
---       The Collider or Collider2D for the GameObject struck by the particles.
UnityEngine.ParticleCollisionEvent = {}

---  Generated By xerysherry