--- @class UnityEngine.AnchoredJoint2D:UnityEngine.Joint2D Parent class for all joints that have anchor points.
--- @field anchor UnityEngine.Vector2 property getset
---       The joint's anchor point on the object that has the joint component.
--- @field connectedAnchor UnityEngine.Vector2 property getset
---       The joint's anchor point on the second object (ie, the one which doesn't have the joint component).
--- @field autoConfigureConnectedAnchor boolean property getset
---       Should the connectedAnchor be calculated automatically?
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field connectedBody UnityEngine.Rigidbody2D
--- @field enableCollision boolean
--- @field breakForce number
--- @field breakTorque number
--- @field reactionForce UnityEngine.Vector2
--- @field reactionTorque number
--- @field collideConnected boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.AnchoredJoint2D = {}

--- @param value UnityEngine.Vector2 
function UnityEngine.AnchoredJoint2D:set_anchor(value) end

--- @param value UnityEngine.Vector2 
function UnityEngine.AnchoredJoint2D:set_connectedAnchor(value) end

--- @param value boolean 
function UnityEngine.AnchoredJoint2D:set_autoConfigureConnectedAnchor(value) end

---  Generated By xerysherry