--- @class UnityEngine.iPhoneKeyboard 
--- @field hideInput boolean
--- @field area UnityEngine.Rect
--- @field visible boolean
--- @field text string
--- @field active boolean
--- @field done boolean
UnityEngine.iPhoneKeyboard = {}

--- @param value boolean 
function UnityEngine.iPhoneKeyboard.set_hideInput(value) end

--- @param value string 
function UnityEngine.iPhoneKeyboard:set_text(value) end

--- @param value boolean 
function UnityEngine.iPhoneKeyboard:set_active(value) end

---  Generated By xerysherry