--- @class UnityEngine.EventSystems.PointerEventData.FramePressState
UnityEngine.EventSystems.PointerEventData.FramePressState = {
    Pressed = 0,
    Released = 1,
    PressedAndReleased = 2,
    NotChanged = 3,
}

---  Generated By xerysherry