--- @class UnityEngine.SpritePackingMode Sprite packing modes for the Sprite Packer.
UnityEngine.SpritePackingMode = {
    --- Tight mesh based packing.
    Tight = 0,
    --- Alpha-cropped ractangle packing.
    Rectangle = 1,
}

---  Generated By xerysherry