--- @class UnityEngine.Rendering.SupportedRenderingFeatures.LightmapMixedBakeModes Same as MixedLightingMode for baking, but is used to determine what is supported by the pipeline.
UnityEngine.Rendering.SupportedRenderingFeatures.LightmapMixedBakeModes = {
    --- No mode is supported.
    None = 0,
    --- Same as MixedLightingMode.IndirectOnly but determines if it is supported by the pipeline.
    IndirectOnly = 1,
    --- Same as MixedLightingMode.Subtractive but determines if it is supported by the pipeline.
    Subtractive = 2,
    --- Determines what is supported by the rendering pipeline. This enum is similar to MixedLightingMode.
    Shadowmask = 4,
}

--- @class UnityEngine.Rendering.SupportedRenderingFeatures.LightmapMixedBakeModes Same as MixedLightingMode for baking, but is used to determine what is supported by the pipeline.
UnityEngine.Rendering.SupportedRenderingFeatures.LightmapMixedBakeModes = {
    --- No mode is supported.
    None = 0,
    --- Same as MixedLightingMode.IndirectOnly but determines if it is supported by the pipeline.
    IndirectOnly = 1,
    --- Same as MixedLightingMode.Subtractive but determines if it is supported by the pipeline.
    Subtractive = 2,
    --- Determines what is supported by the rendering pipeline. This enum is similar to MixedLightingMode.
    Shadowmask = 4,
}

---  Generated By xerysherry