--- @class UnityEngine.StaticBatchingUtility StaticBatchingUtility can prepare your objects to take advantage of Unity's static batching.
UnityEngine.StaticBatchingUtility = {}

--- StaticBatchingUtility.Combine prepares all children of the staticBatchRoot for static batching.
--- @param staticBatchRoot UnityEngine.GameObject The GameObject that should become the root of the combined batch.
function UnityEngine.StaticBatchingUtility.Combine(staticBatchRoot) end

--- StaticBatchingUtility.Combine prepares all GameObjects contained in gos for static batching. staticBatchRoot is treated as their parent.
--- @param gos UnityEngine.GameObject[] The GameObjects to prepare for static batching.
--- @param staticBatchRoot UnityEngine.GameObject The GameObject that should become the root of the combined batch.
function UnityEngine.StaticBatchingUtility.Combine(gos, staticBatchRoot) end

---  Generated By xerysherry