--- @class UnityEngine.TargetJoint2D:UnityEngine.Joint2D The joint attempts to move a Rigidbody2D to a specific target position.
--- @field anchor UnityEngine.Vector2 property getset
---       The local-space anchor on the rigid-body the joint is attached to.
--- @field target UnityEngine.Vector2 property getset
---       The world-space position that the joint will attempt to move the body to.
--- @field autoConfigureTarget boolean property getset
---       Should the target be calculated automatically?
--- @field maxForce number property getset
---       The maximum force that can be generated when trying to maintain the target joint constraint.
--- @field dampingRatio number property getset
---       The amount by which the target spring force is reduced in proportion to the movement speed.
--- @field frequency number property getset
---       The frequency at which the target spring oscillates around the target position.
--- @field attachedRigidbody UnityEngine.Rigidbody2D
--- @field connectedBody UnityEngine.Rigidbody2D
--- @field enableCollision boolean
--- @field breakForce number
--- @field breakTorque number
--- @field reactionForce UnityEngine.Vector2
--- @field reactionTorque number
--- @field collideConnected boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.TargetJoint2D = {}

function UnityEngine.TargetJoint2D:set_anchor(value) end

function UnityEngine.TargetJoint2D:set_target(value) end

function UnityEngine.TargetJoint2D:set_autoConfigureTarget(value) end

function UnityEngine.TargetJoint2D:set_maxForce(value) end

function UnityEngine.TargetJoint2D:set_dampingRatio(value) end

function UnityEngine.TargetJoint2D:set_frequency(value) end

---  Generated By xerysherry