--- @class UnityEngine.DrivenTransformProperties An enumeration of transform properties that can be driven on a RectTransform by an object.
UnityEngine.DrivenTransformProperties = {
    --- Deselects all driven properties.
    None = 0,
    --- Selects all driven properties.
    All = -1,
    --- Selects driven property RectTransform.anchoredPosition.x.
    AnchoredPositionX = 2,
    --- Selects driven property RectTransform.anchoredPosition.y.
    AnchoredPositionY = 4,
    --- Selects driven property RectTransform.anchoredPosition3D.z.
    AnchoredPositionZ = 8,
    --- Selects driven property Transform.localRotation.
    Rotation = 16,
    --- Selects driven property Transform.localScale.x.
    ScaleX = 32,
    --- Selects driven property Transform.localScale.y.
    ScaleY = 64,
    --- Selects driven property Transform.localScale.z.
    ScaleZ = 128,
    --- Selects driven property RectTransform.anchorMin.x.
    AnchorMinX = 256,
    --- Selects driven property RectTransform.anchorMin.y.
    AnchorMinY = 512,
    --- Selects driven property RectTransform.anchorMax.x.
    AnchorMaxX = 1024,
    --- Selects driven property RectTransform.anchorMax.y.
    AnchorMaxY = 2048,
    --- Selects driven property RectTransform.sizeDelta.x.
    SizeDeltaX = 4096,
    --- Selects driven property RectTransform.sizeDelta.y.
    SizeDeltaY = 8192,
    --- Selects driven property RectTransform.pivot.x.
    PivotX = 16384,
    --- Selects driven property RectTransform.pivot.y.
    PivotY = 32768,
    --- Selects driven property RectTransform.anchoredPosition.
    AnchoredPosition = 6,
    --- Selects driven property RectTransform.anchoredPosition3D.
    AnchoredPosition3D = 14,
    --- Selects driven property combining ScaleX, ScaleY && ScaleZ.
    Scale = 224,
    --- Selects driven property combining AnchorMinX and AnchorMinY.
    AnchorMin = 768,
    --- Selects driven property combining AnchorMaxX and AnchorMaxY.
    AnchorMax = 3072,
    --- Selects driven property combining AnchorMinX, AnchorMinY, AnchorMaxX and AnchorMaxY.
    Anchors = 3840,
    --- Selects driven property combining SizeDeltaX and SizeDeltaY.
    SizeDelta = 12288,
    --- Selects driven property combining PivotX and PivotY.
    Pivot = 49152,
}

---  Generated By xerysherry