--- @class UnityEngine.Rendering.CameraEvent Defines a place in camera's rendering to attach Rendering.CommandBuffer objects to.
UnityEngine.Rendering.CameraEvent = {
    --- Before camera's depth texture is generated.
    BeforeDepthTexture = 0,
    --- After camera's depth texture is generated.
    AfterDepthTexture = 1,
    --- Before camera's depth+normals texture is generated.
    BeforeDepthNormalsTexture = 2,
    --- After camera's depth+normals texture is generated.
    AfterDepthNormalsTexture = 3,
    --- Before deferred rendering G-buffer is rendered.
    BeforeGBuffer = 4,
    --- After deferred rendering G-buffer is rendered.
    AfterGBuffer = 5,
    --- Before lighting pass in deferred rendering.
    BeforeLighting = 6,
    --- After lighting pass in deferred rendering.
    AfterLighting = 7,
    --- Before final geometry pass in deferred lighting.
    BeforeFinalPass = 8,
    --- After final geometry pass in deferred lighting.
    AfterFinalPass = 9,
    --- Before opaque objects in forward rendering.
    BeforeForwardOpaque = 10,
    --- After opaque objects in forward rendering.
    AfterForwardOpaque = 11,
    --- Before image effects that happen between opaque & transparent objects.
    BeforeImageEffectsOpaque = 12,
    --- After image effects that happen between opaque & transparent objects.
    AfterImageEffectsOpaque = 13,
    --- Before skybox is drawn.
    BeforeSkybox = 14,
    --- After skybox is drawn.
    AfterSkybox = 15,
    --- Before transparent objects in forward rendering.
    BeforeForwardAlpha = 16,
    --- After transparent objects in forward rendering.
    AfterForwardAlpha = 17,
    --- Before image effects.
    BeforeImageEffects = 18,
    --- After image effects.
    AfterImageEffects = 19,
    --- After camera has done rendering everything.
    AfterEverything = 20,
    --- Before reflections pass in deferred rendering.
    BeforeReflections = 21,
    --- After reflections pass in deferred rendering.
    AfterReflections = 22,
    --- Before halo and lens flares.
    BeforeHaloAndLensFlares = 23,
    --- After halo and lens flares.
    AfterHaloAndLensFlares = 24,
}

---  Generated By xerysherry