--- @class UnityEngine.UI.InputField.ContentType
UnityEngine.UI.InputField.ContentType = {
    Standard = 0,
    Autocorrected = 1,
    IntegerNumber = 2,
    DecimalNumber = 3,
    Alphanumeric = 4,
    Name = 5,
    EmailAddress = 6,
    Password = 7,
    Pin = 8,
    Custom = 9,
}

---  Generated By xerysherry