--- @class UnityEngine.iOS.SystemGestureDeferMode Bit-mask used to control the deferring of system gestures on iOS.
UnityEngine.iOS.SystemGestureDeferMode = {
    --- Disables gesture deferring on all edges.
    None = 0,
    --- Identifies top screen edge.
    TopEdge = 1,
    --- Identifies left screen edge.
    LeftEdge = 2,
    --- Identifies bottom screen edge.
    BottomEdge = 4,
    --- Identifies right screen edge.
    RightEdge = 8,
    --- Identifies all screen edges.
    All = 15,
}

---  Generated By xerysherry