--- @class UnityEngine.Internal.DefaultValueAttribute:System.Attribute 
--- @field Value System.Object
--- @field TypeId System.Object
UnityEngine.Internal.DefaultValueAttribute = {}

--- @return boolean
function UnityEngine.Internal.DefaultValueAttribute:Equals(obj) end

--- @return number
function UnityEngine.Internal.DefaultValueAttribute:GetHashCode() end

---  Generated By xerysherry