--- @class UnityEngine.Rendering.ShaderPropertyType Type of a given shader property.
UnityEngine.Rendering.ShaderPropertyType = {
    --- The property holds a Vector4 value representing a color.
    Color = 0,
    --- The property holds a Vector4 value.
    Vector = 1,
    --- The property holds a floating number value.
    Float = 2,
    --- The property holds a floating number value in a certain range.
    Range = 3,
    --- The property holds a Texture object.
    Texture = 4,
}

---  Generated By xerysherry