--- @class UnityEngine.Experimental.Rendering.ShaderWarmupSetup Rendering setup to use when warming up shader.
--- @field vdecl UnityEngine.Rendering.VertexAttributeDescriptor[] Vertex Format to be used with shader.
UnityEngine.Experimental.Rendering.ShaderWarmupSetup = {}

---  Generated By xerysherry