--- @class UnityEngine.HumanPoseHandler A handler that lets you read or write a HumanPose from or to a humanoid avatar skeleton hierarchy.
UnityEngine.HumanPoseHandler = {}

function UnityEngine.HumanPoseHandler:Dispose() end

--- Gets a human pose from the handled avatar skeleton.
--- @param humanPose UnityEngine.HumanPose& The output human pose.
function UnityEngine.HumanPoseHandler:GetHumanPose(humanPose) end

--- Sets a human pose on the handled avatar skeleton.
--- @param humanPose UnityEngine.HumanPose& The human pose to be set.
function UnityEngine.HumanPoseHandler:SetHumanPose(humanPose) end

---  Generated By xerysherry