--- @class UnityEngine.U2D.SpriteShapeParameters Input parameters for the SpriteShape tessellator.
--- @field transform UnityEngine.Matrix4x4 The world space transform of the GameObject used for calculating the UVs of the Fill texture.
--- @field fillTexture UnityEngine.Texture2D The texture to be used for the fill of the SpriteShape.
--- @field fillScale number The scale to be used to calculate the UVs of the fill texture.
--- @field splineDetail number The tessellation quality of the input Spline that determines the complexity of the mesh.
--- @field angleThreshold number The threshold of the angle that indicates whether it is a corner or not.
--- @field borderPivot number The local displacement of the Sprite when tessellated.
--- @field bevelCutoff number The threshold of the angle that decides if it should be tessellated as a curve or a corner.
--- @field bevelSize number The radius of the curve to be tessellated.
--- @field carpet boolean If true, the Shape will be tessellated as a closed form.
--- @field smartSprite boolean If enabled the tessellator will consider creating corners based on the various input parameters.
--- @field adaptiveUV boolean If enabled, the tessellator will adapt the size of the quads based on the height of the edge.
--- @field spriteBorders boolean The borders to be used for calculating the uv of the edges based on the border info found in Sprites.
--- @field stretchUV boolean Stretch the UV mapping for the Fill texture.
UnityEngine.U2D.SpriteShapeParameters = {}

---  Generated By xerysherry