--- @class UnityEngine.UI.Mask:UnityEngine.EventSystems.UIBehaviour 
--- @field rectTransform UnityEngine.RectTransform
--- @field showMaskGraphic boolean
--- @field graphic UnityEngine.UI.Graphic
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.Mask = {}

--- @param value boolean 
function UnityEngine.UI.Mask:set_showMaskGraphic(value) end

--- @return boolean
function UnityEngine.UI.Mask:MaskEnabled() end

function UnityEngine.UI.Mask:OnSiblingGraphicEnabledDisabled() end

--- @param sp UnityEngine.Vector2 
--- @param eventCamera UnityEngine.Camera 
--- @return boolean
function UnityEngine.UI.Mask:IsRaycastLocationValid(sp, eventCamera) end

--- @param baseMaterial UnityEngine.Material 
--- @return UnityEngine.Material
function UnityEngine.UI.Mask:GetModifiedMaterial(baseMaterial) end

---  Generated By xerysherry