--- @class UnityEngine.UI.GridLayoutGroup:UnityEngine.UI.LayoutGroup 
--- @field startCorner UnityEngine.UI.GridLayoutGroup.Corner
--- @field startAxis UnityEngine.UI.GridLayoutGroup.Axis
--- @field cellSize UnityEngine.Vector2
--- @field spacing UnityEngine.Vector2
--- @field constraint UnityEngine.UI.GridLayoutGroup.Constraint
--- @field constraintCount number
--- @field padding UnityEngine.RectOffset
--- @field childAlignment UnityEngine.TextAnchor
--- @field minWidth number
--- @field preferredWidth number
--- @field flexibleWidth number
--- @field minHeight number
--- @field preferredHeight number
--- @field flexibleHeight number
--- @field layoutPriority number
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.UI.GridLayoutGroup = {}

function UnityEngine.UI.GridLayoutGroup:set_startCorner(value) end

function UnityEngine.UI.GridLayoutGroup:set_startAxis(value) end

function UnityEngine.UI.GridLayoutGroup:set_cellSize(value) end

function UnityEngine.UI.GridLayoutGroup:set_spacing(value) end

function UnityEngine.UI.GridLayoutGroup:set_constraint(value) end

function UnityEngine.UI.GridLayoutGroup:set_constraintCount(value) end

function UnityEngine.UI.GridLayoutGroup:CalculateLayoutInputHorizontal() end

function UnityEngine.UI.GridLayoutGroup:CalculateLayoutInputVertical() end

function UnityEngine.UI.GridLayoutGroup:SetLayoutHorizontal() end

function UnityEngine.UI.GridLayoutGroup:SetLayoutVertical() end

---  Generated By xerysherry