--- @class UnityEngine.Rendering.RenderPipelineManager Render Pipeline manager.
--- @field currentPipeline UnityEngine.Rendering.RenderPipeline property get
---       Returns the instance of the current RenderPipeline.
UnityEngine.Rendering.RenderPipelineManager = {}

function UnityEngine.Rendering.RenderPipelineManager.add_beginFrameRendering(value) end

function UnityEngine.Rendering.RenderPipelineManager.remove_beginFrameRendering(value) end

function UnityEngine.Rendering.RenderPipelineManager.add_beginCameraRendering(value) end

function UnityEngine.Rendering.RenderPipelineManager.remove_beginCameraRendering(value) end

function UnityEngine.Rendering.RenderPipelineManager.add_endFrameRendering(value) end

function UnityEngine.Rendering.RenderPipelineManager.remove_endFrameRendering(value) end

function UnityEngine.Rendering.RenderPipelineManager.add_endCameraRendering(value) end

function UnityEngine.Rendering.RenderPipelineManager.remove_endCameraRendering(value) end

---  Generated By xerysherry