--- @class UnityEngine.AI.NavMeshPathStatus Status of path.
UnityEngine.AI.NavMeshPathStatus = {
    --- The path terminates at the destination.
    PathComplete = 0,
    --- The path cannot reach the destination.
    PathPartial = 1,
    --- The path is invalid.
    PathInvalid = 2,
}

---  Generated By xerysherry