--- @class UnityEngine.VR.VRDevice 
--- @field isPresent boolean
--- @field userPresence UnityEngine.XR.UserPresenceState
--- @field family string
--- @field model string
--- @field refreshRate number
UnityEngine.VR.VRDevice = {}

--- @return UnityEngine.XR.TrackingSpaceType
function UnityEngine.VR.VRDevice.GetTrackingSpaceType() end

--- @return boolean
function UnityEngine.VR.VRDevice.SetTrackingSpaceType(trackingSpaceType) end

--- @return System.IntPtr
function UnityEngine.VR.VRDevice.GetNativePtr() end

function UnityEngine.VR.VRDevice.DisableAutoVRCameraTracking(camera, disabled) end

---  Generated By xerysherry