--- @class UnityEngine.AI.OffMeshLink:UnityEngine.Behaviour Link allowing movement outside the planar navigation mesh.
--- @field activated boolean property getset
---       Is link active.
--- @field occupied boolean property get
---       Is link occupied. (Read Only)
--- @field costOverride number property getset
---       Modify pathfinding cost for the link.
--- @field biDirectional boolean property getset
---       Can link be traversed in both directions.
--- @field navMeshLayer number property getset
---       NavMeshLayer for this OffMeshLink component.
--- @field area number property getset
---       NavMesh area index for this OffMeshLink component.
--- @field autoUpdatePositions boolean property getset
---       Automatically update endpoints.
--- @field startTransform UnityEngine.Transform property getset
---       The transform representing link start position.
--- @field endTransform UnityEngine.Transform property getset
---       The transform representing link end position.
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.AI.OffMeshLink = {}

--- @param value boolean 
function UnityEngine.AI.OffMeshLink:set_activated(value) end

--- @param value number 
function UnityEngine.AI.OffMeshLink:set_costOverride(value) end

--- @param value boolean 
function UnityEngine.AI.OffMeshLink:set_biDirectional(value) end

--- Explicitly update the link endpoints.
function UnityEngine.AI.OffMeshLink:UpdatePositions() end

--- @param value number 
function UnityEngine.AI.OffMeshLink:set_navMeshLayer(value) end

--- @param value number 
function UnityEngine.AI.OffMeshLink:set_area(value) end

--- @param value boolean 
function UnityEngine.AI.OffMeshLink:set_autoUpdatePositions(value) end

--- @param value UnityEngine.Transform 
function UnityEngine.AI.OffMeshLink:set_startTransform(value) end

--- @param value UnityEngine.Transform 
function UnityEngine.AI.OffMeshLink:set_endTransform(value) end

---  Generated By xerysherry