--- @class UnityEngine.UI.Toggle:UnityEngine.UI.Selectable 
--- @field group UnityEngine.UI.ToggleGroup
--- @field isOn boolean
--- @field navigation UnityEngine.UI.Navigation
--- @field transition UnityEngine.UI.Selectable.Transition
--- @field colors UnityEngine.UI.ColorBlock
--- @field spriteState UnityEngine.UI.SpriteState
--- @field animationTriggers UnityEngine.UI.AnimationTriggers
--- @field targetGraphic UnityEngine.UI.Graphic
--- @field interactable boolean
--- @field image UnityEngine.UI.Image
--- @field animator UnityEngine.Animator
--- @field useGUILayout boolean
--- @field runInEditMode boolean
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
--- @field toggleTransition UnityEngine.UI.Toggle.ToggleTransition
--- @field graphic UnityEngine.UI.Graphic
--- @field onValueChanged UnityEngine.UI.Toggle.ToggleEvent
UnityEngine.UI.Toggle = {}

--- @param value UnityEngine.UI.ToggleGroup 
function UnityEngine.UI.Toggle:set_group(value) end

--- @param executing UnityEngine.UI.CanvasUpdate 
function UnityEngine.UI.Toggle:Rebuild(executing) end

function UnityEngine.UI.Toggle:LayoutComplete() end

function UnityEngine.UI.Toggle:GraphicUpdateComplete() end

--- @param value boolean 
function UnityEngine.UI.Toggle:set_isOn(value) end

--- @param value boolean 
function UnityEngine.UI.Toggle:SetIsOnWithoutNotify(value) end

--- @param eventData UnityEngine.EventSystems.PointerEventData 
function UnityEngine.UI.Toggle:OnPointerClick(eventData) end

--- @param eventData UnityEngine.EventSystems.BaseEventData 
function UnityEngine.UI.Toggle:OnSubmit(eventData) end

---  Generated By xerysherry