--- @class UnityEngine.UIElements.VisualElementStyleSheetSet This structure manipulates the set of StyleSheet objects attached to the owner VisualElement.
--- @field count number property get
---       Number of style sheets attached to the owner element.
---                       
--- @field Item UnityEngine.UIElements.StyleSheet
UnityEngine.UIElements.VisualElementStyleSheetSet = {}

--- @return boolean
function UnityEngine.UIElements.VisualElementStyleSheetSet.op_Equality(left, right) end

--- @return boolean
function UnityEngine.UIElements.VisualElementStyleSheetSet.op_Inequality(left, right) end

--- Adds a style sheet for the owner element.
--- @param styleSheet UnityEngine.UIElements.StyleSheet 
function UnityEngine.UIElements.VisualElementStyleSheetSet:Add(styleSheet) end

--- Removes all style sheets for the owner element.
function UnityEngine.UIElements.VisualElementStyleSheetSet:Clear() end

--- Removes a style sheet for the owner element.
--- @return boolean 
function UnityEngine.UIElements.VisualElementStyleSheetSet:Remove(styleSheet) end

--- Looks for the specified StyleSheet
--- @param styleSheet UnityEngine.UIElements.StyleSheet 
--- @return boolean True if the style sheet is attached to the owner element, false otherwise.
function UnityEngine.UIElements.VisualElementStyleSheetSet:Contains(styleSheet) end

--- @return boolean
function UnityEngine.UIElements.VisualElementStyleSheetSet:Equals(other) end

--- @return boolean
function UnityEngine.UIElements.VisualElementStyleSheetSet:Equals(obj) end

--- @return number
function UnityEngine.UIElements.VisualElementStyleSheetSet:GetHashCode() end

---  Generated By xerysherry