--- @class UnityEngine.UIElements.Foldout:UnityEngine.UIElements.BindableElement Collapsable section of UI.
--- @field ussClassName string USS class name of elements of this type.
--- @field toggleUssClassName string USS class name of toggle elements in elements of this type.
--- @field contentUssClassName string USS class name of content element in a Foldout.
--- @field contentContainer UnityEngine.UIElements.VisualElement
--- @field text string
--- @field value boolean property getset
---       Contains the collapse state. True if the Foldout is open and the contents are visible. False if it's collapsed.
--- @field binding UnityEngine.UIElements.IBinding
--- @field bindingPath string
--- @field viewDataKey string
--- @field userData System.Object
--- @field canGrabFocus boolean
--- @field focusController UnityEngine.UIElements.FocusController
--- @field usageHints UnityEngine.UIElements.UsageHints
--- @field transform UnityEngine.UIElements.ITransform
--- @field layout UnityEngine.Rect
--- @field contentRect UnityEngine.Rect
--- @field worldBound UnityEngine.Rect
--- @field localBound UnityEngine.Rect
--- @field worldTransform UnityEngine.Matrix4x4
--- @field pickingMode UnityEngine.UIElements.PickingMode
--- @field name string
--- @field enabledInHierarchy boolean
--- @field enabledSelf boolean
--- @field visible boolean
--- @field generateVisualContent function
--- @field experimental UnityEngine.UIElements.IExperimentalFeatures
--- @field hierarchy UnityEngine.UIElements.VisualElement.Hierarchy
--- @field cacheAsBitmap boolean
--- @field parent UnityEngine.UIElements.VisualElement
--- @field panel UnityEngine.UIElements.IPanel
--- @field Item UnityEngine.UIElements.VisualElement
--- @field childCount number
--- @field schedule UnityEngine.UIElements.IVisualElementScheduler
--- @field style UnityEngine.UIElements.IStyle
--- @field customStyle UnityEngine.UIElements.ICustomStyle
--- @field resolvedStyle UnityEngine.UIElements.IResolvedStyle
--- @field styleSheets UnityEngine.UIElements.VisualElementStyleSheetSet
--- @field tooltip string
--- @field focusable boolean
--- @field tabIndex number
--- @field delegatesFocus boolean
UnityEngine.UIElements.Foldout = {}

--- @param value string 
function UnityEngine.UIElements.Foldout:set_text(value) end

--- @param value boolean 
function UnityEngine.UIElements.Foldout:set_value(value) end

--- @param newValue boolean 
function UnityEngine.UIElements.Foldout:SetValueWithoutNotify(newValue) end

---  Generated By xerysherry