--- @class UnityEngine.AreaEffector2D:UnityEngine.Effector2D Applies forces within an area.
--- @field forceAngle number property getset
---       The angle of the force to be applied.
--- @field useGlobalAngle boolean property getset
---       Should the forceAngle use global space?
--- @field forceMagnitude number property getset
---       The magnitude of the force to be applied.
--- @field forceVariation number property getset
---       The variation of the magnitude of the force to be applied.
--- @field drag number property getset
---       The linear drag to apply to rigid-bodies.
--- @field angularDrag number property getset
---       The angular drag to apply to rigid-bodies.
--- @field forceTarget UnityEngine.EffectorSelection2D property getset
---       The target for where the effector applies any force.
--- @field forceDirection number
--- @field useColliderMask boolean
--- @field colliderMask number
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.AreaEffector2D = {}

--- @param value number 
function UnityEngine.AreaEffector2D:set_forceAngle(value) end

--- @param value boolean 
function UnityEngine.AreaEffector2D:set_useGlobalAngle(value) end

--- @param value number 
function UnityEngine.AreaEffector2D:set_forceMagnitude(value) end

--- @param value number 
function UnityEngine.AreaEffector2D:set_forceVariation(value) end

--- @param value number 
function UnityEngine.AreaEffector2D:set_drag(value) end

--- @param value number 
function UnityEngine.AreaEffector2D:set_angularDrag(value) end

--- @param value UnityEngine.EffectorSelection2D 
function UnityEngine.AreaEffector2D:set_forceTarget(value) end

--- @param value number 
function UnityEngine.AreaEffector2D:set_forceDirection(value) end

---  Generated By xerysherry