--- @class UnityEngine.Rendering.FilteringSettings Filter settings for ScriptableRenderContext.DrawRenderers.
--- @field defaultValue UnityEngine.Rendering.FilteringSettings property get
---       Provides a set of default values that causes no filtering to occur.
--- @field renderQueueRange UnityEngine.Rendering.RenderQueueRange property getset
---       Render objects whose material render queue in inside this range.
--- @field layerMask number property getset
---       Only render objects in the given layer mask.
--- @field renderingLayerMask number property getset
---       The rendering layer mask to use when filtering available renderers for drawing.
--- @field excludeMotionVectorObjects boolean property getset
---       Set to true to exclude objects that are currently in motion from rendering. The default value is false.
--- @field sortingLayerRange UnityEngine.Rendering.SortingLayerRange property getset
---       Render objects whose sorting layer is inside this range.
UnityEngine.Rendering.FilteringSettings = {}

--- @return boolean
function UnityEngine.Rendering.FilteringSettings.op_Equality(left, right) end

--- @return boolean
function UnityEngine.Rendering.FilteringSettings.op_Inequality(left, right) end

function UnityEngine.Rendering.FilteringSettings:set_renderQueueRange(value) end

function UnityEngine.Rendering.FilteringSettings:set_layerMask(value) end

function UnityEngine.Rendering.FilteringSettings:set_renderingLayerMask(value) end

function UnityEngine.Rendering.FilteringSettings:set_excludeMotionVectorObjects(value) end

function UnityEngine.Rendering.FilteringSettings:set_sortingLayerRange(value) end

--- @return boolean
function UnityEngine.Rendering.FilteringSettings:Equals(other) end

--- @return boolean
function UnityEngine.Rendering.FilteringSettings:Equals(obj) end

--- @return number
function UnityEngine.Rendering.FilteringSettings:GetHashCode() end

---  Generated By xerysherry