--- @class UnityEngine.Font:UnityEngine.Object Script interface for.
--- @field material UnityEngine.Material property getset
---       The material used for the font display.
--- @field fontNames string[]
--- @field dynamic boolean property get
---       Is the font a dynamic font.
--- @field ascent number property get
---       The ascent of the font.
--- @field fontSize number property get
---       The default size of the font.
--- @field characterInfo UnityEngine.CharacterInfo[] property getset
---       Access an array of all characters contained in the font texture.
--- @field lineHeight number property get
---       The line height of the font.
--- @field textureRebuildCallback function
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Font = {}

function UnityEngine.Font.add_textureRebuilt(value) end

function UnityEngine.Font.remove_textureRebuilt(value) end

--- Creates a Font object which lets you render a font installed on the user machine.
--- @return UnityEngine.Font The generate Font object.
function UnityEngine.Font.CreateDynamicFontFromOSFont(fontname, size) end

--- Creates a Font object which lets you render a font installed on the user machine.
--- @return UnityEngine.Font The generate Font object.
function UnityEngine.Font.CreateDynamicFontFromOSFont(fontnames, size) end

--- Returns the maximum number of verts that the text generator may return for a given string.
--- @param str string Input string.
--- @return number 
function UnityEngine.Font.GetMaxVertsForString(str) end

--- Get names of fonts installed on the machine.
--- @return string[] An array of the names of all fonts installed on the machine.
function UnityEngine.Font.GetOSInstalledFontNames() end

--- Gets the file paths of the fonts that are installed on the operating system.
--- @return string[] An array of the file paths of all fonts installed on the machine.
function UnityEngine.Font.GetPathsToOSFonts() end

function UnityEngine.Font:set_material(value) end

function UnityEngine.Font:set_fontNames(value) end

function UnityEngine.Font:set_characterInfo(value) end

function UnityEngine.Font:set_textureRebuildCallback(value) end

--- Does this font have a specific character?
--- @param c number The character to check for.
--- @return boolean Whether or not the font has the character specified.
function UnityEngine.Font:HasCharacter(c) end

--- Get rendering info for a specific character.
--- @param ch number The character you need rendering information for.
--- @param size number The size of the character (default value of zero will use font default size).
--- @param style UnityEngine.FontStyle The style of the character.
--- @return boolean 
--- @return UnityEngine.CharacterInfo& Returns the CharacterInfo struct with the rendering information for the character (if available).
function UnityEngine.Font:GetCharacterInfo(ch, size, style) end

--- Get rendering info for a specific character.
--- @return boolean 
function UnityEngine.Font:GetCharacterInfo(ch, size) end

--- Get rendering info for a specific character.
--- @return boolean 
function UnityEngine.Font:GetCharacterInfo(ch) end

--- Request characters to be added to the font texture (dynamic fonts only).
--- @param characters string The characters which are needed to be in the font texture.
--- @param size number The size of the requested characters (the default value of zero will use the font's default size).
--- @param style UnityEngine.FontStyle The style of the requested characters.
function UnityEngine.Font:RequestCharactersInTexture(characters, size, style) end

--- Request characters to be added to the font texture (dynamic fonts only).
function UnityEngine.Font:RequestCharactersInTexture(characters, size) end

--- Request characters to be added to the font texture (dynamic fonts only).
function UnityEngine.Font:RequestCharactersInTexture(characters) end

---  Generated By xerysherry