--- @class UnityEngine.Joint2D:UnityEngine.Behaviour Parent class for joints to connect Rigidbody2D objects.
--- @field attachedRigidbody UnityEngine.Rigidbody2D property get
---       The Rigidbody2D attached to the Joint2D.
--- @field connectedBody UnityEngine.Rigidbody2D property getset
---       The Rigidbody2D object to which the other end of the joint is attached (ie, the object without the joint component).
--- @field enableCollision boolean property getset
---       Should the two rigid bodies connected with this joint collide with each other?
--- @field breakForce number property getset
---       The force that needs to be applied for this joint to break.
--- @field breakTorque number property getset
---       The torque that needs to be applied for this joint to break.
--- @field reactionForce UnityEngine.Vector2 property get
---       Gets the reaction force of the joint.
--- @field reactionTorque number property get
---       Gets the reaction torque of the joint.
--- @field collideConnected boolean property getset
---       Can the joint collide with the other Rigidbody2D object to which it is attached?
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.Joint2D = {}

--- @param value UnityEngine.Rigidbody2D 
function UnityEngine.Joint2D:set_connectedBody(value) end

--- @param value boolean 
function UnityEngine.Joint2D:set_enableCollision(value) end

--- @param value number 
function UnityEngine.Joint2D:set_breakForce(value) end

--- @param value number 
function UnityEngine.Joint2D:set_breakTorque(value) end

--- Gets the reaction force of the joint given the specified timeStep.
--- @param timeStep number The time to calculate the reaction force for.
--- @return UnityEngine.Vector2 The reaction force of the joint in the specified timeStep.
function UnityEngine.Joint2D:GetReactionForce(timeStep) end

--- Gets the reaction torque of the joint given the specified timeStep.
--- @param timeStep number The time to calculate the reaction torque for.
--- @return number The reaction torque of the joint in the specified timeStep.
function UnityEngine.Joint2D:GetReactionTorque(timeStep) end

--- @param value boolean 
function UnityEngine.Joint2D:set_collideConnected(value) end

---  Generated By xerysherry