--- @class UnityEngine.SocialPlatforms.UserState User presence state.
UnityEngine.SocialPlatforms.UserState = {
    --- The user is online.
    Online = 0,
    --- The user is online but away from their computer.
    OnlineAndAway = 1,
    --- The user is online but set their status to busy.
    OnlineAndBusy = 2,
    --- The user is offline.
    Offline = 3,
    --- The user is playing a game.
    Playing = 4,
}

---  Generated By xerysherry