--- @class UnityEngine.Rendering.VertexAttributeDescriptor Information about a single VertexAttribute of a Mesh vertex.
--- @field attribute UnityEngine.Rendering.VertexAttribute property getset
---       The vertex attribute.
--- @field format UnityEngine.Rendering.VertexAttributeFormat property getset
---       Format of the vertex attribute.
--- @field dimension number property getset
---       Dimensionality of the vertex attribute.
--- @field stream number property getset
---       Which vertex buffer stream the attribute should be in.
UnityEngine.Rendering.VertexAttributeDescriptor = {}

--- @param lhs UnityEngine.Rendering.VertexAttributeDescriptor 
--- @param rhs UnityEngine.Rendering.VertexAttributeDescriptor 
--- @return boolean
function UnityEngine.Rendering.VertexAttributeDescriptor.op_Equality(lhs, rhs) end

--- @param lhs UnityEngine.Rendering.VertexAttributeDescriptor 
--- @param rhs UnityEngine.Rendering.VertexAttributeDescriptor 
--- @return boolean
function UnityEngine.Rendering.VertexAttributeDescriptor.op_Inequality(lhs, rhs) end

--- @param value UnityEngine.Rendering.VertexAttribute 
function UnityEngine.Rendering.VertexAttributeDescriptor:set_attribute(value) end

--- @param value UnityEngine.Rendering.VertexAttributeFormat 
function UnityEngine.Rendering.VertexAttributeDescriptor:set_format(value) end

--- @param value number 
function UnityEngine.Rendering.VertexAttributeDescriptor:set_dimension(value) end

--- @param value number 
function UnityEngine.Rendering.VertexAttributeDescriptor:set_stream(value) end

--- @return string
function UnityEngine.Rendering.VertexAttributeDescriptor:ToString() end

--- @return number
function UnityEngine.Rendering.VertexAttributeDescriptor:GetHashCode() end

--- @param other System.Object 
--- @return boolean
function UnityEngine.Rendering.VertexAttributeDescriptor:Equals(other) end

--- @param other UnityEngine.Rendering.VertexAttributeDescriptor 
--- @return boolean
function UnityEngine.Rendering.VertexAttributeDescriptor:Equals(other) end

---  Generated By xerysherry