--- @class UnityEngine.TextGenerationSettings A struct that stores the settings for TextGeneration.
--- @field font UnityEngine.Font Font to use for generation.
--- @field color UnityEngine.Color The base color for the text generation.
--- @field fontSize number Font size.
--- @field lineSpacing number The line spacing multiplier.
--- @field richText boolean Allow rich text markup in generation.
--- @field scaleFactor number A scale factor for the text. This is useful if the Text is on a Canvas and the canvas is scaled.
--- @field fontStyle UnityEngine.FontStyle Font style.
--- @field textAnchor UnityEngine.TextAnchor How is the generated text anchored.
--- @field alignByGeometry boolean Use the extents of glyph geometry to perform horizontal alignment rather than glyph metrics.
--- @field resizeTextForBestFit boolean Should the text be resized to fit the configured bounds?
--- @field resizeTextMinSize number Minimum size for resized text.
--- @field resizeTextMaxSize number Maximum size for resized text.
--- @field updateBounds boolean Should the text generator update the bounds from the generated text.
--- @field verticalOverflow UnityEngine.VerticalWrapMode What happens to text when it reaches the bottom generation bounds.
--- @field horizontalOverflow UnityEngine.HorizontalWrapMode What happens to text when it reaches the horizontal generation bounds.
--- @field generationExtents UnityEngine.Vector2 Extents that the generator will attempt to fit the text in.
--- @field pivot UnityEngine.Vector2 Generated vertices are offset by the pivot.
--- @field generateOutOfBounds boolean Continue to generate characters even if the text runs out of bounds.
UnityEngine.TextGenerationSettings = {}

--- @param other UnityEngine.TextGenerationSettings 
--- @return boolean
function UnityEngine.TextGenerationSettings:Equals(other) end

---  Generated By xerysherry