--- @class UnityEngine.AI.NavMeshTriangulation Contains data describing a triangulation of a navmesh.
--- @field layers number[] property get
---       NavMeshLayer values for the navmesh triangulation.
--- @field vertices UnityEngine.Vector3[] Vertices for the navmesh triangulation.
--- @field indices number[] Triangle indices for the navmesh triangulation.
--- @field areas number[] NavMesh area indices for the navmesh triangulation.
UnityEngine.AI.NavMeshTriangulation = {}

---  Generated By xerysherry