--- @class UnityEngine.EventSystems.ExecuteEvents 
--- @field pointerEnterHandler function
--- @field pointerExitHandler function
--- @field pointerDownHandler function
--- @field pointerUpHandler function
--- @field pointerClickHandler function
--- @field initializePotentialDrag function
--- @field beginDragHandler function
--- @field dragHandler function
--- @field endDragHandler function
--- @field dropHandler function
--- @field scrollHandler function
--- @field updateSelectedHandler function
--- @field selectHandler function
--- @field deselectHandler function
--- @field moveHandler function
--- @field submitHandler function
--- @field cancelHandler function
UnityEngine.EventSystems.ExecuteEvents = {}

--- @param data UnityEngine.EventSystems.BaseEventData 
--- @return UnityEngine.EventSystems.ExecuteEvents.T
function UnityEngine.EventSystems.ExecuteEvents.ValidateEventData(data) end

--- @param target UnityEngine.GameObject 
--- @param eventData UnityEngine.EventSystems.BaseEventData 
--- @param functor function 
--- @return boolean
function UnityEngine.EventSystems.ExecuteEvents.Execute(target, eventData, functor) end

--- @param root UnityEngine.GameObject 
--- @param eventData UnityEngine.EventSystems.BaseEventData 
--- @param callbackFunction function 
--- @return UnityEngine.GameObject
function UnityEngine.EventSystems.ExecuteEvents.ExecuteHierarchy(root, eventData, callbackFunction) end

--- @param go UnityEngine.GameObject 
--- @return boolean
function UnityEngine.EventSystems.ExecuteEvents.CanHandleEvent(go) end

--- @param root UnityEngine.GameObject 
--- @return UnityEngine.GameObject
function UnityEngine.EventSystems.ExecuteEvents.GetEventHandler(root) end

---  Generated By xerysherry