--- @class UnityEngine.TextCore.LowLevel.FontEngineError Error code returned by the various FontEngine functions.
UnityEngine.TextCore.LowLevel.FontEngineError = {
    --- Error code returned when the function was successfully executed.
    Success = 0,
    --- Error code returned by the LoadFontFace function when the file path to the source font file appears invalid.
    Invalid_File_Path = 1,
    --- Error code returned by the LoadFontFace function when the source font file is of an unknown or invalid format.
    Invalid_File_Format = 2,
    --- Error code returned by the LoadFontFace function when the source font file appears invalid or improperly formatted.
    Invalid_File_Structure = 3,
    --- Error code indicating an invalid font file.
    Invalid_File = 4,
    --- Error code indicating failure to load one of the tables of the font file.
    Invalid_Table = 8,
    --- Error code returned by the LoadGlyph function when referencing an invalid or out of range glyph index value.
    Invalid_Glyph_Index = 16,
    --- Error code returned by the LoadGlyph function when referencing an invalid Unicode character value.
    Invalid_Character_Code = 17,
    --- Error code returned by the LoadGlyph or SetFaceSize functions using an invalid pointSize value.
    Invalid_Pixel_Size = 23,
    --- Error code indicating failure to initialize the font engine library.
    Invalid_Library = 33,
    --- Error code indicating an invalid font face.
    Invalid_Face = 35,
    --- Error code indicating failure to initialize the font engine library and / or successfully load a font face.
    Invalid_Library_or_Face = 41,
    --- Error code returned when the FontEngine glyph packing or rendering process has been cancelled.
    Atlas_Generation_Cancelled = 100,
    Invalid_SharedTextureData = 101,
}

---  Generated By xerysherry