--- @class UnityEngine.LightProbeProxyVolume.ProbePositionMode The mode in which the interpolated Light Probe positions are generated.
UnityEngine.LightProbeProxyVolume.ProbePositionMode = {
    --- Divide the volume in cells based on resolution, and generate interpolated Light Probes positions in the corner/edge of the cells.
    CellCorner = 0,
    --- Divide the volume in cells based on resolution, and generate interpolated Light Probe positions in the center of the cells.
    CellCenter = 1,
}

---  Generated By xerysherry