--- @class UnityEngine.ParticleSystemEmissionType The mode in which particles are emitted.
UnityEngine.ParticleSystemEmissionType = {
    --- Emit over time.
    Time = 0,
    --- Emit when emitter moves.
    Distance = 1,
}

---  Generated By xerysherry