--- @class UnityEngine.AI.NavMeshLinkData Used for runtime manipulation of links connecting polygons of the NavMesh.
--- @field startPosition UnityEngine.Vector3 property getset
---       Start position of the link.
--- @field endPosition UnityEngine.Vector3 property getset
---       End position of the link.
--- @field costModifier number property getset
---       If positive, overrides the pathfinder cost to traverse the link.
--- @field bidirectional boolean property getset
---       If true, the link can be traversed in both directions, otherwise only from start to end position.
--- @field width number property getset
---       If positive, the link will be rectangle aligned along the line from start to end.
--- @field area number property getset
---       Area type of the link.
--- @field agentTypeID number property getset
---       Specifies which agent type this link is available for.
UnityEngine.AI.NavMeshLinkData = {}

--- @param value UnityEngine.Vector3 
function UnityEngine.AI.NavMeshLinkData:set_startPosition(value) end

--- @param value UnityEngine.Vector3 
function UnityEngine.AI.NavMeshLinkData:set_endPosition(value) end

--- @param value number 
function UnityEngine.AI.NavMeshLinkData:set_costModifier(value) end

--- @param value boolean 
function UnityEngine.AI.NavMeshLinkData:set_bidirectional(value) end

--- @param value number 
function UnityEngine.AI.NavMeshLinkData:set_width(value) end

--- @param value number 
function UnityEngine.AI.NavMeshLinkData:set_area(value) end

--- @param value number 
function UnityEngine.AI.NavMeshLinkData:set_agentTypeID(value) end

---  Generated By xerysherry