--- @class UnityEngine.Camera.GateFitMode Enum used to specify how the sensor gate (sensor frame) defined by Camera.sensorSize fits into the resolution gate (render frame).
UnityEngine.Camera.GateFitMode = {
    --- 
    ---                     Fit the resolution gate vertically within the sensor gate.
    ---                 
    Vertical = 1,
    --- 
    ---                     Fit the resolution gate horizontally within the sensor gate.
    ---                 
    Horizontal = 2,
    --- 
    ---                     Automatically selects a horizontal or vertical fit so that the sensor gate fits completely inside the resolution gate.
    ---                 
    Fill = 3,
    --- 
    ---                     Automatically selects a horizontal or vertical fit so that the render frame fits completely inside the resolution gate.
    ---                 
    Overscan = 4,
    --- 
    ---                     Stretch the sensor gate to fit exactly into the resolution gate.
    ---                 
    None = 0,
}

--- @class UnityEngine.Camera.GateFitMode Enum used to specify how the sensor gate (sensor frame) defined by Camera.sensorSize fits into the resolution gate (render frame).
UnityEngine.Camera.GateFitMode = {
    --- 
    ---                     Fit the resolution gate vertically within the sensor gate.
    ---                 
    Vertical = 1,
    --- 
    ---                     Fit the resolution gate horizontally within the sensor gate.
    ---                 
    Horizontal = 2,
    --- 
    ---                     Automatically selects a horizontal or vertical fit so that the sensor gate fits completely inside the resolution gate.
    ---                 
    Fill = 3,
    --- 
    ---                     Automatically selects a horizontal or vertical fit so that the render frame fits completely inside the resolution gate.
    ---                 
    Overscan = 4,
    --- 
    ---                     Stretch the sensor gate to fit exactly into the resolution gate.
    ---                 
    None = 0,
}

---  Generated By xerysherry