--- @class UnityEngine.MonoBehaviour:UnityEngine.Behaviour MonoBehaviour is the base class from which every Unity script derives.
--- @field useGUILayout boolean property getset
---       Disabling this lets you skip the GUI layout phase.
--- @field runInEditMode boolean property getset
---       Allow a specific instance of a MonoBehaviour to run in edit mode (only available in the editor).
--- @field enabled boolean
--- @field isActiveAndEnabled boolean
--- @field transform UnityEngine.Transform
--- @field gameObject UnityEngine.GameObject
--- @field tag string
--- @field rigidbody UnityEngine.Component
--- @field rigidbody2D UnityEngine.Component
--- @field camera UnityEngine.Component
--- @field light UnityEngine.Component
--- @field animation UnityEngine.Component
--- @field constantForce UnityEngine.Component
--- @field renderer UnityEngine.Component
--- @field audio UnityEngine.Component
--- @field networkView UnityEngine.Component
--- @field collider UnityEngine.Component
--- @field collider2D UnityEngine.Component
--- @field hingeJoint UnityEngine.Component
--- @field particleSystem UnityEngine.Component
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.MonoBehaviour = {}

--- Logs message to the Unity Console (identical to Debug.Log).
--- @param message System.Object 
function UnityEngine.MonoBehaviour.print(message) end

--- Is any invoke pending on this MonoBehaviour?
--- @return boolean 
function UnityEngine.MonoBehaviour:IsInvoking() end

--- Cancels all Invoke calls on this MonoBehaviour.
function UnityEngine.MonoBehaviour:CancelInvoke() end

--- Invokes the method methodName in time seconds.
--- @param methodName string 
--- @param time number 
function UnityEngine.MonoBehaviour:Invoke(methodName, time) end

--- Invokes the method methodName in time seconds, then repeatedly every repeatRate seconds.
--- @param methodName string 
--- @param time number 
--- @param repeatRate number 
function UnityEngine.MonoBehaviour:InvokeRepeating(methodName, time, repeatRate) end

--- Cancels all Invoke calls with name methodName on this behaviour.
--- @param methodName string 
function UnityEngine.MonoBehaviour:CancelInvoke(methodName) end

--- Is any invoke on methodName pending?
--- @param methodName string 
--- @return boolean 
function UnityEngine.MonoBehaviour:IsInvoking(methodName) end

--- Starts a Coroutine.
--- @return UnityEngine.Coroutine 
function UnityEngine.MonoBehaviour:StartCoroutine(methodName) end

--- Starts a coroutine named methodName.
--- @param methodName string 
--- @param value System.Object 
--- @return UnityEngine.Coroutine 
function UnityEngine.MonoBehaviour:StartCoroutine(methodName, value) end

--- Starts a Coroutine.
--- @param routine System.Collections.IEnumerator 
--- @return UnityEngine.Coroutine 
function UnityEngine.MonoBehaviour:StartCoroutine(routine) end

--- @return UnityEngine.Coroutine
function UnityEngine.MonoBehaviour:StartCoroutine_Auto(routine) end

--- Stops the first coroutine named methodName, or the coroutine stored in routine running on this behaviour.
function UnityEngine.MonoBehaviour:StopCoroutine(routine) end

--- Stops the first coroutine named methodName, or the coroutine stored in routine running on this behaviour.
function UnityEngine.MonoBehaviour:StopCoroutine(routine) end

--- Stops the first coroutine named methodName, or the coroutine stored in routine running on this behaviour.
function UnityEngine.MonoBehaviour:StopCoroutine(methodName) end

--- Stops all coroutines running on this behaviour.
function UnityEngine.MonoBehaviour:StopAllCoroutines() end

function UnityEngine.MonoBehaviour:set_useGUILayout(value) end

function UnityEngine.MonoBehaviour:set_runInEditMode(value) end

---  Generated By xerysherry