--- @class UnityEngine.Collision2D Collision details returned by 2D physics callback functions.
--- @field collider UnityEngine.Collider2D property get
---       The incoming Collider2D involved in the collision with the otherCollider.
--- @field otherCollider UnityEngine.Collider2D property get
---       The other Collider2D involved in the collision with the collider.
--- @field rigidbody UnityEngine.Rigidbody2D property get
---       The incoming Rigidbody2D involved in the collision with the otherRigidbody.
--- @field otherRigidbody UnityEngine.Rigidbody2D property get
---       The other Rigidbody2D involved in the collision with the rigidbody.
--- @field transform UnityEngine.Transform property get
---       The Transform of the incoming object involved in the collision.
--- @field gameObject UnityEngine.GameObject property get
---       The incoming GameObject involved in the collision.
--- @field relativeVelocity UnityEngine.Vector2 property get
---       The relative linear velocity of the two colliding objects (Read Only).
--- @field enabled boolean property get
---       Indicates whether the collision response or reaction is enabled or disabled.
--- @field contacts UnityEngine.ContactPoint2D[] property get
---       The specific points of contact with the incoming Collider2D. You should avoid using this as it produces memory garbage. Use GetContact or GetContacts instead.
--- @field contactCount number property get
---       Gets the number of contacts for this collision.
UnityEngine.Collision2D = {}

--- Gets the contact point at the specified index.
--- @param index number The index of the contact to retrieve.
--- @return UnityEngine.ContactPoint2D The contact at the specified index.
function UnityEngine.Collision2D:GetContact(index) end

--- Retrieves all contact points for contacts between collider and otherCollider.
--- @param contacts UnityEngine.ContactPoint2D[] An array of ContactPoint2D used to receive the results.
--- @return number Returns the number of contacts placed in the contacts array.
function UnityEngine.Collision2D:GetContacts(contacts) end

--- Retrieves all contact points for contacts between collider and otherCollider.
--- @param contacts UnityEngine.ContactPoint2D[] An array of ContactPoint2D used to receive the results.
--- @return number Returns the number of contacts placed in the contacts array.
function UnityEngine.Collision2D:GetContacts(contacts) end

---  Generated By xerysherry