--- @class UnityEngine.VFX.VFXSpawnerCallbacks:UnityEngine.ScriptableObject This abstract class provides a way to implement custom spawner block in C#.
--- @field name string
--- @field hideFlags UnityEngine.HideFlags
UnityEngine.VFX.VFXSpawnerCallbacks = {}

--- Unity invokes this method when a parent spawner system triggers Play.
--- @param state UnityEngine.VFX.VFXSpawnerState The spawner state.
--- @param vfxValues UnityEngine.VFX.VFXExpressionValues The values of expression (input properties for a spawner block).
--- @param vfxComponent UnityEngine.VFX.VisualEffect The visual effect.
function UnityEngine.VFX.VFXSpawnerCallbacks:OnPlay(state, vfxValues, vfxComponent) end

--- Unity invokes this method when a parent spawner system triggers Update.
--- @param state UnityEngine.VFX.VFXSpawnerState The spawner state.
--- @param vfxValues UnityEngine.VFX.VFXExpressionValues The values of expression (input properties for a spawner block).
--- @param vfxComponent UnityEngine.VFX.VisualEffect The visual effect.
function UnityEngine.VFX.VFXSpawnerCallbacks:OnUpdate(state, vfxValues, vfxComponent) end

--- Unity invokes this method when a parent spawner system triggers Stop.
--- @param state UnityEngine.VFX.VFXSpawnerState The spawner state.
--- @param vfxValues UnityEngine.VFX.VFXExpressionValues The values of expression (input properties for a spawner block).
--- @param vfxComponent UnityEngine.VFX.VisualEffect The visual effect.
function UnityEngine.VFX.VFXSpawnerCallbacks:OnStop(state, vfxValues, vfxComponent) end

---  Generated By xerysherry