--- @class UnityEngine.HeadDof Enumeration of all the muscles in the head.
UnityEngine.HeadDof = {
    --- The neck front-back muscle.
    NeckFrontBack = 0,
    --- The neck left-right muscle.
    NeckLeftRight = 1,
    --- The neck roll left-right muscle.
    NeckRollLeftRight = 2,
    --- The head front-back muscle.
    HeadFrontBack = 3,
    --- The head left-right muscle.
    HeadLeftRight = 4,
    --- The head roll left-right muscle.
    HeadRollLeftRight = 5,
    --- The left eye down-up muscle.
    LeftEyeDownUp = 6,
    --- The left eye in-out muscle.
    LeftEyeInOut = 7,
    --- The right eye down-up muscle.
    RightEyeDownUp = 8,
    --- The right eye in-out muscle.
    RightEyeInOut = 9,
    --- The jaw down-up muscle.
    JawDownUp = 10,
    --- The jaw left-right muscle.
    JawLeftRight = 11,
    --- The last value of the HeadDof enum.
    LastHeadDof = 12,
}

---  Generated By xerysherry