--- @class UnityEngine.UIElements.UQueryExtensions UQuery is a set of extension methods allowing you to select individual or collection of visualElements inside a complex hierarchy.
UnityEngine.UIElements.UQueryExtensions = {}

--- Convenience overload, shorthand for Query<T>.Build().First().
--- @param e UnityEngine.UIElements.VisualElement 
--- @param name string 
--- @param classes string[] 
--- @return UnityEngine.UIElements.UQueryExtensions.T The first element matching all the criteria, or null if none was found.
function UnityEngine.UIElements.UQueryExtensions.Q(e, name, classes) end

--- Convenience overload, shorthand for Query<T>.Build().First().
--- @param e UnityEngine.UIElements.VisualElement 
--- @param name string 
--- @param classes string[] 
--- @return UnityEngine.UIElements.VisualElement The first element matching all the criteria, or null if none was found.
function UnityEngine.UIElements.UQueryExtensions.Q(e, name, classes) end

--- Convenience overload, shorthand for Query<T>.Build().First().
--- @param e UnityEngine.UIElements.VisualElement 
--- @param name string 
--- @param className string 
--- @return UnityEngine.UIElements.UQueryExtensions.T The first element matching all the criteria, or null if none was found.
function UnityEngine.UIElements.UQueryExtensions.Q(e, name, className) end

--- Convenience overload, shorthand for Query<T>.Build().First().
--- @param e UnityEngine.UIElements.VisualElement 
--- @param name string 
--- @param className string 
--- @return UnityEngine.UIElements.VisualElement The first element matching all the criteria, or null if none was found.
function UnityEngine.UIElements.UQueryExtensions.Q(e, name, className) end

--- Initializes a QueryBuilder with the specified selection rules.
--- @param e UnityEngine.UIElements.VisualElement 
--- @param name string 
--- @param classes string[] 
--- @return UnityEngine.UIElements.UQueryBuilder`1 QueryBuilder configured with the associated selection rules.
function UnityEngine.UIElements.UQueryExtensions.Query(e, name, classes) end

--- Initializes a QueryBuilder with the specified selection rules.
--- @param e UnityEngine.UIElements.VisualElement 
--- @param name string 
--- @param className string 
--- @return UnityEngine.UIElements.UQueryBuilder`1 QueryBuilder configured with the associated selection rules.
function UnityEngine.UIElements.UQueryExtensions.Query(e, name, className) end

--- Initializes a QueryBuilder with the specified selection rules.
--- @param e UnityEngine.UIElements.VisualElement 
--- @param name string 
--- @param classes string[] 
--- @return UnityEngine.UIElements.UQueryBuilder`1 QueryBuilder configured with the associated selection rules.
function UnityEngine.UIElements.UQueryExtensions.Query(e, name, classes) end

--- Initializes a QueryBuilder with the specified selection rules.
--- @param e UnityEngine.UIElements.VisualElement 
--- @param name string 
--- @param className string 
--- @return UnityEngine.UIElements.UQueryBuilder`1 QueryBuilder configured with the associated selection rules.
function UnityEngine.UIElements.UQueryExtensions.Query(e, name, className) end

--- Initializes an empty QueryBuilder on a specified root element.
--- @param e UnityEngine.UIElements.VisualElement Root VisualElement on which the selector will be applied.
--- @return UnityEngine.UIElements.UQueryBuilder`1 An empty QueryBuilder on a specified root element.
function UnityEngine.UIElements.UQueryExtensions.Query(e) end

---  Generated By xerysherry