--- @class UnityEngine.iOS.LocalNotification iOS.LocalNotification is a wrapper around the UILocalNotification class found in the Apple UIKit framework and is only available on iPhoneiPadiPod Touch.
--- @field defaultSoundName string property get
---       The default system sound. (Read Only)
--- @field timeZone string property getset
---       The time zone of the notification's fire date.
--- @field repeatCalendar UnityEngine.iOS.CalendarIdentifier property getset
---       The calendar type (Gregorian, Chinese, etc) to use for rescheduling the notification.
--- @field repeatInterval UnityEngine.iOS.CalendarUnit property getset
---       The calendar interval at which to reschedule the notification.
--- @field fireDate System.DateTime property getset
---       The date and time when the system should deliver the notification.
--- @field alertBody string property getset
---       The message displayed in the notification alert.
--- @field alertTitle string property getset
---       A short description of the reason for the alert.
--- @field alertAction string property getset
---       The title of the action button or slider.
--- @field alertLaunchImage string property getset
---       Identifies the image used as the launch image when the user taps the action button.
--- @field soundName string property getset
---       The name of the sound file to play when an alert is displayed.
--- @field applicationIconBadgeNumber number property getset
---       The number to display as the application's icon badge.
--- @field userInfo System.Collections.IDictionary property getset
---       A dictionary for passing custom information to the notified application.
--- @field hasAction boolean property getset
---       A boolean value that controls whether the alert action is visible or not.
UnityEngine.iOS.LocalNotification = {}

function UnityEngine.iOS.LocalNotification:set_timeZone(value) end

function UnityEngine.iOS.LocalNotification:set_repeatCalendar(value) end

function UnityEngine.iOS.LocalNotification:set_repeatInterval(value) end

function UnityEngine.iOS.LocalNotification:set_fireDate(value) end

function UnityEngine.iOS.LocalNotification:set_alertBody(value) end

function UnityEngine.iOS.LocalNotification:set_alertTitle(value) end

function UnityEngine.iOS.LocalNotification:set_alertAction(value) end

function UnityEngine.iOS.LocalNotification:set_alertLaunchImage(value) end

function UnityEngine.iOS.LocalNotification:set_soundName(value) end

function UnityEngine.iOS.LocalNotification:set_applicationIconBadgeNumber(value) end

function UnityEngine.iOS.LocalNotification:set_userInfo(value) end

function UnityEngine.iOS.LocalNotification:set_hasAction(value) end

---  Generated By xerysherry