--- @class UnityEngine.Random Class for generating random data.
--- @field seed number
--- @field state UnityEngine.Random.State property getset
---       Gets/Sets the full internal state of the random number generator.
--- @field value number property get
---       Returns a random number between 0.0 [inclusive] and 1.0 [inclusive] (Read Only).
--- @field insideUnitSphere UnityEngine.Vector3 property get
---       Returns a random point inside a sphere with radius 1 (Read Only).
--- @field insideUnitCircle UnityEngine.Vector2 property get
---       Returns a random point inside a circle with radius 1 (Read Only).
--- @field onUnitSphere UnityEngine.Vector3 property get
---       Returns a random point on the surface of a sphere with radius 1 (Read Only).
--- @field rotation UnityEngine.Quaternion property get
---       Returns a random rotation (Read Only).
--- @field rotationUniform UnityEngine.Quaternion property get
---       Returns a random rotation with uniform distribution (Read Only).
UnityEngine.Random = {}

--- @param value number 
function UnityEngine.Random.set_seed(value) end

--- Initializes the random number generator state with a seed.
--- @param seed number Seed used to initialize the random number generator.
function UnityEngine.Random.InitState(seed) end

--- @param value UnityEngine.Random.State 
function UnityEngine.Random.set_state(value) end

--- Return a random float number between min [inclusive] and max [inclusive] (Read Only).
--- @param min number 
--- @param max number 
--- @return number 
function UnityEngine.Random.Range(min, max) end

--- Return a random float number between min [inclusive] and max [inclusive] (Read Only).
--- @param min number 
--- @param max number 
--- @return number 
function UnityEngine.Random.Range(min, max) end

--- @param min number 
--- @param max number 
--- @return number
function UnityEngine.Random.RandomRange(min, max) end

--- @param min number 
--- @param max number 
--- @return number
function UnityEngine.Random.RandomRange(min, max) end

--- Generates a random color from HSV and alpha ranges.
--- @return UnityEngine.Color A random color with HSV and alpha values in the input ranges.
function UnityEngine.Random.ColorHSV() end

--- Generates a random color from HSV and alpha ranges.
--- @param hueMin number 
--- @param hueMax number 
--- @return UnityEngine.Color A random color with HSV and alpha values in the input ranges.
function UnityEngine.Random.ColorHSV(hueMin, hueMax) end

--- Generates a random color from HSV and alpha ranges.
--- @param hueMin number 
--- @param hueMax number 
--- @param saturationMin number 
--- @param saturationMax number 
--- @return UnityEngine.Color A random color with HSV and alpha values in the input ranges.
function UnityEngine.Random.ColorHSV(hueMin, hueMax, saturationMin, saturationMax) end

--- Generates a random color from HSV and alpha ranges.
--- @param hueMin number 
--- @param hueMax number 
--- @param saturationMin number 
--- @param saturationMax number 
--- @param valueMin number 
--- @param valueMax number 
--- @return UnityEngine.Color A random color with HSV and alpha values in the input ranges.
function UnityEngine.Random.ColorHSV(hueMin, hueMax, saturationMin, saturationMax, valueMin, valueMax) end

--- Generates a random color from HSV and alpha ranges.
--- @param hueMin number Minimum hue [0..1].
--- @param hueMax number Maximum hue [0..1].
--- @param saturationMin number Minimum saturation [0..1].
--- @param saturationMax number Maximum saturation[0..1].
--- @param valueMin number Minimum value [0..1].
--- @param valueMax number Maximum value [0..1].
--- @param alphaMin number Minimum alpha [0..1].
--- @param alphaMax number Maximum alpha [0..1].
--- @return UnityEngine.Color A random color with HSV and alpha values in the input ranges.
function UnityEngine.Random.ColorHSV(hueMin, hueMax, saturationMin, saturationMax, valueMin, valueMax, alphaMin, alphaMax) end

---  Generated By xerysherry